### PR TITLE
thorvg: Update to 0.14.7

### LINKED ISSUE #95861: Fail to build on windows using MSVC 14.42 due to ThorVG
### Tested versions

- Reproducible with commit 826de7976a6add282c7b14d4be2a7e6d775821d8 on windows

### System information

Windows 11 - MSVC 14.42

### Issue description

- When trying to build on windows with C# support it throws the following errors due to thorvg, it builds fine on linux

```
D:\IDE\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34226\include\mutex(37): error C3861: '_Mtx_init_in_situ': identifier not found
D:\IDE\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34226\include\mutex(536): error C3861: '_Cnd_init_in_situ': identifier not found
D:\IDE\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.42.34226\include\condition_variable(56): error C3861: '_Cnd_init_in_situ': identifier not found
scons: *** [thirdparty\thorvg\src\loaders\svg\tvgSvgLoader.windows.editor.x86_64.obj] Error 2
scons: building terminated because of errors.
```

### Steps to reproduce

- Simply build the engine source with C# support using latest MSVC 14.42 with latest Windows 11 SDK on Windows.

### Minimal reproduction project (MRP)

This is an engine build problem, thus it does not have an actual project.

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #95861.

### CODE REVIEW

**Comment by mikemaas** [comment]
Can confirm this fix works with the latest VS preview. I hit the issue but can now successfully compile and link. 

- Windows 11 (10.0.22631 Build 22631)
- Visual Studio 17.12.0 Preview 1.0
- SCons v4.8.0

Thank you.

**Comment by aaronfranke** [comment]
This caused a regression: https://github.com/godotengine/godot/issues/96262

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.
