### PR TITLE
Fix macOS export plugin build without regex module.

### LINKED ISSUE #67339: Can't compile Godot with minimal build
### Godot version

4.0 42ebc4ef65093ac7bb4e1785054e4632d3ddc9bc

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

This is max 1 day old regression

```
scons -j2 dev_build=yes target=editor linker=gold module_basis_universal_enabled=no module_bmp_enabled=no 
module_camera_enabled=no module_csg_enabled=no module_cvtt_enabled=no module_dds_enabled=no 
module_denoise_enabled=no module_enet_enabled=no module_etcpak_enabled=no brotli=no module_gltf_enabled=no 
module_gridmap_enabled=no module_hdr_enabled=no module_jpg_enabled=no module_jsonrpc_enabled=no 
module_lightmapper_rd_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no 
module_minimp3_enabled=no module_mobile_vr_enabled=no module_msdfgen_enabled=no module_multiplayer_enabled=no 
module_noise_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no 
module_regex_enabled=no module_squish_enabled=no graphite=no module_text_server_adv_enabled=no 
module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no 
module_vhacd_enabled=no module_vorbis_enabled=no module_webp_enabled=no module_webrtc_enabled=no 
module_websocket_enabled=no module_webxr_enabled=no module_xatlas_unwrap_enabled=no
```
fails to compile with this error
```
 Compiling platform/linuxbsd/export/export_plugin.cpp ...
Compiling platform/macos/export/codesign.cpp ...
Compiling platform/macos/export/export.cpp ...
Compiling platform/macos/export/export_plugin.cpp ...
Compiling platform/macos/export/lipo.cpp ...
Compiling platform/macos/export/macho.cpp ...
platform/macos/export/export_plugin.cpp: In member function 'virtual bool EditorExportPlatformMacOS::is_executable(const String&) const':
platform/macos/export/export_plugin.cpp:909:9: error: 'MachO' has not been declared
  909 |  return MachO::is_macho(p_path) || LipO::is_lipo(p_path) || is_shbang(p_path);
      |         ^~~~~
platform/macos/export/export_plugin.cpp:909:36: error: 'LipO' has not been declared
  909 |  return MachO::is_macho(p_path) || LipO::is_lipo(p_path) || is_shbang(p_path);
      |                                    ^~~~
scons: *** [platform/macos/export/export_plugin.linuxbsd.editor.dev.x86_64.san.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:04:38.197]
```

Looks like regression from https://github.com/godotengine/godot/pull/66952
CC @bruvzg 

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/67339

### CODE REVIEW

File: platform/macos/export/lipo.cpp [hunk 1]
```diff
@@ -32,8 +32,6 @@
 
 #include "lipo.h"
 
-#ifdef MODULE_REGEX_ENABLED
```
Comment (akien-mga) [inline platform/macos/export/lipo.cpp:35]: You can also remove the include for `modules_enabled.gen.h` in those files if not used.

Comment (bruvzg) [reply platform/macos/export/lipo.cpp:35]: Done.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
