### ISSUE TITLE
AnimationPlayer: cannot insert key for Rect2 properties (like rect2.x)

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#27418]
**Godot version:**
3.1 stable

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
Trying to insert a key for a rect property like `Sprite:region_rect:x` throws an error in output and no key is added, this break the possibility of making animated regions by axis.
The error is:
```
core/undo_redo.cpp:291 - Error calling method from signal 'track_insert_key': 'Animation::track_insert_key': Method expected 3 arguments, but called with 2.
```

Is possible that more built in types are affected by this bug.
This works fine on 3.0.x and there are no issues with Vector2 for example.

**Steps to reproduce:**
Try to animate `region_rect:x` on a sprite (not the full rect).

**Comment by qarmin** [comment]
This error happens because value variable from this line:
https://github.com/godotengine/godot/blob/7b67c5857fd7715774c7a2e07a05ff1fb7304ed1/editor/animation_track_editor.cpp#L3753

Is never initialized, in _find_hint_for_track function
https://github.com/godotengine/godot/blob/7b67c5857fd7715774c7a2e07a05ff1fb7304ed1/editor/animation_track_editor.cpp#L2967-L2981

**Comment by hbina** [comment]
What should it be initialized to?

**Comment by eon-s** [comment]
Like the rest, current value I guess? If it cannot be retrieved, a `Rect(0,0,0,0)` would be fine.

**Comment by bojidar-bg** [comment]
I think you should be animating `region_rect:position:x`, since `Rect2` has no member named `x`.

**Comment by eon-s** [comment]
God(ot)s, I'm dumb :sweat_smile: 

Thanks @bojidar-bg !

ps: I guess the player should be more clear when adding a broken property, but this is solved then.
