### ISSUE TITLE
Update Android build system for NDK 11

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#4081]
With the release of a new version of the Android NDK, some things need to change in Godot's build system. The new NDK is deprecating GCC in favor of Clang. Also, GCC 4.8 is not bundled anymore, so we must look for GCC 4.9 instead, even though Clang should become the default.

Just as a note, this will also require an update to the documentation about compiling for Android.

**Comment by teamblubee** [comment]
ahh, no wonder. I was just trying to compile and it seem like it was grinding its wheels for way too long especially with -j 16. I initially though it was a neon issue, Here's a sample output right before the build fails
```bash
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-eabi-g++ -o core/bind/core_bind..opt.debug.armv7.neon.o -c -DNO_STATVFS -MMD -MP -MF -fpic -ffunction-sections -funwind-tables -fstack-protector -fvisibility=hidden -D__ARM_ARCH_7__ -D__ARM_ARCH_7A__ -D__GLIBC__ -Wno-psabi -march=armv7-a -mfloat-abi=softfp -ftree-vectorize -funsafe-math-optimizations -fno-strict-aliasing -DANDROID -Wa,--noexecstack -DGLES2_ENABLED -mfpu=neon -D__ARM_NEON__ -O2 -ffast-math -DDEBUG_ENABLED -fno-exceptions -DNO_SAFE_CAST -DANDROID_ENABLED -DUNIX_ENABLED -DNO_FCNTL -DMPC_FIXED_POINT -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DPNG_ARM_NEON_OPT=2 -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/ -I/home/usr/sdk/ndk-r11/platforms15/arch-arm/usr/include -I/home/usr/sdk/ndk-r11/sources/cxx-stl/gabi++/include -I/home/usr/sdk/ndk-r11/sources/cpufeatures -Idrivers/builtin_openssl2 -Icore/bind/vorbis -Idrivers/builtin_openssl2/crypto -Idrivers/builtin_openssl2/openssl -Idrivers/builtin_openssl2/crypto/evp -Idrivers/builtin_openssl2/crypto/asn1 -Idrivers/builtin_openssl2/crypto/modes core/bind/core_bind.cpp
In file included from core/math/math_funcs.h:36:0,
                 from core/math/vector3.h:34,
                 from core/math/aabb.h:34,
                 from core/variant.h:36,
                 from core/object.h:33,
                 from core/resource.h:32,
                 from core/io/resource_loader.h:32,
                 from core/bind/core_bind.h:4,
                 from core/bind/core_bind.cpp:1:
/home/usr/sdk/ndk-r11/platforms15/arch-arm/usr/include/math.h:24:0: warning: "__pure2" redefined
 #define __pure2
 ^
In file included from /home/usr/sdk/ndk-r11/platforms15/arch-arm/usr/include/math.h:20:0,
                 from core/math/math_funcs.h:36,
                 from core/math/vector3.h:34,
                 from core/math/aabb.h:34,
                 from core/variant.h:36,
                 from core/object.h:33,
                 from core/resource.h:32,
                 from core/io/resource_loader.h:32,
                 from core/bind/core_bind.h:4,
                 from core/bind/core_bind.cpp:1:
/home/usr/sdk/ndk-r11/platforms15/arch-arm/usr/include/sys/cdefs.h:198:0: note: this is the location of the previous definition
 #define __pure2 __attribute__((__const__)) /* Android-added: used by FreeBSD libm */
 ^
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-eabi-ar rc core/libcore..opt.debug.armv7.neon.a platform/iphone/globals/global_defaults..opt.debug.armv7.neon.o platform//globals/global_defaults..opt.debug.armv7.neon.o core/register_core_types..opt.debug.armv7.neon.o core/variant_call..opt.debug.armv7.neon.o core/color..opt.debug.armv7.neon.o core/string_db..opt.debug.armv7.neon.o core/script_debugger_remote..opt.debug.armv7.neon.o core/variant_op..opt.debug.armv7.neon.o core/safe_refcount..opt.debug.armv7.neon.o core/variant_construct_string..opt.debug.armv7.neon.o core/script_debugger_local..opt.debug.armv7.neon.o core/global_constants..opt.debug.armv7.neon.o core/method_bind..opt.debug.armv7.neon.o core/error_macros..opt.debug.armv7.neon.o core/variant_parser..opt.debug.armv7.neon.o core/func_ref..opt.debug.armv7.neon.o core/resource..opt.debug.armv7.neon.o core/core_string_names..opt.debug.armv7.neon.o core/ref_ptr..opt.debug.armv7.neon.o core/packed_data_container..opt.debug.armv7.neon.o core/script_language..opt.debug.armv7.neon.o core/command_queue_mt..opt.debug.armv7.neon.o core/dvector..opt.debug.armv7.neon.o core/script_encryption_key..opt.debug.armv7.neon.o core/vset..opt.debug.armv7.neon.o core/script_debugger_debugger..opt.debug.armv7.neon.o core/message_queue..opt.debug.armv7.neon.o core/pool_allocator..opt.debug.armv7.neon.o core/path_db..opt.debug.armv7.neon.o core/image..opt.debug.armv7.neon.o core/res_ptr..opt.debug.armv7.neon.o core/pair..opt.debug.armv7.neon.o core/rid..opt.debug.armv7.neon.o core/variant..opt.debug.armv7.neon.o core/print_string..opt.debug.armv7.neon.o core/undo_redo..opt.debug.armv7.neon.o core/fpstr..opt.debug.armv7.neon.o core/input_map..opt.debug.armv7.neon.o core/path_remap..opt.debug.armv7.neon.o core/global_defaults..opt.debug.armv7.neon.o core/vmap..opt.debug.armv7.neon.o core/compressed_translation..opt.debug.armv7.neon.o core/reference..opt.debug.armv7.neon.o core/event_queue..opt.debug.armv7.neon.o core/dictionary..opt.debug.armv7.neon.o core/image_quantize..opt.debug.armv7.neon.o core/ustring..opt.debug.armv7.neon.o core/object_type_db..opt.debug.armv7.neon.o core/array..opt.debug.armv7.neon.o core/globals..opt.debug.armv7.neon.o core/translation..opt.debug.armv7.neon.o core/object..opt.debug.armv7.neon.o core/os/main_loop..opt.debug.armv7.neon.o core/os/shell..opt.debug.armv7.neon.o core/os/copymem..opt.debug.armv7.neon.o core/os/memory_pool_dynamic..opt.debug.armv7.neon.o core/os/semaphore..opt.debug.armv7.neon.o core/os/keyboard..opt.debug.armv7.neon.o core/os/thread_safe..opt.debug.armv7.neon.o core/os/memory_pool_static..opt.debug.armv7.neon.o core/os/dir_access..opt.debug.armv7.neon.o core/os/memory_pool_dynamic_static..opt.debug.armv7.neon.o core/os/os..opt.debug.armv7.neon.o core/os/input..opt.debug.armv7.neon.o core/os/file_access..opt.debug.armv7.neon.o core/os/thread_dummy..opt.debug.armv7.neon.o core/os/memory..opt.debug.armv7.neon.o core/os/mutex..opt.debug.armv7.neon.o core/os/memory_pool_dynamic_prealloc..opt.debug.armv7.neon.o core/os/thread..opt.debug.armv7.neon.o core/os/input_event..opt.debug.armv7.neon.o core/math/quat..opt.debug.armv7.neon.o core/math/triangulate..opt.debug.armv7.neon.o core/math/quick_hull..opt.debug.armv7.neon.o core/math/camera_matrix..opt.debug.armv7.neon.o core/math/face3..opt.debug.armv7.neon.o core/math/plane..opt.debug.armv7.neon.o core/math/vector3..opt.debug.armv7.neon.o core/math/triangle_mesh..opt.debug.armv7.neon.o core/math/aabb..opt.debug.armv7.neon.o core/math/bsp_tree..opt.debug.armv7.neon.o core/math/math_funcs..opt.debug.armv7.neon.o core/math/geometry..opt.debug.armv7.neon.o core/math/transform..opt.debug.armv7.neon.o core/math/math_2d..opt.debug.armv7.neon.o core/math/triangulator..opt.debug.armv7.neon.o core/math/matrix3..opt.debug.armv7.neon.o core/math/bezier_curve..opt.debug.armv7.neon.o core/math/math_defs..opt.debug.armv7.neon.o core/io/resource_loader..opt.debug.armv7.neon.o core/io/resource_format_binary..opt.debug.armv7.neon.o core/io/file_access_pack..opt.debug.armv7.neon.o core/io/file_access_network..opt.debug.armv7.neon.o core/io/md5..opt.debug.armv7.neon.o core/io/json..opt.debug.armv7.neon.o core/io/packet_peer_udp..opt.debug.armv7.neon.o core/io/translation_loader_po..opt.debug.armv7.neon.o core/io/stream_peer_tcp..opt.debug.armv7.neon.o core/io/file_access_zip..opt.debug.armv7.neon.o core/io/tcp_server..opt.debug.armv7.neon.o core/io/marshalls..opt.debug.armv7.neon.o core/io/config_file..opt.debug.armv7.neon.o core/io/file_access_buffered..opt.debug.armv7.neon.o core/io/xml_parser..opt.debug.armv7.neon.o core/io/resource_saver..opt.debug.armv7.neon.o core/io/resource_format_xml..opt.debug.armv7.neon.o core/io/ip_address..opt.debug.armv7.neon.o core/io/stream_peer..opt.debug.armv7.neon.o core/io/image_loader..opt.debug.armv7.neon.o core/io/compression..opt.debug.armv7.neon.o core/io/http_client..opt.debug.armv7.neon.o core/io/packet_peer..opt.debug.armv7.neon.o core/io/file_access_memory..opt.debug.armv7.neon.o core/io/ip..opt.debug.armv7.neon.o core/io/stream_peer_ssl..opt.debug.armv7.neon.o core/io/file_access_compressed..opt.debug.armv7.neon.o core/io/aes256..opt.debug.armv7.neon.o core/io/file_access_encrypted..opt.debug.armv7.neon.o core/io/unzip..opt.debug.armv7.neon.o core/io/base64..opt.debug.armv7.neon.o core/io/ioapi..opt.debug.armv7.neon.o core/io/zip..opt.debug.armv7.neon.o core/io/fastlz..opt.debug.armv7.neon.o core/bind/core_bind..opt.debug.armv7.neon.o
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-eabi-ranlib core/libcore..opt.debug.armv7.neon.a
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-eabi-g++ -o bin/libgodot..opt.debug.armv7.neon.so -g --sysroot=/home/usr/sdk/ndk-r11/platforms15/arch-arm -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-soname,libgodot_.so -shared platform//os_.os platform//godot_.os platform//file_access_.os platform//dir_access_.os platform//audio_driver_opensl.os platform//file_access_j.os platform//dir_access_j.os platform//thread_j.os platform//audio_driver_j.os platform//ifaddrs_.os platform//_native_app_glue.os platform//java_glue.os platform//cpu-features.os platform//java_class_wrapper.os -L/home/usr/sdk/ndk-r11/sources/cxx-stl/gabi++/libs/armeabi-v7a main/libmain..opt.debug.armv7.neon.a modules/libmodules..opt.debug.armv7.neon.a bin/tests/libtests..opt.debug.armv7.neon.a drivers/libdrivers..opt.debug.armv7.neon.a scene/libscene..opt.debug.armv7.neon.a servers/libservers..opt.debug.armv7.neon.a core/libcore..opt.debug.armv7.neon.a -lOpenSLES -lEGL -lOpenSLES -l -lc -lm -lstdc++ -llog -lGLESv1_CM -lGLESv2 -lz -lgabi++_static
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-eabi/4.9/../../../../arm-linux-eabi/bin/ld: error: cannot find -lgabi++_static
platform//os_.os:os_.cpp:typeinfo for AudioDriverSW: error: undefined reference to 'vtable for __cxxabiv1::__class_type_info'
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-eabi/4.9/../../../../arm-linux-eabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
platform//os_.os:os_.cpp:typeinfo for OS_Android: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-eabi/4.9/../../../../arm-linux-eabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
platform//file_access_.os:file_access_.cpp:typeinfo for FileAccessAndroid: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-eabi/4.9/../../../../arm-linux-eabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
platform//audio_driver_opensl.os:audio_driver_opensl.cpp:typeinfo for AudioDriverOpenSL: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-eabi/4.9/../../../../arm-linux-eabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
platform//file_access_j.os:file_access_j.cpp:typeinfo for FileAccessJAndroid: error: undefined reference to 'vtable for __cxxabiv1::__si_class_type_info'
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-eabi/4.9/../../../../arm-linux-eabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
modules/libmodules..opt.debug.armv7.neon.a(register_types..opt.debug.armv7.neon.o):register_types.cpp:typeinfo for ResourceFormatSaver: error: undefined reference to 'vtable for __cxxabiv1::__class_type_info'
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-eabi/4.9/../../../../arm-linux-eabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
modules/libmodules..opt.debug.armv7.neon.a(gd_script..opt.debug.armv7.neon.o):gd_script.cpp:typeinfo for GDTokenizer: error: undefined reference to 'vtable for __cxxabiv1::__class_type_info'
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-eabi/4.9/../../../../arm-linux-eabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
modules/libmodules..opt.debug.armv7.neon.a(gd_parser..opt.debug.armv7.neon.o):gd_parser.cpp:typeinfo for GDParser::Node: error: undefined reference to 'vtable for __cxxabiv1::__class_type_info'
/home/usr/sdk/ndk-r11/toolchains/arm-linux-eabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-eabi/4.9/../../../../arm-linux-eabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
collect2: error: ld returned 1 exit status
scons: *** [bin/libgodot..opt.debug.armv7.neon.so] Error 1
scons: building terminated because of errors.
```

**Comment by teamblubee** [comment]
any news on updating the build process for godot?

**Comment by reduz** [comment]
Feel free to submit a PR if you get it to work!

**Comment by teamblubee** [comment]
where exactly do you call ndk-build in all your scripts? I think the problem is that the latest version of android ndk r11 uses toolchain 4.9, updating to toolchain 4.9 in platform/android/detect.py builds for a while then fails at:

```bash
sdk/android/android-ndk-r11/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-li
nux-androideabi/bin/ld: error: cannot find -lgabi++_static
```

both gcc and the toolchain need to be on the same version by doing something like this:

```bash
ndk-build
```
to

```bash
ndk-build NDK_TOOLCHAIN_VERSION=4.9
```

so where exactly are you calling ndk-build scripts from?

**Comment by reduz** [comment]
We dont use ndk-build, we just build with scons

**Comment by teamblubee** [comment]
that's causing issues then since updating the toolchain version to 4.9 from 4.8  is causing the static standard library not getting linked in properly. Changing the toolchain to 4.8 it errors out really early because there is no 4.8 tools in my r11 ndk but at 4.9 the build goes for a while then fails linking with the above error.

We have to synchronize the gcc and toolchain version, I think.

```scons
			('ANDROID_NDK_ROOT', 'the path to Android NDK', os.environ.get("ANDROID_NDK_ROOT", 0)),
			('NDK_TOOLCHAIN', 'toolchain to use for the NDK',"arm-eabi-4.4.0"),
			('NDK_TARGET', 'toolchain to use for the NDK',"arm-linux-androideabi-4.9"), //-----here
			('NDK_TARGET_X86', 'toolchain to use for the NDK x86',"x86-4.8"),
			('ndk_platform', 'compile for platform: (android-<api> , example: android-15)',"android-15"),
			('android_arch', 'select compiler architecture: (armv7/armv6/x86)',"armv7"),
			('android_neon','enable neon (armv7 only)',"yes"),
			('android_stl','enable STL support in android port (for modules)',"no")
```

**Comment by teamblubee** [comment]
looking at the file platform/android/detect.py

```scons
		env.Append(CPPPATH=[env["ANDROID_NDK_ROOT"]+"/sources/cxx-stl/gabi++/include"])
		env.Append(CPPPATH=[env["ANDROID_NDK_ROOT"]+"/sources/cpufeatures"])
		if env['android_arch']=='x86':
			env.Append(LIBPATH=[env["ANDROID_NDK_ROOT"]+"/sources/cxx-stl/gabi++/libs/x86"])
		elif env["android_arch"]=="armv6":
			env.Append(LIBPATH=[env["ANDROID_NDK_ROOT"]+"/sources/cxx-stl/gabi++/libs/armeabi"])
		elif env["android_arch"]=="armv7":
			env.Append(LIBPATH=[env["ANDROID_NDK_ROOT"]+"/sources/cxx-stl/gabi++/libs/armeabi-v7a"])
		env.Append(LIBS=['gabi++_static'])
		env.Append(CCFLAGS=["-fno-exceptions",'-DNO_SAFE_CAST'])
```

you're looking for a folder 

```shell
ANDROID_NDK_ROOT/sources/cxx_stl/gabi++/libs
```

there is no libs folder under that path.

This is what I see

```bash
blubee:~/sdk/android/android-ndk-r11/sources/cxx-stl/gabi++$ ls
Android.mk  include  NOTICE  repo.prop  sources.mk  src  tests
blubee:~/sdk/android/android-ndk-r11/sources/cxx-stl/gabi++$ 
```

I did notice that if I look under 

```bash
gnu-libstdc++/4.9/ 
```

there is a libs with all the platforms and include directory. I tried changing gabi++ to lib-libstdc++

**Comment by teamblubee** [comment]
actually I just got it to build and link. Let me test it to see if I have a proper working android export template, if it does I'll post the files.

**Comment by teamblubee** [comment]
With these settings I am able to compile the android apks

I am using ndk version r11 which upgraded to toolchain 4.9, that gabi++ stub code is still in the ndk folder the libs folder is missing.

platform/android/detect.py : 25
```bash
	return [
			('ANDROID_NDK_ROOT', 'the path to Android NDK', os.environ.get("ANDROID_NDK_ROOT", 0)),
			('NDK_TOOLCHAIN', 'toolchain to use for the NDK',"arm-eabi-4.4.0"),
			('NDK_TARGET', 'toolchain to use for the NDK',"arm-linux-androideabi-4.9"), //here
			('NDK_TARGET_X86', 'toolchain to use for the NDK x86',"x86-4.8"),
			('ndk_platform', 'compile for platform: (android-<api> , example: android-15)',"android-15"),
			('android_arch', 'select compiler architecture: (armv7/armv6/x86)',"armv7"),
			('android_neon','enable neon (armv7 only)',"yes"),
			('android_stl','enable STL support in android port (for modules)',"no")
	]
```
platform/android/detect.py : 234
```bash
	else:

		env.Append(CPPPATH=[env["ANDROID_NDK_ROOT"]+"/sources/cxx-stl/gnu-libstdc++/4.9/include"])
		env.Append(CPPPATH=[env["ANDROID_NDK_ROOT"]+"/sources/cpufeatures"])
		if env['android_arch']=='x86':
			env.Append(LIBPATH=[env["ANDROID_NDK_ROOT"]+"/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86"])
		elif env["android_arch"]=="armv6":
			env.Append(LIBPATH=[env["ANDROID_NDK_ROOT"]+"/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi"])
		elif env["android_arch"]=="armv7":
			env.Append(LIBPATH=[env["ANDROID_NDK_ROOT"]+"/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a"])
		env.Append(LIBS=['gnustl_static'])
		env.Append(CCFLAGS=["-fno-exceptions",'-DNO_SAFE_CAST'])
```

**Comment by teamblubee** [comment]
@reduz did you take a look at the above post, this will allow godot to build on android now. Can you update the files?

**Comment by akien-mga** [comment]
Well if you know how to fix it it's best if you make a pull request.

**Comment by teamblubee** [comment]
I just made a pull request, it's going through the travis build system currently. It might fail because some new environmental variables needs to be exported.

**Comment by KelinciFX** [comment]
To be honest, I already used GCC 4.9 and G++ 4.9 that comes with NDK-r10e for around one year. Before compiling android, I always change detect.py in order to get used by gcc g++ 4.9. So, I never used that 4.8 for my libgodot_android.so

What I do is simple enough. Just change arm-linux-androideabi-4.8 to arm-linux-androideabi-4.9. There are 9 lines (in platform/android/detect.py) that need to be changed and do not need anything else. This way always work (at least for me).

:-)

**Comment by teamblubee** [comment]
okay i submitted a pull request that passed on all platforms. @reduz can you merge pull request #4104

**Comment by teamblubee** [comment]
I guess this issue can be closed now.

**Comment by akien-mga** [comment]
Fixed by #4104.
