### ISSUE TITLE
Unable to compile template with MinGW

### ISSUE THREAD

**Issue by MmAaXx500** [godotengine/godot#52318]
### Godot version

4.0.dev 4c3f7d1

### System information

Windows 10 21H1

### Issue description

Unable to compile `debug` and `release_debug` template with MinGW on Windows 10 because of the following error:
```
b'In file included from ./core/templates/hash_map.h:34,
                 from ./core/object/object.h:38,

    from ./core/variant/binder_common.h:35,
                 from ./core/object/method_bind.h:34,
                 from ./core/object/class_db.h:34,
                 from ./core/object/ref_counted.h:34,
                 from ./servers/text_server.h:34,
                 from modules\\text_server_adv\\text_server_adv.h:39,
                 from modules\\text_server_adv\\text_server_adv.cpp:31:
modules\\text_server_adv\\text_server_adv.cpp: In member function \'bool TextServerAdvanced::_ensure_cache_for_size(TextServerAdvanced::FontDataAdvanced*, const Vector2i&) const\':
./core/string/ustring.h:526:22: error: invalid cast to function type \'String()\'
  526 | #define TTR(m_value) (String())
./core/error/error_macros.h:94:26: note: in definition of macro \'DEBUG_STR\'
   94 | #define DEBUG_STR(m_msg) m_msg
      |                          ^~~~~
modules\\text_server_adv\\text_server_adv.cpp:1234:4: note: in expansion of macro \'ERR_FAIL_COND_V_MSG\'
 1234 |    ERR_FAIL_COND_V_MSG(error != 0, false, TTR("FreeType: Error initializing library:") + " \'" + String(FT_Error_String(error)) + "\'.");
      |    ^~~~~~~~~~~~~~~~~~~
modules\\text_server_adv\\text_server_adv.cpp:1234:43: note: in expansion of macro \'TTR\'
 1234 |    ERR_FAIL_COND_V_MSG(error != 0, false, TTR("FreeType: Error initializing library:") + " \'" + String(FT_Error_String(error)) + "\'.");
      |
  ^~~
./core/string/ustring.h:526:22: error: invalid cast to function type \'String()\'
  526 | #define TTR(m_value) (String())
./core/error/error_macros.h:94:26: note: in definition of macro \'DEBUG_STR\'
   94 | #define DEBUG_STR(m_msg) m_msg
      |                          ^~~~~
modules\\text_server_adv\\text_server_adv.cpp:1252:4: note: in expansion of macro \'ERR_FAIL_V_MSG\'
 1252 |    ERR_FAIL_V_MSG(false, TTR("FreeType: Error loading font:") + " \'" + String(FT_Error_String(error)) + "\'.");
      |    ^~~~~~~~~~~~~~
modules\\text_server_adv\\text_server_adv.cpp:1252:26: note: in expansion of macro \'TTR\'
 1252 |    ERR_FAIL_V_MSG(false, TTR("FreeType: Error loading font:") + " \'" + String(FT_Error_String(error)) + "\'.");
      |                          ^~~
'
```
This error introduced with 4c3f7d1

### Steps to reproduce

Checkout 4c3f7d1 and `scons platform=windows target=debug use_mingw=yes tools=no`

**Comment by bruvzg** [comment]
Added fix #52292. Translations should use `RTR` not `TTR`, to work with both tools and template builds.

**Comment by MmAaXx500** [comment]
@bruvzg Works for me, thanks!
