### ISSUE TITLE
Compilation errors AF_INET undeclared (lws_peer.cpp, socket_helpers.h)

### ISSUE THREAD

**Issue by robfram** [godotengine/godot#18317]
**Godot version:**
7d6f210ccb5de9ef414f94ad42f9f3dea14c0493 but probably fails since 1710582473330dc6e7758953e3378187b5e3f226 or so.

**OS/device including version:**
FreeBSD 11.1-RELEASE-p4

**Issue description:**
Compilation fails:

```
[ 55%] Compiling ==> drivers/unix/os_unix.cpp
In file included from modules/websocket/lws_peer.cpp:40:
./drivers/unix/socket_helpers.h:58:24: error: use of undeclared identifier
      'AF_INET6'
                addr6->sin6_family = AF_INET6;
                                     ^
./drivers/unix/socket_helpers.h:69:23: error: use of undeclared identifier
      'AF_INET'
                addr4->sin_family = AF_INET;
                                    ^
./drivers/unix/socket_helpers.h:81:23: error: use of undeclared identifier
      'AF_INET'
                addr4->sin_family = AF_INET;

[...]

./drivers/unix/socket_helpers.h:140:34: error: use of undeclared identifier
      'AF_INET6'
        } else if (p_addr->ss_family == AF_INET6) {
                                        ^
modules/websocket/lws_peer.cpp:197:12: error: use of undeclared identifier
      'getpeername'
        int ret = getpeername(fd, (struct sockaddr *)&addr, &len);
                  ^
modules/websocket/lws_peer.cpp:216:12: error: use of undeclared identifier
      'getpeername'
        int ret = getpeername(fd, (struct sockaddr *)&addr, &len);
                  ^
13 errors generated.
scons: *** [modules/websocket/lws_peer.x11.tools.64.llvm.o] Error 1
scons: building terminated because of errors.
```

All symbols are defined in `<sys/socket.h>`, but nor `modules/websocket/lws_peer.cpp` nor `drivers/unix/socket_helpers.h` include `<sys/socket.h>`. 

For example, adding `#include <sys/socket.h>` to `socket_helpers.h:36`solves the problem.

**Steps to reproduce:**
```
$ time scons -c platform=x11 use_llvm=yes -j 4
$ time scons platform=x11 use_llvm=yes -j 4
```

**Comment by akien-mga** [comment]
CC @Faless
