### PR TITLE
Compress embedded GDExtension interface

### PR DESCRIPTION
**Pull request by RedworkDE**
Stops older MSCV compiler versions from failing to build because of the huge string literal and saves about 60kb in the final executable.

Code largely follows that same patterns as `make_doc_header` and `make_certs_header`.

### CODE REVIEW

**Comment by YuriSizov** [comment]
So, what prompted this PR is that I reported that I can no longer build master after https://github.com/godotengine/godot/pull/76406. I use MSVC 14.2 (builds tools from Visual Studio 2019), and I encountered this issue:

> core/extension/gdextension_interface_dump.gen.h(1589): fatal error C1091: compiler limit: string exceeds 65535 bytes in length

I can confirm that with this patch applied my builds can continue past the point of previous error.

**Comment by dsnopek** [comment]
I built and tested `godot --dump-gdextension-interface` with this PR, and it worked as expected! So, from a GDExtension perspective, this looks good.

Comparing the new code with `make_doc_header()` in the buildsystem and `DocTools::load_compressed()` in the engine, it does really look the same.

**Review by YuriSizov — APPROVED** [review]
Approving it then, tentatively :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
