### ISSUE TITLE
New webp driver does not build on linux with gcc 4.9.2

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#2995]
The error is:
```
drivers/webp/enc/webpenc.c: In function 'WebPEncode':
drivers/webp/enc/webpenc.c:324:14: error: 'WebPConfig' has no member named 'exact'
   if (!config->exact) {
              ^
```

Seen on Mageia 5, x86_64.
GCC 4.9.2, glibc 2.20.

**Comment by bojidar-bg** [comment]
Can confirm on 98c54827ae4696b0d9a4c56a2879ac294a79fe11.

Seems like a regression from da113fe40d0a9410859912473d53e43903dc6c8e.

**Comment by akien-mga** [comment]
@fry- reports that it builds fine for him on Fedora with GCC 5.1.1.

**Comment by bojidar-bg** [comment]
I'm on GCC 5.2.0 :smile:

**Comment by akien-mga** [comment]
If I comment out the offending line, it throws out some other errors:
```
drivers/webp/enc/alpha.c: In function 'ApplyFiltersAndEncode':
drivers/webp/enc/alpha.c:266:12: error: 'WebPAuxStats' has no member named 'lossless_hdr_size'
       stats->lossless_hdr_size = best.stats.lossless_hdr_size;
            ^
drivers/webp/enc/alpha.c:266:44: error: 'WebPAuxStats' has no member named 'lossless_hdr_size'
       stats->lossless_hdr_size = best.stats.lossless_hdr_size;
                                            ^
drivers/webp/enc/alpha.c:267:12: error: 'WebPAuxStats' has no member named 'lossless_data_size'
       stats->lossless_data_size = best.stats.lossless_data_size;
            ^
drivers/webp/enc/alpha.c:267:45: error: 'WebPAuxStats' has no member named 'lossless_data_size'
       stats->lossless_data_size = best.stats.lossless_data_size;
                                             ^
```

**Comment by DerRidda** [comment]
I'm seeing the same multiple WebP related compile errors on Ubuntu with GCC 5.2.1.

**Comment by nounoursheureux** [comment]
Same error with Clang++ v.3.7.0 on ArchLinux

**Comment by TeddyDD** [comment]
Seems like the same error under Arch ```drivers/webp/enc/webpenc.c: In function 'WebPEncode':
drivers/webp/enc/webpenc.c:324:14: error: 'WebPConfig {aka const struct WebPConfig}' has no member named 'exact'
   if (!config->exact) {
              ^
drivers/webp/enc/webpenc.c:335:14: warning: implicit declaration of function 'WebPPictureSmartARGBToYUVA' [-Wimplicit-function-declaration]
         if (!WebPPictureSmartARGBToYUVA(pic)) {
              ^
scons: *** [drivers/webp/enc/webpenc.x11.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by hetdegon** [comment]
Can confirm the same error ('exact' not being a member) on Ubuntu 15.10.

**Comment by romulox-x** [comment]
Builds fine for me in Ubuntu 13.10 64 bit, gcc 4.8.1

**Comment by reduz** [comment]
Im ubuntu 14.04 and windows 10 and it works. It also works with the android
compiler
