### ISSUE TITLE
Unit tests fail under `lldb` supervision

### ISSUE THREAD

**Issue by Ivorforce** [godotengine/godot#105097]
### Tested versions

a210fe6dbd27cc01bffacb0ce2816e0cf303af5e / 4.0+

### System information

Godot v4.4.1.stable - macOS Sequoia (15.3.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

When using `lldb`, `test_os.h` fails `[OS] Execute`.
This is a regression from https://github.com/godotengine/godot/pull/42069 (4.0), cc @Calinou.

### Steps to reproduce

1. Be on macOS (may fail on linux too)
2. run  `❯ lldb bin/godot.macos.editor.arm64 -- --test`
3. run `run`
4. Observe the error:

```
./tests/core/os/test_os.h:199: ERROR: CHECK( exit_code == 0 ) is NOT correct!
  values: CHECK( 230 == 0 )
  logged: Running the command `sh -c "ls > /dev/null"` returns a zero (successful) exit code.

Process 42405 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x1005063b0)
    frame #0: 0x00000001005063b0 godot.macos.editor.arm64.master`TestOS::DOCTEST_ANON_FUNC_4825() at test_os.h:197:2 [opt]
   194          CHECK_MESSAGE(
   195                          err == OK,
   196                          "(Running the command `sh -c \"ls > /dev/null\"` returns the expected Godot error code (OK).");
-> 197          CHECK_MESSAGE(
   198                          exit_code == 0,
   199                          "Running the command `sh -c \"ls > /dev/null\"` returns a zero (successful) exit code.");
   200  #endif
Target 0: (godot.macos.editor.arm64.master) stopped.
warning: godot.macos.editor.arm64.master was compiled with optimization - stepping may behave oddly; variables may not be available.
```

The rest of the unit tests run through, so deleting the test is a temporary fix.

### Minimal reproduction project (MRP)

N/A

**Comment by PhairZ** [comment]
I don't really know how this works, but I've tested this on a WSL Environment and this is what I got:
```
Process 38477 launched: '/home/seif-eldin/repos/godot/bin/godot.linuxbsd.editor.dev.x86_64.llvm' (x86_64)
Process 38477 stopped and restarted: thread 1 received signal: SIGCHLD
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
tERROR: Unrecognized binary resource file: 'res://gltf_placed_in_dot_godot_imported.scn'.
   at: open (./core/io/resource_format_binary.cpp:1002)
ERROR: EditorNode doesn't exist.
   at: make_scene_preview (./editor/editor_interface.cpp:236)
ERROR: Unrecognized binary resource file: 'res://gltf_pointing_to_texture_outside_of_res_folder.scn'.
   at: open (./core/io/resource_format_binary.cpp:1002)
ERROR: EditorNode doesn't exist.
   at: make_scene_preview (./editor/editor_interface.cpp:236)
ERROR: Unrecognized binary resource file: 'res://embedded_texture.scn'.
   at: open (./core/io/resource_format_binary.cpp:1002)
ERROR: EditorNode doesn't exist.
   at: make_scene_preview (./editor/editor_interface.cpp:236)
Process 38477 stopped and restarted: thread 1 received signal: SIGCHLD
===============================================================================
[doctest] test cases:    1216 |    1216 passed | 0 failed | 3 skipped
[doctest] assertions: 2441777 | 2441777 passed | 0 failed |
[doctest] Status: SUCCESS!
Process 38477 exited with status = 0 (0x00000000) 
```
So probably MacOS only

**Comment by bruvzg** [comment]
I can reproduce it, but not sure what's the reason, seems like `fork` fail under LLDB.
