### PR TITLE
Various coverity scan fixes, WS FreeBSD fixes

### LINKED ISSUE #18317: Compilation errors AF_INET undeclared (lws_peer.cpp, socket_helpers.h)
**Godot version:**
7d6f210ccb5de9ef414f94ad42f9f3dea14c0493 but probably fails since 1710582473330dc6e7758953e3378187b5e3f226 or so.

**OS/device including version:**
FreeBSD 11.1-RELEASE-p4

**Issue description:**
Compilation fails:

```
[ 55%] Compiling ==> drivers/unix/os_unix.cpp
In file included from modules/websocket/lws_peer.cpp:40:
./drivers/unix/socket_helpers.h:58:24: error: use of undeclared identifier
      'AF_INET6'
                addr6->sin6_family = AF_INET6;
                                     ^
./drivers/unix/socket_helpers.h:69:23: error: use of undeclared identifier
      'AF_INET'
                addr4->sin_family = AF_INET;
                                    ^
./drivers/unix/socket_helpers.h:81:23: error: use of undeclared identifier
      'AF_INET'
                addr4->sin_family = AF_INET;

[...]

./drivers/unix/socket_helpers.h:140:34: error: use of undeclared identifier
      'AF_INET6'
        } else if (p_addr->ss_family == AF_INET6) {
                                        ^
modules/websocket/lws_peer.cpp:197:12: error: use of undeclared identifier
      'getpeername'
        int ret = getpeername(fd, (struct sockaddr *)&addr, &len);
                  ^
modules/websocket/lws_peer.cpp:216:12: error: use of undeclared identifier
      'getpeername'
        int ret = getpeername(fd, (struct sockaddr *)&addr, &len);
                  ^
13 errors generated.
scons: *** [modules/websocket/lws_peer.x11.tools.64.llvm.o] Error 1
scons: building terminated because of errors.
```

All symbols are defined in `<sys/socket.h>`, but nor `modules/websocket/lws_peer.cpp` nor `drivers/unix/socket_helpers.h` include `<sys/socket.h>`. 

For example, adding `#include <sys/socket.h>` to `socket_helpers.h:36`solves the problem.

**Steps to reproduce:**
```
$ time scons -c platform=x11 use_llvm=yes -j 4
$ time scons platform=x11 use_llvm=yes -j 4
```

### PR DESCRIPTION
**Pull request by Faless**
Various Coverity scan fixes.

Fix compilation error on *BSD with recent websocket module update.
Closes #18317 .

### CODE REVIEW

File: drivers/unix/ip_unix.cpp [hunk 1]
```diff
@@ -101,7 +101,7 @@ IP_Address IP_Unix::_resolve_hostname(const String &p_hostname, Type p_type) {
 		hints.ai_family = AF_UNSPEC;
 		hints.ai_flags = AI_ADDRCONFIG;
 	};
-	hints.ai_flags &= !AI_NUMERICHOST;
+	hints.ai_flags &= ~AI_NUMERICHOST;
```
Comment (Faless) [inline drivers/unix/ip_unix.cpp]: :alarm_clock: 
Apparently, up until now, we have been always setting `ai_flags` to `0`.
This was a mistake I introduced when trying to fix some address resolution issues when IPv6 and IPv4 where both active.
This might introduce regressions on some platform, we might just go for `ai_flags = 0` always since it always worked for us, but I figure it would be better to actually let the system recognize the preferred IP type if that does not cause troubles.
:alarm_clock:

Comment (akien-mga) [reply drivers/unix/ip_unix.cpp]: Since setting it to `0` was a mistake, I'd say let's fix it and see what happens. This should probably not be cherry-picked for *3.0* though to prevent possible regressions in stable - in *master* we can cope with them :)
