### PR TITLE
GDScript 2.0 enum fixes

### LINKED ISSUE #45558: Size() function on named enum is broken in gdscript 2.0
**Godot version:**
4.0 nightly from calinou website

**OS/device including version:**
windows 10

**Issue description:**
I got the error message:

> "Cannot find value "size in "ENUM_NAME (enum)".

Expected the `ENUM_NAME.size()` method to work like in godot 3.2

**Steps to reproduce:**
Make an enum and try to call .size() method on it

**Minimal reproduction project:**

```
enum ENUM_NAME {
	VALUE_1,
	VALUE_2,
}

func _ready():
        print(ENUM_NAME.size())
```

### LINKED ISSUE #49357: Assigning enum-typed function argument to a variable triggers error (GDScript 2)
**Godot version:**
master branch, commit 94c31ba3

**OS/device including version:**
Linux Mint 20.1

**Issue description:**
When trying to assign an enum value to a variable from a function argument typed to that enum, an incoherent error occurs: `Cannot assign a value of type MyEnum (enum) to a target of type MyEnum (enum)`
Removing the type from the argument does not trigger an error.

**Steps to reproduce:**
Run the following script:
``` GDScript
extends Node

enum MyEnum {ONE, TWO, THREE}

var test: MyEnum = MyEnum.ONE

func myfunc(myvar: MyEnum) -> void: # no error with func myfunc(myvar) -> void:
	test = myvar
```

**Minimal reproduction project:**
None. Using the above script is enough to reproduce.

### LINKED ISSUE #50293: GDScript 2.0: Enum values can't be compared to variable integers
### Godot version

v4.0.dev.calinou [bfc14a635]

### System information

Windows 10

### Issue description

Once comparing an enum against an integer in code it will be marked as an error. I am assuming that this is a regression since it did work in GDScript 1.0 (Godot 3.x). Note that this behaviour occurs regardless of the enum value having an integer value assigned to it.

### Steps to reproduce

Compare an enum value against an integer inside a GDScript file (see below)

### Minimal reproduction project

Create a new GDScript file inside the engine and paste the following:
```
enum SomeEnum {
	VALUE = 1
}

func function():
	if 0 == SomeEnum.VALUE:
		pass
	
	const integer_const: int = 1
	if integer_const == SomeEnum.VALUE:
		pass
	
	var integer_var: int = 1
	if integer_var == SomeEnum.VALUE: # Error
		pass
```

### PR DESCRIPTION
**Pull request by MarianoGnu**
This PR aims to fix many issues with ENUMs reported:
Fixes godotengine/godot#45558
Fixes godotengine/godot#49357
Fixes godotengine/godot#50293

### CODE REVIEW

File: modules/gdscript/gdscript_analyzer.cpp [hunk 1]
```diff
@@ -1717,11 +1717,21 @@ void GDScriptAnalyzer::reduce_binary_op(GDScriptParser::BinaryOpNode *p_binary_o
 
 	GDScriptParser::DataType left_type;
 	if (p_binary_op->left_operand) {
-		left_type = p_binary_op->left_operand->get_datatype();
+		if (p_binary_op->left_operand->is_constant && p_binary_op->left_operand->reduced) {
```
Comment (RandomShaper) [inline modules/gdscript/gdscript_analyzer.cpp:1720]: Not sure about the `&& p_binary_op->left_operand->reduced` part. Shouldn't it have been reduced for sure at that point? If so, moving that part of the condition into a `CRASH_COND` or a less harsh `WARN_PRINT` would be better. That would help catching bugs in GDScript.

File: modules/gdscript/gdscript_analyzer.cpp [hunk 2]
```diff
@@ -2351,7 +2361,10 @@ void GDScriptAnalyzer::reduce_identifier_from_base(GDScriptParser::IdentifierNod
 				result.enum_type = name;
 				p_identifier->set_datatype(result);
 			} else {
-				push_error(vformat(R"(Cannot find value "%s" in "%s".)", name, base.to_string()), p_identifier);
+				// Consider as a Dictionary
```
Comment (RandomShaper) [inline modules/gdscript/gdscript_analyzer.cpp:2364]: Maybe a _TODO_ based on what you discussed at #45558 would help catching this as not fully solved.

**Review by RandomShaper — APPROVED** [review]
Besides the comments, this looks good!

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (MarianoGnu) [reply modules/gdscript/gdscript_analyzer.cpp:1720]: Oh, that is probably me missunderstanding the meaning of **reduced**. Will remove it 👍

File: modules/gdscript/gdscript_analyzer.cpp (hunk 2 above)
Comment (MarianoGnu) [reply modules/gdscript/gdscript_analyzer.cpp:2362]: I dont know enough "git" to ammend a previous commit in the branch 😅 but i will put this if i am asked to squash everything

File: modules/gdscript/gdscript_analyzer.cpp (hunk 1 above)
Comment (RandomShaper) [reply modules/gdscript/gdscript_analyzer.cpp]: Maybe I'm on the same boat. I'm just trying to be sure that we who didn't write GDScript understand the role of every piece.

File: modules/gdscript/gdscript_analyzer.cpp (hunk 2 above)
Comment (vnen) [reply modules/gdscript/gdscript_analyzer.cpp:2362]: I'm not super fond of this because it looks to me like it would allow arbitrary changes to an enum that supposedly should be constant. While it's a dictionary behind the curtain, it shouldn't be used like so.

Although I do want to do some changes on how enum works, so we could merge it like this for now and I change it later when I get to it.

**Comment by vnen** [comment]
If you could add some test cases for this (see [GDScript test docs](https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html#integration-tests-for-gdscript) to confirm the issues are fixed it would be great.

**Comment by akien-mga** [comment]
@MarianoGnu Will you be able to add some test cases as requested? Or should this be merged and test cases added in a follow up PR?

**Review by akien-mga — APPROVED** [review]
As discussed with @vnen on Rocket Chat, let's merge as is and improve the enum test suite later.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Welp, even without new tests, this should have been rebased to pass the GDScript test suite. It's failing: https://github.com/godotengine/godot/runs/3758512075?check_suite_focus=true

**Comment by akien-mga** [comment]
I reverted commit 62077086076fb99fb7fe014522c44ae83f87dc4d which caused the regression (but kept the other two commits merged). See d2b8560d7a871a7bab27e68835f86e69e47e79ad.
