### ISSUE TITLE
Godot 3.2.4 RC5 fails to build on FreeBSD

### ISSUE THREAD

**Issue by nonfatmatt** [godotengine/godot#46998]
**Godot version:**
1d0929a

**OS/device including version:**
FreeBSD 13-RC2 / AMD64

**Issue description:**

Build process seems to hang multiple times on pthreads.

`
[Initial build] Compiling ==> drivers/gles3/rasterizer_scene_gles3.cpp
drivers/unix/thread_posix.cpp: In function 'Error set_name(const String&)':
drivers/unix/thread_posix.cpp:53:2: error: 'pthread_set_name_np' was not declared in this scope; did you mean 'pthread_setname_np'?
   53 |  pthread_set_name_np(running_thread, p_name.utf8().get_data());
      |  ^~~~~~~~~~~~~~~~~~~
      |  pthread_setname_np
scons: *** [drivers/unix/thread_posix.x11.tools.64.o] Error 1
`

**Steps to reproduce:*
Clone latest Godot 3.2.4 from git. Build with scons -j8 builtin-libvpx=False pulseaudio=False platform=x11

also will fail when adding use_llvm=yes to the command line.

**Comment by akien-mga** [comment]
I remember fixing this in the past, must have regressed in #45618.

**Comment by akien-mga** [comment]
Is this error new in 3.2.4 RCs or do you have the same build issue with 3.2.3-stable? Did it work in the past, and if so did you get a FreeBSD system update that could have changed the `pthread` API?

Last time this code changed was to fix NetBSD support in #42157. My understanding was that both OpenBSD and FreeBSD use `pthread_set_name_np`:

- https://man.openbsd.org/pthread_set_name_np
- https://www.freebsd.org/cgi/man.cgi?query=pthread_set_name_np&apropos=0&sektion=3&manpath=FreeBSD+13.0-current&arch=default&format=html

**Comment by akien-mga** [comment]
Right it's #45618 which broke it, @RandomShaper was a bit heavy handed and removed:
```cpp
#ifdef PTHREAD_BSD_SET_NAME
#include <pthread_np.h>
#endif
```

**Comment by nonfatmatt** [comment]
I've successfully built 3.2.3 stable from ports, which doesn't kick up any errors.

**Comment by akien-mga** [comment]
Did you check that my PR does fix the issue?

**Comment by nonfatmatt** [comment]
Sorry, was fumbling around and accidentally fatfingered the close issue button. AFAIK now it still doesn't work but I pulled the source from 3.2 master branch, so maybe I didn't get your parch?  I'm not a regular user of github.

This is what I get from building as of pulling the main 3.2 branch about 10 minutes ago:

`[Initial build] Linking Static Library ==> modules/libmodules.x11.tools.64.a
drivers/unix/thread_posix.cpp: In function 'Error set_name(const String&)':
drivers/unix/thread_posix.cpp:53:2: error: 'pthread_set_name_np' was not declared in this scope; did you mean 'pthread_setname_np'?
   53 |  pthread_set_name_np(running_thread, p_name.utf8().get_data());
      |  ^~~~~~~~~~~~~~~~~~~
      |  pthread_setname_np
[Initial build] Compiling ==> drivers/alsa/asound-so_wrap.c
[Initial build] Compiling ==> drivers/alsa/audio_driver_alsa.cpp
[Initial build] Compiling ==> drivers/coreaudio/audio_driver_coreaudio.cpp
scons: *** [drivers/unix/thread_posix.x11.tools.64.o] Error 1
`

It's indeed possible that BSD updated the pthread library was changed, but to make sure this was a regression I built 3.2.3 stable from the ports tree last night. So, even though I'm using a RC level BSD Kernel / Libraries that one still builds, as long as you tell it not to use built-in libvpx.

**Comment by nonfatmatt** [comment]
However, now that I look at it, the pthread errors *seem* to be related to built-in libraries so maybe I can try building it using external versions.

**Comment by nonfatmatt** [comment]
Sorry @akien-mga I fat-fingered the close button. Issue now closed, PR works. I just didn't pull the PR correctly. I really need to read some git tutorials.

Anyhow, I just manually changed the file with your PR and it seems to work, so I'm sure it's good to go. About the issue with FreeBSD changing their libraries, 3.2.3 builds just fine even on the new FreeBSD 13 so I don't think they actually mucked around with pthreads.
