### ISSUE TITLE
Linking issue cross-compiling with MinGW 5.0.4 / GCC 8.2.0 on Arch Linux

### ISSUE THREAD

**Issue by pokemonchw** [godotengine/godot#21096]
**Godot version:**

3.0.5/3.1

**OS/device including version:**

archlinux

**Issue description:**

I need to add a module to godot
And I smoothly compiled the Linux version.
But there was a problem in compiling the Windows version through MinGW.
What should I do now?
```
[100%] Linking Program        ==> bin/godot.windows.tools.64.exe
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2.o: in function `__tmainCRTStartup':
/tmp/yaourt-tmp-byayoi/aur-mingw-w64-crt/src/mingw-w64-v5.0.4/mingw-w64-crt/crt/crtexe.c:294: undefined reference to `__p__acmdln'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: platform/windows/godot_win.windows.tools.64.o: in function `wprintf':
/usr/x86_64-w64-mingw32/include/stdio.h:937: undefined reference to `__imp___acrt_iob_func'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: platform/windows/os_windows.windows.tools.64.o: in function `RedirectIOToConsole()':
/home/byayoi/godot/platform/windows/os_windows.cpp:146: undefined reference to `__imp___acrt_iob_func'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/byayoi/godot/platform/windows/os_windows.cpp:148: undefined reference to `__imp___acrt_iob_func'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/byayoi/godot/platform/windows/os_windows.cpp:158: undefined reference to `__imp___acrt_iob_func'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /home/byayoi/godot/platform/windows/os_windows.cpp:160: undefined reference to `__imp___acrt_iob_func'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: platform/windows/os_windows.windows.tools.64.o:/home/byayoi/godot/platform/windows/os_windows.cpp:170: more undefined references to `__imp___acrt_iob_func' follow
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-merr.o): in function `_matherr':
/tmp/yaourt-tmp-byayoi/aur-mingw-w64-crt/src/mingw-w64-v5.0.4/mingw-w64-crt/crt/merr.c:72: undefined reference to `__acrt_iob_func'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-pseudo-reloc.o): in function `__report_error':
/tmp/yaourt-tmp-byayoi/aur-mingw-w64-crt/src/mingw-w64-v5.0.4/mingw-w64-crt/crt/pseudo-reloc.c:149: undefined reference to `__acrt_iob_func'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /tmp/yaourt-tmp-byayoi/aur-mingw-w64-crt/src/mingw-w64-v5.0.4/mingw-w64-crt/crt/pseudo-reloc.c:150: undefined reference to `__acrt_iob_func'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: /usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingwex.a(lib64_libmingwex_a-wassert.o): in function `_wassert':
/tmp/yaourt-tmp-byayoi/aur-mingw-w64-crt/src/mingw-w64-v5.0.4/mingw-w64-crt/misc/wassert.c:53: undefined reference to `__acrt_iob_func'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.tools.64.exe] Error 1
scons: building terminated because of errors.
```

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Sounds like either a MinGW regression (5.0.4 is cutting edge, not tested much) or a setup issue.

@hpvb Any idea?

**Comment by bruvzg** [comment]
Cross-build with MinGW 5.0.4 works fine on macOS ( gcc 8.2.0 ) and Debian unstable ( gcc 7.3.0 ).

`__acrt_iob_func` is Visual Studio 2015+ CRT's internal function for standard I/O, older MSVCRTs use another function name. MinGW can use different versions Visual Studio CRT (`msvcr???.dll`) or Windows default `msvcrt.dll`, probably some part of MinGW was built wrong one.

**Comment by hpvb** [comment]
What scons build line do you use exactly?

**Comment by akien-mga** [comment]
AFAICT that's an issue with Arch Linux's MinGW setup, so it's probably best to discuss it with them directly unless it has been fixed already.
