### PR TITLE
OpenXR: Limit Windows includes to COM interface

### PR DESCRIPTION
**Pull request by Repiteo**
Fixes the following compilation errors that show up when `d3d12=no`
```
Compiling modules\openxr\openxr_api.cpp ...
D:\a\godot4-nightly\godot4-nightly\thirdparty\openxr\include\openxr/openxr_platform.h(565): error C2061: syntax error: identifier 'IUnknown'
D:\a\godot4-nightly\godot4-nightly\thirdparty\openxr\include\openxr/openxr_platform.h(566): error C2061: syntax error: identifier 'IUnknown'
D:\a\godot4-nightly\godot4-nightly\thirdparty\openxr\include\openxr/openxr_platform.h(594): error C2143: syntax error: missing ';' before '*'
D:\a\godot4-nightly\godot4-nightly\thirdparty\openxr\include\openxr/openxr_platform.h(594): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
scons: *** [bin\obj\modules\openxr\openxr_api.windows.editor.dev.x86_64.obj] Error 2
```

### CODE REVIEW

**Review by Bromeon — APPROVED** [review]
Fixes the issue for me locally. Thanks!

Btw, to find what introduced this, I bisected history -- first bad commit 2146b49a49cd504a2247446ba13c761efd5649b5 (#116693).
