### ISSUE TITLE
[Master] Failure to compile using Clang 3.8.1.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#7467]
**Operating system or device - Godot version:**
Ubuntu 16.10 64-bit, Godot 3.0 from master branch (as of latest pull).

**Issue description** (what happened, and what was expected):
Unable to compile using Clang 3.8.1 as it gives an error:
```
clang++ -o drivers/unix/rw_lock_posix.x11.tools.64.llvm.o -c -g2 -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DFREETYPE_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DENABLE_DEPRECATED -DTYPED_METHOD_BIND -DOPENGL_ENABLED -DALSA_ENABLED -DJOYDEV_ENABLED -DPULSEAUDIO_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DGLES_OVER_GL -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DGLAD_ENABLED -DGLES_OVER_GL -D_REENTRANT -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/x11 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/alsa -Ithirdparty/glad drivers/unix/rw_lock_posix.cpp
drivers/unix/rw_lock_posix.cpp:66:9: error: expected expression
        rwlock=PTHREAD_RWLOCK_INITIALIZER;
               ^
/usr/include/pthread.h:133:3: note: expanded from macro 'PTHREAD_RWLOCK_INITIALIZER'
  { { 0, 0, 0, 0, 0, 0, 0, 0, __PTHREAD_RWLOCK_ELISION_EXTRA, 0, 0 } }
  ^
1 error generated.
```

**Steps to reproduce:**
Compile Godot using use_llvm=yes.

**Comment by RameshRavone** [comment]
chaning

rwlock=PTHREAD_RWLOCK_INITIALIZER;

to 

rwlock = (pthread_rwlock_t) PTHREAD_RWLOCK_INITIALIZER;

fixed that.

**Comment by Hinsbart** [comment]
Indeed, this is fixed as of 8ecc34b.
