### ISSUE TITLE
Can't compile without tools

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#3213]
There's an error when compiling the current HEAD without tools enabled. It was introduced in 2db78e8f.

Error message:
```
scene/main/scene_main_loop.cpp:624:24: error: use of undeclared identifier 'edited_scene_root'
        return editor_hint && edited_scene_root && edited_scene_root->is_a_parent_of(p_node);
                              ^
```
 
`edited_scene_root` is only there if `TOOLS_ENABLED` is defined

**Comment by purpleorangegames** [comment]
Confirmed, all my release and debug builds failed.
