### ISSUE TITLE
Cannot link on Windows

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5182]
Sorry, another build-related issue:
When I execute SCons to build Godot, I get this linking error:

```
   Création de la bibliothèque bin\godot.windows.tools.64.lib et de l'objet bin\godot.windows.tools.64.exp
main.windows.tools.64.lib(main.windows.tools.64.obj) : error LNK2019: symbole externe non résolu "char const * * __cdecl tests_get_names(void)" (?tests_get_names@@YAPEAPEBDXZ) référencé dans la fonction "private: static void __cdecl Main::print_help(char const *)" (?print_help@Main@@CAXPEBD@Z)
main.windows.tools.64.lib(main.windows.tools.64.obj) : error LNK2019: symbole externe non résolu "class MainLoop * __cdecl test_main(class String,class List<class String,class DefaultAllocator> const &)" (?test_main@@YAPEAVMainLoop@@VString@@AEBV?$List@VString@@VDefaultAllocator@@@@@Z) référencé dans la fonction "public: static bool __cdecl Main::start(void)" (?start@Main@@SA_NXZ)
bin\godot.windows.tools.64.exe : fatal error LNK1120: 2 externes non résolus
scons: building terminated because of errors.
```

Looks like the linker cannot find `tests_get_names` and `test_main` functions.

**Comment by Zylann** [comment]
Actually I'm developping a script to one-click-build Godot on Windows after clone/pull.
This is what I have at the moment:

```
echo "Building Godot..."
@echo off

rem Setups the Visual Studio 2015 environment variables.
rem vcvarsall.bat is a script that sets up environment variables for Visual Studio.
rem amd64 specifies that we are going to use 64 bits compiler.
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

rem Executes SCons to clean previous build files.
scons platform=windows -c > cmd_build_log.txt

rem Executes SCons to generate the Visual Studio solution.
rem The output of this command is stored in a text file.
rem `>>` appends to existing log file.
scons platform=windows vsproj=yes -c >> cmd_build_log.txt

pause
```
I added `-c`, which removed some files, but it doesn't removes all .obj/.lib files, and the second SCons command appears to be skipped...

**Comment by vnen** [comment]
BTW, what SCons version you are using?

**Comment by Zylann** [comment]
I installed it last month.
```
D:\>scons -version
SCons by Steven Knight et al.:
        script: v2.5.0.rel_2.5.0:3544:95d356f188a3[MODIFIED], 2016/04/09 14:38:50, by bdbaddog on ubuntu1404-32bit
        engine: v2.5.0.rel_2.5.0:3544:95d356f188a3[MODIFIED], 2016/04/09 14:38:50, by bdbaddog on ubuntu1404-32bit
        engine path: ['C:\\Python27\\Lib\\site-packages\\scons-2.5.0\\SCons']
Copyright (c) 2001 - 2016 The SCons Foundation
```

**Comment by vnen** [comment]
@Zylann can you try to downgrade to 2.4.1? This is not the same error as #5042, but it might be related to SCons version too.

**Comment by Zylann** [comment]
```bat
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
scons platform=windows vsproj=yes > cmd_build_log2.txt
pause
```
```
main.windows.tools.64.lib(main.windows.tools.64.obj) : error LNK2019: symbole externe non résolu "char const * * __cdecl tests_get_names(void)" (?tests_get_names@@YAPEAPEBDXZ) référencé dans la fonction "private: static void __cdecl Main::print_help(char const *)" (?print_help@Main@@CAXPEBD@Z)
main.windows.tools.64.lib(main.windows.tools.64.obj) : error LNK2019: symbole externe non résolu "class MainLoop * __cdecl test_main(class String,class List<class String,class DefaultAllocator> const &)" (?test_main@@YAPEAVMainLoop@@VString@@AEBV?$List@VString@@VDefaultAllocator@@@@@Z) référencé dans la fonction "public: static bool __cdecl Main::start(void)" (?start@Main@@SA_NXZ)
bin\godot.windows.tools.64.exe : fatal error LNK1120: 2 externes non résolus
scons: building terminated because of errors.
```
Didn't fixed.

I see there are still .obj files scattered everywhere even after cleaning (although the build produces .64.obj files).

I also notice that my .bat file still terminates before the `pause` statement, as if scons was closing the console after execution Oo

**Comment by vnen** [comment]
I have no idea what's going on here. Have you tried a clean clone too?

**Comment by Zylann** [comment]
I tried by cloning the repo and it worked... well, I hope I won't have to do this everytime :s

Hmm but the console still closes without reaching pause (I need help for this part because it could  simplify Visual Studio development down to a few clicks).

On my original repo I also tried to delete ALL .obj, .lib, .pyc and .exe files, run scons clean, then `git pull upstream master`, try to compile again by outputting the log in a file...
But it resulted in the same error. In the process, the Windows console dropped a random "unable to do something with a file, already used by process" thing (not telling which file is the most useful error message ever :p), and because it didn't printed it in the log I cannot see when it happened or if it has to do with my problem.

**Comment by vnen** [comment]
You're not the only one (see #5276). I'll keep this open for reference, but I'm still completely clueless about it.

**Comment by ragas** [comment]
Did a clean by 
`scons platform=windows target=release_debug  -c`

Compile got this error

```
.\drivers/gles2/rasterizer_gles2.h(55): fatal error C1083: Cannot open include file: 'drivers/gles2/shaders/canvas.glsl.h': No such file or directory
scons: *** [platform\windows\os_windows.windows.opt.tools.64.obj] Error 2
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xlocale(341): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\exception(358): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
scons: building terminated because of errors.
```

**Comment by vnen** [comment]
@ragas this is the same as #5042, a problem with parallel builds with SCons >= 2.5.0.

**Comment by ragas** [comment]
ok so did the clean again
and this time it worked !
I did `scons platform=windows target=release_debug  -c` and then did a checkout on `SCsub` file because it seems to have deleted somehow
Did not have to do any clean git clone. Hope this helps.

**Comment by Zylann** [comment]
I am able to build normally nowadays in one click from QtCreator, so I guess this can be closed
