### PR TITLE
Fix build on Python <3.7: helper modules declaration compat

### LINKED ISSUE #56778: Fresh first time scons compilation failing
### Godot version

4.0 dev

### System information

Ubuntu 18

### Issue description

My fresh cloning and scons compilation is failing.

**godot/@$ scons platform=linuxbsd**
```
scons: Reading SConscript files ...
Note: Building a debug binary (which will run slowly). Use `target=release_debug` to build an optimized release binary.
AttributeError: module 'editor' has no attribute 'template_builders':
  File "/tmp/godot/SConstruct", line 764:
    SConscript("modules/SCsub")
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/tmp/godot/modules/SCsub", line 46:
    SConscript(name + "/SCsub")  # Built-in.
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/tmp/godot/modules/gdscript/SCsub", line 25:
    SConscript("editor_templates/SCsub")
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/scons/SCons/Script/SConscript.py", line 256:
    call_stack[-1].globals)
  File "/tmp/godot/modules/gdscript/editor_templates/SCsub", line 5:
    import editor.template_builders as build_template_gd
```

### Steps to reproduce

git clone 'godot repo'

cd godot

scons platform=linuxbsd

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by touilleMan**
see https://github.com/godotengine/godot/pull/56698#issuecomment-1012260428

<i>Bugsquad edit</i>:
- Fix https://github.com/godotengine/godot/issues/56778

### CODE REVIEW

**Comment by akien-mga** [comment]
That's starting to be a lot of code to workaround the need to duplicate a single file, or actually use SCons' `site-scons` feature :|

But well, if it works, it works. We can always clean up later ;)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
