### PR TITLE
Add special compat methods for EditorFileDialog enum functions 

### PR DESCRIPTION
**Pull request by Bromeon**
While the general derived-to-base compat mechanism works, there seems to be a problem when enum types are also moved between classes. This commit restores the original enums as dummies in the derived class, to restore compatibility.

Fixes compatibility breakage introduced by #111212.

---

Earlier implementation via compat methods: https://github.com/godotengine/godot/commit/25f21edfc4109d9f82294d554a0daaee44f7096a
Current approach uses the hardcoded special mapping, due to problem with C# codegen.

### CODE REVIEW

File: editor/gui/editor_file_dialog.h [hunk 1]
```diff
@@ -52,8 +52,27 @@ class EditorFileDialog : public FileDialog {
...
+	FileMode _get_file_mode_compat_113524() const;
+	void _set_file_mode_compat_113524(FileMode p_mode);
+
+	static void _bind_compatibility_methods();
 #endif
 };
+
+VARIANT_ENUM_CAST(EditorFileDialog::Access);
+VARIANT_ENUM_CAST(EditorFileDialog::DisplayMode);
+VARIANT_ENUM_CAST(EditorFileDialog::FileMode);
```
Comment (KoBeWi) [inline editor/gui/editor_file_dialog.h]: This also needs to be wrapped in DISABLE_DEPRECATED.

**Comment by Bromeon** [comment]
I'm not quite sure about the [C# errors](https://github.com/godotengine/godot/actions/runs/19906651560/job/57064552192?pr=113524#step:17:89):
```
Error: /home/runner/work/godot/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorFileDialog.cs(101,16):
error CS0108: 'EditorFileDialog.GetFileMode()' hides inherited member 'FileDialog.GetFileMode()'.
Use the new keyword if hiding was intended. 
[/home/runner/work/godot/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj]
```

Do compatibility methods clash with regular ones?

File: editor/gui/editor_file_dialog.h [hunk 2]
```diff
@@ -52,8 +52,29 @@ class EditorFileDialog : public FileDialog {
 
 public:
 #ifndef DISABLE_DEPRECATED
+	// These enums need to exist with their original names, to be registered with backwards-compatible hashes for GDExtension.
+	enum Access {};
+	enum DisplayMode {};
+	enum FileMode {};
```
Comment (dsnopek) [inline editor/gui/editor_file_dialog.h]: Does making these aliases via `using` work? Something like:

```suggestion
	using Access = FileDialog::Access;
	using DisplayMode = FileDialog::DisplayMode;
	using FileMode = FileDialog::FileMode;
```

Comment (KoBeWi) [reply editor/gui/editor_file_dialog.h]: This requires C++20

Comment (dsnopek) [reply editor/gui/editor_file_dialog.h]: Ah, ok. It doesn't really matter in this case, but it would look nicer if it was easy :-)

**Comment by dsnopek** [comment]
@raulsntos Do you have any ideas for how to handle the C# issues?

File: editor/gui/editor_file_dialog.h (hunk 2 above)
Comment (Bromeon) [reply editor/gui/editor_file_dialog.h]: Unfortunately it wouldn't work either way. It then uses the `VARIANT_ENUM_CAST` from the base class, which seems to register the enums with a different hash...

**Comment by raulsntos** [comment]
Hiding inherited methods only happens when both methods have the same signature or only differ by the return type which can't be overloaded. So the only problematic methods are:

- `int GetFileMode()`
- `int GetDisplayMode()`
- `int GetAccess()`
- `void AddFilter(string filter, string description)`

It doesn't seem necessary to add a compat method for `add_filter` since the hash should match, right? There's no enum involved in this method.

And by the way, the getters are returning `int` instead of the enum because the compat enums aren't "exposed" (I think you need to add and expose the enum constants).

But either way, I don't think there's anything we can do about the getters other than:

1. Skip these methods in the C# bindings and break compatibility.
2. Use the `new` keyword to silence the warnings, but this will make these compat methods preferred over the base methods from `FileDialog`. It's probably fine since these compat methods are just calling the base methods anyway, but they will return the compat enum and that may result in an annoying user experience of mixing both enum types in different APIs.

**Comment by dsnopek** [comment]
If having compat methods will cause too many problems for C#, instead we could add the hashes to `GDExtensionSpecialCompatHashes`?

That would fix the issue this PR aims to fix for just GDExtension

**Review by dsnopek — APPROVED** [review]
Thanks!

I manually double checked the hash numbers, and they look good to me.

Assuming you've tested this with godot-rust (using the mode where it loads all methods) and this worked and it didn't turn up any other instances of missing methods - then I think we're good :-)

**Review by akien-mga — APPROVED** [review]

**Comment by Bromeon** [comment]
I applied David's suggestion with the special compat-hash mapping. Seems to work in Rust at least :slightly_smiling_face: 

---

> It doesn't seem necessary to add a compat method for `add_filter` since the hash should match, right? There's no enum involved in this method.

@raulsntos the hash is different, however the regular derived->base lookup seems to work here. I thus removed `add_filter`. Thanks!

---

> Assuming you've tested this with godot-rust (using the mode where it loads all methods) and this worked and it didn't turn up any other instances of missing methods - then I think we're good :-)

I did! Also added [an integration test](https://github.com/godot-rust/gdext/pull/1432) which calls the 3 method pairs, to make sure there's no UB in the hash forwarding. That said, it's a bit of an unusual setup, since the class is only available in the editor... so I hope I didn't miss anything!

**Comment by akien-mga** [comment]
Thanks!
