### ISSUE TITLE
The editor fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#16497]
**Godot version:** Godot Git https://github.com/godotengine/godot/commit/cbdd410a6f476503ee4bc27ac2f475a73960236d

**OS/device including version:** Ubuntu 14.04 with GCC 4.8.2 from repositories

**Issue description:** The editor build fails. See the error log below:

```
Compiling ==> thirdparty/lws/client/ssl-client.c
Compiling ==> thirdparty/lws/ext/extension.c
thirdparty/lws/client/ssl-client.c: In function 'lws_ssl_client_bio_create':
thirdparty/lws/client/ssl-client.c:147:7: error: 'X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS' undeclared (first use in this function)
       X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS);
       ^
thirdparty/lws/client/ssl-client.c:147:7: note: each undeclared identifier is reported only once for each function it appears in
scons: *** [thirdparty/lws/client/ssl-client.x11.opt.tools.64.o] Error 1
scons: building terminated because of errors.
```

[Full GitLab CI job log](https://gitlab.com/Calinou/godot-builds-ci/-/jobs/51702476)

The build succeeds with recent GCC and Clang compilers (tested on Fedora 27). Building export templates works as expected; only editor builds are affected by this issue.

**Comment by akien-mga** [comment]
CC @Faless

**Comment by akien-mga** [comment]
Ah right, it was mentioned here: https://github.com/godotengine/godot/pull/14888#issuecomment-353400377

We now default to building with `builtin_openssl=yes` on Travis to work it around. This issue will eventually be fixed once #16519 is merged.

**Comment by robfram** [comment]
It fails to me in FreeBSD with both options also after #16519.
This is the error message I get trying to compile master (3647ebc8341ea22dce07d7eb5e47ece8d29c5565):

```
thirdparty/lws/client/ssl-client.c:147:7: error: use of undeclared identifier
      'X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS'
                                                X509_CHECK_FLAG_NO_PARTIAL_...
                                                ^
thirdparty/lws/client/ssl-client.c:521:9: error: conflicting types for 'd2i_X509'
                X509 *d2i_X509(X509 **cert, const unsigned char *buffer, long len);
                      ^
/usr/local/include/openssl/x509.h:823:1: note: previous declaration is here
DECLARE_ASN1_FUNCTIONS(X509)
^
/usr/local/include/openssl/asn1.h:303:39: note: expanded from macro
      'DECLARE_ASN1_FUNCTIONS'
# define DECLARE_ASN1_FUNCTIONS(type) DECLARE_ASN1_FUNCTIONS_name(type, type)
                                      ^
/usr/local/include/openssl/asn1.h:310:9: note: expanded from macro
      'DECLARE_ASN1_FUNCTIONS_name'
        DECLARE_ASN1_ENCODE_FUNCTIONS(type, name, name)
        ^
/usr/local/include/openssl/asn1.h:317:15: note: expanded from macro
      'DECLARE_ASN1_ENCODE_FUNCTIONS'
        type *d2i_##name(type **a, const unsigned char **in, long len); \
              ^
<scratch space>:19:1: note: expanded from here
d2i_X509
^
2 errors generated.
scons: *** [thirdparty/lws/client/ssl-client.x11.tools.64.llvm.o] Error 1
scons: building terminated because of errors.
```

I used `builtin_openssl=yes` and `builtin_openssl=no` with identical results, and I'm using LLVM as usual.

**Comment by Faless** [comment]
@robfram , the issue should be fixed with mbedTLS, the builtin_openssl option does nothing anymore (openssl is not there at all anymore).
Can you try doing a fresh build? Clone the repository from scratch to a new location and compile that?
(as an alternative option try to delete the `modules/openssl` and `thirdparty/openssl` folder, plus a `git clean -f -x modules/websocket` and `git clean -f -x thirdparty/lws`)

**Comment by robfram** [comment]
I just followed your instructions. Same result with a fresh clone.
```
[Initial build] Compiling ==> thirdparty/lws/client/ssl-client.c
thirdparty/lws/client/ssl-client.c:147:7: error: use of undeclared identifier
      'X509_CHECK_FLAG_NO_PARTIAL_WILDCARDS'
                                                X509_CHECK_FLAG_NO_PARTI...
```
And so on.

Any thoughs?

**Comment by Faless** [comment]
I've just tried compiling with FreeBSD `11.1` and I'm actually getting an error about `malloc.h` not being available on FreeBSD, fixing that, it compiles fine.

**Comment by robfram** [comment]
I understand no ssl library is needed installed in the system then, like openssl. Any dependence required to compile? Any package version? What scons command line arguments did you use?

Which version of LLVM are you using? I'm not sure if it's using 5.0.0 or 4.0.1.

**Comment by Faless** [comment]
@robfram , let's move the discussion on #16991

**Comment by robfram** [comment]
@Faless , ok. I didn't do it because I though the compilation error was more an openssl case than the mbedtls.

**Comment by Faless** [comment]
@Calinou this seems fixed in current master, can you confirm?

**Comment by Faless** [comment]
Tried out building editor and release on Ubuntu 14.04, all good. Fixed by #16519 (+ #17115 on FreeBSD)
