### PR TITLE
Fix tonemapper, incorrect vertex count was specified

### LINKED ISSUE #80493: Vulkan Mobile error with OpenXR at Scale 1: "Draw command lacks indices, but pipeline format does not use vertices"
### Godot version

v4.2.dev3.official [013e8e3af]

### System information

Godot v4.2.dev3 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3667) - AMD Ryzen 7 5800X3D 8-Core Processor (16 Threads)

### Issue description

When I open my OpenXR mobile project in 4.2.dev3 I get the error 

> "Draw command lacks indices, but pipeline format does not use vertices". 

The 3D Viewport is completely black when this error is going. The error disappears and 3D Viewport works again as soon as scaling (both bilinear and FSR) are changed to anything other than 1. It only happens when Project Settings > Rendering > Scaling 3D > Scale == 1

This error also disappears when switching to the Foward+ renderer. I tried to see if disabling OpenXR Shaders would fix things but it crashes the editor and makes a project unopenable. This occurs with the base Godot XR Template (which is what my XR project is based on).

Additionally, at the beginning of opening the project there will be several errors when loading various scripts from the godot-xr-tools addon: 

> Failed to load script "res://addons/godot-xr-tools/functions/movement_sprint.gd" with error "Compilation failed".

This may have been introduced by the fix in: https://github.com/godotengine/godot/pull/80368

### Steps to reproduce

Open the [OpenXR template](https://github.com/GodotVR/godot-xr-template) and set renderer to Mobile

### Minimal reproduction project

[Open XR Template](https://github.com/GodotVR/godot-xr-template)

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Fix a small typo introduced in #80311 

Fixes: #80493

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
