### ISSUE TITLE
"Redefinition" of a shader function has different meaning in Godot 3.2.alpha1 than in 3.1.1

### ISSUE THREAD

**Issue by loganjk** [godotengine/godot#32587]
**Godot version:** 3.2.alpha1.official win64 (Classical)

**OS/device including version:** Windows 10 Pro, Intel i7-4790K, integrated GPU only (Intel HD Graphics 4600), driver igdkmd64.sys version 20.19.15.5058

**Issue description:** Syntax in GLES2 shader that now causes redefinition compilation errors did not in 3.1.1. Specifically, using a function name as a variable name outside that function or as a parameter name in a different function both cause redefinition errors, but did not previously.  I do not know whether this is intended behavior, but I'm reporting it in case it is not and should actually be considered a regression.

**Steps to reproduce:**

In a new project, create a Node2D with a ColorRect child node with a ShaderMaterial with the following shader:

```
shader_type canvas_item;
render_mode unshaded;

float a(in float x) {return 0.0;}

float b(in float x) {return 0.0;}

float c(in float b) {return 0.0;}

void fragment() {float a=b(0.0);}
```

This compiled in 3.1.1 but fails to compile in 3.2.alpha1.official with errors claiming that `a` and `b` have been redefined.

**Minimal reproduction project:**
[Godot Bug Report 4.zip](https://github.com/godotengine/godot/files/3694384/Godot.Bug.Report.4.zip)

**Comment by Chaosus** [comment]
Yeah, its definite regression, thanks for reporting this!

**Comment by loganjk** [comment]
> Yeah, its definite regression, thanks for reporting this!

Glad to help in a small way. Thanks for working to fix this so quickly.
