### PR TITLE
Fix builds on FreeBSD, OpenBSD, and NetBSD

### LINKED ISSUE #55192: Godot failing to build on OpenBSD 7.0
### Godot version

dd3acd74bbd0c682f489693e31961aba54bde10a

### System information

OpenBSD 7.0, OpenBSD clang version 11.1.0

### Issue description

I am trying to build Godot on OpenBSD 7.0. I followed this guide* https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html (*the guide says I should install scons with pkg_add but that doesn't work becuase the python version that is used with it is 2.7 and godot uses type anotations which are not supported by python2.7 so I used pip install scons). when I run
 ```scons platform=linuxbsd -j2 use_llvm=yes``` I get the follwing error:
```
thirdparty/embree/common/sys/sysinfo.cpp:630:5: error: unknown type name 'cpu_set_t'
    cpu_set_t set;
    ^
1 error generated.
scons: *** [thirdparty/embree/common/sys/sysinfo.x11.tools.64.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:08:05.616]
```

### Steps to reproduce

```
doas pkg_add llvm python3
pip install scons # python version 3.8.12
git clone https://github.com/godotengine/godot.git -b 3.x
cd godot
scons platform=linuxbsd -j2 use_llvm=yes

```

### Minimal reproduction project

_No response_

### LINKED ISSUE #92130: OpenBSD build is broken due to compilation errors
### Tested versions

Reproducible with the `4.3 dev` (master branch, e.g. commit `64520fe`)

### System information

OpenBSD 7.5 GENERIC amd64 (running on QEMU)

### Issue description

OpenBSD build is broken.

I've tried to build it on freshly installed OpenBSD 7.5 in QEMU, and the build is broken due to compilation errors. I've found 2 main problems:

- With the default `scons` build command it fails because the definition of `quick_exit` standard function cannot be found when compiling the file `platform/linuxbsd/x11/detect_prime_x11.cpp`, although the header `<stdlib.h>` is included.
- If I build with OpenGL disabled with `scons opengl3=no` (that way the source file above won't be included in the build), it sill fails with another error: it can't find the header file `#include <linux/input-event-codes.h>` (which is included in `platform/linuxbsd/wayland/wayland_thread.cpp`).

And most likely there are other errors.

### Steps to reproduce

1. Checkout Godot source code, master branch
2. Install build dependencies: `pkg_add python scons llvm`
3. Run `scons` or `scons opengl3=no`

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Kaleb-Reid**
I was able to compile from scratch on FreeBSD 15.0 / 13.5, OpenBSD 7.8 / 7.7, and NetBSD 10.1 without disabling anything using this pr.

I briefly ran the editor on OpenBSD, created a new project, and add a couple nodes in 3D. I currently do not have access to a FreeBSD or NetBSD machine with a display out so I have only briefly tested them in headless mode.

Basically what I've done when compiling under bsd:
- Use bsd joystick implementation in sdl.
- Disabled haptics.
- Disabled camera module.
- Dont set `HAVE_SECURE_GETENV` for openxr.
- Modify linker flags and fix clang / gcc detection.
- Directly define mouse button codes so that `input-event-codes.h` can be removed because it is not available on NetBSD.
- Replace a few system apis with their bsd counterparts.
- Fix some warnings which become errors when compiling in dev mode.
- Replace some problem instances of `size_t` with `uint64_t` in the wayland implementation instead of adding a `long` constructor to `Variant` due to OpenBSD defining `size_t` as `long`. The two wayland files are the only ones in the project with this problem so it seems overkill to change `Variant` to fix the problem.

Also the issue in https://github.com/godotengine/godot/pull/101588#issue-2790302628 where the editor would not compile is due to the process memory limit being relatively low in OpenBSD by default (1.5GB for users with the `staff` class). I also had this failure around the same part, but if you raise the limit (e.g. `ulimit -d 10000000`), then you can compile fine.

Fixes https://github.com/godotengine/godot/issues/55192
Fixes https://github.com/godotengine/godot/issues/92130
Fixes https://github.com/godotengine/godot/issues/110606
Supersedes https://github.com/godotengine/godot/issues/101588

### CODE REVIEW

File: thirdparty/sdl/patches/0007-fix-openbsd.patch [hunk 1]
```diff
@@ -0,0 +1,13 @@
+diff --git a/thirdparty/sdl/joystick/bsd/SDL_bsdjoystick.c b/thirdparty/sdl/joystick/bsd/SDL_bsdjoystick.c
+index b3fd3e9ca3..76568e33b1 100644
+--- a/thirdparty/sdl/joystick/bsd/SDL_bsdjoystick.c
++++ b/thirdparty/sdl/joystick/bsd/SDL_bsdjoystick.c
+@@ -710,7 +710,7 @@ static void BSD_JoystickUpdate(SDL_Joystick *joy)
+                     //default:
+                         // no-op
+                     }
+-                    SDL_PrivateJoystickHat(joy, 0, (dpad[0] * HAT_UP) |
++                    SDL_GetJoystickHat(joy, (dpad[0] * HAT_UP) |
```
Comment (Nintorch) [inline thirdparty/sdl/patches/0007-fix-openbsd.patch]: I'm not sure this is going to send the hat events, could `SDL_SendJoystickHat` (see line 689 of the original file) be used instead?
If it ends up working, may I ask if you can also make a pull request with this change for the SDL repository? :D

Comment (Kaleb-Reid) [reply thirdparty/sdl/patches/0007-fix-openbsd.patch]: @nintorch Was pretty tired, makes sense. I will make a pr upstream. It actually was changed to `SDL_SendJoystickHat` upstream until someone made a pr that I guess was never tested which changed it back even though the function doesn't exist anymore.

File: thirdparty/linuxbsd_headers/input-event-codes/input-event-codes.h
Comment (hpvb) [inline thirdparty/linuxbsd_headers/input-event-codes/input-event-codes.h:1]: I think including this file will require us to have a copy of the GPLv2 as well as the Linux-syscall note in our source tree.

I don't think that that is disqualifying, but it is currently missing in the PR.

Comment (akien-mga) [reply thirdparty/linuxbsd_headers/input-event-codes/input-event-codes.h:1]: I'd prefer to avoid having to bundle a Linux header with GPLv2 license.
I understand the Linux syscall note makes it likely non viral and fine to use as a header for doing syscalls, but people auditing Godot license for commercial usage might be very spooked to see the GPL in our `COPYRIGHT.txt`.

File: drivers/sdl/SDL_build_config_private.h [hunk 2]
```diff
@@ -110,13 +98,49 @@
...
+#define SDL_PLATFORM_PRIVATE_NAME "NetBSD"
+#define HAVE_USBHID_H 1
+#define USBHID_NEW 1
+#define USBHID_UCR_DATA 1
+#endif
+
+#define SDL_HAPTIC_DISABLED 1
+#define SDL_JOYSTICK_USBHID 1
+
+#endif
```
Comment (akien-mga) [inline drivers/sdl/SDL_build_config_private.h:142]: Suggestion for readability:
```suggestion
#if defined(SDL_PLATFORM_LINUX)

#define SDL_PLATFORM_PRIVATE_NAME "Linux"

#define HAVE_LINUX_INPUT_H 1

#define SDL_HAPTIC_LINUX 1
#define SDL_JOYSTICK_LINUX 1
#define SDL_INPUT_LINUXEV 1

#define HAVE_INOTIFY 1
#define HAVE_INOTIFY_INIT1 1

// Don't add these defines, for some reason they mess with C#'s ability
// to use environment variables (see GH-109024)
//#define HAVE_GETENV 1
//#define HAVE_SETENV 1
//#define HAVE_UNSETENV 1

#else // *BSD

#if defined(SDL_PLATFORM_FREEBSD)

#define SDL_PLATFORM_PRIVATE_NAME "FreeBSD"
#define HAVE_USBHID_H 1

#elif defined(SDL_PLATFORM_OPENBSD)

#define SDL_PLATFORM_PRIVATE_NAME "OpenBSD"
#define HAVE_USBHID_H 1
#define USBHID_NEW 1
#define USBHID_UCR_DATA 1

#elif defined(SDL_PLATFORM_NETBSD)

#define SDL_PLATFORM_PRIVATE_NAME "NetBSD"
#define HAVE_USBHID_H 1
#define USBHID_NEW 1
#define USBHID_UCR_DATA 1

#endif

#define SDL_HAPTIC_DISABLED 1
#define SDL_JOYSTICK_USBHID 1

#endif
```

Comment (akien-mga) [reply drivers/sdl/SDL_build_config_private.h:142]: Or another option:

```suggestion
#if defined(SDL_PLATFORM_LINUX)

#define SDL_PLATFORM_PRIVATE_NAME "Linux"

#define HAVE_LINUX_INPUT_H 1

#define SDL_HAPTIC_LINUX 1
#define SDL_JOYSTICK_LINUX 1
#define SDL_INPUT_LINUXEV 1

#define HAVE_INOTIFY 1
#define HAVE_INOTIFY_INIT1 1

// Don't add these defines, for some reason they mess with C#'s ability
// to use environment variables (see GH-109024)
//#define HAVE_GETENV 1
//#define HAVE_SETENV 1
//#define HAVE_UNSETENV 1

#else // *BSD

#if defined(SDL_PLATFORM_FREEBSD)
#define SDL_PLATFORM_PRIVATE_NAME "FreeBSD"
#elif defined(SDL_PLATFORM_OPENBSD)
#define SDL_PLATFORM_PRIVATE_NAME "OpenBSD"
#elif defined(SDL_PLATFORM_NETBSD)
#define SDL_PLATFORM_PRIVATE_NAME "NetBSD"
#endif

#define HAVE_USBHID_H 1

#if !defined(SDL_PLATFORM_FREEBSD)
#define USBHID_NEW 1
#define USBHID_UCR_DATA 1
#endif

#define SDL_HAPTIC_DISABLED 1
#define SDL_JOYSTICK_USBHID 1

#endif
```
Not sure that's significantly better.

File: modules/camera/config.py [hunk 3]
```diff
@@ -1,7 +1,12 @@
 def can_build(env, platform):
     import sys
 
-    if sys.platform.startswith("freebsd") or sys.platform.startswith("openbsd"):
+    if (
+        sys.platform.startswith("dragonfly")
```
Comment (akien-mga) [inline modules/camera/config.py:5]: Do we actually support DragonFlyBSD?

We might want to add some `is_bsd` helper method in `platform_methods.py` to streamline these checks.

File: thirdparty/linuxbsd_headers/input-event-codes/input-event-codes.h
Comment (bruvzg) [reply thirdparty/linuxbsd_headers/input-event-codes/input-event-codes.h:1]: The whole file is used only for a few mouse button `BTN_*` codes, including it and a license seems like overkill. We can redefine it directly, or just use hex value with a comment.

```
#define BTN_LEFT		0x110
#define BTN_RIGHT		0x111
#define BTN_MIDDLE		0x112
#define BTN_SIDE		0x113
#define BTN_EXTRA		0x114
#define BTN_STYLUS		0x14b
#define BTN_STYLUS2		0x14c
```

File: platform/linuxbsd/wayland/wayland_embedder.cpp [hunk 4]
```diff
@@ -2949,15 +2954,34 @@ void WaylandEmbedder::handle_fd(int p_fd, int p_revents) {
...
+
+#ifdef __OpenBSD__
+		struct sockpeercred cred = {};
+#else
 		struct ucred cred = {};
+#endif
 		socklen_t cred_size = sizeof cred;
 		getsockopt(new_fd, SOL_SOCKET, SO_PEERCRED, &cred, &cred_size);
+		cred_pid = cred.pid;
+#endif //__FreeBSD__
```
Comment (akien-mga) [inline platform/linuxbsd/wayland/wayland_embedder.cpp:2978]: It's a bit hard to parse with nested pre-processor checks IMO, I'd streamline it a bit:

```suggestion
		pid_t cred_pid;
		{
#if defined(__FreeBSD__)
			struct xucred cred = {};
			socklen_t cred_size = sizeof cred;
			getsockopt(new_fd, SOL_LOCAL, LOCAL_PEERCRED, &cred, &cred_size);
			cred_pid = cred.cr_pid;
#elif defined(__NetBSD__)
			struct sockcred cred = {};
			socklen_t cred_size = sizeof cred;
			getsockopt(new_fd, SOL_LOCAL, LOCAL_PEEREID, &cred, &cred_size);
			cred_pid = cred.sc_pid;
#elif defined(__OpenBSD__)
			struct sockpeercred cred = {};
			socklen_t cred_size = sizeof cred;
			getsockopt(new_fd, SOL_SOCKET, SO_PEERCRED, &cred, &cred_size);
			cred_pid = cred.pid;
#else // Linux.
			struct ucred cred = {};
			socklen_t cred_size = sizeof cred;
			getsockopt(new_fd, SOL_SOCKET, SO_PEERCRED, &cred, &cred_size);
			cred_pid = cred.pid;
#endif
		}
```

Or move that scope I added to a `get_cred_pid()` helper method.

File: platform/linuxbsd/detect.py [hunk 5]
```diff
@@ -424,9 +424,13 @@ def configure(env: "SConsEnvironment"):
     if env["sdl"]:
         if env["builtin_sdl"]:
             env.Append(CPPDEFINES=["SDL_ENABLED"])
+            if platform.system() in ["FreeBSD", "OpenBSD", "NetBSD"]:
+                env["LINKCOM"] += " -l:libusbhid.a"
```
Comment (akien-mga) [inline platform/linuxbsd/detect.py:428]: Are we sure `+=` works as intended here? I note that for libatomic.a we do:
```diff
       if env["use_llvm"] and platform.system() != "FreeBSD":
            env["LINKCOM"] = env["LINKCOM"] + " -l:libatomic.a"
```
There would also be `env.Append(LINKCOM=["-l:libusbhid.a"])` which would be the most idiomatic for SCons, but maybe it doesn't work as expected?

File: platform/linuxbsd/detect.py [hunk 6]
```diff
@@ -424,9 +424,13 @@ def configure(env: "SConsEnvironment"):
...
         elif os.system("pkg-config --exists sdl3") == 0:  # 0 means found
             env.ParseConfig("pkg-config sdl3 --cflags --libs")
             env.Append(CPPDEFINES=["SDL_ENABLED"])
+            if platform.system() in ["FreeBSD", "OpenBSD", "NetBSD"]:
```
Comment (akien-mga) [inline platform/linuxbsd/detect.py:432]: In this file we seem to do `platform.system()` checks but in others we use `sys.platform`. Are both reliable and should we consolidate them?

File: platform/linuxbsd/detect.py [hunk 7]
```diff
@@ -568,9 +575,17 @@ def configure(env: "SConsEnvironment"):
...
+        # TODO Test NetBSD clang, guessing that it also does not support -static-libstdc++? Does its libc++ have other deps?
+        if env["use_llvm"] and platform.system() in ["FreeBSD", "OpenBSD", "NetBSD"]:
+            env.Append(LINKFLAGS=["-nostdlib++"])
+            env["LINKCOM"] += " -l:libc++.a"
+            if platform.system() == "OpenBSD":
+                env["LINKCOM"] += " -l:libc++abi.a"
+        else:
+            env.Append(LINKFLAGS=["-static-libgcc", "-static-libstdc++"])
+
+        if env["use_llvm"] and platform.system() not in ["FreeBSD", "OpenBSD", "NetBSD"]:
```
Comment (akien-mga) [inline platform/linuxbsd/detect.py:587]: Isn't this basically `== "Linux"`?

File: platform/linuxbsd/detect.py [hunk 8]
```diff
@@ -568,9 +575,17 @@ def configure(env: "SConsEnvironment"):
 
     # Link those statically for portability
     if env["use_static_cpp"]:
-        env.Append(LINKFLAGS=["-static-libgcc", "-static-libstdc++"])
-        if env["use_llvm"] and platform.system() != "FreeBSD":
-            env["LINKCOM"] = env["LINKCOM"] + " -l:libatomic.a"
+        # TODO Test NetBSD clang, guessing that it also does not support -static-libstdc++? Does its libc++ have other deps?
```
Comment (akien-mga) [inline platform/linuxbsd/detect.py:578]: Is this really not supported, or is it just a question of which stdlib implementation is the default? Linux distros tend to default Clang to libstdc++, but it can also default to libc++, which might be what BSDs do (like Apple platforms).

If so I believe it could be selected with `-stdlib=libstdc++`.
If using `libc++`, we might not need to link statically, that needs to be checked. The whole point of this is to make binaries more portable so the question is what does it take to make a FreeBSD binary portable to all FreeBSD versions.

File: platform/linuxbsd/platform_config.h [hunk 9]
```diff
@@ -30,18 +30,22 @@
...
 
+// alloca
 #ifdef __linux__
 #include <alloca.h>
+#elif defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__)
+#ifdef __cplusplus
+#include <cstdlib>
+#else
+#include <stdio.h>
+#endif
```
Comment (akien-mga) [inline platform/linuxbsd/platform_config.h:41]: Do we ever include this file in C code? And wouldn't the C equivalent be `stdlib.h`?

File: thirdparty/sdl/hidapi/netbsd/hid.c
Comment (akien-mga) [inline thirdparty/sdl/hidapi/netbsd/hid.c:1]: I might have missed it, but is this compiled explicitly anywhere?

File: drivers/sdl/SCsub [hunk 10]
```diff
@@ -132,6 +144,7 @@ if env["builtin_sdl"]:
             "core/unix/SDL_poll.c",
             "haptic/linux/SDL_syshaptic.c",
             "joystick/linux/SDL_sysjoystick.c",
+            "joystick/bsd/SDL_bsdjoystick.c",
```
Comment (akien-mga) [inline drivers/sdl/SCsub:147]: Does it "just work" to have a mix of Linux and BSD specific files compiled for both Linux and *BSD builds?

File: thirdparty/linuxbsd_headers/input-event-codes/input-event-codes.h
Comment (akien-mga) [reply thirdparty/linuxbsd_headers/input-event-codes/input-event-codes.h:1]: Yeah let's define those directly then, with a comment that indicates they're from `linux/input-event-codes.h`.
A quick interpretation of the Linux syscall note makes me think that this is spirit of that note and doesn't require any license or copyright attribution (which would likely also not really mean much for just some numbers).

Comment (hpvb) [reply thirdparty/linuxbsd_headers/input-event-codes/input-event-codes.h:1]: I think that is fine. But including the whole file I think would have required us to include the text of the GPL.

I agree that copying those constants is fine.

File: platform/linuxbsd/detect.py (hunk 6 above)
Comment (Kaleb-Reid) [reply platform/linuxbsd/detect.py]: According to [this](https://stackoverflow.com/questions/446209/possible-values-from-sys-platform/13874620#13874620), `platform.system()` is determined at runtime and will normalize the name using heuristics, which makes it dependent on python developers keeping said heuristics up to date. `sys.platform` will be a value determined at compile time of Python, which I would assume makes it more reliable  although the names may have a version number at the end (hence why we use `sys.platform.startswith()`). I will change the few occurrences from `platform.system()` to `sys.platform` for now unless we decide otherwise.

File: platform/linuxbsd/detect.py (hunk 5 above)
Comment (Kaleb-Reid) [reply platform/linuxbsd/detect.py]: `+=` seems to work as intended, I would assume `a += b` for string concatenation in python would be the same as `a = a + b`. I will however switch them to use `env.Append` for the sake of consistency which from a quick test appears to work correctly.

File: drivers/sdl/SCsub (hunk 10 above)
Comment (Kaleb-Reid) [reply drivers/sdl/SCsub:147]: Yes, the entirety of `joystick/linux/SDL_sysjoystick.c` is behind a `#ifdef SDL_JOYSTICK_LINUX` and `joystick/bsd/SDL_bsdjoystick.c` is behind `#ifdef SDL_JOYSTICK_USBHID` (which are defined in `drivers/sdl/SDL_build_config_private.h` depending on the target platform).

File: thirdparty/sdl/hidapi/netbsd/hid.c
Comment (Kaleb-Reid) [reply thirdparty/sdl/hidapi/netbsd/hid.c:1]: It is included from another file.
https://github.com/Kaleb-Reid/godot/blob/d04ff90d24a9208b4bb76c8bef3a3f799b8e4a14/thirdparty/sdl/hidapi/SDL_hidapi.c#L576-L577
https://github.com/Kaleb-Reid/godot/blob/d04ff90d24a9208b4bb76c8bef3a3f799b8e4a14/thirdparty/sdl/hidapi/SDL_hidapi_netbsd.h#L23

File: modules/camera/config.py (hunk 3 above)
Comment (Kaleb-Reid) [reply modules/camera/config.py]: There already exists some instances where DragonFlyBSD is checked for e.g. https://github.com/godotengine/godot/blob/583596cd50bbdd29c5ee033d944410035eeb87fb/methods.py#L1100-L1107 so I've added it where we check for BSD in general. All of the cases I looked at point to it being very different from modern FreeBSD even though it is derived from it, so I did not include it with any of the FreeBSD specific checks.

I will add an `is_bsd` method as you suggested.

File: platform/linuxbsd/detect.py (hunk 8 above)
Comment (Kaleb-Reid) [reply platform/linuxbsd/detect.py]: Just tested on OpenBSD and I am unable to figure out how to link against libstdc++ using clang in the first place as `-stdlib=libstdc++` doesn't seem to do anything even though the library is installed. This may be why `-static-libstdc++` doesn't do anything and I get `c++: warning: argument unused during compilation: '-static-libstdc++'` at link time. Really all excluding the flags solves is removing warnings so I could revert this change and keep the linker warnings if that would be preferred.

In terms of portability, [llvm](https://libcxx.llvm.org/ABIGuarantees.html#availability-of-symbols-in-the-built-library-both-static-and-shared) claims libc++ is generally backwards-compatible with no guarantees for forwards-compatibility. Not sure what this means for whether we should link it statically or not. Is this the same case as libstdc++? libc++ versions should not be stable on the BSDs from one release to the next.

File: thirdparty/linuxbsd_headers/input-event-codes/input-event-codes.h
Comment (Kaleb-Reid) [reply thirdparty/linuxbsd_headers/input-event-codes/input-event-codes.h:1]: I removed the header and directly defined the mouse button codes where necessary with a comment that they came from `linux/input-event-codes.h`

File: platform/linuxbsd/detect.py (hunk 5 above)
Comment (Kaleb-Reid) [reply platform/linuxbsd/detect.py]: Switching all instances to the format `env.Append(LINKCOM=["-l: ... .a"])` does not appear to actually do anything so I will change them back to env["LINKCOM"] += " -l: ... .a"

File: platform/linuxbsd/detect.py (hunk 8 above)
Comment (Kaleb-Reid) [reply platform/linuxbsd/detect.py]: After more research, I really don't think clang supports the `-static-libstdc++` option on any BSD. Searching for the option [here](https://github.com/search?q=repo%3Allvm%2Fllvm-project+path%3A%2F%5Eclang%5C%2Flib%5C%2FDriver%5C%2FToolChains%5C%2F%2F+options%3A%3AOPT_static_libstdcxx&type=code) shows that none of the BSDs check for this option at all. I tested on both OpenBSD and NetBSD and was unable to find a use for the flags (NetBSD's default standard library implementation is libstdc++).

File: modules/camera/config.py (hunk 3 above)
Comment (Kaleb-Reid) [reply modules/camera/config.py]: I'm actually going to instead just use `not sys.platform.startswith("linux")` instead as `linuxbsd` should be either Linux or BSD

File: platform/linuxbsd/detect.py (hunk 8 above)
Comment (Kaleb-Reid) [reply platform/linuxbsd/detect.py]: Also I've realized that linking libc++ statically on OpenBSD is not useful because the binaries are not intended to be compatible between versions anyways. I was unable to run a binary on OpenBSD 7.8 which was compiled on 7.7 because of mismatches between libc as well as libpthread versions. FreeBSD seemed to work when running a binary compiled in 13.5 on 15.0 and NetBSD I gave up on trying to install packages for 9.4 so I didn't test but I assume it also attempts to preserve compatibility.

File: drivers/unix/os_unix.cpp [hunk 11]
```diff
@@ -504,7 +504,7 @@ Dictionary OS_Unix::get_memory_info() const {
 	uint64_t sused = 0;
 	int count = swapctl(SWAP_NSWAP, 0, 0);
 	if (count > 0) {
-		swapent swap_info[count];
+		swapent *swap_info = (swapent *)memalloc(count * sizeof(swapent));
```
Comment (akien-mga) [inline drivers/unix/os_unix.cpp:507]: CC @bruvzg to review this bit.

Comment (bruvzg) [reply drivers/unix/os_unix.cpp:507]: It seems fine, but not sure why having it on stack was an issue, was it too large because of `PATH_MAX`?

File: platform/linuxbsd/detect.py [hunk 12]
```diff
@@ -117,13 +117,14 @@ def configure(env: "SConsEnvironment"):
...
+        # Convenience check to enforce the use_llvm overrides when using clang.
         env["use_llvm"] = True
 
     if env["use_llvm"]:
-        if "clang++" not in os.path.basename(env["CXX"]):
+        if os.path.basename(env["CC"]) != "clang":
             env["CC"] = "clang"
+        if os.path.basename(env["CXX"]) != "clang++":
             env["CXX"] = "clang++"
         env.extra_suffix = ".llvm" + env.extra_suffix
```
Comment (akien-mga) [inline platform/linuxbsd/detect.py:128]: What is this addressing?

Doing checks with `"clang" in $CC`/`"clang++" in $CXX` is meant to support potentially prefixed binary names, e.g. with a target triple. For example our Linux SDKs (currently using GCC) provide `x86_64-godot-linux-gnu-gcc` as one of the options someone could pass to `CC`.

I don't know if there are actual uses for this currently out in the wild, but I'd be wary of breaking some workflows and forcing users to use their `PATH`'s `clang` when they wanted to use a specific toolchain via a manually specified `CC`/`CXX`.

File: thirdparty/embree/common/sys/sysinfo.cpp [hunk 13]
```diff
@@ -616,6 +624,56 @@ namespace embree
 
 #endif
 
+////////////////////////////////////////////////////////////////////////////////
+/// OpenBSD Platform
+////////////////////////////////////////////////////////////////////////////////
+
+#if defined (__OPENBSD__)
```
Comment (akien-mga) [inline thirdparty/embree/common/sys/sysinfo.cpp:631]: Did you look into contributing this upstream to Embree?

File: methods.py [hunk 14]
```diff
@@ -808,11 +808,16 @@ def update_compiler_version_cache(value):
...
+        sys.platform.startswith("netbsd") and os.path.basename(env["CC"] == "cc")
+    )
 
 
 def using_clang(env):
-    return "clang" in os.path.basename(env["CC"])
+    return "clang" in os.path.basename(env["CC"]) or (
+        (sys.platform.startswith("freebsd") or sys.platform.startswith("openbsd"))
+        and os.path.basename(env["CC"]) == "cc"
+    )
```
Comment (akien-mga) [inline methods.py]: That sounds quite error prone if either of these *BSD platforms change their default `cc` compiler in the future. They don't provide `gcc` and `clang` binaries?

It's been working in the past without requiring those changes, I wonder why this is needed now.

File: methods.py [hunk 15]
```diff
@@ -1099,10 +1104,10 @@ def get_dependencies(file, env, exts, headers, sources, others):
     host_platform = "windows"
     if (
         sys.platform.startswith("linux")
-        or sys.platform.startswith("dragonfly")
         or sys.platform.startswith("freebsd")
-        or sys.platform.startswith("netbsd")
         or sys.platform.startswith("openbsd")
+        or sys.platform.startswith("netbsd")
+        or sys.platform.startswith("dragonfly")
```
Comment (akien-mga) [inline methods.py]: I'd suggest we drop the `dragonfly` check here and in `SConstruct`, since we haven't tested that it actually works. I seriously doubt it will if the only DragonFlyBSD specific code we have is auto-detecting that it's a `linuxbsd` platform.

File: drivers/unix/os_unix.cpp (hunk 11 above)
Comment (Kaleb-Reid) [reply drivers/unix/os_unix.cpp:507]: @bruvzg This triggered a compiler warning for having a variable length array, which in dev mode aborted compilation.

File: methods.py (hunk 14 above)
Comment (Kaleb-Reid) [reply methods.py]: @akien-mga I may be able to revert the NetBSD one, but the other two are necessary because it was causing builds done with the default system compiler (`cc` which is a copy of `clang`) to not be forced as llvm builds which made certain compiler flags not be applied, causing issues such as failing when compiling in dev mode due to missing flags to ignore warnings as well as not adding the clang-specific linker flags for statically linking libc++. If instead we check `CXX`, I believe only OpenBSD would need a workaround because it's default is `c++` which is a copy of `clang++`.

File: thirdparty/embree/common/sys/sysinfo.cpp (hunk 13 above)
Comment (Kaleb-Reid) [reply thirdparty/embree/common/sys/sysinfo.cpp:631]: @akien-mga I didn't bother to because the OpenBSD implementations of the functions are just dummy implementations. Until now so were the NetBSD ones, but I just changed them to be the same as the Linux implementations as NetBSD seems to support the same interfaces as Linux in this case.

File: methods.py (hunk 14 above)
Comment (Kaleb-Reid) [reply methods.py]: I've reverted the modification to `using_gcc` but kept the one to `using_clang`

**Comment by pescador-barquero** [comment]
I just noticed there's a FreeBSD ports update for 4.6.1. Sharing here just in case you haven't seen it.
https://www.freshports.org/devel/godot
