### ISSUE TITLE
[3.x] New warnings at startup on web export

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#92239]
### Tested versions

Reproducible in 3.6:
beta 5
beta 4
beta 3

Not reproducible in 3.5.3
3.6 beta 2

### System information

Linux Mint

### Issue description

Log shows new errors at startup:
```
tmp_js_export.js:369 ERROR: Condition "!configured" is true.
onPrintError @ tmp_js_export.js:369
tmp_js_export.js:369    at: StringName (core/string_name.cpp:161)
onPrintError @ tmp_js_export.js:369
tmp_js_export.js:369 ERROR: Parameter "p_object" is null.
onPrintError @ tmp_js_export.js:369
tmp_js_export.js:369    at: get_property (core/class_db.cpp:1030)
onPrintError @ tmp_js_export.js:369
tmp_js_export.js:369 ERROR: Condition "!configured" is true.
onPrintError @ tmp_js_export.js:369
tmp_js_export.js:369    at: unref (core/string_name.cpp:86)
onPrintError @ tmp_js_export.js:369
tmp_js_export.js:354 Godot Engine v3.6.beta5.official.2a347ab86 - https://godotengine.org
```
The export does however seem to run correctly ok, so this seems somewhat benign.

Note: This was reported on reddit by whupazz:
https://www.reddit.com/r/godot/comments/1cqzrut/dev_snapshot_godot_36_beta_5/

### Steps to reproduce

Run web build.

### Minimal reproduction project (MRP)

N/A

**Comment by lawnjelly** [comment]
Bisected to https://github.com/godotengine/godot/commit/18ee8da7d6dbb07a9ac1f436ab180a9ed83f4a87
#77352

@bruvzg

**Comment by bruvzg** [comment]
Probably, it's in DisplayServer in 4.x.

**Comment by lawnjelly** [comment]
Fixed by #92261.
