### ISSUE TITLE
HTML5 build error related to PCRE2

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#10834]
Compiling Godot Git https://github.com/godotengine/godot/commit/a717083235b3369aef9a3846b5071fac023a60b2 fails for the HTML5 (WebAssembly) platform, on an Ubuntu 16.04 host running the latest stable Emscripten version:

```
In file included from thirdparty/pcre2/src/pcre2_jit_compile.c:78:
thirdparty/pcre2/src/sljit/sljitLir.c:1754:49: error: conflicting types for 'sljit_create_compiler'
SLJIT_API_FUNC_ATTRIBUTE struct sljit_compiler* sljit_create_compiler(void)
                                                ^
thirdparty/pcre2/src/sljit/sljitLir.h:424:49: note: previous declaration is here
SLJIT_API_FUNC_ATTRIBUTE struct sljit_compiler* sljit_create_compiler(void *allocator_data);
                                                ^
thirdparty/pcre2/src/pcre2_jit_compile.c:81:2: error: Unsupported architecture
#error Unsupported architecture
 ^
Compiling ==> thirdparty/pcre2/src/pcre2_match.c
In file included from thirdparty/pcre2/src/pcre2_jit_compile.c:11499:
thirdparty/pcre2/src/pcre2_jit_misc.c:113:1: error: implicit declaration of function 'sljit_free_unused_memory_exec' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
sljit_free_unused_memory_exec();
^
3 errors generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
scons: *** [thirdparty/pcre2/src/pcre2_jit_compile_16.javascript.opt.debug.webassembly.bc] Error 1
scons: building terminated because of errors.
```

According to the error message, this is likely a regression from https://github.com/godotengine/godot/pull/10148.

**Comment by akien-mga** [comment]
CC @leezh. Is it possible to disable the JIT compiler for the javascript platform?

**Comment by leezh** [comment]
Ah, sorry for breaking HTML5 :( The flag that adds in JIT support is here: https://github.com/godotengine/godot/blob/master/modules/regex/SCsub#L12

Is it best to hide it behind a whitelist or a blacklist?

**Comment by akien-mga** [comment]
A blacklist should be fine. You can use something like `if "platform" in env and not env["platform"] == "javascript":` or something like that.
