### ISSUE TITLE
Visual Shader Editor UniformRef Node has a "Redefinition of 'uniform node here' error

### ISSUE THREAD

**Issue by NothingAnimated** [godotengine/godot#63021]
### Godot version

v3.4.stable.mono.official[206ba70f4]

### System information

Windows 10, Amd Rx 570, I3 cpu, GLES3

### Issue description

When Using the UnformRef node in godot for some reason you get a Redefinition error
I checked over the code and yes for some reason the uniform is redefined in the code which is odd because I just expect it to reference the uniform with name only.
![image](https://user-images.githubusercontent.com/69369888/179147017-d20766d0-9651-429f-ae5a-330ef44834a4.png)

### Steps to reproduce

-Make a new visual editor resource
-Add in a uniform node and name it
-Add a UniformRef node and in the drop down select the uniform node

### Minimal reproduction project
[VS problem.zip](https://github.com/godotengine/godot/files/9117665/VS.problem.zip)

**Comment by Chaosus** [comment]
Yeah, seems like it broken for 3.x branch for some reason, in 4.0 it works correctly.

**Comment by NothingAnimated** [comment]
Ok, glad to know this is working on godot 4.0
thanks

**Comment by akien-mga** [comment]
Fixed by #63105.
