### PR TITLE
UWP: Incorporate toolchain for building ANGLE using Ninja

### PR DESCRIPTION
**Pull request by Xrayez**
Microsoft ANGLE sources are outdated as noted in the documentation for [compiling for UWP](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_uwp.html).

This PR aims to add a front-end to https://chromium.googlesource.com/angle/angle project. You are expected to setup necessary toolchains for building ANGLE itself: https://chromium.googlesource.com/angle/angle/+/HEAD/doc/DevSetup.md. Once this is done, SCons will call `autoninja` to compile ANGLE along with Godot.

Have to compile with `scons angle_toolchain=ninja`. I've preserved the previous build toolchain using MSVC, but I don't guarantee it to still work (not being able to compile ANGLE using MSVC is one of the motivations behind making this PR).

~~Even though I've managed to build ANGLE and some Godot export templates that way, I have no way to actually test this due to export/signing issues, see #30558, even with official builds of Godot, so I'm losing motivation in working on this further.~~ Seems like there's a way at the end of the day: https://github.com/godotengine/godot/issues/30558#issuecomment-797831794.

`arm` does not seem to be available in ANGLE master branch, only `arm64`.

Note that this was done purely out of personal interest/educational purpose, there's a lot of thing I don't even understand, but since there's no active UWP maintainers, I decided to submit this PR. Perhaps @vnen could find something useful from this. 🙂

Some useful snippets:
```bat
set ANGLE_SRC_PATH=d:/src/angle
vcvarsall.bat x64
scons platform=uwp tools=no target=release_debug angle_toolchain=ninja
```

## To-do
- [ ] Figure out how to compile for `arm64` (host/target args).
- [ ] Add concurrent job option to ANGLE.

### CODE REVIEW

**Comment by Xrayez** [comment]
I've finally figured how to export to UWP with workaround (https://github.com/godotengine/godot/issues/30558#issuecomment-797831794), so reporting that I've managed to build ANGLE libs and successfully exported project on `x64`, `debug` with a custom export template. Should also work for `x86`.

The remaining problem is being able to build for `arm`:

```
Traceback (most recent call last):
  File "d:/src/angle/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "d:/src/angle/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "d:/src/angle/build/vs_toolchain.py", line 396, in CopyDlls
    raise Exception('Unknown target_cpu: ' + target_cpu)
Exception: Unknown target_cpu: arm
ERROR at //build/toolchain/win/BUILD.gn:54:3: Script returned non-zero exit code.
  exec_script("../../vs_toolchain.py",
  ^----------
```

and `arm64`:

```
Traceback (most recent call last):
  File "d:/src/angle/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "d:/src/angle/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "d:/src/angle/build/vs_toolchain.py", line 397, in CopyDlls
    _CopyRuntime(target_dir, runtime_dir, target_cpu, debug=False)
  File "d:/src/angle/build/vs_toolchain.py", line 372, in _CopyRuntime
    _CopyUCRTRuntime(target_dir, source_dir, target_cpu, suffix)
  File "d:/src/angle/build/vs_toolchain.py", line 291, in _CopyUCRTRuntime
    _CopyRuntimeImpl(target, source)
  File "d:/src/angle/build/vs_toolchain.py", line 234, in _CopyRuntimeImpl
    abs(os.stat(target).st_mtime - os.stat(source).st_mtime) >= 0.01)):
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Program Files (x86)/Microsoft Visual Studio/2019/Community\\VC\\Redist\\MSVC\\14.28.29325\\arm64\\Microsoft.VC142.CRT\\msvcp140.dll'
ERROR at //build/toolchain/win/BUILD.gn:54:3: Script returned non-zero exit code.
  exec_script("../../vs_toolchain.py",
  ^----------
```

**Comment by BastiaanOlij** [comment]
Owh cool, I didn't realize Googles version of Angle actually runs on UWP. They don't mention it by name which I always found weird.

**Comment by vnen** [comment]
> Owh cool, I didn't realize Googles version of Angle actually runs on UWP. They don't mention it by name which I always found weird.

It did in the beginning, then they switched buildsystems and removed it, then they started supporting it (for quite a while actually). It's not mentioned in the Readme but it is on the build instructions page.

**Comment by BastiaanOlij** [comment]
> 
> 
> > Owh cool, I didn't realize Googles version of Angle actually runs on UWP. They don't mention it by name which I always found weird.
> 
> It did in the beginning, then they switched buildsystems and removed it, then they started supporting it again (for quite a while actually). It's not mentioned in the Readme but it is on the build instructions page.

Ok, sounds like I need to give this a try too soon

**Comment by SLGamesCregg** [comment]
Got this to build and it runs fine as x64 on PC, but unfortunately it crashes instantly when ran on Xbox. It doesn't crash with the current stable build when ran on Xbox. I'll try looking further into it and hopefully will find a fix for it. This PR could very well be the fix for [#9168](https://github.com/godotengine/godot/issues/9168) that we need as well as a few other UWP port bugs. For the arm64 build problem it looks like you're just missing a DLL. I'll try at that one this weekend. Not sure what to do about the arm problem though...seems like that is the main thing that'll be a showstopper about this.

**Comment by SLGamesCregg** [comment]
I got angle with arm64 to compile but keep running into problems with a handful of modules due to what seems to be similar issues as this one [#45687](https://github.com/godotengine/godot/issues/45687) where it is saying "emmintrin.h(20): fatal error C1189: #error:  This header is specific to X86 and X64 targets". Disabling some of these modules, specifically vorbis, is just getting me LNK2019 errors so unfortunately the compilation isn't finishing. BUT the angle part is compiling fine at least. Someone who has more experience with compiling for ARM/ARM64 might know some workarounds for these module specific issues.

**Comment by Xrayez** [comment]
> Got this to build and it runs fine as x64 on PC, but unfortunately it crashes instantly when ran on Xbox. It doesn't crash with the current stable build when ran on Xbox.

I've forgot to ask: how do you setup the environment? There seems to be some UWP-specific options when running `vcvarsall.bat`, perhaps they can help:

image


> Disabling some of these modules, specifically vorbis, is just getting me LNK2019 errors so unfortunately the compilation isn't finishing.

There was indeed some issues around this in the past: #39219, likely not everything can be disabled safely: #39196.

**Comment by SLGamesCregg** [comment]
Hmm yeah I can give it a go using the store parameter and see if that helps. Before I just used the 'x64' parameter. Just connected to my xbox from Visual Studio to debug remotely and go this before it crashed:

dllmissing

Calling dumpbin /DEPENDENTS on the godot.uwp.exe spit out quite a few dependencies, and more than I remember seeing when checking for dependencies of my uwp builds on 3.2.x. So it's likely there is just a DLL missing...now to find which one of these it is...

dependencies

**Comment by SLGamesCregg** [comment]
Okay running `vcvarsall.bat x64 store` is the fix. Runs fine on xbox now. Thanks! Also now that I got it running I can confirm that this fixes [#9168](https://github.com/godotengine/godot/issues/9168). No input lag at all on xbox! :smiley:

**Comment by Antokolos** [comment]
By the way, I wanted to discuss the current state of GLES3 support in Godot UWP, probably it is the right place to ask :)
Our game I was trying to port on Xbox worked with GLES3 renderer. The game works on Godot 3.1.2.
I've changed the following line:
https://github.com/godotengine/godot/blob/e16f264a7e0bec6acd07284a1fc9c256fc483368/platform/uwp/os_uwp.cpp#L189
to the following
ContextEGL_UWP::Driver opengl_api_type = ContextEGL_UWP::GLES_3_0;
then I rebuilt Godot with libEGL.dll and libGLESv2.dll from Google Angle and Voila, our GLES3 Godot game works as UWP on our laptop. It is not working on Xbox though, but it is a different story.

Right now this line still holds GLES_2_0
https://github.com/godotengine/godot/blob/80fc90e82a57e8111cb7577b05bb2de021000e75/platform/uwp/os_uwp.cpp#L167
with the following comment
// FIXME: Hardcoded for now, add Vulkan support.

So, my questions are:
1) Will it be possible to run GLES3 games in Godot 3.x UWP without a need to tweak the code?
2) Will Vulkan renderer work well with UWP on Xbox one (probably no, I guess Xbox supports only DirectX)

Sorry for such a long comment. I just really want our game to work on Xbox via UWP, but it seems that right now it is not possible :)

**Comment by Calinou** [comment]
> 2. Will Vulkan renderer work well with UWP on Xbox one (probably no, I guess Xbox supports only DirectX)

This is likely possible using a Vulkan to DirectX 12 translation layer.

**Comment by Antokolos** [comment]
Wow, glad to hear that, I hope Angle has or will have such support!
Also, there is some kind of translation layer here, although the project seems abandoned...
https://github.com/twinaphex/VulkanOnD3D12

**Comment by GeorgeS2019** [comment]
The "official" in 2022 for  Vulkan over D3D12 is [Dozen](https://gitlab.freedesktop.org/mesa/mesa/-/issues/6330)

**Comment by akien-mga** [comment]
Closing as this contributor can no longer update this further.
