### ISSUE TITLE
Build fails if sub-directory under 'modules/mono/glue/cs_files' contains special characters

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#21139]
**Godot version:**

`master` / c93888ae

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
The current master branch fails to build due to compilation errors in _cs_compressed.gen.h_ as shown below:

```
In file included from modules/mono/editor/bindings_generator.cpp:43:
modules/mono/editor/../glue/cs_compressed.gen.h:132:18: error: default initialization of an object of const type 'const int'
static const int _cs_Godot API_Properties_AssemblyInfo_compressed_size = 627;
                 ^
                           = 0                                                                                                                                                              
modules/mono/editor/../glue/cs_compressed.gen.h:132:27: error: expected ';' after top level declarator
static const int _cs_Godot API_Properties_AssemblyInfo_compressed_size = 627;
                          ^
                          ;
modules/mono/editor/../glue/cs_compressed.gen.h:133:18: error: redefinition of '_cs_Godot'
static const int _cs_Godot API_Properties_AssemblyInfo_uncompressed_size = 1355;
                 ^
modules/mono/editor/../glue/cs_compressed.gen.h:132:18: note: previous definition is here
static const int _cs_Godot API_Properties_AssemblyInfo_compressed_size = 627;
                 ^
modules/mono/editor/../glue/cs_compressed.gen.h:133:27: error: expected ';' after top level declarator
static const int _cs_Godot API_Properties_AssemblyInfo_uncompressed_size = 1355;
                          ^
                          ;
modules/mono/editor/../glue/cs_compressed.gen.h:134:28: error: redefinition of '_cs_Godot' with a different type: 'const unsigned char' vs 'const int'
static const unsigned char _cs_Godot API_Properties_AssemblyInfo_compressed[] = { 120, 156, 133, 84, 75, 110, 26, 65, 16, 221, 115, 138, 18, 27, 19, 43, 96, 76, 140, 228, 207, 10, ...
                           ^
modules/mono/editor/../glue/cs_compressed.gen.h:132:18: note: previous definition is here
static const int _cs_Godot API_Properties_AssemblyInfo_compressed_size = 627;
                 ^
modules/mono/editor/../glue/cs_compressed.gen.h:134:37: error: expected ';' after top level declarator
static const unsigned char _cs_Godot API_Properties_AssemblyInfo_compressed[] = { 120, 156, 133, 84, 75, 110, 26, 65, 16, 221, 115, 138, 18, 27, 19, 43, 96, 76, 140, 228, 207, 10, ...
                                    ^
                                    ;
modules/mono/editor/../glue/cs_compressed.gen.h:187:82: error: expected ')'
        r_files.insert("Godot API/Properties/AssemblyInfo.cs", CompressedFile(_cs_Godot API_Properties_AssemblyInfo_compressed_size, _cs_Godot API_Properties_AssemblyInfo_uncompres...
                                                                                        ^
modules/mono/editor/../glue/cs_compressed.gen.h:187:71: note: to match this '('
        r_files.insert("Godot API/Properties/AssemblyInfo.cs", CompressedFile(_cs_Godot API_Properties_AssemblyInfo_compressed_size, _cs_Godot API_Properties_AssemblyInfo_uncompres...
                                                                             ^
modules/mono/editor/../glue/cs_compressed.gen.h:187:57: error: no matching conversion for functional-style cast from 'const int' to 'CompressedFile'
        r_files.insert("Godot API/Properties/AssemblyInfo.cs", CompressedFile(_cs_Godot API_Properties_AssemblyInfo_compressed_size, _cs_Godot API_Properties_AssemblyInfo_uncompres...
                                                               ^~~~~~~~~~~~~~~~~~~~~~~~
modules/mono/editor/../glue/cs_compressed.gen.h:138:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const int' to
      'const CompressedFile' for 1st argument
struct CompressedFile
       ^
modules/mono/editor/../glue/cs_compressed.gen.h:138:8: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'const int' to 'CompressedFile' for
      1st argument
struct CompressedFile
       ^
modules/mono/editor/../glue/cs_compressed.gen.h:151:2: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
        CompressedFile() {}
        ^
modules/mono/editor/../glue/cs_compressed.gen.h:144:2: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
        CompressedFile(int p_comp_size, int p_uncomp_size, const unsigned char* p_data)
        ^
[ 29%] 8 errors generated.
```
(@neikeq Could it be possible that it was caused by 72873004332b?)

**Comment by Noshyaar** [comment]
Just want to make sure that you delete *.gen.h before compiling?

**Comment by mysticfall** [comment]
@Noshyaar  I just test again after deleting `*.gen.h` and got the same result.

**Comment by neikeq** [comment]
What's your directories structure in glue/cs_files?

**Comment by mysticfall** [comment]
@neikeq It looks like this : 
```
[fender@manjaro godot]$ find modules/mono/glue/cs_files/
modules/mono/glue/cs_files/
modules/mono/glue/cs_files/Transform.cs
modules/mono/glue/cs_files/GodotMethodAttribute.cs
modules/mono/glue/cs_files/DebuggingUtils.cs
modules/mono/glue/cs_files/Quat.cs
modules/mono/glue/cs_files/MathfEx.cs
modules/mono/glue/cs_files/SignalAttribute.cs
modules/mono/glue/cs_files/Color.cs
modules/mono/glue/cs_files/RPCAttributes.cs
modules/mono/glue/cs_files/Dictionary.cs
modules/mono/glue/cs_files/Vector2.cs
modules/mono/glue/cs_files/.gitignore
modules/mono/glue/cs_files/IAwaiter.cs
modules/mono/glue/cs_files/GodotSynchronizationContext.cs
modules/mono/glue/cs_files/GodotTaskScheduler.cs
modules/mono/glue/cs_files/Mathf.cs
modules/mono/glue/cs_files/StringExtensions.cs
modules/mono/glue/cs_files/Array.cs
modules/mono/glue/cs_files/Vector3.cs
modules/mono/glue/cs_files/Transform2D.cs
modules/mono/glue/cs_files/SignalAwaiter.cs
modules/mono/glue/cs_files/Godot API
modules/mono/glue/cs_files/Godot API/Properties
modules/mono/glue/cs_files/Godot API/Properties/AssemblyInfo.cs
modules/mono/glue/cs_files/Godot API/bin
modules/mono/glue/cs_files/Godot API/bin/Debug
modules/mono/glue/cs_files/Godot API/Godot API.csproj
modules/mono/glue/cs_files/Godot API/obj
modules/mono/glue/cs_files/Godot API/obj/Debug
modules/mono/glue/cs_files/Godot API/obj/Godot API.csproj.nuget.g.targets
modules/mono/glue/cs_files/Godot API/obj/Godot API.csproj.nuget.g.props
modules/mono/glue/cs_files/Godot API/obj/project.assets.json
modules/mono/glue/cs_files/Godot API/obj/Godot API.csproj.nuget.cache
modules/mono/glue/cs_files/ObjectExtensions.cs
modules/mono/glue/cs_files/ToolAttribute.cs
modules/mono/glue/cs_files/ExportAttribute.cs
modules/mono/glue/cs_files/AABB.cs
modules/mono/glue/cs_files/Basis.cs
modules/mono/glue/cs_files/cs_files.sln
modules/mono/glue/cs_files/IAwaitable.cs
modules/mono/glue/cs_files/NodeExtensions.cs
modules/mono/glue/cs_files/MarshalUtils.cs
modules/mono/glue/cs_files/ResourceLoaderExtensions.cs
modules/mono/glue/cs_files/Rect2.cs
modules/mono/glue/cs_files/Plane.cs
modules/mono/glue/cs_files/GD.cs
```

**Comment by neikeq** [comment]
The solution for the error is simple, we can make it remove spaces, as we do with dots. Although we need to have a convention to not use any other special character (spaces can be common, and dots tend to indicate a namespace, so it's desired to allow them).
However, I don't want it to include the `AssemblyInfo.cs`, and I don't want to hard-code it to ignore that file.
I think it would be better to place the C# files in another sub-directory, where the build script will search them, and then the sub-directory can contain other files. We may even want to have a solution and project by default, to benefit of tooling when editing these files.

**Comment by mysticfall** [comment]
@neikeq That indeed fixed the problem for me thanks!

I changed the title to reflect the new information. As it turns out to be a problem was caused by a special case, I'd fine with removing this issue from the 3.1 milestone if desired.

**Comment by mysticfall** [comment]
Actually, those files are left overs from my previous attempt to set up a working environment for modifying the C# API with a minimal hassle.

Anyway, it seems to be a minor problem which only occurs on such a specific setup, so I wouldn't mind making this a low priority issue.

**Comment by neikeq** [comment]
Never mind about non-identifier characters. Name the files however you want.
