### ISSUE TITLE
Compilation in MSYS2/MinGW with GCC 13.1 fails: symbols not declared in this scope

### ISSUE THREAD

**Issue by germanbv** [godotengine/godot#77927]
### Godot version

4.0

### System information

Windows 10, NVidiaRTX 2070

### Issue description

When trying to compile using MinGW with GCC 13.1 compilation fails throwing a bunch of errors like this one:

```
G:/MABS/build/glslang-git/glslang/MachineIndependent/SymbolTable.h:71:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?

G:/MABS/build/glslang-git/glslang/MachineIndependent/SymbolTable.h:662:22: error: 'uint64_t' does not name a type
  662 |     static constexpr uint64_t uniqueIdMask = (1LL << LevelFlagBitOffset) - 1;
```

It looks like the problem comes from third parties: vhacd, openxr and glslang

I've solved the issue by adding:
**#include <stdint.h>**

to 
**\thirdparty\vhacd\inc\vhacdManifoldMesh.h
\thirdparty\openxr\src\common\platform_utils.hpp
\thirdparty\glslang\glslang\Include\Common.h**

I'm not sure how to proceed after finding the fix...

### Steps to reproduce

Try compiling the editor from Master or version 4.0 using MinGW with GCC 13.1

### Minimal reproduction project

N/A
