### ISSUE TITLE
C# threads / tasks don't work on the web.

### ISSUE THREAD

**Issue by wihrl** [godotengine/godot#34506]
**Godot version:**
3.2 beta 4
**OS/device including version:**
Windows 10
**Issue description:**
Threading and tasks don't seem to work at all when exporting mono projects to the web.
**Steps to reproduce:**
1. Create a new project.
2. Create a new thread or task in a c# script that does something ( I tried printing to the console via GD.Print )
3. Export for the web
4. Run the exported project in the web browser.
**Minimal reproduction project:**
https://1drv.ms/u/s!AvsEaC7oMEMagstwXvyFlCMdOOMO2A?e=uuytsD
The label should change text to "it worked" when the program starts.

**Comment by akien-mga** [comment]
Browsers don't enable multithreading in WebAssembly for now, so this is normal.

Duplicate of #12699.

**Comment by neikeq** [comment]
There is a `runtime-threads` target in Mono's wasm sdks: https://github.com/mono/mono/blob/master/sdks/wasm/README.md#threading-support
I haven't tested this yet. We're using the `runtime` target for now.

I'll re-open this as this is about Mono's threading while #12699 is about Godot's.

**Comment by NovemberDev** [comment]
Apparently in Chrome 70, webassembly will be able to support threads 

Source: https://developers.google.com/web/updates/2018/10/wasm-threads

**Comment by robbertzzz** [comment]
According to the article linked by @NovemberDev Google Chrome 74+ should have threads for webassembly enabled by default, but doesn't work with my Mono build in Chrome 79

**Comment by Flavelius** [comment]
It should be possible to schedule the work to run on the main thread. I think unity does this aswell. This would make it more compatible for browsers that don't support threads.

**Comment by lenscas** [comment]
I wouldn't mind checking myself but had trouble compiling godot myself (ran both into an error and finding time is also not the easiest)

because threaded wasm is a thing in 3.2.4 due to: https://github.com/godotengine/godot/issues/12699 does that mean that threads and/or tasks now also work in C#? 

if it doesn't work in the normal C# way, is there a (possible) work around because that feature got closed? (Maybe through communication with gdscript to have that spawn the thread?)

thanks in advance :)

**Comment by Faless** [comment]
> because threaded wasm is a thing in 3.2.4 due to: #12699 does that mean that threads and/or tasks now also work in C#?

@lenscas Sadly, we were not yet able to build a mono version with threads support.
So at least the upcoming beta will only ship the threads-enabled and the gdnative-enabled versions for the "classical" builds and not the "mono" one.
We still plan to expand both threads support (hopefully soon) and gdnative support (probably later on) to "mono" builds too.

**Comment by akien-mga** [comment]
@neikeq Now that #12699 is solved (threads support in Godot's WebAssembly port), we could indeed try https://github.com/mono/mono/blob/master/sdks/wasm/README.md#threading-support to see if it can work with Mono.

**Comment by animanmaster** [comment]
> @neikeq Now that #12699 is solved (threads support in Godot's WebAssembly port), we could indeed try https://github.com/mono/mono/blob/master/sdks/wasm/README.md#threading-support to see if it can work with Mono.

Just curious if anyone has tried a custom build with this yet or if this is working in 4.0? Would I just have to compile a new wasm export template with threads on in order to try this myself, or would I have to recompile the engine too?

**Comment by Beliaar** [comment]
@animanmaster I tried compiling a mono wasm export template with threads for 3.4, but I am always running into some problems. For example, I get several duplicate symbols between libmonosgen and libstubs.a (from emscripten) (getpwnam_r, getpwuid_r, getgrnam, getgrgid, pthread_sigmask), but maybe someone with more knowledge has better luck.

**Comment by Bip901** [comment]
Related to [100740](https://github.com/godotengine/godot/issues/100740)
