### ISSUE TITLE
3.2 compiler errors related to jpgd upgrade.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#38128]
**Godot version:**
3b44f34166a5efa068305a3160caa3415064990a

**OS/device including version:**
Win10 64-bit

**Issue description:**

Have been getting errors today when trying to build on the lastest 3.2 commit.

@akien-mga Seems related to this.  https://github.com/godotengine/godot/commit/c7ad8f539b52dfe7a76a7051505a9891f98e46d6

```
thirdparty\jpeg-compressor\jpgd.cpp(2129): error C2668: 'jpgd::_setjmp': ambiguous call to overloaded function
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\intrin.h(915): note: could be 'int jpgd::_setjmp(_JBTYPE ])'
C:\ProgramFiles(x86)\MicrosoftVisualStudio\2019\Community\VC\Tools\MSVC\14.22.27905\include\setjmp.h(157):note:or      'int_setjmp(_JBTYPE[])'[foundusingargument-dependentlookup]
thirdparty\jpeg-compressor\jpgd.cpp(2129):note:whiletryingtomatchtheargumentlist'(jmp_buf)'
thirdparty\jpeg-compressor\jpgd.cpp(3045):errorC2668:'jpgd::_setjmp':ambiguouscalltooverloadedfunction
C:\ProgramFiles(x86)\MicrosoftVisualStudio\2019\Community\VC\Tools\MSVC\14.22.27905\include\intrin.h(915):note:couldbe'intjpgd::_setjmp(_JBTYPE[])'
C:\ProgramFiles(x86)\MicrosoftVisualStudio\2019\Community\VC\Tools\MSVC\14.22.27905\include\setjmp.h(157):note:or      'int_setjmp(_JBTYPE[])'[foundusingargument-dependentlookup]
thirdparty\jpeg-compressor\jpgd.cpp(3045):note:whiletryingtomatchtheargumentlist'(jmp_buf)'
thirdparty\jpeg-compressor\jpgd.cpp(3058):errorC2668:'jpgd::_setjmp':ambiguouscalltooverloadedfunction
C:\ProgramFiles(x86)\MicrosoftVisualStudio\2019\Community\VC\Tools\MSVC\14.22.27905\include\intrin.h(915):note:couldbe'intjpgd::_setjmp(_JBTYPE[])'
C:\ProgramFiles(x86)\MicrosoftVisualStudio\2019\Community\VC\Tools\MSVC\14.22.27905\include\setjmp.h(157):note:or      'int_setjmp(_JBTYPE[])'[foundusingargument-dependentlookup]
thirdparty\jpeg-compressor\jpgd.cpp(3058):note:whiletryingtomatchtheargumentlist'(jmp_buf)'
scons:*[thirdparty\jpeg-compressor\jpgd.windows.tools.64.obj Error 2
scons: building terminated because of errors.

```

**Comment by avencherus** [comment]
Compiles fine on a different machine.  Did clean builds on both, not exactly sure what's different.

**Comment by akien-mga** [comment]
Fixed by #38091.

**Comment by avencherus** [comment]
Nice nice, working again.  Thanks for the fast inclusion.
