### ISSUE TITLE
[3.5 rc4] 3D editor viewport doesn't render any contents.

### ISSUE THREAD

**Issue by icecoldtofu** [godotengine/godot#62203]
### Godot version

v3.5.rc4.official [e047c5006]

### System information

Windows 10, Intel Graphics, GLES3

### Issue description

3D viewport in the editor doesn't render anything except for background color or the sky. 

No origin, no grids, no nodes, gizmos etc.

Everything worked fine on v3.5.rc3.official [af8a02dda].

On launch, Godot prints a bunch of shader compilation errors to stderr.

[stderr.txt](https://github.com/godotengine/godot/files/8934881/stderr.txt)
[stdout.txt](https://github.com/godotengine/godot/files/8934884/stdout.txt)

### Steps to reproduce

Create and open a new project.

**Comment by lawnjelly** [comment]
Could be related to #61995?

**Comment by icecoldtofu** [comment]
I just checked and the same behavior happens in rc3 when async shader compilation is enabled in project settings.

**Comment by akien-mga** [comment]
Fixed by #62226.
