### ISSUE TITLE
UWP doesn't like GL_BGRA

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#19009]
**Godot version:**
Godot Master 19 May 2018

**OS/device including version:**
UWP

**Issue description:**
Getting the following compiler error for UWP:
```
rasterizer_canvas_gles3.cpp
[ 43%] Compiling ==> drivers\gles3\rasterizer_gles3.cpp
rasterizer_gles3.cpp
drivers\gles3\rasterizer_gles3.cpp(342): error C2065: 'GL_BGRA': undeclared identifier
drivers\gles3\rasterizer_gles3.cpp(399): error C2065: 'GL_BGRA': undeclared identifier
scons: *** [drivers\gles3\rasterizer_gles3.uwp.debug.64.x64.obj] Error 2
scons: building terminated because of errors.
```

**Steps to reproduce:**
Compile for UWP :)
Managed to compile a week or two ago so must be a recent change.

**Comment by akien-mga** [comment]
CC @reduz @vnen

**Comment by bruvzg** [comment]
Regression from #14622 (This code is for Window desktop only).
