### ISSUE TITLE
Can't cross-compile to Windows with `module_mbedtls_enabled=no`

### ISSUE THREAD

**Issue by kus04e4ek** [godotengine/godot#90652]
### Tested versions

43b32f9d0baa13ef8e7079521fbef7c4f090aa88 (latest)
* Introduced by #90482

### System information

Linux

### Issue description

When I cross-compile from Linux to Windows using `module_mbedtls_enabled=no`, I get the following errors:
```
In file included from thirdparty/mbedtls/include/mbedtls/build_info.h:174,
                 from thirdparty/mbedtls/library/common.h:14,
                 from thirdparty/mbedtls/library/aes.c:14:
thirdparty/mbedtls/include/mbedtls/check_config.h:28:2: error: #error "MBEDTLS_PLATFORM_C is required on Windows"
   28 | #error "MBEDTLS_PLATFORM_C is required on Windows"
      |  ^~~~~
In file included from thirdparty/mbedtls/include/mbedtls/build_info.h:174,
                 from thirdparty/mbedtls/library/common.h:14,
                 from thirdparty/mbedtls/library/aes.c:14:
thirdparty/mbedtls/include/mbedtls/check_config.h:578:2: error: #error "MBEDTLS_PLATFORM_SNPRINTF_ALT defined, but not all prerequisites"
  578 | #error "MBEDTLS_PLATFORM_SNPRINTF_ALT defined, but not all prerequisites"
      |  ^~~~~
thirdparty/mbedtls/include/mbedtls/check_config.h:592:2: error: #error "MBEDTLS_PLATFORM_VSNPRINTF_ALT defined, but not all prerequisites"
  592 | #error "MBEDTLS_PLATFORM_VSNPRINTF_ALT defined, but not all prerequisites"
      |  ^~~~~
```
Just compiling to Linux doesn't produce any errors.
This diff seems to fix it partially, though I get linker errors with undefined references:
```diff
diff --git a/thirdparty/mbedtls/include/godot_core_mbedtls_config.h b/thirdparty/mbedtls/include/godot_core_mbedtls_config.h
index d27bf608fbe..e65f332849f 100644
--- a/thirdparty/mbedtls/include/godot_core_mbedtls_config.h
+++ b/thirdparty/mbedtls/include/godot_core_mbedtls_config.h
@@ -33,6 +33,9 @@
 
 #include <limits.h>
 
+// Include default mbedTLS config.
+#include <mbedtls/mbedtls_config.h>
+
 // For AES
 #define MBEDTLS_CIPHER_MODE_CBC
 #define MBEDTLS_CIPHER_MODE_CFB
```
Copied from:
https://github.com/godotengine/godot/blob/578d937927ea9735aa7a8e0535f57801406b0b82/thirdparty/mbedtls/include/godot_module_mbedtls_config.h#L43-L44

Cross-compiling is probably unrelated to this, but I can't test it on Windows and thought it would be better to mention it.

### Steps to reproduce

Compile to Windows using `module_mbedtls_enabled=no`

**Comment by Faless** [comment]
Just tested building Windows with VS 2019 MSVC and `module_mbedtls_enabled=no` and I get no error.

So it might be a mingw specific path, I'll try cross compiling from linux now.

**Comment by Faless** [comment]
I confirm I get the same error with MinGW/LLVM from Linux, will investigate, we might be missing some new define in our core config.

**Comment by Faless** [comment]
And this is why it works on VS 2019 (`_MSC_VER > 1900`):

https://github.com/godotengine/godot/blob/c951421c996467dcb7106a33774410a7b5258690/thirdparty/mbedtls/include/mbedtls/check_config.h#L26-L32
