### ISSUE TITLE
Build fail: module 'detect' has no attribute 'is_active'

### ISSUE THREAD

**Issue by TailyFair** [godotengine/godot#24965]
**Godot version:**
1ff170e67f0044b0a9f42fc936f09847c5ec4127

**OS/device including version:**
Windows 10 x64
Python 3.7.2 (Didn't worked with 3.7.1 either)
Scons 3.0.1

**Issue description:**
When compiling, error is thrown:

```
C:\Users\x\Documents\godot>scons -j6 platform=windows
scons: Reading SConscript files ...
AttributeError: module 'detect' has no attribute 'is_active':
  File "C:\Users\x\Documents\godot\SConstruct", line 37:
    if (detect.is_active()):
```

It seems like `detect.py` is taken from:
`C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\site-packages\detect\__init__.py`
instead of:
`C:\Users\x\Documents\godot\platform\windows\detect.py`

**Comment by touilleMan** [comment]
Hi, sorry for the delay

I guess this is an import clash between Godot and https://pypi.org/project/detect/ 
@TailyFair  simplest solution for you should be to do a `pip uninstall detect` or (much better solution given removing a package like this could break another python application) create a virtual env with only scons installed.

> How can I force a relative import?

You are supposed to do `from . import detect`, however relative import is supposed to go through python packages (i.e. folders containing `__init__.py`), so if your import path miss a `__init__.py` (like `platform` and `platform/<platform>` do) the import should fail.

Regarding the issue itself:

https://github.com/godotengine/godot/blob/4fd579b271e1b5274266843b9b19ed60f4c8a9a1/SConstruct#L254-L255

`sys.path` will be used to look for the detect module in order (hence `"./platform/" + selected_platform` will be checked last).
To solve this you can do:
```python
sys.path.insert(0, "./platform/" + selected_platform)
```

But this is pretty ugly given you actually shadow all modules including the one from the stdlib (hence another crash if the python `detect` module is needed somewhere, for instance if scons internally add a dependency)

A cleaner way to do would be to use the `importlib` module (https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly)

```python
import importlib.util

spec = importlib.util.spec_from_file_location('detect', "./platform/" + selected_platform)
detect = importlib.util.module_from_spec(spec)
spec.loader.exec_module(detect)
print('godot==>', detect.__file__)

import detect as stdlib_detect
print('stdlib==>', stdlib_detect.__file__)

# Should output:
# godot==> ./platform/<platform>/asyncio.py
# stlib==> /usr/local/lib/python3.7/lib/site-packages/detect/__init__.py
```

But this doesn't protect against import shadowing from modules at the root of the godot directory (i.e. if `detect.py` would have been in the root directory there would be no way to prevent it from shadowing the other `detect` package)

Another thing to consider is Python2 compatibility (tick, tack, [the clock is ticking](https://pythonclock.org/)):
- relative import system works differently
- `importlib` is not available there

Last way to do would be to use `exec` builtin to manually read the `detect.py` file and load it. This is not so broken because this file hasn't any relative imports has has the advantage of portability, but it is really, really ugly so don't do that ;-)

So in the end I guess sticking with the first solution (doing `sys.path.insert`) is the least bad solution considering the chances scons (our only 3rd party dep) ending up having a dependency clashing with our few file names is pretty low (and doing a rename on our side to fix this would be quiet cheap).

**Comment by sersoong** [comment]
@akien-mga 
May be it can cherry-pick to **branch 3.0**??
**Branch 3.0** also has this problem.Please check.
