### ISSUE TITLE
Templates build failure since fc70824

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#6358]
Android and iOS builds are failing on Travis, i.e. the templates (`tools=no`) builds are broken:
https://travis-ci.org/godotengine/godot/jobs/156638801
https://travis-ci.org/godotengine/godot/jobs/156638802

For both, the error is:
```
modules/visual_script/visual_script.cpp: In member function 'virtual bool VisualScript::are_subnodes_edited() const':
modules/visual_script/visual_script.cpp:1124:23: error: 'const class VisualScriptNode' has no member named 'is_edited'
    if (F->get().node->is_edited()) {
                       ^
scons: *** [modules/visual_script/visual_script.android.debug.armv7.neon.o] Error 1
```
i.e. caused by https://github.com/godotengine/godot/commit/fc70824f7c6ab1944d54194f54b816e55671e177#diff-ca2cc3b4424c9b4e61a3d69f5ded492cR1124

Please fix.

**Comment by akien-mga** [comment]
Hopefully we can have a fix before another 3 weeks of broken travis builds.

**Comment by wmiler** [comment]
This is caused by a TOOLS_ENABLED issue. A quick (although not verified as truly working) fix, was to place `#ifdef TOOLS_ENABLED` at line 1120 and `#endif` right before the return false.

**Comment by jedStevens** [comment]
Unsure if this helps or not but I'm getting the same error when I build for javascript

running `scons p=javascript tools=no -j4` gives me this same error.

**Comment by jedStevens** [comment]
I fixed the javascript compilation by fixing 3 files, `modules/visual_script/visual_script.h`, `modules/visual_script/visual_script.cpp` and `modules/visual_script/visual_script_expression.cpp`

`modules/visual_script/visual_script.h:77`
`bool is_edited() const;`

`modules/visual_script/visual_script.cpp:18-21`
    
    bool VisualScriptNode::is_edited() const {
    
        return false;
    }

`modules/visual_script/visual_script_expression.cpp:1399-1400`

        }
    #endif
(Move the endif to the outside of the if statement)

Seems to have built fine, untested however

**Comment by jedStevens** [comment]
My fixes seem to have solved my issues for now. I am running into unrelated Javascript building issues now.

**Comment by akien-mga** [comment]
Fixed by #6403.
