### ISSUE TITLE
Can't clear exported node.

### ISSUE THREAD

**Issue by Okxa** [godotengine/godot#94396]
### Tested versions

v4.2.2.stable.arch_linux

### System information

Godot v4.2.2.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:37 +0000 - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 XT (RADV NAVI10) () - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

Clearing an exported Node using the drop down menu does not clear the property.

```gdscript
@export var annotation_node:Node = null
```

![image](https://github.com/user-attachments/assets/74a47344-79a7-4b7d-b84f-f6ba793142cc)

Additionally, if exporting a property of type Node with `_get_property_list()`, results in error when pressing the clear button:

`Trying to assign value of type 'NodePath' to a variable of type 'Node'.`

Because of the error I believe the issue is probably similiar as in: https://github.com/godotengine/godot/issues/62481. (As the issue says, currently the reset arrow works and set the variable to `Nil` correctly.)

In fact when printing the type of the value in `_set`, it gives `Object` when setting a node, `Nil` when resetting with the arrow, and `NodePath` when pressing clear button in the drop down.

For Node exported with `@export`, when pressing the clear button will not print anything in it's setter, as if the setter is not called:

```gdscript
@export var annotation_node:Node:
    set(value):
        print(type_string(typeof(value)))
        annotation_node = value
```

### Steps to reproduce

1. Export a property of type Node with `@export var node:Node` or using `get_property_list()`.
2. Assign a node to it.
3. Press the Clear button in the drop down menu.
4. Observe as the value is not cleared

### Minimal reproduction project (MRP)

[mrp-node-export-clear.zip](https://github.com/user-attachments/files/16238208/mrp-node-export-clear.zip)

**Comment by KoBeWi** [comment]
Does it work in 4.3?

**Comment by Okxa** [comment]
Same behaviour on `v4.3.beta3.official [82cedc83c]`

**Comment by KoBeWi** [comment]
If you remove `@tool`, the node can be cleared normally.

**Comment by HolonProduction** [comment]
Can't reproduce in v4.7.stable.flathub [5b4e0cb0f] (after fixing some compilation errors in the MRP)
