### PR TITLE
fix string conversion in javascript export

### PR DESCRIPTION
**Pull request by 27thLiz**
fixes the following compile error (introduced in #3391):

```
platform/javascript/export/export.cpp:188:78: error: conditional expression is ambiguous; 'String' can be converted to 'Variant' and vice versa
  ...?html_title: Globals::get_singleton()->get("application/name"));
     ^~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

### CODE REVIEW

**Comment by eska014** [comment]
Thanks.
