### PR TITLE
[TextServer] Fix regression from #51908, HarfBuzz handle init and MinGW build.

### LINKED ISSUE #52318: Unable to compile template with MinGW
### Godot version

4.0.dev 4c3f7d1

### System information

Windows 10 21H1

### Issue description

Unable to compile `debug` and `release_debug` template with MinGW on Windows 10 because of the following error:
```
b'In file included from ./core/templates/hash_map.h:34,
                 from ./core/object/object.h:38,

    from ./core/variant/binder_common.h:35,
                 from ./core/object/method_bind.h:34,
                 from ./core/object/class_db.h:34,
                 from ./core/object/ref_counted.h:34,
                 from ./servers/text_server.h:34,
                 from modules\\text_server_adv\\text_server_adv.h:39,
                 from modules\\text_server_adv\\text_server_adv.cpp:31:
modules\\text_server_adv\\text_server_adv.cpp: In member function \'bool TextServerAdvanced::_ensure_cache_for_size(TextServerAdvanced::FontDataAdvanced*, const Vector2i&) const\':
./core/string/ustring.h:526:22: error: invalid cast to function type \'String()\'
  526 | #define TTR(m_value) (String())
./core/error/error_macros.h:94:26: note: in definition of macro \'DEBUG_STR\'
   94 | #define DEBUG_STR(m_msg) m_msg
      |                          ^~~~~
modules\\text_server_adv\\text_server_adv.cpp:1234:4: note: in expansion of macro \'ERR_FAIL_COND_V_MSG\'
 1234 |    ERR_FAIL_COND_V_MSG(error != 0, false, TTR("FreeType: Error initializing library:") + " \'" + String(FT_Error_String(error)) + "\'.");
      |    ^~~~~~~~~~~~~~~~~~~
modules\\text_server_adv\\text_server_adv.cpp:1234:43: note: in expansion of macro \'TTR\'
 1234 |    ERR_FAIL_COND_V_MSG(error != 0, false, TTR("FreeType: Error initializing library:") + " \'" + String(FT_Error_String(error)) + "\'.");
      |
  ^~~
./core/string/ustring.h:526:22: error: invalid cast to function type \'String()\'
  526 | #define TTR(m_value) (String())
./core/error/error_macros.h:94:26: note: in definition of macro \'DEBUG_STR\'
   94 | #define DEBUG_STR(m_msg) m_msg
      |                          ^~~~~
modules\\text_server_adv\\text_server_adv.cpp:1252:4: note: in expansion of macro \'ERR_FAIL_V_MSG\'
 1252 |    ERR_FAIL_V_MSG(false, TTR("FreeType: Error loading font:") + " \'" + String(FT_Error_String(error)) + "\'.");
      |    ^~~~~~~~~~~~~~
modules\\text_server_adv\\text_server_adv.cpp:1252:26: note: in expansion of macro \'TTR\'
 1252 |    ERR_FAIL_V_MSG(false, TTR("FreeType: Error loading font:") + " \'" + String(FT_Error_String(error)) + "\'.");
      |                          ^~~
'
```
This error introduced with 4c3f7d1

### Steps to reproduce

Checkout 4c3f7d1 and `scons platform=windows target=debug use_mingw=yes tools=no`

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
Move HarfBuzz handle creation, after setting font size.

Fixes regression from #51908 mentioned in the comment - https://github.com/godotengine/godot/pull/51908#issuecomment-909520725

Fixes #52318

Screenshot 2021-08-31 at 22 31 19

### CODE REVIEW

File: modules/text_server_adv/text_server_adv.cpp [hunk 1]
```diff
@@ -1284,6 +1278,13 @@ _FORCE_INLINE_ bool TextServerAdvanced::_ensure_cache_for_size(FontDataAdvanced
 			FT_Set_Pixel_Sizes(fd->face, 0, fd->size.x * fd->oversampling);
 		}
 
+		fd->hb_handle = hb_ft_font_create(fd->face, nullptr);
+		if (fd->hb_handle == nullptr) {
```
Comment (khaledhosny) [inline modules/text_server_adv/text_server_adv.cpp:1282]: FWIW, `hb_ft_font_create()` never returns NULL.

File: modules/text_server_adv/text_server_adv.cpp [hunk 2]
```diff
@@ -1598,14 +1594,11 @@ _FORCE_INLINE_ bool TextServerAdvanced::_ensure_cache_for_size(FontDataAdvanced
 			FT_Done_MM_Var(library, amaster);
 		}
 #else
-		ERR_FAIL_V_MSG(false, TTR("FreeType: Can't load dynamic font, engine is compiled without FreeType support!");
+		ERR_FAIL_V_MSG(false, RTR("FreeType: Can't load dynamic font, engine is compiled without FreeType support!");
 #endif
 	} else {
 		// Init bitmap font.
 		fd->hb_handle = hb_bmp_font_create(fd, nullptr);
```
Comment (khaledhosny) [inline modules/text_server_adv/text_server_adv.cpp:1601]: It is probably a good idea not to use `hb_` prefix for your functions, to avoid potentially clashing with HarfBuzz API if it ever provided a function with the same name.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
