### PR TITLE
Wayland: Commit surface on window creation

### LINKED ISSUE #94204: Wayland: Godot v4.3 beta3 crashes when running on linux
### Tested versions

- Reproducible in Godot v4.3 beta3 only.

### System information

Godot v4.3.beta3.official.82cedc83c Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 22:11:24 +0000 - Wayland - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) () - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 Threads)

### Issue description

Godot will instantly crash after starting when running under wayland, using ```--display-driver x11``` will make godot start normally.

Error message:
```
xdg_surface#41: error 3: xdg_surface has never been configured
ERROR: Wayland protocol error 3 on interface xdg_surface@41.
   at: _poll_events_thread (platform/linuxbsd/wayland/wayland_thread.cpp:2739)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.3.beta3.official (82cedc83c9069125207c128f9a07ce3d82c317cc)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3cae0) [0x70cbcbe59ae0] (??:0)
[2] godot_v4.3-beta3() [0x487dd7] (??:0)
[3] godot_v4.3-beta3() [0x3e3a645] (??:0)
[4] godot_v4.3-beta3() [0x4adff23] (??:0)
[5] /usr/lib/libc.so.6(+0x92ded) [0x70cbcbeafded] (??:0)
[6] /usr/lib/libc.so.6(+0x1160dc) [0x70cbcbf330dc] (??:0)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
```

### Steps to reproduce

Run ```./Godot_v4.3-beta3_linux.x86_64``` under wayland.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by deralmas**
Fixes #94204.
Possible regression from #93684.

This is needed for initializing xdg_surfaces when not using libdecor. Now the pure xdg_shell code path should work again.

### CODE REVIEW

**Comment by em-s-h** [comment]
Hi, I tried to compile this to test if #94204 had been fixed but I got this error during compilation.

```
[Initial build] Compiling thirdparty/glad/gl.c ...
In file included from thirdparty/vulkan/vk_mem_alloc.cpp:7:
thirdparty/vulkan/vk_mem_alloc.h: In function 'void VmaUint32ToStr(char*, size_t, uint32_t)':
thirdparty/vulkan/vk_mem_alloc.h:2821:9: error: 'snprintf' was not declared in this scope
 2821 |         snprintf(outStr, strLen, "%u", static_cast<unsigned int>(num));
      |         ^~~~~~~~
thirdparty/vulkan/vk_mem_alloc.h:2655:1: note: 'snprintf' is defined in header '<cstdio>'; this is probably fixable by adding '#include <cstdio>'
 2654 |     #include <mutex>
  +++ |+#include <cstdio>
 2655 | #else
thirdparty/vulkan/vk_mem_alloc.h: In function 'void VmaUint64ToStr(char*, size_t, uint64_t)':
thirdparty/vulkan/vk_mem_alloc.h:2825:9: error: 'snprintf' was not declared in this scope
 2825 |         snprintf(outStr, strLen, "%llu", static_cast<unsigned long long>(num));
      |         ^~~~~~~~
thirdparty/vulkan/vk_mem_alloc.h:2825:9: note: 'snprintf' is defined in header '<cstdio>'; this is probably fixable by adding '#include <cstdio>'
thirdparty/vulkan/vk_mem_alloc.h: In function 'void VmaPtrToStr(char*, size_t, const void*)':
thirdparty/vulkan/vk_mem_alloc.h:2829:9: error: 'snprintf' was not declared in this scope
 2829 |         snprintf(outStr, strLen, "%p", ptr);
      |         ^~~~~~~~
thirdparty/vulkan/vk_mem_alloc.h:2829:9: note: 'snprintf' is defined in header '<cstdio>'; this is probably fixable by adding '#include <cstdio>'
scons: *** [thirdparty/vulkan/vk_mem_alloc.linuxbsd.editor.x86_64.o] Error 1
In file included from ./core/os/thread.h:42,
                 from drivers/alsa/audio_driver_alsa.h:37,
                 from drivers/alsa/audio_driver_alsa.cpp:31:
./core/templates/safe_refcount.h:135:49: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  135 |         _ALWAYS_INLINE_ explicit SafeNumeric<T>(T p_value = static_cast<T>(0)) {
      |                                                 ^
./core/templates/safe_refcount.h:135:49: note: remove the '< >'
In file included from ./core/os/thread.h:42,
                 from drivers/pulseaudio/audio_driver_pulseaudio.h:37,
                 from drivers/pulseaudio/audio_driver_pulseaudio.cpp:31:
./core/templates/safe_refcount.h:135:49: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  135 |         _ALWAYS_INLINE_ explicit SafeNumeric<T>(T p_value = static_cast<T>(0)) {
      |                                                 ^
./core/templates/safe_refcount.h:135:49: note: remove the '< >'
scons: building terminated because of errors.
[Time elapsed: 00:20:59.712]
```

**Comment by em-s-h** [comment]
> Have you cherry-picked the change or something like that?

No, I simply cloned your fork and tried to build using the aur PKGBUILD script, although after reading the Godot documentation on compiling for linux it says that LTO (the default on the script) requires 7GB of ram while I only have 4, so could that cause this issue?

**Comment by BasilYes** [comment]
Patch work for me

**Comment by em-s-h** [comment]
I can also confirm that the patch works.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
