### PR TITLE
Fix int to uint implicit cast error when use mat3 uniform in compatibility renderer

### LINKED ISSUE #81473: Shaders fail to compile with matrix-type global uniforms (4.1 Compatibility renderer)
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Linux Mint 20.2 (Uma) - Vulkan (Compatibility) - NVIDIA GeForce GTX 1660 Ti (nvidia; 470.199.02) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

When using the Compatibility renderer, shaders fail to compile if a matrix-type global uniform is used in `vertex()`. The error given is an internal cast from `int` to `uint`:
```
drivers/gles3/shader_gles3.cpp:242 - SceneShaderGLES3: Vertex shader compilation failed:
error C7011: implicit cast from "int" to "uint"
```

### Steps to reproduce

Add a matrix global shader uniform (like a `mat3`, below) in the project settings. This shader will fail to compile:
```
shader_type spatial;

global uniform mat3 bug;

void vertex() {
	mat3 cannot_compile = bug;
}
```

### Minimal reproduction project

[Reproduction 9-8-23.zip](https://github.com/godotengine/godot/files/12564495/Reproduction.9-8-23.zip)

### PR DESCRIPTION
**Pull request by jsjtxietian**
This should fix #81473

In `_get_global_shader_uniform_from_type_and_index`, we should use unit to do the math when the uniform is an index to the global table.
But this commit might have other implications, feel free to correct me !

### CODE REVIEW

File: servers/rendering/shader_compiler.cpp [hunk 1]
```diff
@@ -381,7 +381,12 @@ void ShaderCompiler::_dump_function_deps(const SL::ShaderNode *p_node, const Str
 	}
 }
 
-static String _get_global_shader_uniform_from_type_and_index(const String &p_buffer, const String &p_index, ShaderLanguage::DataType p_type) {
+static String _get_global_shader_uniform_from_type_and_index(const String &p_buffer, const String &p_index, ShaderLanguage::DataType p_type, bool use_uint_as_index = false) {
```
Comment (AThousandShips) [inline servers/rendering/shader_compiler.cpp:384]:
```suggestion
static String _get_global_shader_uniform_from_type_and_index(const String &p_buffer, const String &p_index, ShaderLanguage::DataType p_type, bool p_use_uint_as_index = false) {
```

File: servers/rendering/shader_compiler.cpp [hunk 2]
```diff
@@ -381,7 +381,12 @@ void ShaderCompiler::_dump_function_deps(const SL::ShaderNode *p_node, const Str
 	}
 }
 
-static String _get_global_shader_uniform_from_type_and_index(const String &p_buffer, const String &p_index, ShaderLanguage::DataType p_type) {
+static String _get_global_shader_uniform_from_type_and_index(const String &p_buffer, const String &p_index, ShaderLanguage::DataType p_type, bool p_use_uint_as_index = false) {
+	String index_suffix = {};
```
Comment (akien-mga) [inline servers/rendering/shader_compiler.cpp:385]: Strings are default initialized to `""` already.
```suggestion
	String index_suffix;
```

Comment (jsjtxietian) [reply servers/rendering/shader_compiler.cpp:385]: Ah I know that, just a C++ habit of of always zero initializing a variable. Will fix it.

Comment (AThousandShips) [reply servers/rendering/shader_compiler.cpp:385]: Here initialisation like this would be wrong anyway at least style wise, if anything it should be either `String()` or `""`, good to get used to

File: servers/rendering/shader_compiler.cpp [hunk 3]
```diff
@@ -381,7 +381,12 @@ void ShaderCompiler::_dump_function_deps(const SL::ShaderNode *p_node, const Str
 	}
 }
 
-static String _get_global_shader_uniform_from_type_and_index(const String &p_buffer, const String &p_index, ShaderLanguage::DataType p_type) {
+static String _get_global_shader_uniform_from_type_and_index(const String &p_buffer, const String &p_index, ShaderLanguage::DataType p_type, bool p_use_uint_as_index = false) {
+	String index_suffix;
+	if (p_use_uint_as_index) {
+		index_suffix = "u";
+	}
```
Comment (clayjohn) [inline servers/rendering/shader_compiler.cpp:388]: I see that this function is only called in 4 places. Two are using global variables and 2 are using instance variables. Is there any reason that instance variables shouldn't have "u" appended to the 1? 

If not, the "u" could just be added to the string which would avoid doing these string operations at run time.

Comment (jsjtxietian) [reply servers/rendering/shader_compiler.cpp:388]: No

Comment (clayjohn) [reply servers/rendering/shader_compiler.cpp:388]: I think we can most likely just always add the "u"

Comment (jsjtxietian) [reply servers/rendering/shader_compiler.cpp:388]: Agreed!

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.
