### PR TITLE
C#: Don't return MethodInfo for overloaded methods

### LINKED ISSUE #89924: GDScript Analyzer cannot correctly resolve C# arguments methods.
### Tested versions

v4.3.dev5.mono.official.89f70e98d

### System information

Windows 10.0.22000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.5123) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

It runs correctly in version 4.2.1, but errors occur starting from version 4.3.
If this segment of source code is removed, runs normally.
https://github.com/godotengine/godot/blob/7d151c83811f8ac8873439826c16d88c83aba12f/modules/gdscript/gdscript_analyzer.cpp#L3307

CSharp:
```csharp
using Godot;
using System;

public partial class GlobalDotnetScript : Node
{
    public static void SayHi(int a, int b, int c, int d, int e, int f)
    {
        GD.Print($"[GlobalDotnetScript] SayHi: {a}, {b}, {c}, {d}, {e}, {f}");
    }

    public void SayHello(int a, int b, int c, int d, int e, int f)
    {
        GD.Print($"[GlobalDotnetScript] SayHello: {a}, {b}, {c}, {d}, {e}, {f}");
    }
    public static void SayHi()
    {
        GD.Print($"[GlobalDotnetScript] SayHi!");
    }

    public void SayHello()
    {
        GD.Print($"[GlobalDotnetScript] SayHello!");
    }
}
```
GDScript:
```gdscript
extends Node

const GlobalDotnetScript = preload("res://GlobalDotnetScript.cs");

func _ready() -> void:
	GlobalDotnetScript.SayHi(1,2,3,4,5,6);
	var node =GlobalDotnetScript.new();
	add_child(node);
	node.SayHello(1,2,3,4,5,6)
	# Parse Error: Too few arguments for "SayHello()" call. Expected at least 6 but received 0.
	node.SayHello();
	# Parse Error: Too few arguments for "SayHi()" call. Expected at least 6 but received 0.
	GlobalDotnetScript.SayHi();
```

### Steps to reproduce

1. Open the project.
2. Open the 'test_node.tscn' scene and run it.

### Minimal reproduction project (MRP)

[csharp-test-method.zip](https://github.com/godotengine/godot/files/14764056/csharp-test-method.zip)

### LINKED ISSUE #90946: Impossible to call overloaded methods between languages
### Tested versions

- Reproducible in v4.3.dev.mono.custom_build [4a0160241]
- Reproducible in v4.2.2.stable.mono.official [15073afe3]
- Not reproducible in v4.2.1.stable.mono.official [b09f793f5]
- Bisected back to #86259

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 31.0.15.5222) - Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 Threads)

### Issue description

Calling overloaded methods across language boundaries is not possible any more. Given the `Bar.cs` script provided below, trying to call `Bar.SayHello()` from GDScript is raising the following error:
```
Too few arguments for "SayHello()" call. Expected at least 1 but received 0.
```
Such a call was possible without any issue in earlier versions (up to, including, 4.2.1).

### Steps to reproduce

- Make a scene with the following structure.
   ```
   Foo [Foo.gd]
   └── Bar [Bar.cs]
   ```
- Attach `Foo.gd`.
   ```gdscript
   extends Node
   
   @onready
   var bar : Bar = get_node("Bar") as Bar
   
   func _ready() -> void:
       bar.SayHello()
       bar.SayHello("World")
   ```
- Attach `Bar.cs`.
   ```cs
   [GlobalClass]
   public partial class Bar : Node
   {
       public void SayHello(string name)
       {
           GD.Print($"Hello {name}!");
       }
       
       public void SayHello()
       {
           GD.Print("Hello World!");
       }
   }
   ```
- Build.
- Witness the error.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/15048428/MRP.zip)

### PR DESCRIPTION
**Pull request by raulsntos**
This means the GDScript analyzer loses the method signature information so it can't do type checking for the parameters.

- Fixes https://github.com/godotengine/godot/issues/90946.
- Fixes https://github.com/godotengine/godot/issues/89924.

### CODE REVIEW

**Review by paulloz — APPROVED** [review]
It works fine 👌

Now, I'm not the one to judge whether the downside outweighs the benefits here, or not.

**Comment by akien-mga** [comment]
Thanks!
