### PR TITLE
[3.x] Use signed integers for async shader conditionals

### LINKED ISSUE #62203: [3.5 rc4] 3D editor viewport doesn't render any contents.
### Godot version

v3.5.rc4.official [e047c5006]

### System information

Windows 10, Intel Graphics, GLES3

### Issue description

3D viewport in the editor doesn't render anything except for background color or the sky. 

No origin, no grids, no nodes, gizmos etc.

Everything worked fine on v3.5.rc3.official [af8a02dda].

On launch, Godot prints a bunch of shader compilation errors to stderr.

[stderr.txt](https://github.com/godotengine/godot/files/8934881/stderr.txt)
[stdout.txt](https://github.com/godotengine/godot/files/8934884/stdout.txt)

### Steps to reproduce

Create and open a new project.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by RandomShaper**
My great suspect for the regression is #57674, which was merged between those two milestones. Looks like Intel's GLSL implementation is not very compliant with unsigned literals. Maybe the more recent ones are.

**NOTE:** In order to be sure we're happy with this, we'd have to check again async compilation on a bit more GL ES implementations. I've tested myself on recent integrated AMD and discrete Nvidia GPUs, with no issues. Of course, someone should check Intel HD Graphics. Some Androids would be cool as well, ensuring project settings don't forbid it, which is the default, if I recall correctly.

Fixes #62203.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
