### ISSUE TITLE
[Regression] Mono build fails after recent update

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22127]
**Godot version:**
`master` / 9af72f0

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
Since a recent update, building Godot with Mono support fails with following errors:
```
[  5%] Compiling ==> main/main.cpp
[ 26%] Compiling ==> modules/mono/glue/mono_glue.gen.cpp
[ 26%] Compiling ==> modules/mono/mono_gd/gd_mono_marshal.cpp
[ 26%] Compiling ==> modules/mono/mono_gd/gd_mono_method.cpp
modules/mono/glue/mono_glue.gen.cpp:3:22: error: unknown type name 'MethodBind'
void godot_icall_1_0(MethodBind* method, Object* ptr, int32_t arg1) {
                     ^
modules/mono/glue/mono_glue.gen.cpp:3:42: error: unknown type name 'Object'
void godot_icall_1_0(MethodBind* method, Object* ptr, int32_t arg1) {
                                         ^
modules/mono/glue/mono_glue.gen.cpp:3:55: error: unknown type name 'int32_t'
void godot_icall_1_0(MethodBind* method, Object* ptr, int32_t arg1) {
                                                      ^
modules/mono/glue/mono_glue.gen.cpp:5:2: error: unknown type name 'int64_t'
        int64_t arg1_in = (int64_t)arg1;
        ^
modules/mono/glue/mono_glue.gen.cpp:5:21: error: use of undeclared identifier 'int64_t'
        int64_t arg1_in = (int64_t)arg1;
                           ^
modules/mono/glue/mono_glue.gen.cpp:7:34: error: use of undeclared identifier 'NULL'
        method->ptrcall(ptr, call_args, NULL);
                                        ^
modules/mono/glue/mono_glue.gen.cpp:10:1: error: unknown type name 'int32_t'
int32_t godot_icall_0_1(MethodBind* method, Object* ptr) {
^
modules/mono/glue/mono_glue.gen.cpp:10:25: error: unknown type name 'MethodBind'
int32_t godot_icall_0_1(MethodBind* method, Object* ptr) {
                        ^
modules/mono/glue/mono_glue.gen.cpp:10:45: error: unknown type name 'Object'
int32_t godot_icall_0_1(MethodBind* method, Object* ptr) {
                                            ^
modules/mono/glue/mono_glue.gen.cpp:11:2: error: unknown type name 'int64_t'
        int64_t ret;
        ^
modules/mono/glue/mono_glue.gen.cpp:12:23: error: use of undeclared identifier 'int32_t'
        ERR_FAIL_NULL_V(ptr, int32_t());
                             ^
modules/mono/glue/mono_glue.gen.cpp:13:23: error: use of undeclared identifier 'NULL'
        method->ptrcall(ptr, NULL, &ret);
                             ^
modules/mono/glue/mono_glue.gen.cpp:14:10: error: use of undeclared identifier 'int32_t'
        return (int32_t)ret;
                ^
modules/mono/glue/mono_glue.gen.cpp:17:1: error: unknown type name 'MonoString'
MonoString* godot_icall_0_2(MethodBind* method, Object* ptr) {
^
modules/mono/glue/mono_glue.gen.cpp:17:29: error: unknown type name 'MethodBind'
MonoString* godot_icall_0_2(MethodBind* method, Object* ptr) {
                            ^
modules/mono/glue/mono_glue.gen.cpp:17:49: error: unknown type name 'Object'
MonoString* godot_icall_0_2(MethodBind* method, Object* ptr) {
                                                ^
modules/mono/glue/mono_glue.gen.cpp:18:2: error: unknown type name 'String'
        String ret;
        ^
modules/mono/glue/mono_glue.gen.cpp:19:23: error: use of undeclared identifier 'NULL'
        ERR_FAIL_NULL_V(ptr, NULL);
                             ^
modules/mono/glue/mono_glue.gen.cpp:20:23: error: use of undeclared identifier 'NULL'
        method->ptrcall(ptr, NULL, &ret);
                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by akien-mga** [comment]
Probably the intended regression mentioned by @neikeq in https://github.com/godotengine/godot/pull/21990#issuecomment-420500493

**Comment by mysticfall** [comment]
@akien-mga Yes, deleting the mentioned file indeed fixed the problem. Thanks for the head up!
