### ISSUE TITLE
Build error: EGL/egl.h not found (buildroot)

### ISSUE THREAD

**Issue by roalyr** [godotengine/godot#98820]
### Tested versions

4.x as of 1bffd6c73b44b85e5889f54e14b2193940cf5bb1

### System information

Buildroot version: godot-2023.08.x-3

### Issue description

```
...
Generating modules/modules_enabled.gen.h ...
Compiling thirdparty/openxr/src/common/filesystem_utils.cpp ...
In file included from thirdparty/openxr/src/common/platform_utils.hpp:12,
                 from thirdparty/openxr/src/common/filesystem_utils.cpp:13:
thirdparty/openxr/src/common/xr_dependencies.h:80:10: fatal error: EGL/egl.h: No such file or directory
   80 | #include <EGL/egl.h>
```

`libegl1-mesa-dev` is installed on system path just in case.

### Steps to reproduce

Build from source `master` branch.

### Minimal reproduction project (MRP)

-

**Comment by akien-mga** [comment]
That's a regression from #97771 which added EGL as a new dependency. So the buildroot would need to be updated to include it too.

But I need to first check why this system-wide dependency was needed. CC @dsnopek @Riteo

**Comment by dsnopek** [comment]
Hm, we should already already be using EGL headers, either via `EGL/egl.h` or GLAD - I don't see why there would a _new_ dependency.

**Comment by akien-mga** [comment]
Right we need to patch the OpenXR header then.

**Comment by dsnopek** [comment]
PR https://github.com/godotengine/godot/pull/98824 will hopefully do it!
