### ISSUE TITLE
[3.0] Godot fails to compile on Linux master a8e845a because of a core/math function

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#9166]
**Operating system or device - Godot version:**
Linux Ubuntu 16.04 64bits
3.0 master commit a8e845a474c01c4cde1416ed00e6ae456786c1fb

**Issue description:**
with the latest master 3.0 there is a compilation error, yesterday it was compiling O.K.

**Steps to reproduce:**
updated the code with git pull, try to compile as usual with scons platform=x11 -j 4
an error appears:
core/math/math_funcs.h: In static member function 'static bool Math::is_inf(double)':
core/math/math_funcs.h:123:21: error: 'isinf' was not declared in this scope

**Comment by akien-mga** [comment]
Likely related to changes in 6a9c990d, though I don't see why they would trigger an issue. (cc @tagcup)

**Comment by rubenjavier** [comment]
I also went tocheck the changes on core/math/math_funcs.h but I dont see why they would trigger this either... maybe its coming from another change on an include file

**Comment by tagcup** [comment]
Works fine with gcc 6 and 7, so that's clearly an issue with outdated compilers, probably with C++11 enabled etc2comp files, can you send more information about the compilation and error, maybe put the whole thing in pastebin or alike?

We may need to use the mingw workaround in that commit for that particular version of gcc too.

**Comment by akien-mga** [comment]
I confirm it builds fine with GCC 5.4.0.

**Comment by rubenjavier** [comment]
**from the command line:
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609


**with a clean
$ git clone https://github.com/godotengine/godot
$ cd godot
$ scons log=environment
scons: Reading SConscript files ...
sh: 1: i586-mingw32msvc-gcc: not found
sh: 1: i686-w64-mingw32-gcc: not found
No valid target platform selected.
The following were detected:
        server
        haiku
        windows
        x11

Please run scons again with argument: platform=<string>
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.


$ scons platform=x11 -j 4

**and the error appears:
core/math/math_funcs.h: In static member function 'static bool Math::is_inf(double)':
core/math/math_funcs.h:123:21: error: 'isinf' was not declared in this scope
   return isinf(p_val);
                     ^
core/math/math_funcs.h:123:21: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from thirdparty/etc2comp/EtcFilter.h:3,
                 from modules/etc/image_etc.cpp:32:
/usr/include/c++/5/cmath:621:5: note:   'std::isinf'
     isinf(_Tp __x)
     ^
In file included from core/color.h:33:0,
                 from core/image.h:33,
                 from modules/etc/image_etc.cpp:33:
core/math/math_funcs.h: In static member function 'static bool Math::is_inf(float)':
core/math/math_funcs.h:139:21: error: 'isinf' was not declared in this scope
   return isinf(p_val);
                     ^
core/math/math_funcs.h:139:21: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from thirdparty/etc2comp/EtcFilter.h:3,
                 from modules/etc/image_etc.cpp:32:
/usr/include/c++/5/cmath:621:5: note:   'std::isinf'
     isinf(_Tp __x)

**Comment by Zireael07** [comment]
@rubenjavier: Tried to compile without -j4? Threading sometimes makes scons misbehave...

**Comment by rubenjavier** [comment]
@Zireael07 
just tried as suggested:
clean
$ scons platform=x11 -c
build
$ scons platform=x11

*same error

**Comment by rubenjavier** [comment]
could this be because math.h is now also included with "pragma once" on?:
thirdparty/etc2comp/EtcColor.h
thirdparty/etc2comp/EtcColorFloatRGBA.h
thirdparty/etc2comp/EtcMath.h

**Comment by tagcup** [comment]
This is because isinf from math.h isn't accessible in C++11 mode (which is required by etc2comp) in certain 5.x versions of GCC.

As I explained last time, I already added a workaround for this math_funcs.h, see [this](https://github.com/godotengine/godot/blob/master/core/math/math_funcs.h#L114) and [this](https://github.com/godotengine/godot/blob/master/core/math/math_funcs.h#L131) line, but it is enabled only for mingw at the moment. We can enable for all gcc versions <6 as a workaround for people using old versions of gcc.

**Comment by tagcup** [comment]
@rubenjavier I just submitted #9177 (will mention this issue in the commit message once it passes the tests), could you give it a try?

**Comment by lethiandev** [comment]
I've fixed it by adding the cmath header and using `std` namespace for isinf, like `std::isinf`. Works on my local build. I'm using the same gcc compiler as @rubenjavier `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609`

**Comment by tagcup** [comment]
@lethiandev We can't use STL stuff in Godot

**Comment by lethiandev** [comment]
@tagcup that's why i didn't pull request, but it works as workaround for me meantime :smiley:

**Comment by tagcup** [comment]
Well, I'm mentioning this for the 3rd time in this thread, but there already is a workaround for that in math_funcs.h which you can use, and you can try #9177 if you want to avoid any manual labor.

**Comment by akien-mga** [comment]
> We can't use STL stuff in Godot

Are you sure `<cmath>` is part of the [STL](https://en.wikipedia.org/wiki/Standard_Template_Library) though? I would have say it's provided by the [C standard library](https://en.wikipedia.org/wiki/C_standard_library)?

**Comment by capnm** [comment]
FYI
It's a LTS, also this gcc5 will be there as default for long time.  Here is some related ubuntu issue:
https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1617838

On the same OS, e.g. the gcc7 ```gcc version 7.1.0 (Ubuntu 7.1.0-6ubuntu2~16.04.york0)```
from the https://launchpad.net/~jonathonf PPA compiles the godot tip fine.

**Comment by rubenjavier** [comment]
@tagcup Thank you very much, and sorry I wont be near my machine until tomorrow, but I'll test it tomorrow, first thing in the morning (Im on Spain GTM+1), so if anyone else can test tagcup`s submit in the meantime, go for it and report back.

**Comment by lethiandev** [comment]
@rubenjavier, @tagcup's solution works perfectly. Tested on my Ubuntu 16.04 LTS with gcc 5.4.0.

**Comment by tagcup** [comment]
It is a dependency of STL. `math.h` is a part of libc, `cmath` apparently comes with g++. I honestly don't know the exact boundaries of "STL" as referenced in Godot policy, libstdc++ and whatever comes with g++ (crt0, libgcc, language specific stuff). I opened open `cmath` and it does contain lots of templates and other includes other templated headers.

I avoided `cmath` and stuck with `math.h` because that's how it was. @reduz (or whoever wrote that bit of code) can probably tell you about the reasoning.

**Comment by rubenjavier** [comment]
@lethiandev great to hear that, thank you for your testing, glad to know there is a way to keep the LTS gcc version and the new features, thanks again @tagcup

**Comment by tagcup** [comment]
@akien-mga I now remember when I first implemented the float and double versions of math functions (sin, log, isinf, and all that), I simply used cmath, as it readily contains both versions and submitted the PR like that, but later on it turned out to be a no-go, so I manually added overloaded versions of those.

**Comment by akien-mga** [comment]
@tagcup Right, we discussed this on IRC and @hpvb mentioned that:
```
#include <math.h> isinf() is c99
#include <cmath> std::isinf() is c++11
```

**Comment by tagcup** [comment]
Yeah, we're only using the one from libc, which is also available from C++ since about last 2 decades. It's actually a macro BTW.

Seems like this was a [gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=48891), not sure if everyone backported it properly.

**Comment by akien-mga** [comment]
> Seems like this was a libstdc++ bug, not sure if everyone backported it properly.

Thanks for digging this up, that makes sense. Mageia's GCC is synced with the upstream 5.4.x branch to get bugfixes, so that explains why I can't reproduce the bug.
