### PR TITLE
Fix compile error when tools=no

### LINKED ISSUE #3213: Can't compile without tools
There's an error when compiling the current HEAD without tools enabled. It was introduced in 2db78e8f.

Error message:
```
scene/main/scene_main_loop.cpp:624:24: error: use of undeclared identifier 'edited_scene_root'
        return editor_hint && edited_scene_root && edited_scene_root->is_a_parent_of(p_node);
                              ^
```
 
`edited_scene_root` is only there if `TOOLS_ENABLED` is defined

### PR DESCRIPTION
**Pull request by mrezai**
Fix #3213

### CODE REVIEW

**Comment by reduz** [comment]
I would instead just leave the function be, is there any problem with it?

**Comment by akien-mga** [comment]
There seems to be an issue (#3213), but indeed the fix is overkill. I guess ```editor_hint``` should have been false and the second part of the return statement should not be processed.

A simpler workaround would be:
```
bool SceneTree::is_node_being_edited(const Node* p_node) const {
#ifdef TOOLS_ENABLED
    return editor_hint && edited_scene_root && edited_scene_root->is_a_parent_of(p_node);
#else
    return false;
#endif
}
```

**Comment by reduz** [comment]
ah I understand now, thanks, that seems ok to me

**Comment by mrezai** [comment]
It makes sense if is_node_being_edited function only should be used in tools mode

**Comment by akien-mga** [comment]
I think we'd better investigate why editor_hint is true though, it looks like a regression.

**Comment by mrezai** [comment]
I checked, set_editor_hint only calls in editor_node and project_manager so I think your suggestion is ok

**Comment by akien-mga** [comment]
I pushed the fix proposed above in a new PR, so I'll close this one.
