### PR TITLE
Revert "Fix mbedTLS and websocket module for UWP"

### PR DESCRIPTION
**Pull request by fire**
Reverts godotengine/godot#16865

Breaks mingw build on centos 7.4.

```
[go] Task: /bin/bash -c "scons platform=windows target=release_debug -j`nproc --all` use_lto=no gdnative_wrapper=yes deprecated=no"took: 11.138sexited: 2
scons: Reading SConscript files ...
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
Compiling ==> main/main.cpp
Compiling ==> thirdparty/mbedtls/library/entropy_poll.c
thirdparty/mbedtls/library/entropy_poll.c:66:21: fatal error: intsafe.h: No such file or directory
 #include <intsafe.h>
                     ^
compilation terminated.
scons: *** [thirdparty/mbedtls/library/entropy_poll.windows.opt.tools.64.o] Error 1
```

### CODE REVIEW

**Comment by vnen** [comment]
I would try to fix the build for MinGW instead of just reverting the commit.

**Comment by fire** [comment]
Well, I guess, I can wait a day, but I don't know when @Faless will fix it. It's been broken for 2 days.

**Comment by vnen** [comment]
Well, the UWP build was broken for a much longer time, but we were only aware when someone reported it. If you knew it was broken 2 days ago you should have reported then.

I just don't like reverting because then we are back to the previous state and have to add yet another patch for UWP, probably repeating part of it (or is the lws lib also broken?). It think it's less trouble to just investigate a fix for MinGW.

**Comment by akien-mga** [comment]
We don't support such an old MinGW, so we won't revert a fix for a supported platform for it. I'll gladly merge a fix that lets old MinGW build, but without crippling other platforms.

**Comment by bruvzg** [comment]
macOS / mingw-w64 5.0.3 / gcc 7.3.0 and Debian buster/sid / mingw-w64 5.0.3-1 / gcc 7.2.0-20: mingw builds works ok.

`intsafe.h` header only present in 5.x branch of mingw-w64.

**Comment by AlexHolly** [comment]
Is there an open issue for that? I ran into it yesterday (cross compiling with ubuntu).

**Comment by Faless** [comment]
@AlexHolly no, there isn't, though we are evaluating a workaround. If you want you can try this branch and let me know it it works for you: https://github.com/Faless/godot/tree/mingw4fix

**Comment by Faless** [comment]
@AlexHolly you might still want to update your mingw toolchain if you plan to build production ready templates with it, as newer versions (5.x) produce much better binaries (i.e. more performance in game)
