### PR TITLE
Initial Vulkan support for macOS (MoltenVK) and Windows

### PR DESCRIPTION
**Pull request by bruvzg**
Adds initial MoltenVK support (macOS Vulkan context, static MoltenVK or via loader)
Adds initial Windows support (Vulkan context)
Adds built-in Vulkan ICD loader (`builtin_vulkan_loader` option)

**Opening it mainly for future reference, probably it's not very useful at this point.**

*Current status (11 July 2019): everything seems to work as expected*

Screenshot 2019-07-11 at 09 17 28

### CODE REVIEW

**Comment by bruvzg** [comment]
Added Windows context as well (as separate commit). Everything seems to work at the same level as Linux/X11 build.

windows_vulkan_editor

*Here's Vulkan Info outputs from the same hardware on macOS, Windows and Linux to compare capabilities:*

[Vulkan Info - Windows](https://gist.github.com/bruvzg/ff712ae45c6e9793a33e06fdadf36637)
[Vulkan Info - macOS](https://gist.github.com/bruvzg/a14eacf9e7aad44e2b623997ea0afcb0)
[Vulkan Info - Linux](https://gist.github.com/bruvzg/1e7cc052e6500c9775f3356667317973)

**Comment by clayjohn** [comment]
Amazing! I will test on Windows tonight.

**Comment by bruvzg** [comment]
Now it's working with MSVC too (tested with Visual Studio 2019).

**Comment by akien-mga** [comment]
We need to figure out how to install the Vulkan SDK on Travis and AppVeyor.
Or should we vendor those headers?

**Comment by bruvzg** [comment]
> We need to figure out how to install the Vulkan SDK on Travis and AppVeyor.
Or should we vendor those headers?

LunarG SDKs are downloadable via direct link - https://vulkan.lunarg.com/sdk/download/1.1.108.0/mac/vulkan-1.1.108.0.tar.gz, but it's 160 to 500 MB for each platform, we only need 3.5 MB of headers (same for all platforms, and probably significant part can be omitted) and 50-300 KB `libvulkan` loader lib to link.

For macOS, I have added SDK install via homebrew, It's passing CI (https://travis-ci.org/godotengine/godot/jobs/551020951) but homebrew update is really slow (takes almost 5 minutes, without update package is not found, and it's outdated even after update). And AFAIK all Linux distros Travis provide have outdated Vulkan package as well.

Maybe it's more reasonable to add both includes and loader binaries from LunarG SDK to the repo. 

Or include Vulkan loader (https://github.com/KhronosGroup/Vulkan-Loader) source as the part of engine.

**Comment by akien-mga** [comment]
I don't want to add binaries to the repo, but we could consider building Vulkan-Loader yeah.

**Comment by bruvzg** [comment]
> but we could consider building Vulkan-Loader yeah.

Let's give it a try. (I have temporary removed Android/iOS builds and `werror=yes` to test whether it's building at all).

**Comment by bruvzg** [comment]
Well that's some progress, if built-in Vulkan loader doesn't affect portability in some negative way (if I understand it correctly it shouldn't) it is at least a viable option.

Screenshot 2019-07-04 at 18 18 12
Screenshot 2019-07-04 at 19 30 24

Editor for Windows, Linux and macOS builds (with multiple warnings).

Export templates fail, but now we have a bit more useful errors:

*Linux export template (release, Clang):*
```
scene/gui/graph_edit.cpp:680:51: error: too many arguments to function call,
      expected at most 3, have 4
        p_where->draw_polyline_colors(points, colors, 2, true);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                    ^~~~
./scene/2d/canvas_item.h:323:2: note: 'draw_polyline_colors' declared here
        void draw_polyline_colors(const Vector<Point2> &p_points, const ...
        ^
```

*Linux export template (release_debug, GCC 5, without 3D support):*
```
./thirdparty/glslang/glslang/Public/ShaderLang.h: In member function 'virtual glslang::TShader::Includer::IncludeResult* glslang::TShader::Includer::includeSystem(const char*, const char*, size_t)':
./thirdparty/glslang/glslang/Public/ShaderLang.h:526:82: error: 'nullptr' was not declared in this scope
                                  size_t /*inclusionDepth*/) { return nullptr; }
                                                                      ^
./thirdparty/glslang/glslang/Public/ShaderLang.h: In member function 'virtual glslang::TShader::Includer::IncludeResult* glslang::TShader::Includer::includeLocal(const char*, const char*, size_t)':
./thirdparty/glslang/glslang/Public/ShaderLang.h:533:81: error: 'nullptr' was not declared in this scope
                                  size_t /*inclusionDepth*/) { return nullptr; }
                                                                      ^
./thirdparty/glslang/glslang/Public/ShaderLang.h: In constructor 'glslang::TObjectReflection::TObjectReflection()':
./thirdparty/glslang/glslang/Public/ShaderLang.h:641:68: error: 'nullptr' was not declared in this scope
           topLevelArrayStride(0), stages(EShLanguageMask(0)), type(nullptr)
                                                                    ^
```

**Comment by bruvzg** [comment]
After rebasing to c96937c6b7767ef447f2c44ae2fee00fc70a9411, macOS app fails with the following errors:

```
VK_KHR_incremental_present extension NOT AVAILABLE

VK_GOOGLE_display_timing extension NOT AVAILABLE

Vulkan physical device creation success o_O
update size: 64
ERROR: _render_pass_create: Index p_format[i].samples=32698 out of size (TEXTURE_SAMPLES_MAX=7)
   At: drivers/vulkan/rendering_device_vulkan.cpp:2446.
ERROR: render_pipeline_create: Mismatch fragment output bindings (1) and framebuffer color buffers (0) when binding both in render pipeline.
   At: drivers/vulkan/rendering_device_vulkan.cpp:4349.
ERROR: render_pipeline_create: Mismatch fragment output bindings (1) and framebuffer color buffers (0) when binding both in render pipeline.
   At: drivers/vulkan/rendering_device_vulkan.cpp:4349.
ERROR: render_pipeline_create: Mismatch fragment output bindings (1) and framebuffer color buffers (0) when binding both in render pipeline.
   At: drivers/vulkan/rendering_device_vulkan.cpp:4349.

[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:189:433: error: 'texture' has a duplicate index '3'
fragment main0_out main0(main0_in in [[stage_in]], constant uint* spvSwizzleConstants [[buffer(3)]], constant CanvasData& canvas_data [[buffer(0)]], constant LightData& light_array [[buffer(1)]], constant DrawData& draw_data [[buffer(2)]], texture2d<float> color_texture [[texture(0)]], texture2d<float> normal_texture [[texture(1)]], texture2d<float> specular_texture [[texture(2)]], array<texture2d<float>, 1024> light_textures [[texture(3)]], sampler texture_sampler [[sampler(0)]])
                                                                                                                                                                                                                                                                                                                                                                                                                                                ^
program_source:327:23: warning: unused variable 'cVdotH'
                float cVdotH = fast::max(dot(view, half_vec), 0.0);
                      ^
program_source:328:23: warning: unused variable 'cLdotH'
                float cLdotH = fast::max(dot(light_vec, half_vec), 0.0);
                      ^
.
```

File: SConstruct [hunk 1]
```diff
@@ -298,6 +298,8 @@ if selected_platform in platform_list:
     CXXFLAGS = env.get('CXXFLAGS', '')
     env['CXXFLAGS'] = ''
     env.Append(CXXFLAGS=str(CXXFLAGS).split())
+    if not env.msvc:
+        env.Append(CXXFLAGS="-std=c++11")
```
Comment (akien-mga) [inline SConstruct]: While we'll do that Soon™ for real, it should be sufficient to do it for the `env_vlk_ldr` environment for now, no?

Comment (bruvzg) [reply SConstruct]: Part of vulkan related includes (glslang) used in the "platform" have `nullptr`s, and "platform" doesn't have separate environment. This cause GCC 5 build to fail, newer compilers seems to have some of c+11 stuff enabled by default.

Comment (aaronfranke) [reply SConstruct]: Sounds like the ideal solution is to wait for after 3.2 is released and Godot upgrades C++ for 4.0.

File: SConstruct [hunk 2]
```diff
@@ -110,7 +110,10 @@ opts.Add('p', "Platform (alias for 'platform')", '')
 opts.Add('platform', "Target platform (%s)" % ('|'.join(platform_list), ), '')
 opts.Add(EnumVariable('target', "Compilation target", 'debug', ('debug', 'release_debug', 'release')))
 opts.Add(EnumVariable('optimize', "Optimization type", 'speed', ('speed', 'size')))
+
 opts.Add(EnumVariable('renderer', "Renderer type", 'vulkan', ('vulkan', 'opengl')))
+opts.Add(BoolVariable('builtin_vulkan_loader', 'Use built-in Vlukan loader (libvulkan)', True))
```
Comment (akien-mga) [inline SConstruct]: Typo, "Vlukan".

File: drivers/vulkan/SCsub [hunk 3]
```diff
@@ -4,68 +4,119 @@ Import('env')
...
-"SPIRV/InReadableOrder.cpp",
-"SPIRV/GlslangToSpv.cpp",
-"SPIRV/SpvBuilder.cpp",
-"SPIRV/SpvTools.cpp",
-"SPIRV/disassemble.cpp",
-"SPIRV/doc.cpp",
-"SPIRV/SPVRemapper.cpp",
-"SPIRV/SpvPostProcess.cpp",
-"SPIRV/Logger.cpp"
+	"glslang/MachineIndependent/RemoveTree.cpp",
```
Comment (akien-mga) [inline drivers/vulkan/SCsub]: Should use 4 spaces for indentation in Python files.

File: platform/windows/detect.py [hunk 4]
```diff
@@ -217,9 +217,21 @@ def configure_msvc(env, manual_msvc_config):
 
     ## Libs
 
-    LIBS = ['winmm', 'opengl32', 'dsound', 'kernel32', 'ole32', 'oleaut32',
+    LIBS = ['winmm','dsound', 'kernel32', 'ole32', 'oleaut32',
             'user32', 'gdi32', 'IPHLPAPI', 'Shlwapi', 'wsock32', 'Ws2_32',
-	    'shell32', 'advapi32', 'dinput8', 'dxguid', 'imm32', 'bcrypt','Avrt']
+        'shell32', 'advapi32', 'dinput8', 'dxguid', 'imm32', 'bcrypt','Avrt']
```
Comment (akien-mga) [inline platform/windows/detect.py]: Alignment issue (though it preexisted). Might be worth adding the missing space before 'Avrt' and 'dsound' too.

File: SConstruct [hunk 5]
```diff
@@ -110,6 +110,10 @@ opts.Add('p', "Platform (alias for 'platform')", '')
 opts.Add('platform', "Target platform (%s)" % ('|'.join(platform_list), ), '')
 opts.Add(EnumVariable('target', "Compilation target", 'debug', ('debug', 'release_debug', 'release')))
 opts.Add(EnumVariable('optimize', "Optimization type", 'speed', ('speed', 'size')))
+
+opts.Add(EnumVariable('renderer', "Renderer type", 'vulkan', ('vulkan', 'opengl')))
```
Comment (akien-mga) [inline SConstruct]: AFAIK the plan is to provide both OpenGL ES 2.0 / GL 2.1 and Vulkan support in the same binary, so I don't think it should be a build option (or there should be a "all" option which would be the default value).

I see that Vulkan support raises min macOS version requirements though, so we should see whether we want to keep supporting pre 10.11 versons and have this build option, or drop support for older versions and have Vulkan + OpenGL for everyone.

File: SConstruct [hunk 6]
```diff
@@ -110,6 +110,10 @@ opts.Add('p', "Platform (alias for 'platform')", '')
...
+opts.Add(BoolVariable('builtin_vulkan_loader', 'Use built-in Vulkan loader (libvulkan)', True))
```
Comment (akien-mga) [inline SConstruct]: Should go together with other `builtin_` options, sorted alphabetically.

File: SConstruct (hunk 5 above)
Comment (bruvzg) [reply SConstruct]: Using both will require some extra changes to all platforms.

Currently, OpenGLES 2 stuff is not functional, will it be reimplemented as `RenderingDevice` and use `RasterizerRD` or use existing rasterisers?

Comment (bruvzg) [reply SConstruct]: I removed `renderer` option, and added runtime video driver checks assuming will use `RenderingDevice` (I have tested GL context part compiling, but disabled it for now as there's no `RenderingDevice` for GL). Any future changes (like auto fallback from Vulkan to GL) to the platform probably should wait for the multiple window implementation. Some of Vulkan / GL init could be done only after window creation and window creation have driver specific stuff.

File: thirdparty/glslang/glslang/Include/Common.h [hunk 7]
```diff
@@ -50,7 +50,9 @@ std::string to_string(const T& val) {
 }
 #endif
 
-#if (defined(_MSC_VER) && _MSC_VER < 1900 /*vs2015*/) || defined MINGW_HAS_SECURE_API
+// -- GODOT start --
+#if (defined(_MSC_VER) && _MSC_VER < 1900 /*vs2015*/) /* || defined MINGW_HAS_SECURE_API*/
```
Comment (akien-mga) [inline thirdparty/glslang/glslang/Include/Common.h]: What was the issue with `MINGW_HAS_SECURE_API`? Would it be worth reporting upstream?

Comment (bruvzg) [reply thirdparty/glslang/glslang/Include/Common.h]: Build fails with the following error.
```
stdio_s.h:495:23: error: conflicting declaration of 'int sprintf_s(char*, size_t, const char*, ...)' with 'C' linkage
   _SECIMP int __cdecl sprintf_s(char *_DstBuf,size_t _DstSize,const char *_Format,...);
                       ^~~~~~~~~
In file included from thirdparty/glslang/glslang/MachineIndependent/../Include/intermediate.h:55,
                 from thirdparty/glslang/glslang/MachineIndependent/RemoveTree.cpp:37:
thirdparty/glslang/glslang/MachineIndependent/../Include/../Include/Common.h:58:22: note: previous declaration with 'C++' linkage
     #define snprintf sprintf_s
                      ^~~~~~~~~
```

Some sort of include order issue, this one probably need more investigation to make sure it's not related to the configuration of the macOS homebrew MinGW package configuration.

In the upstream it was changed back and forth few times, same error is mentioned in the upstream PR changing include order (https://github.com/KhronosGroup/glslang/pull/203/files#r56031993). bgfx have a similar fix (https://github.com/bkaradzic/bgfx/pull/1352) for example. Seems to be known problem that's coming back time to time.

**Comment by akien-mga** [comment]
Thanks a lot!

File: platform/windows/detect.py [hunk 8]
```diff
@@ -217,9 +217,20 @@ def configure_msvc(env, manual_msvc_config):
 
     ## Libs
 
-    LIBS = ['winmm', 'opengl32', 'dsound', 'kernel32', 'ole32', 'oleaut32',
+    LIBS = ['winmm', 'dsound', 'kernel32', 'ole32', 'oleaut32',
             'user32', 'gdi32', 'IPHLPAPI', 'Shlwapi', 'wsock32', 'Ws2_32',
-	    'shell32', 'advapi32', 'dinput8', 'dxguid', 'imm32', 'bcrypt','Avrt']
+            'shell32', 'advapi32', 'dinput8', 'dxguid', 'imm32', 'bcrypt', 'Avrt']
+
+    env.Prepend(CPPPATH=['#thirdparty/vulkan/include/', "#thirdparty/vulkan/registry/"])
```
Comment (akien-mga) [inline platform/windows/detect.py]: This should likely be handled directly in `drivers/vulkan_loader/SCsub` (or `drivers/vulkan/SCsub` if moved together), I'll have a look at it.

File: scene/gui/graph_edit.cpp [hunk 9]
```diff
@@ -684,7 +684,7 @@ void GraphEdit::_draw_cos_line(CanvasItem *p_where, const Vector2 &p_from, const
 #ifdef TOOLS_ENABLED
 	p_where->draw_polyline_colors(points, colors, Math::floor(2 * EDSCALE));
 #else
-	p_where->draw_polyline_colors(points, colors, 2, true);
+	p_where->draw_polyline_colors(points, colors, 2);
```
Comment (akien-mga) [inline scene/gui/graph_edit.cpp]: Oops, I missed that one in an earlier rebase.

File: thirdparty/README.md [hunk 10]
```diff
@@ -143,6 +143,15 @@ See the header of glad.c for instructions on how to generate them for
...
 
+## glslang
+
+- Upstream: https://github.com/KhronosGroup/glslang
+- Version: rev.3226
+- License: glslang
+
+Important: File `glslang/glslang/Include/Common.h` has
+Godot-made change marked with `// -- GODOT --` comments.
+
```
Comment (akien-mga) [inline thirdparty/README.md]: Sections are supposed to be separated by two lines (but I should likely drop this convention as literally nobody understands it :P).

File: thirdparty/README.md [hunk 11]
```diff
@@ -263,6 +272,25 @@ changes to ensure they build for Javascript/HTML5. Those
...
 
 
+## Vulkan Ecosystem Components (Vulkan ICD loader and headers)
+
+- Upstream: https://github.com/KhronosGroup/Vulkan-Loader
+- Version: 1.1.113 
+- License: Apache 2.0
+
+
+## wslay
```
Comment (akien-mga) [inline thirdparty/README.md]: `wslay` is already included, it was moved below to respect alphabetical order.

File: thirdparty/README.md [hunk 12]
```diff
@@ -263,6 +272,25 @@ changes to ensure they build for Javascript/HTML5. Those
 changes are marked with `// -- GODOT --` comments.
 
 
+## Vulkan Ecosystem Components (Vulkan ICD loader and headers)
```
Comment (akien-mga) [inline thirdparty/README.md]: Sections should be named like the folder they refer to (another convention that I'm the only one to understand from the context :D). And this should go further down to respect alphabetical ordering.

File: core/os/os.cpp [hunk 13]
```diff
@@ -707,9 +707,9 @@ const char *OS::get_video_driver_name(int p_driver) const {
 	switch (p_driver) {
 		case VIDEO_DRIVER_GLES2:
 			return "GLES2";
-		case VIDEO_DRIVER_GLES3:
```
Comment (aaronfranke) [inline core/os/os.cpp]: So just for clarification, does this mean GLES3 is being removed before Vulkan is finished? This is important to know for anyone who builds from master between 3.2 and 4.0.

File: thirdparty/vulkan/registry/update_deps.py [hunk 14]
```diff
@@ -0,0 +1,679 @@
+#!/usr/bin/env python
```
Comment (akien-mga) [inline thirdparty/vulkan/registry/update_deps.py]: Thirdparty python or shell scripts are not needed in our copy, we should only keep the files that we use. I'll have a look to refine further.

**Review by akien-mga — COMMENTED** [review]
Left some comments but mostly to myself for future edits, the PR is already merged so I'm not asking for any changes ;)

All those are nitpicks so I preferred to merge as is instead of asking for another iteration.

File: core/os/os.cpp (hunk 13 above)
Comment (akien-mga) [reply core/os/os.cpp]: Yes, once the `vulkan` branch is merged in `master` after the `3.2-stable` release, GLES3 will be no more. It will live on in the `3.2` branch of course.

File: SConstruct (hunk 1 above)
Comment (akien-mga) [reply SConstruct]: For the reference, this was added directly to the `master` branch in 5dae2ea777da5395cf1b1e9a8bc6abc93f6ae6bb so it's no longer included in this PR.

File: thirdparty/vulkan/registry/update_deps.py (hunk 14 above)
Comment (akien-mga) [reply thirdparty/vulkan/registry/update_deps.py]: Fixed by #31102.

File: thirdparty/README.md (hunk 12 above)
Comment (akien-mga) [reply thirdparty/README.md]: Fixed by #31102.

File: thirdparty/README.md (hunk 11 above)
Comment (akien-mga) [reply thirdparty/README.md]: Fixed by #31102.

File: thirdparty/README.md (hunk 10 above)
Comment (akien-mga) [reply thirdparty/README.md]: Fixed by #31102.

File: platform/windows/detect.py (hunk 8 above)
Comment (akien-mga) [reply platform/windows/detect.py]: Fixed by #31102.

File: drivers/vulkan_loader/SCsub [hunk 15]
```diff
@@ -0,0 +1,55 @@
+#!/usr/bin/env python
+
+Import('env')
+
+env_vlk_ldr = env.Clone()
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply drivers/vulkan_loader/SCsub]: Fixed by #31102.

File: platform/x11/detect.py [hunk 16]
```diff
@@ -314,9 +314,16 @@ def configure(env):
 
     env.Prepend(CPPPATH=['#platform/x11'])
     env.Append(CPPDEFINES=['X11_ENABLED', 'UNIX_ENABLED'])
+
+    env.Prepend(CPPPATH=['#thirdparty/vulkan/include/', "#thirdparty/vulkan/registry/"])
```
[the remark this answers is not in the document]
Comment (akien-mga) [reply platform/x11/detect.py]: Fixed by #31102.

File: thirdparty/README.md (hunk 10 above)
Comment (akien-mga) [reply thirdparty/README.md]: Fixed by #31102.

File: platform/x11/detect.py (hunk 16 above)
[the remark this answers is not in the document]
Comment (akien-mga) [reply platform/x11/detect.py]: > Note to future self: Mageia's `vulkan.pc` seems bogus, likely an issue you should fix upstream for all distros

PR'ed upstream: https://github.com/KhronosGroup/Vulkan-Loader/pull/214

File: platform/osx/detect.py [hunk 17]
```diff
@@ -127,9 +129,20 @@ def configure(env):
...
+
+    #env.Append(CPPDEFINES=['GLES_ENABLED', 'OPENGL_ENABLED'])
+
+    env.Append(LINKFLAGS=['-framework', 'Metal', '-framework', 'QuartzCore', '-framework', 'IOSurface'])
+    if (env['use_static_mvk']):
+        env.Append(LINKFLAGS=['-framework', 'MoltenVK'])
+    elif not env["builtin_vulkan_loader"]:
+        env.Append(LIBS=['vulkan'])
+
+    env.Append(CCFLAGS=['-mmacosx-version-min=10.11'])
```
[the remark this answers is not in the document]
Comment (bruvzg) [reply platform/osx/detect.py]: > Is version 10.11 a strong requirement to use MoltenVK?

Yes. It's the first OS version with Metal API support (it should run on all 2012+ macs).
