### PR TITLE
Fixes touch events for HTML

### PR DESCRIPTION
**Pull request by Schroedi**
Without this patch, the following exception is thrown when the touch
screen is used: TypeError: e.getBoundingClientRect is not a function.
No touch events arrive in the engine.

From my testing, this PR fixes the issue and behaves as expected.

Tested with godot-demo-projects/misc/multitouch_view/, emscripten 1.39.8
and Firefox mobile emulator as well as FF on Android

### CODE REVIEW

**Comment by akien-mga** [comment]
For the reference, a workaround for a related issue was documented here: https://www.reddit.com/r/godot/comments/fabf4o/fixed_ios_html5_touch_and_scroll/

**Comment by ChronoDK** [comment]
> For the reference, a workaround for a related issue was documented here: https://www.reddit.com/r/godot/comments/fabf4o/fixed_ios_html5_touch_and_scroll/

That was me posting there. I don't think this commit will fix iOS Safari touch support. The passive:false option is needed for that. It would be awesome if there was a guide that could teach me how to implement the fix in the engine :-)

**Review by Faless — APPROVED** [review]
Looks good, thanks! :trophy:

**Comment by akien-mga** [comment]
For the reference, I can't reproduce the issue with 3.2-stable which was built with emscripten 1.38.47-upstream, in chromium 79.0.3945.130 on Linux.

I can however reproduce it in a build of the current `3.2` branch with emscripten 1.39.6, and I confirm that this patch fixes it.

BTW, with Firefox Nightly on Linux I can't get touchscreen buttons to work at all, with or without this PR.

**Comment by akien-mga** [comment]
To be on the safe side I checked a local build with this PR and emscripten 1.38.47-upstream and it works fine too.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.1.

**Comment by Faless** [comment]
I think the problem with touchbutton is that we currently don't detect touch fingers release, not sure it's not a regression of some kind, but I think it was never implemented.

**Comment by ChronoDK** [comment]
Just tested 3.2.1 RC2 and touch is working on iOS without any workarounds now. Nice!

**Comment by SamToorchi** [comment]
I tested InputEventScreenDrag on Safari of iOS 14.2, but it never works. Touch Inputs works very fine, but screen drag will never triggered.
