### ISSUE TITLE
Android crash on Release build relating to virtual keyboard

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#36064]
**Godot version:**
Master

**OS/device including version:**
Google pixel
Android 10

**Issue description:**
When running an app that has been exported as release, the app crashes immediately after opening with the following error
```
java.lang.NoSuchMethodError: no non-static method "Lorg/godotengine/godot/GodotIO;.showKeyboard(Ljava/lang/String;)V"
```

Everything works fine when exporting with debug.

Full Logcat output:
[log.txt](https://github.com/godotengine/godot/files/4178006/log.txt)

Looks like it was introduced in https://github.com/godotengine/godot/commit/a3bcdbeb78715fdc30a130935bd21cb44b969ded

cc @MadEqua

**Comment by clayjohn** [comment]
I can't reproduce with a clean build. I must have done something wrong here. Will re-open if I discover the issue.

**Comment by clayjohn** [comment]
Getting this error again. Will update when I figure out the cause...

![wisdom_of_the_ancients](https://user-images.githubusercontent.com/16521339/79787618-20177880-82fc-11ea-8d86-a0c5b04a9923.png)

**Comment by clayjohn** [comment]
The solution is to do a clean build. This is caused by out of date artifacts
