### ISSUE TITLE
Compilation failure with gcc 7

### ISSUE THREAD

**Issue by WilliamTambellini** [godotengine/godot#39311]
**Godot version:**
todays master: ed9a0d0484411e631b0cc927e46dc234054d5ae5

**OS/device including version:**
Centos7

**Issue description:**
compilation error:
[Initial build] Compiling ==> thirdparty/wslay/wslay_net.c
gcc: error: unrecognized command line option '-Wshadow-local'
scons: *** [thirdparty/wslay/wslay_net.x11.tools.64.o] Error 1
scons: building terminated because of errors.

expected: compilation success

**Steps to reproduce:**
Try to compile godot master with gcc 7

**Minimal reproduction project:**
scons -j1 platform=x11 CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7

Seems to build with gcc 8.4.

**Comment by WilliamTambellini** [comment]
https://www.gnu.org/software/gcc/gcc-7/changes.html

**Comment by akien-mga** [comment]
Which gcc 7 version are you using exactly?

**Comment by WilliamTambellini** [comment]
my bad : fresh master from today seems to build with gcc 7.4. tks.
