### PR TITLE
Fix global script class parsing.

### LINKED ISSUE #72226: Extensions of custom classes invalid upon deletion of .godot folder
### Godot version

v4.0.beta16.official

### System information

Windows 7 64-bit

### Issue description

What should happen:
Extensions of custom classes should work with no hassle when a project is imported
What actually happens:
Extensions of custom classes are invalid and must manually be redefined by changing the name and then undoing the change

Why this is an issue:
Sharing a project over git does not include the .godot folder. Something in the folder is what causes these custom class extensions to be registered for your local copy. So without it, these don't apply in the cloned project

### Steps to reproduce

1. First, create a new class. In my example I have created a class called MyClass.
image
2. Then, extend this class.
image
3. (Optional) Extend that class again to demonstrate the error
image

I've put these 3 nodes in a scene, they all work
image
Classes show up in the node creation menu
image

4. Exit the project and delete the .godot folder
image
5. Relaunch the project
Upon relaunching, it'll display this error:
image

The extension of the custom class is also gone from the node creation scene. It's now invalid.
image

6. Change the name of the class then remove the name
image
I added an "H" to the end
image
It's returned!
image
Upon removing the H, the class returns to how it was before.
It's not that big of a hassle for a single script to go and rename the classes over again and then undo it, but for big projects this can get incredibly irritating.
For example, I recently sent my friend a copy of a project over git. It relies on a lot of custom classes, so when he opened it, he was surprised to find them invalid and had to go and manually alter the names of around 10 classes so he could alter the project. 

### Minimal reproduction project

[CustomClassIssue.zip](https://github.com/godotengine/godot/files/10524420/CustomClassIssue.zip)

### PR DESCRIPTION
**Pull request by reduz**
* Broke with #71634
* Restored previous version of the code, made it even more error tolerant.
* Added a warning to **not** change the code.

Fixes #72226.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
The GDScript test suite seems to be failing, though it doesn't say how:
```
===============================================================================
./modules/gdscript/tests/gdscript_test_runner_suite.h:43:
TEST SUITE: [Modules][GDScript]
TEST CASE:  Script compilation and runtime

modules/gdscript/tests/gdscript_test_runner.cpp:190: FATAL ERROR: An error occurred while generating class index.
```

**Comment by dalexeev** [comment]
I need to test this, but I'm pretty sure this PR will break the `@icon` annotation.

File: modules/gdscript/gdscript.cpp [hunk 1]
```diff
@@ -2448,6 +2448,7 @@ bool GDScriptLanguage::handles_global_class_type(const String &p_type) const {
 }
 
 String GDScriptLanguage::get_global_class_name(const String &p_path, String *r_base_type, String *r_icon_path) const {
+	Vector<uint8_t> sourcef;
```
Comment (dalexeev) [inline modules/gdscript/gdscript.cpp:2451]: Is it an unused variable?

**Comment by reduz** [comment]
@dalexeev This restores the code to the previous version. If `@icon` was broken there, it would continue to be broken.

**Comment by akien-mga** [comment]
> The GDScript test suite seems to be failing, though it doesn't say how:
> 
> ```
> ===============================================================================
> ./modules/gdscript/tests/gdscript_test_runner_suite.h:43:
> TEST SUITE: [Modules][GDScript]
> TEST CASE:  Script compilation and runtime
> 
> modules/gdscript/tests/gdscript_test_runner.cpp:190: FATAL ERROR: An error occurred while generating class index.
> ```

The test error shows up further up, I reproduced it locally:
```
ERROR: Class name 'HelloWorld' from /home/akien/Projects/godot/godot.git/modules/gdscript/tests/scripts/parser/errors/class_name_after_annotation.gd is already used in /home/akien/Projects/godot/godot.git/modules/gdscript/tests/scripts/parser/features/class_name.gd
   at: generate_class_index (modules/gdscript/tests/gdscript_test_runner.cpp:331)
```

**Comment by BastiaanOlij** [comment]
From my limited understanding of the loading process, this change makes sense to me. First time parsing a project its likely we can't load a class because we haven't parsed its dependencies yet. This indeed will allow it to grab what it needs and continue.

Out of experience I've run into many situations where the first time you load a project after cloning, even when it fully imported, there are still a lot of broken bits. When I have a class that extends another class that has export properties, the properties will be missing, because when the class was loaded, the class it was dependent on wasn't there yet.

Now I could be completely barking up the wrong tree here, but as it seems that we're simply accepting the error on the script with a missing dependency and recording the script info, we now have an incomplete script loaded in memory, and it is those that are failing. It seems to be what is still missing is a mechanism to try and re-parse the scripts that failed the first time around now that we've loaded all the class data. Possibly we need to go a few rounds of retrying to parse scripts that won't parse because they may fail to parse because another script that initially failed to load, hasn't been parsed yet.

**Comment by dalexeev** [comment]
> If `@icon` was broken there, it would continue to be broken.

`@icon` hasn't been broken before. But after #71634 annotation arguments are resolved in the analyzer. We can make an exception for `@icon` and resolve its argument in the parser. In this case, the `@icon` argument will have to be a string literal, not a constant expression. I think this is an acceptable solution, we can just add a note to the docs.

File: modules/gdscript/gdscript.cpp [hunk 2]
```diff
@@ -2458,30 +2459,99 @@ String GDScriptLanguage::get_global_class_name(const String &p_path, String *r_b
...
+	 * - It must not fail even if the parsing fails, because even if the file is broken,
+	 *   it should attempt its best to retrieve the inheritance metadata.
+	 *
+	 * Before changing this function, please ask the current maintainer of EditorFileSystem.
+	 */
 
 	if (r_icon_path) {
 		if (c->icon_path.is_empty() || c->icon_path.is_absolute_path()) {
-			*r_icon_path = c->icon_path.simplify_path();
+			*r_icon_path = c->icon_path;
```
Comment (dalexeev) [inline modules/gdscript/gdscript.cpp:2483]: This is a minor remark, but I think `simplify_path()` at least does no harm here. :slightly_smiling_face:

**Comment by reduz** [comment]
ok, suggestions incorporated.
@dalexeev Feel free to make a subsequent PR where icon parsing does not rely on the analyzer or expression reduction. Its fine its just a regular string literal.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
