### PR TITLE
Enable zero padding with float specifier for format strings

### LINKED ISSUE #39237: Zero padding of a float is not working in a format string
**Godot version:** 3.2.1

**OS/device including version:** Linux 64b

**Issue description:**

`%07.2f` format string should insert zeroes as a padding, but instead inserts spaces.

**Steps to reproduce:**

```gdscript
print("<%07.2f>" % [0.123])
```

output:

```c
<   0.12>
```

comparison with C:

```c
$ cat 0.c && echo --- && gcc 0.c -o 0 && ./0
#include <stdio.h>

int main() {
	printf("<%07.2f>\n", 0.123);
}

---
<0000.12>
```

### PR DESCRIPTION
**Pull request by mrushyendra**
Godot currently supports zero padding for integers, octals and
hexadecimals when using format strings, but not for floats.

This commit adds support for zero padding for floats, thus ensuring
consistent behavior for all types, and making Godot's format specifiers'
behavior closer to c's `printf()`.

Before:
```
print("<%07.2f>" % -0.2345) #<  -0.23>
print("<%7.2f>" % -0.2345)  #<  -0.23>
```
Now: 
```
print("<%07.2f>" % -0.2345) #<-000.23>
print("<%7.2f>" % -0.2345)  #<  -0.23>
print("<%+07.2f>" % 0.2345) #<+000.23>
```

More examples can be found in the script in the following [project](https://github.com/godotengine/godot/files/4723725/printing.zip), if you wish to test. The code roughly mimics that for the other cases (integer/hexadecimal), with some differences.

Closes #39237

### CODE REVIEW

**Comment by mrushyendra** [comment]
Any idea why it shows the Travis CI build to still be pending, even though clicking on the associated hyperlink shows that the build has passed?

**Comment by aaronfranke** [comment]
@mrushyendra Ignore it, this kind of thing happens often.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

File: core/ustring.cpp [hunk 1]
```diff
@@ -4143,27 +4143,40 @@ String String::sprintf(const Array &values, bool *error) const {
 					}
 
 					double value = values[value_index];
-					String str = String::num(value, min_decimals);
+					bool is_negative = (value < 0);
+					String str = String::num(abs(value), min_decimals);
```
Comment (akien-mga) [inline core/ustring.cpp:4147]: This should likely have been `Math::abs()`.
Somehow CI passed on the `master` branch but the cherry-pick failed on `3.2`:
```
clang++ -o core/ustring.x11.opt.64.llvm.o -c -std=gnu++14 -Wctor-dtor-privacy -Wnon-virtual-dtor -O3 -pipe -fpie -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Werror -DTYPED_METHOD_BIND -DTOUCH_ENABLED -DALSA_ENABLED -DALSAMIDI_ENABLED -DJOYDEV_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DOPENGL_ENABLED -DGLES_ENABLED -DNDEBUG -DPTRCALL_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -DHAVE_MNTENT -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/x11 -I. core/ustring.cpp
core/ustring.cpp:4215:31: error: using integer absolute value function 'abs' when argument is of floating point type [-Werror,-Wabsolute-value]
                                        String str = String::num(abs(value), min_decimals);
                                                                 ^
core/ustring.cpp:4215:31: note: use function 'std::abs' instead
                                        String str = String::num(abs(value), min_decimals);
                                                                 ^~~
                                                                 std::abs
```

Comment (akien-mga) [reply core/ustring.cpp:4147]: Or `ABS()` I guess:
```
core/typedefs.h
91:#define ABS(m_v) (((m_v) < 0) ? (-(m_v)) : (m_v))
```

Comment (akien-mga) [reply core/ustring.cpp:4147]: Fixed up in cbcc0eacd5cd7af661ec99dcdc8e5a69a8a7ca5d (cherrypick: 362193db6a).

**Comment by cgbeutler** [comment]
Looks like the cherry pick tag was removed. Is this still going to be cherry picked to 3.2? I can't quite tell what happened with this.

**Comment by Calinou** [comment]
@cgbeutler The label is removed when the commit is cherry-picked:

> Cherry-picked for 3.2.2.

**Comment by cgbeutler** [comment]
Ok, sorry, does that mean this should be working in 3.2.2? I just tried it in 3.2.3 and it doesn't seem to work. I though maybe all the `abs` talk may have delayed it or something.

**Comment by Calinou** [comment]
> Ok, sorry, does that mean this should be working in 3.2.2? I just tried it in 3.2.3 and it doesn't seem to work. I though maybe all the `abs` talk may have delayed it or something.

I can't see the commit being reverted in the `3.2` branch history: https://github.com/godotengine/godot/commits/3.2/core/ustring.cpp

Can you open a new issue with a minimal reproduction project attached?

**Comment by mrushyendra** [comment]
Hmm, I just tried it with the latest 3.2 commit `74512f` and it seems to work.

**Comment by cgbeutler** [comment]
Oh... apparently I was just confused on how this worked and didn't read close enough. I thought the number before the decimal would only affect the length on that side. In other words, I was trying to do:
`print("%02.02f" % 2.2)`
instead of:
`print("%04.2f" % 2.2)`
My bad. It all makes sense now.
