### PR TITLE
Add conversion for uniform_name property in visual shader

### LINKED ISSUE #65388: Visual shader broken after uniform->parameter rename
### Godot version

4b164b8e4790cfeb597b763123560b59a96458e5

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

Opening a visual shader in the latest version performs several destructive actions:

* `FloatUniform` nodes are deleted
* All `uniform_name` fields are lost and not converted to `parameter_name`
* Several variables are deleted without replacement (even those who still have nodes), which breaks shader compilation
  ```
  res://src/material/worlds/environment/shader.tres:102 - Unknown identifier in expression: 'TextureUniformTriplanar3'.
    Shader compilation failed.
  ```

Sample shader: https://gist.github.com/jgillich/46fb0753b9f01abb691516f12004ac6a

This diff is produced by opening the shader in the latest version and saving: https://gist.github.com/jgillich/34d843da4d11ed2821204b87d642cacb

Pretty sure this is caused by #64952 @Chaosus.

### Steps to reproduce

Open a visual shader with `TextureUniformTriplanar` and `FloatUniform` nodes in the latest version

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Chaosus**
With https://github.com/godotengine/godot/pull/65455 closes https://github.com/godotengine/godot/issues/65388

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
