### ISSUE TITLE
Can't build template with 3D disabled

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#89550]
### Tested versions

- v3.6.beta.custom_build [1b5fa74e3]
- Godot 3.6 beta 4

### System information

Ubuntu 22.04.4 LTS, GTX1060 6gb,  535.161.07

### Issue description

can't build 3D disabled templates after #85437

error

```console
scons: Reading SConscript files ...
Warning: Speech Dispatcher development libraries not found. Disabling Text-to-Speech support.
collect2 version 11.4.0
/usr/bin/ld -plugin /usr/lib/gcc/x86_64-linux-gnu/11/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper -plugin-opt=-fresolution=/tmp/cc779rto.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/11/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/11 -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/11/../../.. --version -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/11/crtend.o /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crtn.o
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 95%] Linking Program        ==> bin/godot.x11.opt.64
[ 99%] progress_finish(["progress_finish"], [])
[100%] /usr/bin/ld: scene/libscene.x11.opt.64.a(world.x11.opt.64.o): in function `World::notify_saving(bool)':
world.cpp:(.text+0x161): undefined reference to `LODManager::notify_saving(bool)'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.opt.64] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:05.526]
```

bisect
```console
git bisect start
# bad: [bbd9578d181f745f7884be32bece6090fd7df4e4] Merge pull request #89345 from bruvzg/3x_no_li
git bisect bad bbd9578d181f745f7884be32bece6090fd7df4e4
# good: [584dc09ff8af8373289f1a35cad413e7432262c7] Merge pull request #87359 from bruvzg/ios_xc1520_3
git bisect good 584dc09ff8af8373289f1a35cad413e7432262c7
# good: [273d5897a0a0a2ca30c06951c37c100401c52604] Merge pull request #85229 from ztc0611/3.x-ios-add-pause-resume-notifs
git bisect good 273d5897a0a0a2ca30c06951c37c100401c52604
# good: [354404db6067997c1db358ba9c50668e93415b07] Merge pull request #76023 from Ansraer/3.x_orm
git bisect good 354404db6067997c1db358ba9c50668e93415b07
# good: [04670d05cce6fbd5d39ce185646b7f58d206d36f] Merge pull request #87689 from BZ1234567890/issue-87059-b3x
git bisect good 04670d05cce6fbd5d39ce185646b7f58d206d36f
# good: [6c35b4898615c9fdd6f0b18184af9c6669fccf19] Merge pull request #88305 from Ovnuniarchos/editor_properties_fixup
git bisect good 6c35b4898615c9fdd6f0b18184af9c6669fccf19
# bad: [ae7dfd1f130f7a2623072af16879e34057ed73d7] Merge pull request #85437 from lawnjelly/lod_scene_side
git bisect bad ae7dfd1f130f7a2623072af16879e34057ed73d7
# bad: [1b5fa74e396bf2c9cf927608b4c8acef2bb2b97a] Discrete Level of Detail
git bisect bad 1b5fa74e396bf2c9cf927608b4c8acef2bb2b97a
# first bad commit: [1b5fa74e396bf2c9cf927608b4c8acef2bb2b97a] Discrete Level of Detail
```

### Steps to reproduce

1. make sure you're at latest **3.x**
2. build template from terminal with following:
```console
 scons platform=x11 target=release_debug tools=no disable_3d=yes -j4
```

### Minimal reproduction project (MRP)

n/a

**Comment by AThousandShips** [comment]
I believe I can fix this, will test in a bit

**Comment by lawnjelly** [comment]
Fixed by #89565.
