### PR TITLE
Restore numeric from String constructors

### LINKED ISSUE #44407: GDScript No constructor of "int" matches the signature "int(String)"
**Godot version:**

4.0.dev a511a26ad8

**OS/device including version:**

Windows 10

**Issue description:**

```gdscript
var text: String = "12345"
var number: int = int(text)
```
This gives an error "Parser Error: No constructor of "int" matches the signature "int(String)".
Per the [documentation](https://docs.godotengine.org/en/latest/classes/class_int.html#class-int-method-int), this constructor should exist. I know of no other way in GDScript to parse a string without writing the implementation myself, so I'm not sure how to work around this.

**Steps to reproduce:**
See above

**Minimal reproduction project:**

### LINKED ISSUE #67494: GdScript 2.0: String as int casting is broken
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I want to simply cast a numeric string into a int by using the casting operator `as`

var value := "14" as int

results in 
`Invalid cast: could not convert value to 'int'.`

### Steps to reproduce

`var value := "14" as int`

### Workaround
use ` "14".to_int()` instead

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
- Closes #44407
- Closes #67494

### CODE REVIEW

**Comment by akien-mga** [comment]
Lots of CI build errors along those lines:
```
core/variant/variant_construct.h: In static member function 'static void VariantConstructorFromString<T>::ptr_construct(void*, const void**) [with T = long int]':
core/variant/variant_construct.h:258:11: error: 'dst_var' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  258 |   Variant type_test = Variant(dst_var);
      |           ^~~~~~~~~
core/variant/variant_construct.h: In static member function 'static void VariantConstructorFromString<T>::ptr_construct(void*, const void**) [with T = double]':
core/variant/variant_construct.h:258:11: error: 'dst_var' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  258 |   Variant type_test = Variant(dst_var);
      |           ^~~~~~~~~
```

**Comment by cdemirer** [comment]
I guess `GetTypeInfo<T>::VARIANT_TYPE` can be used instead of dummy Variants.

**Comment by reduz** [comment]
I am not happy with this kind of automatic cast, as it an be quite prone to errors. We discussed with @vnen and believed it would be better you use the str() function instead in GDScript.

**Comment by KoBeWi** [comment]
But the PR is about `int("string")`. It no longer works in 4.0.
I don't know how it works internally; if it causes implicit conversions then I agree it's bad :/

**Comment by KoBeWi** [comment]
I checked and this
```GDScript
var a: int
a = "123"
```
does not work, so I guess it's fine? 🤔

**Comment by Mickeon** [comment]
To me this looks completely fine. Reduz may have gotten confused. I tried myself, and no implicit conversion is done.

**Review by akien-mga — APPROVED** [review]
Tested it locally and it seems fine. I did not see cases where implicit conversion would happen unwittingly.

Some tests:
```gdscript
var a1 = "42"
assert(a1 is String)
#var a2 : int = "42"  # Value of type "String" cannot be assigned to a variable of type "int"
var a3 : int = "42" as int
assert(a3 is int)
var a4 := "42"
assert(a4 is String)
var a5 := "42" as int
assert(a5 is int)
#a5 + a4  # Invalid operands "int" and "String" for "+" operator
var a6 = int("42")
assert(a6 is int)
```
```gdscript
var a1 = "42.5"
assert(a1 is String)
#var a2 : float = "42.5"  # Value of type "String" cannot be assigned to a variable of type "float"
var a3 : float = "42.5" as float
assert(a3 is float)
var a4 := "42.5"
assert(a4 is String)
var a5 := "42.5" as float
assert(a5 is float)
#a5 + a4  # Invalid operands "float" and "String" for "+" operator
var a6 = float("42.5")
assert(a6 is float)
```

**Comment by akien-mga** [comment]
Thanks!
