### PR TITLE
Fix scoped enum value reference, breaks GCC 5

### LINKED ISSUE #30044: Error building from master caused by namespace issue
**Godot version:**
Master

**OS/device including version:**
Ubuntu 16.04
gcc version 5.5.0

**Issue description:**
Building from master with ``scons p=x11 target=release_debug -j4"

Error produced is:
```
editor/editor_layouts_dialog.cpp: In constructor 'EditorLayoutsDialog::EditorLayoutsDialog()':
editor/editor_layouts_dialog.cpp:123:42: error: 'ItemList::SelectMode' is not a class or namespace
  layout_names->set_select_mode(ItemList::SelectMode::SELECT_MULTI);
```

Introduced by https://github.com/godotengine/godot/commit/9986cf70058011fed81c8a2bba4df47e3e58b3ba

Appears to be same use of namespaces as https://github.com/godotengine/godot/issues/28634

I looked online and it appears it is a weird thing that is best supported on windows and only on certain versions of GCC

### PR DESCRIPTION
**Pull request by akien-mga**
Introduced in #29376 and recent compilers are fine with it, but GCC 5
complains.

Fixes #30044.

CC @clayjohn

### CODE REVIEW

**Comment by clayjohn** [comment]
Can confirm, it works for me!

**Comment by akien-mga** [comment]
> I should probably also just upgrade to a newer version of Ubuntu and GCC and everything...

Well it's nice to be able to make sure it still builds fine on older distros :)

Next time you run into this issue, you'll know you just have to remove the enum name from the statement, to use `Class::EnumValue` directly.
