### PR TITLE
Fix SDL threading on macOS/Linux.

### PR DESCRIPTION
**Pull request by bruvzg**
These files are used only on Windows and seems to cause infinite loop on macOS.

*Bugsquad edit:*
- Fixup to bugs introduced in #106218 at the last minute.

### CODE REVIEW

File: drivers/sdl/SCsub [hunk 1]
```diff
@@ -90,9 +90,6 @@ if env["builtin_sdl"]:
         "stdlib/SDL_string.c",
         "stdlib/SDL_strtokr.c",
         "thread/SDL_thread.c",
-        "thread/generic/SDL_syscond.c",
-        "thread/generic/SDL_sysrwlock.c",
-        "thread/generic/SDL_systhread.c",
```
Comment (akien-mga) [inline drivers/sdl/SCsub:95]: This was likely the main issue, it seems like I saw it included in the Windows driver:
```
thirdparty/sdl/thread/windows/SDL_systhread.c
29:#include "SDL_systhread_c.h"
```
But I failed to realize this is `thread/windows/SDL_systhread_c.h` and not `thread/generic/SDL_systhread.c`.

It's super confusing that they have files with the same names in different folders (so they seem mutually exclusive) but then the Windows one depends on a couple `thread/generic` files anyway...

**Comment by akien-mga** [comment]
I also fixed the SDL update script to take this into account and document it better, and add the pkgconfig Linux fixup for https://github.com/godotengine/godot/pull/106218#discussion_r2165926735.

**Comment by akien-mga** [comment]
lol what a mess:
```
Error: thirdparty/sdl/thread/pthread/../generic/SDL_syssem.c:25:10: fatal error: 'SDL_systhread_c.h' file not found
#include "SDL_systhread_c.h"
scons: building terminated because of errors.
         ^~~~~~~~~~~~~~~~~~~
```

So we shouldn't build `thread/generic/SDL_systhread.c` as that breaks everything, but `thread/generic/SDL_systhread_c.h` is needed for `thread/generic/SDL_syssem.c` which is included automatically for macOS.

And same issue for the Windows part:
```
Error: thirdparty\sdl\thread\generic\SDL_sysrwlock.c(25): fatal error C1083: Cannot open include file: 'SDL_systhread_c.h': No such file or directory
scons: *** [thirdparty\sdl\thread\generic\SDL_sysrwlock.windows.editor.x86_64.obj] Error 2
```

So I guess I'll add back the header but without the corresponding C file to avoid the risk of compiling it... this could definitely be improved somewhat upstream to be more self-contained.

**Review by akien-mga — APPROVED** [review]
Seems to work fine on Linux, tested with an Xbox Series controller on bluetooth.

**Comment by akien-mga** [comment]
Thanks!
