### PR TITLE
new ColorPicker

### PR DESCRIPTION
**Pull request by MarianoGnu**
These are the features i'm willing to implement. I'm open to suggestions of course.
- [x] Add a visual editor
- [x] Allow to use shaders in default theme.
- [x] Add presets buttons
- [x] Implement screen color picking

### CODE REVIEW

**Comment by reduz** [comment]
this looks very good, my only doubt about it is more related to Godot
design than you code.
It would be desirable to put the shader you use in a shared location for
all color pickers..

Do you think you could modify Theme class to also have shaders? so you can
put your shader in the default_theme.cpp code and share it..

**Comment by MarianoGnu** [comment]
That's interesting! but not related to this PR directly, maybe i can move it latter, in another PR

**Comment by reduz** [comment]
well, i have no idea how many colorpickers are around, but have each create
a shader feels kind of inefficient to me. I would probably prefer to
implement that first in order to merge the colorpicker

**Comment by MarianoGnu** [comment]
Ah, now i get it, i didn't realize the shader was not being shared. we have two options, add shaders to theme or have an static reference (i think Godot doesn't like this thought)

**Comment by MarianoGnu** [comment]
btw @akien-mga color picker and button are topic::core because it can be used in games :)

**Comment by reduz** [comment]
Just add shaders to theme, that should be way simpler

**Comment by akien-mga** [comment]
> btw @akien-mga color picker and button are topic::core because it can be used in games :)

Thanks, fixed :)

**Comment by reduz** [comment]
how's the colorpicker @MarianoGnu ? Did you have time to work on it and make the shaders unique through the Theme class?

**Comment by MarianoGnu** [comment]
@reduz this is ready for merge.

**Comment by akien-mga** [comment]
@MarianoGnu Could you try to run a ```git rebase -i HEAD~7``` and merge the commits 0c2e339 and 88ba8cc in their parent commit? As they are meant to fix issues introduced in the commit just before them, we don't really need to keep them separate when merging in the main repo, we're mostly interested in the working code :)

After running the ```git rebase -i HEAD~7``` command, you should see this in an editor:

> pick f143dca Add a visual editor to color picker.
pick f6abc99 Move shaders to default theme and add shader_override related methods to Control class
pick 00dff39 Add presets. Also fix some bugs.
pick 1849a5e Fix a crash and a minor bug
pick e12844b add screen color picking
pick 2219ead Fix crash
pick aa2845c Add guide lines to visual editor.

Change it to:

> pick f143dca Add a visual editor to color picker.
pick f6abc99 Move shaders to default theme and add shader_override related methods to Control class
pick 00dff39 Add presets. Also fix some bugs.
fixup 1849a5e Fix a crash and a minor bug
pick e12844b add screen color picking
fixup 2219ead Fix crash
pick aa2845c Add guide lines to visual editor.

and it should merge the aforementioned commits into their parent commit.

**Comment by MarianoGnu** [comment]
@akien-mga does this looks better?

**Comment by akien-mga** [comment]
Awesome. :)

**Comment by MarianoGnu** [comment]
Somethimng missing to merge this?

**Comment by akien-mga** [comment]
> Somethimng missing to merge this?

Only testing :) I'm too lazy to review the code thoroughly so I plan to test it live this evening instead.

**Comment by akien-mga** [comment]
It doesn't build on x11 with gcc 4.9.2:
```
scene/gui/color_picker.cpp: In member function 'void ColorPicker::_screen_input(const InputEvent&)':
scene/gui/color_picker.cpp:329:37: error: invalid initialization of non-const reference of type 'Image&' from an rvalue of type 'Image'
   Image &img =r->get_screen_capture();
                                     ^
```

**Comment by reduz** [comment]
ah yes, just use Image without the reference, the DVector class inside
Image will do copy on write, so this is not slow

**Comment by MarianoGnu** [comment]
I'll fix it asap

**Comment by MarianoGnu** [comment]
@akien-mga try again

**Comment by akien-mga** [comment]
It builds fine and it's working great! :D

**Comment by reduz** [comment]
Fantastic!
