### ISSUE TITLE
[MSVC] When building Godot emits error C2440 on MSVC 

### ISSUE THREAD

**Issue by Apriltanq** [godotengine/godot#58703]
### Godot version

86d4c54

### System information

Windows 10, Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz 2.59 GHz

### Issue description

Hi, all
Due to update RWC Sha task recently, Godot fails to build on MSVC build main_20220223.01 due to error C2440. Could you help look?

### Steps to reproduce

1. open VS2019 x86 tools command
2. git clone https://github.com/godotengine/godot F:\gitP\godotengine\godot
3. git -C "F:\gitP\godotengine\godot" remote prune origin
4. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=x86 -arch=x86
5. cd F:\gitP\godotengine\godot
6. scons tools=no target=release verbose=yes 2>&1

**Build.log:**
[Godot build.txt](https://github.com/godotengine/godot/files/8167311/Godot.build.txt)

**Error info:**
modules\openxr\extensions\openxr_vulkan_extension.cpp(308): error C2440: '=': cannot convert from 'nullptr' to 'VkImage'

**Comment by akien-mga** [comment]
This was already fixed 4 days ago: https://github.com/godotengine/godot/pull/58589

**Comment by Apriltanq** [comment]
> This was already fixed 4 days ago: #58589

Got it, thanks.
