### ISSUE TITLE
Compiling without GDScript fails again

### ISSUE THREAD

**Issue by DmitriySalnikov** [godotengine/godot#41710]
**Godot version:**
3.2 d773de6d244116c3ad26f0506a10038cc11019ff
(I didn't check this on the master branch)

**OS/device including version:**
Windows

**Issue description:**
Build without GDScript failed with tools=yes

**Steps to reproduce:**
```scons p=windows tools=yes gdscript=no module_gdscript_enabled=no```

[log_tools.txt](https://github.com/godotengine/godot/files/5163219/log_tools.txt)

**Comment by Xrayez** [comment]
Basically this according to the log:

```
[ 96%] Linking Static Library ==> modules\freetype\freetype_builtin.windows.tools.64.lib
[ 96%] Linking Program        ==> bin\godot.windows.tools.64.exe
   Creating library bin\godot.windows.tools.64.lib and object bin\godot.windows.tools.64.exp
editor.windows.tools.64.lib(plugin_config_dialog.windows.tools.64.obj) : error LNK2019: unresolved external symbol "public: __cdecl GDScript::GDScript(void)" (??0GDScript@@QEAA@XZ) referenced in function "private: void __cdecl PluginConfigDialog::_on_confirmed(void)" (?_on_confirmed@PluginConfigDialog@@AEAAXXZ)
editor.windows.tools.64.lib(plugin_config_dialog.windows.tools.64.obj) : error LNK2001: unresolved external symbol "private: static class GDScriptLanguage * GDScriptLanguage::singleton" (?singleton@GDScriptLanguage@@0PEAV1@EA)
bin\godot.windows.tools.64.exe : fatal error LNK1120: 2 unresolved externals
scons: *** [bin\godot.windows.tools.64.exe] Error 1120
scons: building terminated because of errors.
```

By the way, further regressions like this could be handled by #41091 and including that in CI.

**Comment by akien-mga** [comment]
Fixed by #41869.
