### PR TITLE
Fix `sprite_frames_editor_plugin` compilation with `deprecated=no`

### PR DESCRIPTION
**Pull request by LanzaSchneider**
Fixes compilation error in `sprite_frames_editor_plugin.cpp` when building with `deprecated=no`.

### Issue
When compiling Godot with `deprecated=no`, the following deprecated methods are disabled:
- `format_number()`
- `parse_number()`  
- `percent_sign()`

This caused compilation errors in `sprite_frames_editor_plugin.cpp` which was still using these deprecated APIs.
屏幕截图_20251204_034809

### Solution
Updated `sprite_frames_editor_plugin.cpp` to use the new non-deprecated localization APIs:
- Replaced `TS->format_number()` with new equivalent
- Replaced `TS->percent_sign()` with new equivalent

### CODE REVIEW

**Review by kleonc — APPROVED** [review]
That's a regression from #111471, I should have caught that. Thanks for quick spotting and fixing!

The code looks equivalent.
https://github.com/godotengine/godot/blob/8105ff7ac735f83be221296a6bb9b22caa7d9253/servers/text/text_server.cpp#L2121-L2136

**Comment by Repiteo** [comment]
Thanks!
