### ISSUE TITLE
Linking Errors - undefined references to drmGetDevices on Ubuntu

### ISSUE THREAD

**Issue by winstonliu** [godotengine/godot#16000]
**Godot version:**

Latest master `59e83af201af5a93c7a13750d781c050c2275c07`

**OS/device including version:**

Ubuntu 16.04
Radeon RX 480
Using GCC 5.4.0

**Issue description:**

Running: `scons p=x11 tools=yes target=release_debug`
Linking fails on Linux with:

```
Linking Program        ==> bin/godot.x11.opt.tools.64
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libGL.so: undefined reference to `drmGetDevices2'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libGL.so: undefined reference to `drmGetDevice2'
```

I also experience #15345 when I tried with `use_lto=yes`.

**Steps to reproduce:**
Compile Godot from source.

**Comment by akien-mga** [comment]
We don't use libdrm directly, so this looks like an issue with your system's libGL.so.

**Comment by winstonliu** [comment]
You're right. Issue was fixed after installing the latest `amdgpu-pro` package according to these instructions http://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Install.aspx .

For anyone with similar issues, note that the latest AMD GPU packages (17.40+) only work with the 16.04-hwe kernel releases.
