### ISSUE TITLE
Web export: GLES3 scene forward fragment shader fails to compile on WebGL 2.0 (ANGLE)

### ISSUE THREAD

**Issue by shiena** [godotengine/godot#118684]
### Tested versions

- Reproducible in: 4.7.dev [a8643700ce8affae9fed0d2688b9f7867f5b7d4e]

### System information

Godot v4.7.dev (a8643700c) - Windows 11 (build 26200) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 5070 (NVIDIA; 32.0.15.9602) - AMD Ryzen 9 9900X 12-Core Processor (24 threads) - 61.66 GiB memory

### Issue description

GLES3 scene forward fragment shader compilation fails when running web export in Chrome with WebGL 2.0 backend.
 The error occurs due to mixed int/float type operations that desktop OpenGL drivers accept through implicit
conversion, but WebGL 2.0 (ANGLE) strictly rejects according to GLSL ES 3.00 specification.

<img width="638" height="236" alt="Image" src="https://github.com/user-attachments/assets/f40b0594-2931-4ee1-a2e1-012a685d3037" />

### Steps to reproduce

1. Create any Godot 4.7 project with Compatibility renderer (uses WebGL 2.0 by default)
2. Export to Web with default settings
3. Run in Chrome browser (uses ANGLE for WebGL)
4. Open Developer Tools console to see the shader compilation errors
5. The browser may display a black/broken screen due to failed shader compilation

### Minimal reproduction project (MRP)

- [mcp-shader-error.zip](https://github.com/user-attachments/files/26828361/mcp-shader-error.zip)
- https://shiena.github.io/mcp-shader-error/

**Comment by akien-mga** [comment]
For context, based on the location of the errors fixed by #118695, this was a regression from #108219.
This was also reported by @Alex2782 in https://github.com/godotengine/godot/issues/118586#issuecomment-4254274142.

FYI @CookieBadger

**Comment by Alex2782** [comment]
> This was also reported by [@Alex2782](https://github.com/Alex2782) in [#118586 (comment)](https://github.com/godotengine/godot/issues/118586#issuecomment-4254274142).

I don't know exactly how to reproduce this. I think it always happens when I compile a new version. Disabling the shader cache wasn't enough.
