### PR TITLE
remove usage of C#7 in DebuggingUtils.cs for compatibility with 2015 Build Tools

### LINKED ISSUE #15742: DebuggingUtils syntax error for new projects
**Godot version:**
Godot_v3.0-rc1_mono_win64

**OS/device including version:**
Windows XP

**Issue description:**
Build fails if my project includes a c# script.

**Steps to reproduce:**
I have Mono ~~4.5.0~~ 5.4.0 and Microsoft Build Tools 2015 installed (these were working with 3.0 beta 2)

I have deleted my `C:\Users\<username>\AppData\Roaming\Godot` directory.

If I create a new project and attached a new c# script to a node then when I build I receive three errors:

    Core\DebuggingUtils.cs(37,42): error CS1026: ) expected 
    Core\DebuggingUtils.cs(37,52): error CS1002: ; expected 
    Core\DebuggingUtils.cs(37,52): error CS1513: } expected 

My `C:\Users\<username>\AppData\Roaming\Godot\mono\solutions\GodotSharp_-<somenumber>\Core\DebuggingUtils.cs` contains the following lines:

    // Lines 37-38
    if (methodBase is MethodInfo methodInfo)
        sb.AppendTypeName(methodInfo.ReturnType);

If I modify them to this then no further errors occur:

    // Lines 37-38
    if (methodBase is MethodInfo)
        sb.AppendTypeName(((MethodInfo)methodBase).ReturnType);

**Minimal reproduction project:**
Attached zip contains example project and copy of my `C:\Users\<username>\AppData\Roaming\Godot\mono` directory

[DebuggingUtils_test_files.zip](https://github.com/godotengine/godot/files/1631642/DebuggingUtils_test_files.zip)

### PR DESCRIPTION
**Pull request by KellyThomas**
*Bugsquad edit:* Fixes #15742

### CODE REVIEW

**Comment by akien-mga** [comment]
I imagine that some people will freak out reading the changelog :P

**Comment by mysticfall** [comment]
I was freaked out after seeing this pop up on Discord's `#github` channel, so here I am.
...relieved to see what it actually was 😅

**Review by neikeq — APPROVED** [review]
