### PR TITLE
[2.1] Build fixes for modern toolchains

### LINKED ISSUE #101035: Godot 2.1 - Engine compilation errors on macOS 15/Xcode 16
### Tested versions

- Reproducible in 2.1.7.rc.custom_build [0919ee6], 2.1.7.rc.custom_build [7cef81b]

### System information

macOS 15/Xcode 16 - Mac Mini (Intel i7), MacBook Air (M1)

### Issue description

When compiling Godot 2.1 using macOS 15/Xcode 16, the 'Byte' type is not found by FreeType 1.8.1's included gzip.

The issue is not present on macOS 12/Xcode 14.

```
In file included from thirdparty/freetype/src/gzip/ftgzip.c:77:
In file included from thirdparty/freetype/src/gzip/zlib.h:34:
thirdparty/freetype/src/gzip/ftzconf.h:228:12: error: unknown type name 'Byte'
  228 |    typedef Byte  FAR Bytef;
      |            ^
In file included from thirdparty/freetype/src/gzip/ftgzip.c:95:
thirdparty/freetype/src/gzip/inftrees.h:22:7: error: unknown type name 'Byte'
   22 |       Byte Exop;        /* number of extra bits or operation */
      |       ^
thirdparty/freetype/src/gzip/inftrees.h:23:7: error: unknown type name 'Byte'
   23 |       Byte Bits;        /* number of bits in this code or subcode */
      |       ^
In file included from thirdparty/freetype/src/gzip/ftgzip.c:103:
thirdparty/freetype/src/gzip/inftrees.c:247:21: error: use of undeclared identifier 'Byte'
  247 |           r.bits = (Byte)l;     /* bits to dump before this table */
      |                     ^
thirdparty/freetype/src/gzip/inftrees.c:248:21: error: use of undeclared identifier 'Byte'
  248 |           r.exop = (Byte)j;     /* bits in this table */
      |                     ^
thirdparty/freetype/src/gzip/inftrees.c:258:17: error: use of undeclared identifier 'Byte'
  258 |       r.bits = (Byte)(k - w);
      |                 ^
thirdparty/freetype/src/gzip/inftrees.c:263:19: error: use of undeclared identifier 'Byte'
  263 |         r.exop = (Byte)(*p < 256 ? 0 : 32 + 64);     /* 256 is end-of-block */
      |                   ^
thirdparty/freetype/src/gzip/inftrees.c:268:19: error: use of undeclared identifier 'Byte'
  268 |         r.exop = (Byte)(e[*p - s] + 16 + 64);/* non-simple--look up in lists */
      |                   ^
In file included from thirdparty/freetype/src/gzip/ftgzip.c:105:
thirdparty/freetype/src/gzip/infcodes.c:50:3: error: unknown type name 'Byte'
   50 |   Byte lbits;           /* ltree bits decoded per branch */
      |   ^
thirdparty/freetype/src/gzip/infcodes.c:51:3: error: unknown type name 'Byte'
   51 |   Byte dbits;           /* dtree bits decoder per branch */
      |   ^
thirdparty/freetype/src/gzip/infcodes.c:70:17: error: use of undeclared identifier 'Byte'
   70 |     c->lbits = (Byte)bl;
      |                 ^
thirdparty/freetype/src/gzip/infcodes.c:71:17: error: use of undeclared identifier 'Byte'
   71 |     c->dbits = (Byte)bd;
      |                 ^
thirdparty/freetype/src/gzip/infcodes.c:204:9: error: use of undeclared identifier 'Byte'
  204 |         OUTBYTE(*f++)
      |         ^
thirdparty/freetype/src/gzip/infutil.h:83:27: note: expanded from macro 'OUTBYTE'
   83 | #define OUTBYTE(a) {*q++=(Byte)(a);m--;}
      |                           ^
In file included from thirdparty/freetype/src/gzip/ftgzip.c:105:
thirdparty/freetype/src/gzip/infcodes.c:213:7: error: use of undeclared identifier 'Byte'
  213 |       OUTBYTE(c->sub.lit)
      |       ^
thirdparty/freetype/src/gzip/infutil.h:83:27: note: expanded from macro 'OUTBYTE'
   83 | #define OUTBYTE(a) {*q++=(Byte)(a);m--;}
      |                           ^
14 errors generated.
scons: *** [thirdparty/freetype/src/gzip/ftgzip.osx.opt.tools.64.o] Error 1
```

### Steps to reproduce

Compile the Godot Engine (2.1.x) on macOS 15/Xcode 16.

```
scons platform=osx tools=yes target=release_debug
```

### Minimal reproduction project (MRP)

Godot 2.1.x source: https://github.com/godotengine/godot/tree/2.1

### PR DESCRIPTION
**Pull request by akien-mga**
The `2.1` branch is no longer maintained, but it's still relevant to keep it buildable if we can, for game preservation, or some use cases like support for older platforms like OUYA or homebrew consoles.

I don't intend to spend a lot of effort on this, but if I can make sure the code is still compatible with recent Python 3, SCons 4, and modern compilers, that's worth a try.

- Android: Fix compatibility with Python 3.13 which removed `distutils`. Not tested, maybe you can check it @bherdm since you need it for OUYA?
- OSX (by @bherdm): Fix compatibility with Xcode 16 (possibly earlier versions, I haven't checked details on when that error started).
  * Fixes #101035.
- C++ standards: Set explicitly the standards we used to target implicitly with GCC 5 back then, i.e. C++98 and C11. For MSVC we can't set anything earlier than C++14 - old VS 2015 and 2017 we used back then should default to something old enough (C++11?). Not sure about VS 2019 and later, and if those are supported at all currently.
- Linux/Windows GCC 6/7 compat: GCC > 5 used to be blocked due to #4623 and related bugs, which were fixed in 3.0 by changing `Object::cast_to` to a static method. From testing various versions, I found that GCC 6/7 do reproduce the bug in `target=release tools=no` (release templates), but not GCC 8, GCC 9, or GCC 14. So presumably whatever optimization caused the crash in GCC 6/7 has been fixed. This is still not Safe™, but It Works™, maybe? I don't really want to spend more time on this nor change the behavior of the codebase. @hpvb has some ideas on how to trick GCC into not doing the problematic optimization though.
- speex: GCC 14 was rightfully complaining about that one. The code seems a bit buggy, and it's still the same in latest upstream but speex is a dead project. I chose to just enforce what would happen implicitly before.
- SCons: Fix some Python scripts missing `close()` on file writes, which broke `AndroidManifest.xml` generation with Python 3.13.1 for me.
- libmpcdec: Fix build issue for templates with MSVC due to overriding `log2` with a macro.
- Web: Fix HTML5 gamepad handling on modern browsers (backports #21588 and #25149).

---

Toolchains tested per target, for release templates (prior to blocking GCC 6/7 again, so I could test them). Tested with the `gui/drag_and_drop` official demo from the `2.1` branch, just running it would crash with a `-O3` optimized release template built with GCC 6.

- Linux
  * Fedora 43, Python 3.14.0, SCons 4.10.0: Both GCC 15.2.1 and Clang 21.1.5
  * Fedora 41, Python 3.13.1, SCons 4.8.1: Both GCC 14.2.1 and Clang 19.1.5
  * Ubuntu 16.04, Python 2.7.12, SCons 2.4.1: GCC 6.5.0 (crash), 7.5.0 (crash), 8.4.0 (works), 9.4.0 (works)
  * Ubuntu 16.10, Python 2.7.12, SCons 2.5.0: GCC 6.2.0 and 6.1.1 (installed manually) (both crash)
- Server
  * Ubuntu 16.04, Python 2.7.12, SCons 2.4.1: GCC 6.5.0 (works - not using `-O3`)
- Windows
  * Ubuntu 16.04, Python 2.7.12, SCons 2.4.1: MinGW GCC 5.4.0 (works)
  * Ubuntu 16.10, Python 2.7.12, SCons 2.5.0: MinGW GCC 6.2.0 (crash)
- macOS
  * macOS 15.2, Xcode 16.2: Works fine (tested by @bruvzg in https://github.com/godotengine/godot/pull/101040#pullrequestreview-2528659198)
  * Fedora 41, Python 3.13.0, SCons 4.8.1: osxcross with Xcode 16.2 SDK, Apple Clang 17.0.6 (both editor and release templates build fine with explicit `osxcross_sdk=darwin24.2`, didn't test binaries)
- Android
  * Fedora 41, Python 3.13.1, SCons 4.8.1: NDK r17c 17.2.4988734, Temurin JDK 8 (builds fine, didn't test apk)
- iOS
  * Fedora 41, Python 3.13.0, SCons 4.8.1: osxcross with Xcode 16.2 SDK, Apple Clang 17.0.6 (builds fine with explicit `IPHONESDK="/root/ioscross/arm64/SDK/iPhoneOS18.2.sdk/" IPHONEPATH="/root/ioscross/arm64/" SDKVERSION=18.2 ios_triple="arm-apple-darwin11-"`, didn't test binaries)
- Web
  * Fedora 41, Python 3.13.1, SCons 4.8.1: Emscripten 1.38.34 to Emscripten 1.39.1-fastcomp tested, builds successfully, doesn't run in modern browsers anymore
- BB10, Haiku, WinRT: Out of scope, not supported

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
macOS version builds (using Xcode 16.2) and runs (on macOS 15.2).
Without any visible issues apart from few `ERROR: free_static: Condition ' !MemoryPoolStatic::get_singleton() ' is true.` errors on exit.

**Comment by akien-mga** [comment]
Following up on @bherdm's comment in https://github.com/godotengine/godot/pull/101036#issuecomment-2568642125

> Building the engine is working fine on macOS, but it seems to have broken building the Android export template. Here's the error I'm getting:
> 
> ```
> scons: Reading SConscript files ...
> Using custom revision: OUYA
> Godot Android!!!!! (armv7) (with neon)
> Using NDK unified headers
> NameError: global name 'LooseVersion' is not defined:
>   File "/Users/bherdm/GitHub/godot/SConstruct", line 296:
>     detect.configure(env)
>   File "./platform/android/detect.py", line 259:
>     if ndk_version != None and LooseVersion(ndk_version) >= LooseVersion("15.0.4075724"):
> ```
> 
> I have been using NDK 17.2.4988734.

Indeed I had missed some `LooseVersion`s in the Android fix, should now be fixed in 64a9c5ac.

> Also, and maybe interestingly, this did break building the engine using Windows VS2015 x64 Native, but it's still working in x64 2022 and VS2015 x64 x86 Cross Tools.

What error are you getting?

**Comment by akien-mga** [comment]
Added another fix for a Python 3 issue when writing to text files, which would prevent me from building the Android APK as the AndroidManifest.xml was 0 bytes. With this fix I can generate an APK fine using NDK r17c and Temurin OpenJDK 8.

**Comment by akien-mga** [comment]
Did some testing for the Web platform too, it took me a while to find a version of Emscripten that works.

It seems like the `2.1` branch was still using asm.js, and when Emscripten moved to llvm-upstream in 1.39.0, they dropped support for that. So to compile successfully one needs to use a 1.38.x version (and it seems like only 1.38.33 to 1.38.48 are qavailable, older versions were hosted by Mozilla and are now dead links), or 1.39.x with the `-fastcomp` option while it's supported, so on emsdk:

```
git checkout 1.39.1  # To have old tagged versions and compatible install scripts.
./emsdk install 1.38.48
./emsdk activate 1.38.48
source emsdk_env.sh
```

or likewise with `1.39.1-fastcomp`.

The build succeeds, but I couldn't get a 2.1 project to run on modern browsers with my build. There's a ton of errors in the console. I tested with 2.1.6 export templates and it fails similarly, so I assume it's just that browsers don't support what we were using back then anymore. My archiving work stops here for now :)

**Comment by dsnopek** [comment]
I haven't reviewed the code, but I just tested building the editor on Ubuntu 22.04 with GCC 11.4 and it worked great! I played a nice little game of minesweeper from the template on the asset library :-)

**Comment by Calinou** [comment]
Build error on VS 2022 x64 (using its native command prompt):

```
[ 39%] Compiling ==> core\version_hash.gen.cpp
version_hash.gen.cpp
core\version_hash.gen.cpp(36): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
core\version_hash.gen.cpp(36): error C2146: syntax error: missing ';' before identifier 'VERSION_TIMESTAMP'
core\version_hash.gen.cpp(36): error C2059: syntax error: '='
scons: *** [core\version_hash.gen.windows.tools.64.obj] Error 2
```

**Comment by akien-mga** [comment]
@Calinou Are the build issues on VS introduced by this PR, or also reproducible in the base `2.1` branch?
Aside from trying to properly close files being written by SCons, this PR shouldn't really affect Windows/MSVC builds.

**Comment by minec-c** [comment]
Hiya all,  I've figured out how to make godot 2.1.6 works on modern web browser when building a custom export template with help of Scons 2.5.1, Emscripten 1.38.48, and python 2.7.13.
1.
I used the following CMD command on Windows 11:
```
platform=javascript target=release tools=no disable_3d=yes disable_advanced_gui=yes builtin_openssl=no module_openssl_enabled=no -j1
```
I had to rip off openssl due to the limited command line length on Windows 11 when linking a static library.
2.
I followed the official guide  where it says: 

>[...] This can be done in the export GUI, using the **“Custom Package” option. There’s no need to copy the templates in this case — you can simply reference the resulting files in your Godot source folder**, [...].

> referenced: https://docs.godotengine.org/en/2.1/development/compiling/compiling_for_web.html.

3.
The export worked on Chrome. Well, almost... The **godot.javascript.opt.exe.html** ignored the **data.pck** and just take the following files:
**godot.javascript.opt.exe.asm.js
godot.javascript.opt.exe.html.mem
godot.javascript.opt.exe.js**

**Workaround 1**: I took borrow the .html file of the official export template (javascript.release.zip file) and within that file I just went to the lines of code where the **asm.js**, the **html.mem** and the **.js** files where referenced and I just renamed those files. You can check at the following repository: https://minec-c.github.io/export216x64pj1/godotapk2/godot.javascript.opt.exe.html

**Workaround 2**:
Within the godot.javascript.opt.exe.asm.js file, I replaced the 1th line of code by the 2th line:
```
_emscripten_get_num_gamepads(){return JSEvents.lastGamepadState.length}
_emscripten_get_num_gamepads(){return 0}
```

**Comment by akien-mga** [comment]
Finally revisiting this to get it merged.
So I'm booting Windows for the first time in 6 months 😅 

> If I don't do `git clean -dfx` before, I get a build error on VS 2022 x64 (using its native command prompt):
> 
> ```
> [ 39%] Compiling ==> core\version_hash.gen.cpp
> version_hash.gen.cpp
> core\version_hash.gen.cpp(36): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
> core\version_hash.gen.cpp(36): error C2146: syntax error: missing ';' before identifier 'VERSION_TIMESTAMP'
> core\version_hash.gen.cpp(36): error C2059: syntax error: '='
> scons: *** [core\version_hash.gen.windows.tools.64.obj] Error 2
> ```

I had overlooked this earlier and thought this could be a regression, but no, this is expected and the same issue would happen without this PR.
We fixed that issue for 4.0 in #53860 but I don't intend to backport this to `2.1`. So when switching branches the `.gen.cpp` files need to be deleted (or the whole repo cleaned, which is better IMO when switching to such an old branch).

> With `tools=no target=release`, I get a build error though:
> 
> ```
> [ 10%] Compiling ==> thirdparty\libmpcdec\mpc_bits_reader.c
> mpc_bits_reader.c
> thirdparty\libmpcdec\mpc_bits_reader.c(101): error C2365: 'log2': redefinition; previous definition was 'function'
> thirdparty\libmpcdec\mpc_bits_reader.c(139): error C2109: subscript requires array or pointer type
> thirdparty\libmpcdec\mpc_bits_reader.c(140): error C2109: subscript requires array or pointer type
> thirdparty\libmpcdec\mpc_bits_reader.c(140): error C2198: 'mpc_uint32_t mpc_bits_read(mpc_bits_reader *,const unsigned int)': too few arguments for call
> scons: *** [thirdparty\libmpcdec\mpc_bits_reader.windows.opt.64.obj] Error 2
> scons: building terminated because of errors.
> ```

I could reproduce this, so I'm adding a commit to fix it.

With this patch, I could build `tools=yes`, `tools=no target=release` and `tools=no target=release_debug` fine.
I edited Minilens in the editor and could export a release build, which seems to run fine.

> I also can no longer build on VS after these changes, but haven’t had time to test thoroughly. I’m able to build on VS using the base 2.1 branch.

@bherdm Could you test again and share what issue you are running into? I can't reproduce it.

**Comment by akien-mga** [comment]
@minec-c Great finds, thanks!

For the build command, I got it to compile successfully with Python 3, SCons 3.1.2 and Emscripten 1.38.48 with just `scons p=javascript tools=no target=release`. I used the PowerShell terminal.

For the files naming issue, there's some post-processing necessary on the generated files in `2.1`, which you can follow here:
https://github.com/GodotBuilder/godot-builds/blob/513e409eb4d722f6d98b2bec59058a369ba538c6/.travis.yml#L200-L210

It's also described in the docs for 2.1 but it seems somewhat outdated: https://docs.godotengine.org/en/2.1/development/compiling/compiling_for_web.html#building-export-templates
The above Travis script is what was used to build official releases for 2.1.

> Workaround 2:
> Within the godot.javascript.opt.exe.asm.js file, I replaced the 1th line of code by the 2th line:
> ```
> _emscripten_get_num_gamepads(){return JSEvents.lastGamepadState.length}
> _emscripten_get_num_gamepads(){return 0}
> ```

I confirm that this function causes an error and replacing it with `0` fixes it. Note that it's in the main `godot.js` file, not `godot.asm.js`. It's caused by this Emscripten compat breakage: https://github.com/emscripten-core/emscripten/issues/7840

This was fixed in Godot 3.0 by #25149, so I'm cherry-picking it. That seems to do the trick at least as long as a gamepad isn't connected.

With a gamepad connected I get errors again. I'd say solving gamepad support for the old `2.1` branch is outside the scope of this PR (it's also broken in the current `2.1` HEAD). Eventually the whole Emscripten gamepad API was dropped in #45079 to replace it with a custom one. But that's way too big to backport to `2.1` just for the sake of preservation, at least I'm not doing it ;)

**Comment by akien-mga** [comment]
> With a gamepad connected I get errors again. I'd say solving gamepad support for the old `2.1` branch is outside the scope of this PR (it's also broken in the current `2.1` HEAD). Eventually the whole Emscripten gamepad API was dropped in https://github.com/godotengine/godot/pull/45079 to replace it with a custom one. But that's way too big to backport to `2.1` just for the sake of preservation, at least I'm not doing it ;)

I found another fix for the Emscripten gamepad handling code that fixes this: #21588.

With this cherry-picked, gamepad support seems to work, including hotplugging (only tested in Firefox and Chromium).

In Chromium it seems to work just fine.
In Firefox, the mappings are partially wrong, I believe that's something that was addressed by #45079 but again this is out of scope of this attempt at making 2.1 compile on modern toolchains. On a knockoff PS3 controller, I noticed that the D-pad doesn't seem to work and the face buttons are flipped, but a demo like the 2D platformer is playable.
