### ISSUE TITLE
Error building from master caused by namespace issue

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#30044]
**Godot version:**
Master

**OS/device including version:**
Ubuntu 16.04
gcc version 5.5.0

**Issue description:**
Building from master with ``scons p=x11 target=release_debug -j4"

Error produced is:
```
editor/editor_layouts_dialog.cpp: In constructor 'EditorLayoutsDialog::EditorLayoutsDialog()':
editor/editor_layouts_dialog.cpp:123:42: error: 'ItemList::SelectMode' is not a class or namespace
  layout_names->set_select_mode(ItemList::SelectMode::SELECT_MULTI);
```

Introduced by https://github.com/godotengine/godot/commit/9986cf70058011fed81c8a2bba4df47e3e58b3ba

Appears to be same use of namespaces as https://github.com/godotengine/godot/issues/28634

I looked online and it appears it is a weird thing that is best supported on windows and only on certain versions of GCC

**Comment by akien-mga** [comment]
>  Linux 16.04

Are you from the future or did you just equate Ubuntu with Linux? :P

**Comment by clayjohn** [comment]
> Are you from the future or did you just equate Ubuntu with Linux? :P

Oh no! My mind is somewhere else right now.. Fixed. :)


Also, compiles fine when line 123:
```
layout_names->set_select_mode(ItemList::SelectMode::SELECT_MULTI);
```
is replaced with:
```
layout_names->set_select_mode(ItemList::SELECT_MULTI);
```

**Comment by akien-mga** [comment]
Yeah, that's a classic issue. IIRC `ItemList::SelectMode::SELECT_MULTI` is illegal in theory, but since MSVC was always fine with it, people use it all the time, so GCC must have given up on it and added support for it recently.
