### PR TITLE
Add missing `stdint.h` includes for GCC 13+

### LINKED ISSUE #77927: Compilation in MSYS2/MinGW with GCC 13.1 fails: symbols not declared in this scope
### Godot version

4.0

### System information

Windows 10, NVidiaRTX 2070

### Issue description

When trying to compile using MinGW with GCC 13.1 compilation fails throwing a bunch of errors like this one:

```
G:/MABS/build/glslang-git/glslang/MachineIndependent/SymbolTable.h:71:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?

G:/MABS/build/glslang-git/glslang/MachineIndependent/SymbolTable.h:662:22: error: 'uint64_t' does not name a type
  662 |     static constexpr uint64_t uniqueIdMask = (1LL << LevelFlagBitOffset) - 1;
```

It looks like the problem comes from third parties: vhacd, openxr and glslang

I've solved the issue by adding:
**#include <stdint.h>**

to 
**\thirdparty\vhacd\inc\vhacdManifoldMesh.h
\thirdparty\openxr\src\common\platform_utils.hpp
\thirdparty\glslang\glslang\Include\Common.h**

I'm not sure how to proceed after finding the fix...

### Steps to reproduce

Try compiling the editor from Master or version 4.0 using MinGW with GCC 13.1

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #77927.

Thanks @germanbv for finding and documenting the fixes. FYI, you could have made a PR with those changes directly :)
That being said, we're a bit peculiar with how we handle modifications to thirdparty code vendored in Godot, so I went ahead and did the PR myself.

Added patch files for v-hacd (the issue seems fixed upstream, but we're on an outdated version so making the difference clear is still important) and openxr (PR'ed the fix upstream, might be included in the next release if accepted: https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/406). It's already fixed upstream in glslang so I didn't add a patch file, it will be included next time we update (it's included in #77898 which will supersede this for 4.1, but we still need the patch for 4.0 and earlier).

### CODE REVIEW

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.
