### ISSUE TITLE
[BUILD] Build broken for Android and iOS after 45ad1024

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#3166]
45ad1024e12ffa6db0e56cb36c007dd212d5e37e broke Android and iPhone builds.

```
scene/gui/popup.cpp: In member function 'void Popup::_notification(int)':
scene/gui/popup.cpp:51:51: error: 'class SceneTree' has no member named 'get_edited_scene_root'
   if (get_tree()->is_editor_hint() && get_tree()->get_edited_scene_root() && get_tree()->get_edited_scene_root()->is_a_parent_of(this)) {
                                                   ^
scene/gui/popup.cpp:51:90: error: 'class SceneTree' has no member named 'get_edited_scene_root'
   if (get_tree()->is_editor_hint() && get_tree()->get_edited_scene_root() && get_tree()->get_edited_scene_root()->is_a_parent_of(this)) {
```

Proof Android -  https://travis-ci.org/Marqin/godot/jobs/99270065#L6892
Proof iOS - https://travis-ci.org/Marqin/godot/jobs/99270067#L8229
