### PR TITLE
Fix OSXCROSS build with clang-6.0

### PR DESCRIPTION
**Pull request by Faless**
I was getting the following error:
```
platform/osx/os_osx.mm:916:10: error: cannot initialize return object of type 'int' with an rvalue of type 'nullptr_t'
                return nil;
                       ^~~
../SDK/MacOSX10.11.sdk/usr/include/MacTypes.h:92:19: note: expanded from macro 'nil'
      #define nil nullptr
                  ^~~~~~~
platform/osx/os_osx.mm:1743:24: error: cannot initialize a variable of type 'NSSearchPathDirectory' with an rvalue of type 'int'
        NSSearchPathDirectory id = 0;
```
Which makes sense, `0` is not even a valid `NSSearchPathDirectory` value, the return type of `remapKey` is `int` so returning `0` instead of `nil` should be fine.

### CODE REVIEW

**Comment by hpvb** [comment]
Manually Cherry picked into 3.0.7
