### ISSUE TITLE
Shaders fail to compile with matrix-type global uniforms (4.1 Compatibility renderer)

### ISSUE THREAD

**Issue by Wolfe2x7** [godotengine/godot#81473]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Linux Mint 20.2 (Uma) - Vulkan (Compatibility) - NVIDIA GeForce GTX 1660 Ti (nvidia; 470.199.02) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

When using the Compatibility renderer, shaders fail to compile if a matrix-type global uniform is used in `vertex()`. The error given is an internal cast from `int` to `uint`:
```
drivers/gles3/shader_gles3.cpp:242 - SceneShaderGLES3: Vertex shader compilation failed:
error C7011: implicit cast from "int" to "uint"
```

### Steps to reproduce

Add a matrix global shader uniform (like a `mat3`, below) in the project settings. This shader will fail to compile:
```
shader_type spatial;

global uniform mat3 bug;

void vertex() {
	mat3 cannot_compile = bug;
}
```

### Minimal reproduction project

[Reproduction 9-8-23.zip](https://github.com/godotengine/godot/files/12564495/Reproduction.9-8-23.zip)

**Comment by AThousandShips** [comment]
Does this happen with `Forward+`?

**Comment by clayjohn** [comment]
I've marked this as a good first issue for someone with a small amount of shader experience. Shader experience isn't strictly necessary but it will make this much easier to track down and solve

**Comment by Wolfe2x7** [comment]
> Does this happen with `Forward+`?

No, neither of the other two renderers are affected. Only the OpenGL Compatibility renderer.

**Comment by jsjtxietian** [comment]
I can help debugging this issue.

I think it's because GL will complain about uint can not add with a int `m_bug+1` like the code below 
```
layout(std140) uniform MaterialUniforms { // ubo:3
uint m_bug;
};

mat3 m_cannot_compile=mat3(global_shader_uniforms[m_bug].xyz,global_shader_uniforms[m_bug+1].xyz,global_shader_uniforms[m_bug+2].xyz);
```

Should I change the uniform's type to int, or change the code generated to something like `global_shader_uniforms[m_bug+uint(1)]` ?

**Comment by darksylinc** [comment]
> or change the code generated to something like global_shader_uniforms[m_bug+uint(1)] 

IMHO a cleaner solution than `global_shader_uniforms[m_bug+uint(1)]` would be ``global_shader_uniforms[m_bug+1u]`, but it is pretty much syntactic sugar.

Changing the type to int could have more consequences thus that solution is riskier.

**Comment by Wolfe2x7** [comment]
@jsjtxietian

Please note that I confirmed this error affects all matrix types (`mat2`, `mat3`, `mat4`), not just `mat3`. 🙏

**Comment by jsjtxietian** [comment]
Hi @Wolfe2x7 , In the fix I think I have updated the code for mat2, mat3, mat4 like this, am I missing anything?
![image](https://github.com/godotengine/godot/assets/8315986/4c4de664-8fb8-4e19-a87b-2f44bdb6da70)

**Comment by Wolfe2x7** [comment]
Looks good to me! 👍
