### PR TITLE
Bump minimum macOS version to 12

### PR DESCRIPTION
**Pull request by aaronfranke**
## What problem(s) does this PR solve?

This PR bumps the minimum macOS version to 12, which is required to fix compatibility with the new Vulkan SDK.

This PR fixes `kIOMasterPortDefault`, allowing compiling with the min version set to macOS 12.

I also checked ahead a bit, and included a fix to `NSApplicationActivateIgnoringOtherApps` and a fix to `AVCaptureDeviceTypeExternalUnknown` for compiling with the min version set to macOS 14.

Going further to macOS 15 will be a challenge, due to `CGWindowListCreateImageFromArray` being deprecated without a trivial replacement in macOS 15. This will require migration to `ScreenCaptureKit`.

## Additional information

See PR #122523 for a different fix that disables warnings. I made this commit before that PR was opened.

None of the code is AI generated. I did ask AI to review my work, and it pointed out that `editor_info_plist.template` could also have its version bumped. I decided to include that in this PR.

### CODE REVIEW

File: modules/camera/camera_apple.mm [hunk 1]
```diff
@@ -483,7 +483,9 @@ - (void)dealloc {
 	if (@available(macOS 14.0, *)) {
 		session = [AVCaptureDeviceDiscoverySession discoverySessionWithDeviceTypes:[NSArray arrayWithObjects:AVCaptureDeviceTypeExternal, AVCaptureDeviceTypeBuiltInWideAngleCamera, AVCaptureDeviceTypeContinuityCamera, nil] mediaType:AVMediaTypeVideo position:AVCaptureDevicePositionUnspecified];
 	} else {
+#if MAC_OS_X_VERSION_MIN_REQUIRED < 140000
```
Comment (bruvzg) [inline modules/camera/camera_apple.mm:486]: Should not be necessary, once min. version is bumped to 14.0 or higher, this branch and `available` can be entirely removed.

File: platform/macos/os_macos.mm [hunk 2]
```diff
@@ -932,7 +932,7 @@
 	static String serial_number;
 
 	if (serial_number.is_empty()) {
-#if defined(__x86_64) || defined(__x86_64__)
+#if MAC_OS_X_VERSION_MIN_REQUIRED < 120000
 		io_service_t platform_expert = IOServiceGetMatchingService(kIOMasterPortDefault, IOServiceMatching("IOPlatformExpertDevice"));
```
Comment (bruvzg) [inline platform/macos/os_macos.mm]: Can be simply removed after bumping version to 12.

File: platform/macos/godot_application.mm [hunk 3]
```diff
@@ -193,4 +198,8 @@ - (void)forceUnbundledWindowActivationHackStep3 {
 	[[NSRunningApplication currentApplication] activateWithOptions:NSApplicationActivateIgnoringOtherApps];
```
Comment (bruvzg) [inline platform/macos/godot_application.mm:198]: Instead of passing 0, should be changed to `activate` method without options.

**Review by bruvzg — COMMENTED** [review]
I do not think we should bump it, since it should be still usable with OpenGL on macOS 11.

File: modules/camera/camera_apple.mm (hunk 1 above)
Comment (aaronfranke) [reply modules/camera/camera_apple.mm:486]: I disagree, I think it's better to make the codebase robust to changing the minimum macOS version. Users who make their own Godot builds may need to increase the min version.

Previous PRs have fixed warnings when targeting newer macOS, such as PR #95854.

File: platform/macos/godot_application.mm (hunk 3 above)
Comment (aaronfranke) [reply platform/macos/godot_application.mm:198]: That's not an available API in `NSRunningApplication`. The zero-argument version is only available in `NSApplication`. Trying to use `activate` does not work:

```cpp
platform/macos/godot_application.mm:180:8: error: no visible @interface for 'NSRunningApplication' declares the selector 'activate'
  180 |                 [app activate];
      |                  ~~~ ^~~~~~~~
```

The replacement is `activateWithOptions:0`, so either we need `#define NSApplicationActivateIgnoringOtherApps 0` as this PR does, or put the `#if`s around each usage.

File: platform/macos/os_macos.mm (hunk 2 above)
Comment (aaronfranke) [reply platform/macos/os_macos.mm]: Done for this PR, but I opened PR #122685 which is a subset that should be merged in advance.
