### ISSUE TITLE
Cannot build on macos 15.0 (xcode 16.0)

### ISSUE THREAD

**Issue by sorascode** [godotengine/godot#97741]
### Tested versions

- Reproducible in master

### System information

macos 15.0 - xcode 16.0

### Issue description

When trying to build the project I get an error that 'cstdint' file is not found in `core/typedefs.h` :

```
./core/typedefs.h:45:10: fatal error: 'cstdint' file not found
   45 | #include <cstdint>
      |          ^~~~~~~~~
```

### Steps to reproduce

build the project

### Minimal reproduction project (MRP)

-

**Comment by fire** [comment]
What version of master did you test?

**Comment by sorascode** [comment]
Did some more testing now.
I've tried several version and they all fail.
I've tried:
- `master` (2e144928793f17ebd70e1475bb7a7f4fd1095484)
- `4.3` (6699ae7897658e44efc3cfb2cba91c11a8f5aa6a)
- `3.6` (de25845e8d5b7465e881ada7ca4c458d12a9492e)

`master` and `4.3` both complain about cstdint, but `3.6` complains about atomic:
```
./core/safe_refcount.h:38:10: fatal error: 'atomic' file not found
   38 | #include <atomic>
      |          ^~~~~~~~
```

I think the issue must have something to do with scons not compiling with cpp or the right version of cpp.

**Comment by elpozewaunig** [comment]
@sorascode Have you been able to fix this? I'm running into the same issue after updating to macOS 15.0 (and it persists after updating to macOS 15.0.1).

**Comment by elpozewaunig** [comment]
If anyone else stumbles across this when compiling on macOS 15, uninstalling and reinstalling the Xcode command line tools solved the issue for me.
```shell
sudo rm -r /Library/Developer/CommandLineTools
sudo xcode-select -r
xcode-select --install
# Go to system settings and update command line tools from there if necessary
```
