### PR TITLE
Re-add define for build with 10.14 SDK, remove unsupported 10.12 checks.

### LINKED ISSUE #38236: macOS build error: use of undeclared identifier 'NSAppKitVersionNumber10_14'
**Godot version:**
master (`23b7670`)

**OS/device including version:**
macOS 10.14.6

**Issue description:**
Got the following error when building Godot on macOS.
```
[Initial build] Linking Static Library ==> modules/libmodule_upnp.osx.tools.64.a
platform/osx/display_server_osx.mm:3249:32: error: use of undeclared identifier 'NSAppKitVersionNumber10_14'
                if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_14) {
                                             ^
```

It seems that `NSAppKitVersionNumber10_14` was defined in https://github.com/godotengine/godot/pull/23822/commits/bbac90c85901f9b15afa12075024d11860cd4330 but now it is no longer in the code base. As seen here when I try to grep for occurrences of this identifier, only the following line was found.

```
godot on  master
➜ rg NSAppKitVersionNumber10_14 .
./platform/osx/display_server_osx.mm
3249:		if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_14) {
```

I believe that there will also be errors with `NSAppKitVersionNumber10_12` due to the same reason.

```
godot on  master
➜ rg NSAppKitVersionNumber .
./platform/osx/os_osx.mm
63:				if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_12) {
72:				if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_12) {
81:				if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_12) {
91:				if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_12) {

./platform/osx/display_server_osx.mm
3249:		if (NSAppKitVersionNumber >= NSAppKitVersionNumber10_14) {
```

**Steps to reproduce:**
Run the build command `scons platform=osx --jobs=$(sysctl -n hw.logicalcpu)`

Or is there something wrong with my setup? I am using the xcode command line tools, and my SDK path is as follows:

```
godot on  master
➜ xcrun --sdk macosx --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
```

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #38236

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
