### PR TITLE
Fix Mono and GDNative builds after changes to ObjectID

### LINKED ISSUE #36156: Unable to compile for Windows on Windows 10 after latest commit
**Godot version:**
Latest Commit: cf8c679a23b21d6c6f29cba6a54eaa2eed88bf92

**OS/device including version:**
Windows 10, Version 1909, 2020-02 Cumulative Update

**Issue description:**
The most recent commit has caused a compilation error for me. Compilation succeeds after reverting the latest commit. I am using Visual Studio. I also tested 32-bit, and I received the same error.
Using:
`scons -j6 platform=windows`
Compilation fails here:
```
video_stream_gdnative.cpp
register_types.cpp
[ 35%] Compiling ==> modules\gdnative\gdnative_api_struct.gen.cpp
[ 35%] gdnative_api_struct.gen.cpp
[ 36%] modules\gdnative\gdnative_api_struct.gen.cpp(60): error C2440: 'initializing': cannot convert from 'void (__cdecl *)(godot_int,godot_rid *,godot_rect2 *)' to 'void (__cdecl *)(int,godot_rid *,godot_rect2 *)'
modules\gdnative\gdnative_api_struct.gen.cpp(60): note: None of the functions with this name in scope match the target type
[ 36%] Compiling ==> modules\etc\image_etc.cpp
scons: *** [modules\gdnative\gdnative_api_struct.gen.windows.tools.64.obj] Error 2
image_etc.cpp
scons: building terminated because of errors.
```
output with `scons -j6 verbose=on warnings=all platform=windows`: 
[failed_build.log](https://github.com/godotengine/godot/files/4194244/failed_build.log)

**Steps to reproduce:**
Compile on Windows 10 using above setup.

### PR DESCRIPTION
**Pull request by akien-mga**
Issues caused by cf8c679a23b21d6c6f29cba6a54eaa2eed88bf92.

The Mono change is actually a bugfix (used the int instead of ObjectID
by mistake).

The GDNative change is a temporary revert until a more exhaustive approach
is taken to make 'godot_int' 64-bit, and confirmed wanted by GDNative users.

And this is why @reduz should make PRs to go through CI tests properly... ;)

Fixes #36156.

### CODE REVIEW

**Comment by akien-mga** [comment]
Marking for cherrypicking as the Mono bugfix is relevant in 3.2 too.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.1.
(Only the relevant change to `modules/mono/csharp_script.cpp`.)
