### PR TITLE
C#: Add missing `get_data` when calling `CFStringCreateWithCString` in `macos_utils`

### LINKED ISSUE #103874: Macos build failure passing CharString to CFStringCreateWithCString
### Tested versions

Introduced in https://github.com/godotengine/godot/pull/101293

### System information

Godot v4.5.dev.mono (e278a6e8c) - macOS Sequoia (15.3.1) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M2 (Apple8) - Apple M2 (8 threads)

### Issue description

Noticed local builds failing with `scons module_mono_enabled=yes dev_mode=yes dev_build=yes` (but not `scons dev_mode=yes dev_build=yes` for some reason) after rebasing earlier today and bisected to the above pr. I assume this instance was missed as it's behind `MACOS_ENABLED`. The build error is:
```
[ 56%] modules/mono/utils/macos_utils.cpp:41:26: error: no matching function for call to 'CFStringCreateWithCString'
   41 |         CFStringRef bundle_id = CFStringCreateWithCString(nullptr, p_bundle_id.utf8(), kCFStringEncodingUTF8);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFString.h:181:13: note: candidate function not viable: no known conversion from 'CharString' to 'const char *' for 2nd argument
  181 | CFStringRef CFStringCreateWithCString(CFAllocatorRef alloc, const char *cStr, CFStringEncoding encoding) CF_FORMAT_ARGUMENT(2);
      |             ^                                               ~~~~~~~~~~~~~~~~
```

### Steps to reproduce

Build on macos with c# support, see error from clang/scons

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by a-johnston**
Fixes https://github.com/godotengine/godot/issues/103874

### CODE REVIEW

**Comment by Ivorforce** [comment]
For the record, this was caused by my recent PR #101293. Not sure why it wasn't caught by any builds. Thanks for fixing!

**Review by Ivorforce — APPROVED** [review]

**Comment by a-johnston** [comment]
Yeah, initially I was confused why I could only repro the failure on c# builds and why the automated checks missed this but turns out this this file is exclusive to both [c#](https://github.com/godotengine/godot/blob/master/modules/mono/csharp_script.cpp#L47) and [macos](https://github.com/godotengine/godot/blob/master/modules/mono/editor/editor_internal_calls.cpp#L36) and c# builds are only tested on linux so this just isn't ever tested by CI currently 🤷

**Review by lawnjelly — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
