### PR TITLE
GDScript: Fix subclass methods not inheriting RPC info

### LINKED ISSUE #80087: RPC Config is not properly inherited when a script is loaded
### Godot version

3fa8fad

### System information

Debian Linux x86

### Issue description

#79205 introduces a regression to the way rpc configs are inherited, causing this error:

```
ERROR: Unable to get the RPC configuration for the function "foo" at path: "/root/Node". This happens when the method is missing or not marked for RPCs in the local script.
```

even though the function exists both in the server and the client. If you `print(self.foo)`, it even tells you that it's rpc: `Node(client.gd)::foo (rpc)` 

Before #79205 `GdScriptCompiler::_populate_class_members` used `GDScriptCache::get_full_script` to access the base script. This causes the parent script to be compiled (if it is not compiled yet), which in turn initializes the `rpc_config` property with a copy of the base value in [gdscript.cpp::_init_rpc_methods_properties](https://github.com/godotengine/godot/blob/3fa8fad26b97a8af20e7996b7e17d8f23fc04b89/modules/gdscript/gdscript.cpp#L1398-L1412)

However, `GDScriptCache::get_shallow_script` does not compile and thus does not initialize the `rpc_config` of the base script, causing the rpc functions not being included in the rpc config.

### Steps to reproduce

Extend a gdscript with a `@rpc` function annotation and try to do a network call:

server.gd:
```gdscript
extends Node

func _ready():
	var peer := ENetMultiplayerPeer.new()
	peer.create_server(1337)
	multiplayer.multiplayer_peer = peer

@rpc("any_peer") func foo():
	print("Server")
```

parent.gd:
```gdscript
extends Node

@rpc func foo(): pass
```

client.gd:
```gdscript
extends "parent.gd"

func _ready():
	var peer := ENetMultiplayerPeer.new()
	peer.create_client("localhost", 1337)
	multiplayer.connected_to_server.connect(func (): self.foo.rpc_id(1))
	multiplayer.multiplayer_peer = peer
```

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/12215814/test.zip)

### PR DESCRIPTION
**Pull request by anvilfolk**
Fixes #80087, which has an excellent explanation of the origins of the issue thanks to @Dragoncraft89.

UPDATED

### General issue description

The way that RPC configurations were populated required the full compilation of the base class. Specifically, the order of operations is the following:
```
GDScriptCompiler::compile() // Compiles the main class
|-> GDScriptCompiler::_populate_class_members() // Prepares base class member info, followed by current & inner classes
|-> GDScriptCompiler::_compile_class() // Actually compiles the class to byte code
    |-> GDScript::_init_rpc_methods_properties() // At the end of compilation, obtains RPC information from base classes
|-> GDScriptCache::finish_compiling() // Finally compiles dependencies, which includes base classes
```

So notice that since RPC information requires the base class to be _compiled_, that information isn't available until after, when `GDScriptCache::finish_compiling()` is called. However, the core issue of #78146 was that `_populate_class_members()` was calling for the compilation of the base class, which introduced fundamental cyclic dependency problems during compilation.

We _cannot_ cause the compilation of another class during compilation of the current class. Specifically, `_compile_class()` cannot cause another `compile()` or `get_full_script()` call to anywhere else.

### Solution

The solution is to populate RPC information in a similar manner to how `_populate_class_members()` currently works, after #79205. In essence, RPC configuration should only depend on:

1. Information available from _shallow_ scripts, i.e. parsed & analyzed (but not compiled) scripts,
2. The base class

Crucially, it cannot depend on data obtained from the compilation (meaning `_compile_class()`) of another class. Current code requires `GDScriptFunctions`, which result from compilation.

### Implementation

All the RPC information was actually from simple parsing of the annotation and stored in `FunctionNode`. It turns out `_populate_class_members()` was already using `GDScripts` and their associated `ClassNode`, which contains members, including functions.

All RPC logic was moved into `_populate_class_members()`, which was already recursively being called for base scripts, traversing its `ClassNode` members, and continuing with inner scripts. In essence, doing everything we needed it to do.

The function was also renamed to `_prepare_compilation()`, which is more descriptive of all it does now. Comments were added indicating that the function cannot cause compilation to occur. It's strictly a pre-compilation step. The order is now:

```
GDScriptCompiler::compile() // Compiles the main class
|-> GDScriptCompiler::_prepare_compilation() // Prepares base class member info & RPC info, followed by current & inner classes
|-> GDScriptCompiler::_compile_class() // Actually compiles the class to byte code
|-> GDScriptCache::finish_compiling() // Finally compiles dependencies, which includes base classes
```

### MRP

[Here](https://github.com/godotengine/godot/files/12562953/godot-test.zip) is a project that fails before this PR and is fixed after, and which uses inner class RPCs. Basically a copy of the original issue report. To run it, you can use the following commands from the appropriate directories:

```
godot-binary --path ./godot-test/ server.tscn
godot-binary --path ./godot-test/ client.tscn
```

I doubt it addresses #80597 since that one is present in 4.1.1 but this regression was introduced by #79205, which isn't in 4.1.

### CODE REVIEW

**Comment by marcol1** [comment]
nice work, i'm planning on debuggin + making a sample project for https://github.com/godotengine/godot/issues/80597 next week, I'll make sure to ping you if I can figure it out.

**Comment by anvilfolk** [comment]
After some testing and thinking about it some more, I don't think this approach is going to work. I think it fairly fundamentally relies on `GDScriptCache::finish_compiling()` which `_compile_class()` doesn't use, and that's what's used for inner classes. I suspect adapting `compile()` for inner classes would result in cyclic compilation errors.

I'm going to investigate moving RPC info storage into structures that don't need the class to be compiled, and which can be resolved at analyze-time. That way at compile time we don't need to check _compiled_ superclasses, we can just access data from _analyzed_ superclasses.

**Comment by ryanabx** [comment]
> I'm going to investigate moving RPC info storage into structures that don't need the class to be compiled, and which can be resolved at analyze-time. That way at compile time we don't need to check _compiled_ superclasses, we can just access data from _analyzed_ superclasses.

Out of curiosity, are all annotations currently reliant on the class being compiled?

**Comment by Dragoncraft89** [comment]
@anvilfolk I dont think you can call RPC functions on inner classes. At least I can't manage to do it.

**Comment by anvilfolk** [comment]
I think I've finally come up with a fix that works in the general case, and also does a nice little refactor of the code to boot :) If folks using RPCs could please test this PR that would be wonderful! I've only run some tests locally, but they aren't super complex.

> @anvilfolk I dont think you can call RPC functions on inner classes. At least I can't manage to do it.

@Dragoncraft89 the issue is that you can have a "normal" class extend an inner class, and the inner class can extend from anything, etc, and any point in that hierarchy may have RPC info being inherited from somewhere! I'll attach a project to the OP with an example!

File: modules/gdscript/gdscript_compiler.cpp [hunk 1]
```diff
@@ -2670,9 +2681,7 @@ Error GDScriptCompiler::_populate_class_members(GDScript *p_script, const GDScri
 					}
 					prop_info.hint = export_info.hint;
 					prop_info.hint_string = export_info.hint_string;
-					prop_info.usage = export_info.usage | PROPERTY_USAGE_SCRIPT_VARIABLE;
-				} else {
-					prop_info.usage = PROPERTY_USAGE_SCRIPT_VARIABLE;
+					prop_info.usage |= export_info.usage;
```
Comment (dalexeev) [inline modules/gdscript/gdscript_compiler.cpp:2684]: See [#81079](https://github.com/godotengine/godot/pull/81079/files#diff-43fc69f36899762bf59f1cd731dfc0be1ff0d2b648271e443944e4116c1c28a6L2673-R2683).

Comment (anvilfolk) [reply modules/gdscript/gdscript_compiler.cpp:2684]: Haha, nice! I'll take it out of this one!

**Comment by Dragoncraft89** [comment]
So I just tested some cases and they all work:
* Inheritance Parent -> Child
* Inheritance Grandparent -> Parent -> Child
* The above cases with an inner class
* Without inheritance

Additionally I tested this on my project that prompted me to open the original bug report. This works as well.

Well done @anvilfolk !

**Comment by anvilfolk** [comment]
Thank you so much for testing! ❤️ My favorite PRs are the ones that fix an issue and end up with less code, hehehehe! Hopefully we'll get some reviews here soon and it'll get merged so the issue is fixed in `master`.

**Review by adamscott — APPROVED** [review]
Reviewed during the GDScript Team Meeting. Everything looks fine and that's a nasty bug removed from our codebase. Good job, Ocean!

**Comment by anvilfolk** [comment]
Latest push was just fixing the comments @AThousandShips flagged! Apologies on always forgetting the comment guidelines, I'll try to be better at it :)

**Comment by AThousandShips** [comment]
It's something that takes time to get used to! That's why I'm here ^-^

**Comment by akien-mga** [comment]
Thanks!
