### ISSUE TITLE
Visual shader broken after uniform->parameter rename

### ISSUE THREAD

**Issue by jgillich** [godotengine/godot#65388]
### Godot version

4b164b8e4790cfeb597b763123560b59a96458e5

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

Opening a visual shader in the latest version performs several destructive actions:

* `FloatUniform` nodes are deleted
* All `uniform_name` fields are lost and not converted to `parameter_name`
* Several variables are deleted without replacement (even those who still have nodes), which breaks shader compilation
  ```
  res://src/material/worlds/environment/shader.tres:102 - Unknown identifier in expression: 'TextureUniformTriplanar3'.
    Shader compilation failed.
  ```

Sample shader: https://gist.github.com/jgillich/46fb0753b9f01abb691516f12004ac6a

This diff is produced by opening the shader in the latest version and saving: https://gist.github.com/jgillich/34d843da4d11ed2821204b87d642cacb

Pretty sure this is caused by #64952 @Chaosus.

### Steps to reproduce

Open a visual shader with `TextureUniformTriplanar` and `FloatUniform` nodes in the latest version

**Comment by Chaosus** [comment]
`FloatUniform nodes are deleted`

It's a bug indeed, and can be easily fixed.

> Several variables are deleted without replacement (even those who still have nodes), which breaks shader compilation

Nah, it's just a bug inside `TextureUniformTriplanar` - you cannot use multiple nodes of that types at all.

> All uniform_name fields are lost and not converted to parameter_name

Can you explain what do you mean? Parameters in the inspector lost only when shader fails to compile.

**Comment by jgillich** [comment]
Can confirm that FloatUnforms are now converted, thanks :+1: 

> It's just a bug inside TextureUniformTriplanar - you cannot use multiple nodes of that type at all.

My shader used to work just fine with multiple triplanar texture nodes(?). I'm no shader expert so I'm not sure if there's a better way...

> Can you explain what do you mean? Parameters in the inspector lost only when shader fails to compile. You need to compile the shader successfully at least once - then the internal parameters will be updated.

The shader names are reset to the default because the  `unform_name` field is not converted to the new `parameter_name`.

![Screenshot from 2022-09-06 11-19-01](https://user-images.githubusercontent.com/347965/188597909-c7b625aa-2cfa-4843-8cc1-f5cb8718b7da.png)

They used to be different. It doesn't compile due to the triplanar issue but is that actually the reason?

**Comment by QbieShay** [comment]
I know it's annoying but I think it's okay if some stuff breaks at this stage of development, 4.0 is a breaking change (broke also my stuff for the records x) but it's okay, I think this rename improves things)

**Comment by akien-mga** [comment]
>> The node names are reset to the default because the unform_name field is not converted to the new parameter_name.
>
> Ah, unfortunately there is no way to make a conversion property, so the best way is to rename it back again manually.

If it's a regular Object property, it should be possible to do the conversion by handling it in `_set`, see e.g.:

https://github.com/godotengine/godot/blob/7a620e34bf3fbe3e704c95c3e0ab5565730df651/scene/resources/environment.cpp#L1134-L1151

It's compatibility code that needs to be maintained (and eventually removed) so whether it's worth doing depends on the pros and cons / how many users will be affected by the breakage.

**Comment by jgillich** [comment]
I think it's fine to not add a conversion as long as it is mentioned in the next release changelog. But one does need to be careful, this could also lead to loss of parameter values in ShaderMaterials.

**Comment by Chaosus** [comment]
I've fixed the triplanar texture code generation in the https://github.com/godotengine/godot/pull/65455.

**Comment by jgillich** [comment]
Thank you very much! Everything's looking good now
