### ISSUE TITLE
Failure to import `.blend` with Blender package from Arch Linux

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot#76338]
### Godot version

4.0.2-stable

### System information

Fedora 37

### Issue description

This is related to #67275. I noticed my `.blend` imports failing after my recent upgrade from Blender 3.3.1 to 3.5.0.

Blender 3.5 hasn't yet been discussed in that issue, and so @lyuma suggested this may be a different problem to the ones we've experienced between 3.0 & 3.4.

I have also confirmed this isn't a problem with Blender 3.4.1.

![Screenshot from 2023-04-22 10-05-26](https://user-images.githubusercontent.com/4892574/233774664-5a08720b-b16b-404e-a233-27294b380ec4.png)

As is the case with #67275, the import keeps happening on a loop, which prevents me from working because the import modal repeatedly pops up:

![Screenshot from 2023-04-22 10-05-09](https://user-images.githubusercontent.com/4892574/233774746-7b27b100-f527-4454-aa79-8ed8520df2fc.png)

Aside: it'd be useful to be able to debug this from the production editor build, perhaps by dumping Blender stderr into `.godot/` somewhere.

### Steps to reproduce

- Ensure Blender 3.5 is installed + configured for Godot and that imports are enabled on the current project
- Add any `.blend` file to the project

You'll need to keep mashing Ctrl+Q to get the editor to quit after this.

### Minimal reproduction project

[src.zip](https://github.com/godotengine/godot/files/11300810/src.zip)

**Comment by Cthuflu** [comment]
Some additional logging (using the Overgrown Subway Scene project) and a build of `master` at d023e51363a800a89a8ef30259ac4410dd544354 on Fedora 37 reveals that the same error occurs for every model with
```
Blender 3.5.0 (hash unknown built 2023-04-06 00:00:00)
BLT_lang_init: 'locale' data path for translations not found, continuing
Read prefs: /home/jacob/.config/blender/3.5/config/userpref.blend
Read blend: /home/jacob/Projects/Games/Overgrown Subway Scene/outside_walls/outside_walls.blend
Error: Python: Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/usr/share/blender/3.5/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.export_scene.gltf" error, could not be found

Blender quit
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7431)                                                                                                                                                                                 
ERROR: Error importing 'res://outside_walls/outside_walls.blend'.
   at: _reimport_file (editor/editor_file_system.cpp:2033)
```

**Comment by Cthuflu** [comment]
[Core add-ons got missed, oops](https://discussion.fedoraproject.org/t/blender-on-fedora-38-is-missing-core-add-ons/81521)

This is happening because godot is expecting a plugin like `io_scene_gltf2` to exist, as it's usually packaged by default. However, blender recently restructured their source repository which seems to have removed the addons git submodule; which the package maintainers missed during this update.

**Comment by MartinHaeusler** [comment]
As @lyuma asked for it in another ticket, here's a minimal Godot project which reproduces the problem. Apologies for the file size (25MB zipped, around 80MB unzipped), the bug occurred for me for this particular mesh. Everybody should be able to grab the project here:

https://drive.google.com/file/d/1x0qtp9gOUEhcNYNqRqXPATD7WDu2dPmC/view?usp=sharing

This is what the project looks like for me:

![image](https://github.com/godotengine/godot/assets/16356998/54fb45fa-8ee5-4337-b1c8-ff21a50653c7)

There are several issues with this minimal project for me:

- "gothicWindow1.blend" imports just fine, but "grandLibrary_01.blend" does not. I've verified that the file opens correctly in Blender 3.5.1 and it is fine (some missing textures aside). I haven't been able to discern the decisive difference between these two files.
  -  The error log says: 
     > modules/gltf/gltf_document.cpp:7431 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://grandLibrary_01.blend'.
- Whenever the Godot window loses focus and regains focus, it attempts to reimport the "grandLibrary_01.blend" again.

My Setup:
- OS: Windows 10 x64 
- CPU: AMD Ryzen 7 3700X
- GPU: RTX 3080
- RAM: 32 GB
- Godot: v4.0.3.stable.mono.official [5222a99f5]
- Blender: 3.5.1 


I do have multiple blender installations floating around on my machine, is that a problem? I specified the 3.5.1 version in the Godot settings. I had to disable and re-enable the "Blender" import plugin to make Godot recognize the `*.blend` files at all.

**Comment by Zireael07** [comment]
Does the library blend import if you rename it to something w/o underscore?

**Comment by MartinHaeusler** [comment]
@Zireael07 no, haven't tried that. Would be really funny if that were the case. I can try it when I get home after work today.

**Comment by MartinHaeusler** [comment]
@Zireael07 I've tried renaming the file by removing the underscore, unfortunately the behavior is still the same. So that wasn't the cause.

**Comment by ShawkMusic** [comment]
I'm getting this error in Godot 4.1.1 with Blender 3.6.0

It seemed to be working before, although I don't know if that was because I was on Godot 4.1 or an earlier version of Blender, or something else entirely.

**Comment by nano13** [comment]
Pretty much the same issue here, the error message looks slightly different for me:

```
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7447)
ERROR: Error importing 'res://Models/suzuki_motorbike_wheel_front.blend'.
   at: _reimport_file (editor/editor_file_system.cpp:2044)
Blender 3.6.0 (hash c7fc78b81ecb built 2023-07-07 13:20:07)
Read prefs: "/home/samuel/.config/blender/3.6/config/userpref.blend"
Read blend: "/home/samuel/programmierung/godot/GodotFirstPersonController/Models/suzuki_motorbike_wheel_rear.blend"
Error: Python: Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/usr/share/blender/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Converting py args to operator properties: : keyword "export_nla_strips" unrecognized

Blender quit
```

Godot version

v4.2.dev.custom_build [https://github.com/godotengine/godot/commit/75f9c97deaa8378477441e07ea1782ecab6d2eca]
System information

Godot v4.2.dev (https://github.com/godotengine/godot/commit/75f9c97deaa8378477441e07ea1782ecab6d2eca) - Arch Linux https://github.com/godotengine/godot/issues/1 SMP PREEMPT_DYNAMIC Mon, 24 Jul 2023 20:19:38 +0000 - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 5500 XT () - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

**Comment by ShawkMusic** [comment]
Testing this, I was previously using Blender through pacman (v3.6.0), but the Blender flatpak (v3.6.1) seems to not have this issue. I wonder if this is because of the slightly newer version or because of the packaging format. (flatpak vs system package manager)

**Comment by ShawkMusic** [comment]
Testing this, I was previously using Blender through pacman (v3.6.0), but the Blender flatpak (v3.6.1) seems to not have this issue. I wonder if this is because of the slightly newer version or because of the packaging format. (flatpak vs system package manager)

@nano13 If you want to solve this issue now and don't mind using flatpak, install the org.blender.Blender flatpak and set the "Blender 3 Path" in Godot's editor settings to `/var/lib/flatpak/app/org.blender.Blender/x86_64/stable/active/files/blender/`

**Comment by cg9999** [comment]
Arch linux blender package currently in testing (3.6.1-1) doesn't have this issue anymore. Earlier version had the 
`keyword "export_nla_strips" unrecognized` error message printed.

**Comment by rcorre** [comment]
On blender 3.6.2-1 on ArchLinux, I still get:

```
  File "/usr/share/blender/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Converting py args to operator properties: : keyword "export_nla_strips" unrecognized
```

This happens in a loop, and each re-import opens a new external editor instance, filling the screen with windows.

**Comment by akien-mga** [comment]
See #79881. So far all reports point to the Blender package from Arch Linux being problematic.
One of you should report a bug to the Arch Linux maintainers so they can fix their package.

The workaround is to download Blender from blender.org, which works fine.

**Comment by snoopdouglas** [comment]
Just mentioning - my original report was from Fedora 37. Unsure whether these share the RPM source somehow though, or whether this issue was repurposed.

**Comment by akien-mga** [comment]
My bad, I overlooked this. I guess this ticket is now being repurposed :P 

The problem with Arch is likely similar to the problem Fedora 37 briefly had, where they were not including all core addons. Arch and Fedora don't share package sources but it might be that a missing build dependency or build option leads to not compiling all Blender addons we need (here notably glTF export stuff I suppose).

**Comment by rcorre** [comment]
Aha! Found this in https://projects.blender.org/blender/blender-addons:

```diff
commit 96a73cb664bca687b7ea2e464c4d08f8082d5012
Author: Julien Duroure <julien.duroure@gmail.com>
Date:   Tue May 23 16:12:03 2023 +0200

    glTF exporter: keep backward compatibility for export options

diff --git a/io_scene_gltf2/__init__.py b/io_scene_gltf2/__init__.py
index 0d50f4ad..a469c81e 100755
--- a/io_scene_gltf2/__init__.py
+++ b/io_scene_gltf2/__init__.py
@@ -4,7 +4,7 @@
 bl_info = {
     'name': 'glTF 2.0 format',
     'author': 'Julien Duroure, Scurest, Norbert Nopper, Urs Hanselmann, Moritz Becher, Benjamin Schmithüsen, Jim Eckerlein, and many external contributors',
-    "version": (3, 6, 21),
+    "version": (3, 6, 22),
     'blender': (3, 5, 0),
     'location': 'File > Import-Export',
     'description': 'Import-Export as glTF 2.0',
@@ -601,6 +601,19 @@ class ExportGLTF2_Base(ConvertGLTF2_Base):
         default=False
     )
 
+    # This parameter is only here for backward compatibility, as this option is removed in 3.6
+    # This option does nothing, and is not displayed in UI
+    # What you are looking for is probably "export_animation_mode"
+    export_nla_strips: BoolProperty(
+        name='Group by NLA Track',
+        description=(
+            "When on, multiple actions become part of the same glTF animation if "
+            "they're pushed onto NLA tracks with the same name. "
+            "When off, all the currently assigned actions become one glTF animation"
+        ),
+        default=True
+    )
+
     will_save_settings: BoolProperty(
         name='Remember Export Settings',
         description='Store glTF export settings in the Blender project',
```

I think we want `export_animation_mode=NLA_TRACKS`. I can open a PR.

**Comment by telmotrooper** [comment]
In line with @ShawkMusic's suggestion, a simple workaround on **Arch Linux** is to download **Blender 3.6.2** directly from [their website](https://www.blender.org/download/), extract the "tar.xz" file with `tar xfv blender-3.6.2-linux-x64.tar.xz` and point Godot to that folder (in "Editor > Editor Settings... > FileSystem > Import > Blender 3 Path").

**Comment by marcinn1** [comment]
> See #79881. So far all reports point to the Blender package from Arch Linux being problematic.

Regardless, Godot should not try to import these in a infinite loop.

**Comment by MartinHaeusler** [comment]
One more insight: the model that didn't import for me in Godot is using the Blender Asset Library feature. Could this be the cause?

**Comment by rcorre** [comment]
The comment in https://github.com/godotengine/godot/pull/81194 explains more, but to clarify, this is not specific to ArchLinux. This is specific to a certain range of blender versions that removed the `export_nla_strips` parameter. Arch happened to package a version within that range.

More recent versions add that back for "backwards compatibility", but the re-added parameter does nothing (so it's not really backwards compatible). 

> the model that didn't import for me in Godot is using the Blender Asset Library feature. Could this be the cause?

If you see `keyword "export_nla_strips" unrecognized`, then no. Blender import will fail on all blend files.

**Comment by FaizanMughal** [comment]
![image](https://github.com/godotengine/godot/assets/33963921/60eea95b-c0ab-4b4c-b0e2-5196ee3573b7)
I'm having the same issue.
I've tried with Blender 3.3.0, 3.4.1, 3.5.0, 3.6.4
Always the same problem.

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.3667) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

**Comment by felipejoribeiro** [comment]
I'm having the same problem.

Godot version= 4.1.2-1
blender version=3.6.4

The logs in the infinite loop are these, repeating itself in loop:
```
Blender 3.6.4 (hash 21bfc5e7fe3f built 2023-09-27 00:27:16)
Read prefs: "/home/fejori/.config/blender/3.6/config/userpref.blend"
Exception in module register(): /usr/share/blender/3.6/scripts/addons/amaranth/__init__.py
Traceback (most recent call last):
  File "/usr/share/blender/3.6/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/usr/share/blender/3.6/scripts/addons/amaranth/__init__.py", line 92, in register
    _call_globals("register")
  File "/usr/share/blender/3.6/scripts/addons/amaranth/__init__.py", line 88, in _call_globals
    getattr(m, attr_name)()
  File "/usr/share/blender/3.6/scripts/addons/amaranth/scene/refresh.py", line 53, in register
    km = kc.keymaps.new(name="Window")
         ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keymaps'
Read blend: "/home/user/project/assets/environment/lacume_castle.blend"
Error: Python: Traceback (most recent call last):
  File "<string>", line 9, in <module>
  File "/usr/share/blender/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Converting py args to operator properties: : keyword "export_nla_strips" unrecognized

Blender quit
ERROR: Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
   at: append_from_file (modules/gltf/gltf_document.cpp:7433)
ERROR: Error importing 'res://assets/environment/lacume_castle.blend'.
   at: _reimport_file (editor/editor_file_system.cpp:2044)
```

**Comment by felipejoribeiro** [comment]
I was able to get it working with Godot `4.1.2-1`  by:

- Downloading blender version `3.6.1` from  [this link](https://www.blender.org/download/release/Blender3.6/blender-3.6.1-linux-x64.tar.xz);
- Extracting it somewhere and making godot use this version when importing .blend files, by adding the path to the extracted files in the Godot import configurations;

Not a real solution though. This new blender's version keeps crashing Godot.

**Comment by rcorre** [comment]
@akien-mga any chance this can get backported to 4.1? Are there plans for another 4.1 patch before 4.2 comes out?

**Comment by akien-mga** [comment]
Yes, that's what the `cherrypick:4.1` label means on the PR.

**Comment by rcorre** [comment]
Ah, sorry! I saw the 4.2 milestone on the issue and assumed it was just 4.2. Thanks!
