### PR TITLE
Fix build errors when building with `disable_xr=yes`

### PR DESCRIPTION
**Pull request by darksylinc**
Building with the following params (note: scu_build is enabled):

```
platform=linuxbsd builtin_embree=yes builtin_enet=no
builtin_freetype=yes builtin_graphite=yes builtin_harfbuzz=yes
builtin_libogg=no builtin_libpng=yes builtin_libtheora=no
builtin_libvorbis=no builtin_libwebp=no builtin_miniupnpc=no
builtin_pcre2=no builtin_zlib=yes builtin_zstd=no linker=mold
optimize=none debug_symbols=True tests=True dev_mode=True dev_build=True
use_llvm=yes use_lld=yes opengl3=no openxr=no disable_xr=yes -j 24
scu_build=yes scu_limit=256
```

Results in compiler errors:

```
In file included from servers/register_server_types.cpp:99:
servers/xr/xr_interface.h:52:7: error: redefinition of 'RefCounted'
   52 | class XRInterface : public RefCounted {
      |       ^
./servers/rendering/rendering_method.h:40:21: note: expanded from macro
'XRInterface'
   40 | #define XRInterface RefCounted
      |                     ^
./core/object/ref_counted.h:37:7: note: previous definition is here
   37 | class RefCounted : public Object {
      |       ^
```

This happens because of:

```
#ifdef XR_DISABLED
// RendererSceneCull::render_camera is empty when 3D is disabled, but
// it and RenderingMethod::render_camera have a parameter for
XRInterface.
#define XRInterface RefCounted
#else
#include "servers/xr/xr_interface.h"
#endif // XR_DISABLED
```

In rendering_method.h

The problem was introduced in #103267

### CODE REVIEW

**Comment by darksylinc** [comment]
I don't know if this is the right way to fix the problem. It could use @mux213 eyes.

I disable a lot of stuff to build Godot as fast as possible, and XR was causing build errors with my unusual build settings (probably because of `opengl3=no` because the SDK headers were complaining about EGLDisplay not defined)

**Review by dsnopek — APPROVED** [review]
Thanks! I haven't tested, but the code change looks OK to me

**Review by akien-mga — APPROVED** [review]
Looks good, though this one also seems to be missing:
```diff
diff --git a/scene/register_scene_types.cpp b/scene/register_scene_types.cpp
index 260170dba2..16bf1b8606 100644
--- a/scene/register_scene_types.cpp
+++ b/scene/register_scene_types.cpp
@@ -293,10 +293,12 @@
 #include "scene/3d/visible_on_screen_notifier_3d.h"
 #include "scene/3d/voxel_gi.h"
 #include "scene/3d/world_environment.h"
+#ifndef XR_DISABLED
 #include "scene/3d/xr/xr_body_modifier_3d.h"
 #include "scene/3d/xr/xr_face_modifier_3d.h"
 #include "scene/3d/xr/xr_hand_modifier_3d.h"
 #include "scene/3d/xr/xr_nodes.h"
+#endif
 #include "scene/animation/root_motion_view.h"
 #include "scene/resources/3d/box_shape_3d.h"
 #include "scene/resources/3d/capsule_shape_3d.h"
```

From a quick review of `.*xr/.*` includes, that seems to be it.

FYI @YeldhamDev 

---

The Windows CI error seems to be a fluke, so amending the commit with the above will likely fix it.

File: scene/register_scene_types.cpp [hunk 1]
```diff
@@ -293,10 +293,12 @@
 #include "scene/3d/visible_on_screen_notifier_3d.h"
 #include "scene/3d/voxel_gi.h"
 #include "scene/3d/world_environment.h"
+#ifndef XR_DISABLED
 #include "scene/3d/xr/xr_body_modifier_3d.h"
 #include "scene/3d/xr/xr_face_modifier_3d.h"
 #include "scene/3d/xr/xr_hand_modifier_3d.h"
 #include "scene/3d/xr/xr_nodes.h"
+#endif
```
Comment (YeldhamDev) [inline scene/register_scene_types.cpp:301]:
```suggestion
#endif // XR_DISABLED
```

File: servers/register_server_types.cpp [hunk 2]
```diff
@@ -99,6 +100,7 @@
 #include "xr/xr_interface_extension.h"
 #include "xr/xr_positional_tracker.h"
 #include "xr_server.h"
+#endif
```
Comment (YeldhamDev) [inline servers/register_server_types.cpp:103]:
```suggestion
#endif // XR_DISABLED
```

**Review by YeldhamDev — CHANGES_REQUESTED** [review]
Otherwise, LGTM.

**Comment by darksylinc** [comment]
Changes committed, tests passed :)

**Review by BastiaanOlij — APPROVED** [review]
LGTM

**Review by YeldhamDev — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
