### PR TITLE
Fix typo in shader breaking gles3

### PR DESCRIPTION
**Pull request by semensanyok**
caused by https://github.com/godotengine/godot/commit/e41064388e67cc9bec320ee467757089b150bf20

```
ERROR: SceneShaderGLES3: Fragment shader compilation failed:
0(1142) : error C0116: #endif should not have arguments
0(1860) : error C0116: #endif should not have arguments

   at: _display_error_with_code (drivers\gles3\shader_gles3.cpp:253)
ERROR: Method/function failed.
   at: ShaderGLES3::_compile_specialization (drivers\gles3\shader_gles3.cpp:395)
```

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
