### PR TITLE
SCons: Fix import clash between Godot and system modules

### LINKED ISSUE #24965: Build fail: module 'detect' has no attribute 'is_active'
**Godot version:**
1ff170e67f0044b0a9f42fc936f09847c5ec4127

**OS/device including version:**
Windows 10 x64
Python 3.7.2 (Didn't worked with 3.7.1 either)
Scons 3.0.1

**Issue description:**
When compiling, error is thrown:

```
C:\Users\x\Documents\godot>scons -j6 platform=windows
scons: Reading SConscript files ...
AttributeError: module 'detect' has no attribute 'is_active':
  File "C:\Users\x\Documents\godot\SConstruct", line 37:
    if (detect.is_active()):
```

It seems like `detect.py` is taken from:
`C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\site-packages\detect\__init__.py`
instead of:
`C:\Users\x\Documents\godot\platform\windows\detect.py`

### PR DESCRIPTION
**Pull request by akien-mga**
See #24965 for details. `sys.path.insert` is hacky, but should work
relatively well for both Python 2 and Python 3. When we eventually
deprecate Python 2 support, we could look into using importlib.

Fixes #24965.

Thanks @touilleMan for the help.

### CODE REVIEW

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.
