### PR TITLE
Fix for Clang dev_mode Windows build

### PR DESCRIPTION
**Pull request by bitsawer**
Adds a fix / workaround for `dev_mode` (all warnings and warnings as errors) build when building for Windows using Clang. Seems like a Clang issue, GCC apparently doesn't enable these warnings for `-Wall`.

Alterantively, we could maybe add `-Wno-missing-field-initializers` and `-Wno-missing-braces` when building with Clang to avoid these in the future, but this is probably a pretty rare issue.

Clang error:

```
platform\windows\display_server_windows.cpp:670:31: error: missing field 'biWidth' initializer [-Werror,-Wmissing-field-initializers]
                                BITMAPINFO bmp_info = { 0 };
                                                          ^
platform\windows\display_server_windows.cpp:670:29: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
                                BITMAPINFO bmp_info = { 0 };
                                                        ^
                                                        {}
platform\windows\display_server_windows.cpp:670:31: error: missing field 'bmiColors' initializer [-Werror,-Wmissing-field-initializers]
                                BITMAPINFO bmp_info = { 0 };
                                                          ^
3 errors generated.
```

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by YuriSizov** [comment]
This shouldn't be cherry-picked as it fixes an issue introduced in https://github.com/godotengine/godot/pull/75142, which wasn't cherry-picked.
