### ISSUE TITLE
[3.x] Custom 3.7.0-dev.1 release build crashes with `ERROR: Condition "!instance" is true`

### ISSUE THREAD

**Issue by ee-DavidC** [godotengine/godot#122923]
### Tested versions

I'm building Godot editor myself using `scons platform=windows target=release_debug tools=yes` 
- Reproducible in Godot 3.7.0-dev.1 (a117d512b00f1646db174e703e7e888519b64608)
- Not reproducible in Godot 3.6.2 (3cd3caab6779a7f3ec3bbeb9f200db50c735cfc8)

This is not reproducible with the official 3.7.0-dev.1 build if I don't specify any `Custom Template` in the export settings.

### System information

Windows 11

### Issue description

When running the game with my manually compiled version of Godot 3.7.0-dev.1 in `release`, it crashes.  

When doing the same in `release_debug`, I get the following errors:
```
ERROR: Condition "!instance" is true. Returned: Variant()
   at: MethodBind1<class CanvasItemMaterial,enum CanvasItemMaterial::BlendMode>::call (C:\Projects\godot\core\method_bind.gen.inc:838) - Condition "!instance" is true. Returned: Variant()
```

[godot.log](https://github.com/user-attachments/files/31551249/godot.log)

Those errors do not happen if I use a manually compiled version of Godot 3.6.2.

### Steps to reproduce

1. Fork Godot at commit `a117d512b00f1646db174e703e7e888519b64608`
2. Compile runtime with `scons platform=windows target=release tools=no`
3. Export a game with this compiled runtime 
4. Launch the game and observe the crash after some times

### Minimal reproduction project (MRP)

I'm not sure how to have a minimal project to reproduce this issue.

**Comment by lawnjelly** [comment]
Will take a look into it. 👍 

So far:
Building export template (debug), exporting debug, and running `Platformer3D` works fine for me under Linux.
It going to be difficult to test windows as I don't have windows, but I'll test the regular 3.7 dev 1 builds under WINE.

What project is it you are running, is it Brotato, and does it cause errors with a minimal Godot project?
What compiler + compiler version + linker are you using?
(i.e. it will be good to track down whether it's something particular in the project, or a general problem)

### More investigation
The logs indicate that the engine's ClassDB fails to properly instantiate or look up `CanvasItemMaterial` when `tools=no` is used during compilation on this specific development commit. 

The loop of errors for `BlendMode`, `bool`, and `int` shows the engine trying to map saved properties onto a resource, where the underlying C++ class instance wasn't successfully registered. This will crash on release.

Mismatch between the editor build and the export template seems a possible cause, but I'm assuming that's not the case here due to the error report. NOTE: This can also be a difference in HOW they were compiled (build configurations or modules)

But I'll carry on investigating assuming this isn't the problem.

## Steps
1) As I can't currently reproduce this, it would be helpful if you could bisect it:
https://docs.godotengine.org/en/4.4/contributing/workflow/bisecting_regressions.html
It is highly likely to be bisected to #84804, so probably try that first, before / after.

(I tend to bisect manually)

2) Which compiler version are you using (e.g., MSVC 2022, MinGW)? Since the official pre-compiled template works, it might be an optimization bug triggered by a specific compiler version.

3) We can check whether it is trying to register `CanvasItemMaterial` in your export template:

If you add this debug print in your source code, `register_scene_types.cpp`, line ~599, if you add this debug print immediately before registering:

```
 	print_line("DEBUG: Registering CanvasItemMaterial");
	ClassDB::register_class<CanvasItemMaterial>();
```
Then re-export and run the game, we can see if the debug print appears before the errors.

It could be a macro is disabling it (but it does print on my side when I build this in, so this would seem unlikely). Another possibility is `Static Initialization Order Fiasco`, which is particularly nasty, and is a long running architectural problem in 3.x _and_ 4.x.
https://github.com/godotengine/godot/issues/106235

## More
The fact I can't replicate the problem at all on my Linux Mint (clang, lld), suggests strongly this is is environment-specific, meaning the compiler, linker and optimization flags used on windows vs Linux are the factor changing the outcome.

1) Compiler (especially MSVC, and especially using link time code generation `/LTCG` or whole program optimization `/GL`) could be aggressively removing "dead code" and misclassifying `CanvasItemMaterial` as dead code.

You can also test adding this line before registration:
```
// Add a dummy volatile reference to ensure linkage and avoid compiler bugs.
volatile Object *canvas_material_dummy = Object::cast_to<CanvasItemMaterial>(nullptr);
// Suppress unused warnings.
(void)canvas_material_dummy;
ClassDB::register_class<CanvasItemMaterial>();
```

2) SIOF (static order) - if the compiler executes `register_scene_types` before the main ClassDB internals or VisualServer are ready, this could cause registration failure. On clang, the compilation unit order might sidestep this problem. However, that it hasn't occurred on earlier builds is relevant, but that could be down to chance with SIOF.

I don't *think* it is due to SIOF in this case (as the problem seems to be the class missing from the binary), but I can't rule it out.

3) Recompiling the template with `optimize=none` in the Scons command line will help pin down whether the optimization is the problem.

4) Also, I would ensure running an Scons clean before compiling both the editor and templates, especially when swapping between 3.6 and 3.7. Add `-c` to the Scons command line to clear out intermediates. There are some bugs in Scons / build here for intermediates, and these do occur intermittently, so is worth ruling out.

5) Don't use `SCU` builds for either here, but particularly the template (I don't think it currently compiles for templates actually!), just in case that changes the initialization order / macro order. It's really intended for development speedup rather than final builds.

## Current
I *think* currently that it likely to bisect to my blob shadows PR. But if you are bisecting, that might be the first to try, before after that PR. This is both because it uses editor gizmos, and it also adds two classes to `register_scene_types.cpp`.

Ok, current working theory is that the `#includes` for blob shadows in `register_scene_types.cpp` pushes the distribution layout of the translation unit, exposing a compiler bug.

The working theory is that adding the `volatile` as described in (2) may well fix it (if we are correct), or at least shift the problem onto another class.
If correct, this is a linker stripping issue, caused by lack of explicit class instantiations.

So it:
* may not be strictly speak a compiler "bug"
* may not be SIOF (register_scene_types.cpp code is predictable)
* the error isn't that `CanvasItemMaterial` is being registered too early or late, it's completely missing from the binary

Also see e.g. #112753.
We've run into a lot of issues with certain compilers having problems with builds in the past, so this may be related.
If in doubt, using the official build setup is always a good bet. (That's not an excuse BTW, we should fix these wherever possible.)

**Comment by lawnjelly** [comment]
If the `volatile` fix does fix / do something, I've created a PR #122978 which may use a similar trick but working for all these classes, so we don't just "shift the problem along" to the next class.

It would be good if you can download that branch, compile and test too, if the volatile seems to be working. (I can't test as I cannot replicate.)

**Comment by ee-DavidC** [comment]
My project is indeed Brotato

### Steps section
2. compiled with MSVC 2022 linker version 14.44
3. I can see `DEBUG: Registering CanvasItemMaterial` being logged at the very top of the log file, just after `Async. shader compilation: OFF` and before any error.

### More section
1. I can't add this code snippet, it does not compile (I've done a rough translation of the messages because they were in french):
```
[ 94%] scene\register_scene_types.cpp(601): error C2668: 'Object::cast_to' : ambiguous call to an overloaded function
C:\Projects\godot\core/object.h(653): note: is maybe 'const T *Object::cast_to<CanvasItemMaterial>(const Object *)'
        with
        [
            T=CanvasItemMaterial
        ]
C:\Projects\godot\core/object.h(648): note: or     'T *Object::cast_to<CanvasItemMaterial>(Object *)'
        with
        [
            T=CanvasItemMaterial
        ]
scene\register_scene_types.cpp(601): note: When attempting to map the list of arguments '(nullptr)'
scene\register_scene_types.cpp(601): error C2440: 'initialisation' : unable to convert from '_T' to 'volatile Object *'
        with
        [
            _T=const CanvasItemMaterial *
        ]
scene\register_scene_types.cpp(601): note: The conversion removes the qualifiers
[ 99%] progress_finish(["progress_finish"], [])
scons: *** [scene\register_scene_types.windows.opt.debug.64.obj] Error 2
```
3. Compiling with `scons target=release_debug tools=no optimize=none` still shows the error
4. Cleaning with `-c` before building does not change the error
5. I'm not sure what `scu` builds are, is it a command line option? If so, I'm not using it

### Draft MR
I've tried cherry picking https://github.com/godotengine/godot/pull/122978 but it does not impact the error, it does not change the outcome.

### Next steps 
1. I will try bisecting 
2. I will try to reproduce with a sample project of Godot 

Thanks for your quick answer!

### Update 1
I've tried reproducing with Platformer 3D Demo project, it does work fine with my custom build of godot 3.7.0-dev.1, no error in debug or release.

**Comment by lawnjelly** [comment]
Thanks!

That seems to rule out compiler optimization stripping, macros cutting out code, or build mismatches and suggests the binaries are healthy. That's good, because compiler specific bugs like that can be nightmare to identify and fix. 😁 I'm hopeful that this might not be such a difficult problem after all. 

As the debug print is outputting fine, and it runs `Platformer3D`, this pins it down to something likely simpler, something specific that Brotato is doing which is conflicting with changes since 3.6.

It could well be a script or animation timeline is making calls like setting `BlendMode`, `ints` or `bools` at a variable it assumes holds `CanvasItemMaterial` but it the instance is NULL.

### Pinning down more in the project
We may be able to get the engine to give us the script location where this is happening by enabling script stack traces:
```
cmd godot_binary.exe --path "path/to/brotato" --verbose
```
However this isn't foolproof as it's a silent error occurring in the engine code, so you may have to turn on / off bits of the game to bisect what area is causing it.

Also bisecting the engine back from 3.7 dev 1 to see which commit introduced this behaviour is probably going to be most informative.

_The volatile fix failed to compile because I missed a cast `(Object *) nullptr` and your compiler is flagging higher levels of warnings than mine. But I think we already proved the class is registering ok, so we can revert that change, not need to go further there._

_Incidentally I'm off on holiday AFK from tomorrow till the 11th or so, so, so if I don't get back immediately, that's why._

**Comment by ee-DavidC** [comment]
It took a long time, but I was able to bisect:

```
aa63595b83d0f102b5bb413b4838dca9ab553d57 is the first 'bad' commit
commit aa63595b83d0f102b5bb413b4838dca9ab553d57 (HEAD)
Author: Lukas Tenbrink <lukas.tenbrink@gmail.com>
Date:   Sun Jun 22 15:46:28 2025 +0200

    Use ancestral classes to speed up `Object::cast_to` when possible.
```

which seems coherent because the nullptr is happening after a cast.

**Comment by lawnjelly** [comment]
Great! Thanks for bisecting.

This is the PR: #107844

I'll bring @Ivorforce in here, just in case he can spot a likely culprit while I'm away (we both worked on this), and the same problem might be relevant on 4.x as this was forward ported.

I'll try and have a look if I get a chance before this evening.

**Comment by lawnjelly** [comment]
Some other useful questions:

* what was the cast, what was the type of object?
* were any of these objects custom, i.e. created in your fork of the engine?

It's just possible that a custom object isn't playing nice with the ancestry, so it would be good to know yes / no whether this is something to prioritize in investigating.

**Comment by ee-DavidC** [comment]
The assert happens here:

_method_bind.gen.inc:838_
```c++
virtual Variant call(Object* p_object,const Variant** p_args,int p_arg_count, Variant::CallError& r_error) {

		T *instance=Object::cast_to<T>(p_object);
		r_error.error=Variant::CallError::CALL_OK;
#ifdef DEBUG_METHODS_ENABLED

		ERR_FAIL_COND_V(!instance,Variant());
		if (p_arg_count>get_argument_count()) {
			r_error.error=Variant::CallError::CALL_ERROR_TOO_MANY_ARGUMENTS;
			r_error.argument=get_argument_count();
			return Variant();

		}
		if (p_arg_count<(get_argument_count()-get_default_argument_count())) {

			r_error.error=Variant::CallError::CALL_ERROR_TOO_FEW_ARGUMENTS;
			r_error.argument=get_argument_count()-get_default_argument_count();
			return Variant();
		}
		CHECK_ARG(1);
		
#endif
		(instance->*method)(_VC(1));
		
		return Variant();
	}
```

I did some debug, I know that `p_object` is not null when this is called, but casting it to `CanvasItemMaterial` returns null.
However, I don't know its original type. If you have some debug code that I could add to know, I would be glad to answer

My fork does not modify the engine in any way, my plan is to add a module, but in this issue I've considered the engine without any modifications.

**Comment by lawnjelly** [comment]
I'm hoping this will work:
```
T *instance=Object::cast_to<T>(p_object);
if (!instance && p_object) {
    String class_name = p_object->get_class();
    ObjectID instance_id = p_object->get_instance_id();

    String node_name = "";
    if (p_object->is_class("Node")) {
        node_name = " | Node Name: " + p_object->call("get_name").operator String();
    }

    ERR_PRINT("Cast failed! Source Class: " + class_name + " (ID: " + itos(instance_id) + ")" + node_name);
}
```
_HOWEVER_, I don't think you can put it directly in `method_bind_inc.gen.cpp`, because that is a generated file, and it will probably get overwritten.

Instead I think it needs to go in `core/make_binders.py`, approx line 37, inside `virtual Variant call(Object* p_object,const Variant** p_args,int p_arg_count, Variant::CallError& r_error) {`.

I think it should just pick it up immediately, but if it doesn't rebuild the gen file (check it has changed), then maybe just adding `-c` to your Scons command line to perform a clean, then removing the `-c` and building again normally will do the trick.

Ideally, we would work on an MRP, but I understand that your project is pretty big and isolating it may be difficult.

**Comment by ee-DavidC** [comment]
It worked! 
Here are the logs: 
[godot.log](https://github.com/user-attachments/files/31683574/godot.log)

**Comment by lawnjelly** [comment]
Ah unfortunately there's no node there though so I guess it's not telling us much more. Worth a try though.
I'm on holiday now though, so will catch up with this when I get back.

Other thing to try, just in case, is to delete your `.import` folder in the project, and make sure it is re-imported by 3.7. Just in case there's some difference there.

You could also try creating a `CanvasItemMaterial` manually (so you know it is legit) and try casting to it (especially via  c++, but it might work via gdscript), just in case the casting is completely fubarred.

The other possibility is if @Ivorforce can take a look as it could be `GDSOFT_CLASS` related (given that that's the commit it's bisected to).

**Comment by ee-DavidC** [comment]
Deleting `.import` and making sure the project is imported by the same version used to export the game does not change the error.

Sadly, I don't have much more time to allocate to this bug for now, but I keep in mind that you would like a MRP and, at least, that I try to create a `CanvasItemMaterial` manually to cast it.

Thanks a lot for your help and enjoy your holidays!

**Comment by Ivorforce** [comment]
Edit: Fix submitted https://github.com/godotengine/godot/pull/123099

The problem appears to be the following:

https://github.com/godotengine/godot/blob/dd52ac78293af1cdf3a171647aa18e2227946d04/scene/2d/canvas_item.h#L47-L51

i.e. `CanvasItemMaterial` got the `CanvasItem` ancestral class.

The same is not true for 4.x:

https://github.com/godotengine/godot/blob/6220ead4fa06611918e371e6f51d7b9a3aefe53c/scene/main/canvas_item.h#L47-L53

**Comment by ee-DavidC** [comment]
I can confirm that my issue is fixed with https://github.com/godotengine/godot/pull/123099 applied on top of 3.7.0-dev.1 latest commit.
Thanks for your time and for your quick answer!

**Comment by lawnjelly** [comment]
Fixed by #123099.
