### ISSUE TITLE
`print_verbose` makes build fail when `scu_build=yes`

### ISSUE THREAD

**Issue by ydeltastar** [godotengine/godot#101966]
### Tested versions

- 4.4.beta

### System information

Windows 11

### Issue description

The `print_verbose` macro is causing one of the CI jobs that uses `scu_build=yes` to fail in my PR although I didn't modify the file calling it.
https://github.com/godotengine/godot/actions/runs/12934119444/job/36074414239

My local build also fails when I use `scu_build=yes` but works fine otherwise.
```sh
[100%] godot\core/debugger/remote_debugger_peer.cpp(172): error C3861: 'print_verbose': identifier not found
```

By the way, it works if I replace it with `WARN_VERBOSE`.

### Steps to reproduce

- Checkout https://github.com/godotengine/godot/pull/100516
- I changed calls to `print_verbose`  in `core/debugger/remote_debugger_peer.cpp` to `WARN_VERBOSE` to fix CI. Change it back to `print_verbose`. 
- Build it with `scons scu_build=yes`.

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
I can confirm that cherry-picking the mentioned pr and trying to compile with `scu_build=yes` in MSVC 14.3 results in the error (i cherry-picked before the change in the pr that replace the `print_verbose` for `WARN_VERBOSE`)

![Image](https://github.com/user-attachments/assets/784c5a90-6d12-444c-a35d-05834addb85f)

**Comment by lawnjelly** [comment]
The problem is likely due to this, in `variant_utility.cpp` and `variant_utility.h`:
```
#undef print_verbose
```
This means anything that tries to use `print_verbose` after these files will fail (unless it is defined after this point).

We can't do much about the header, but for the cpp, we can add it as an exception from the scu build so it gets compiled on its own and doesn't affect any other files.

It likely wasn't due to your PR, but your PR may have inadvertently changed the grouping of which files were compiled together, which exposed this bug.

I'll see if it can be fixed with a simple exception rule.

**Comment by lawnjelly** [comment]
I have a potential general fix for this problem but I can't make a PR for 4.x currently because the `clang-format` etc hooks requirements have changed to a version I don't have for my OS so I'd have to compile from source.

So if anyone wants to fix this, try changing `VariantUtility::print_verbose()` to `VariantUtility::_print_verbose()`, and remove both of the `#undef print_verbose`.

Then to bind it, copy the binding macro and change the function name to `_print_verbose`. The commit hooks thoughfully deleted my in progress PR, but that should be enough to go on.
