### ISSUE TITLE
Error when building for Android x86: undefined reference to '__atomic_fetch_add_8'

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#31407]
**Godot version:** Git de8ce3e625e74833aec6a5d165e7e82100a1dbf3

**OS/device including version:** Fedora 28, Android SDK build tools 28.0.3, Android NDK r19

**Issue description:** Building fails for Android x86:

```text
Linking Shared Library ==> bin/libgodot.android.opt.x86.so
platform/android/thread_jandroid.os:thread_jandroid.cpp:function ThreadAndroid::thread_callback(void*): error: undefined reference to '__atomic_fetch_add_8'
platform/android/thread_jandroid.os:thread_jandroid.cpp:function ThreadAndroid::get_thread_id_func_jandroid(): error: undefined reference to '__atomic_fetch_add_8'
drivers/libdrivers.android.opt.x86.a(thread_posix.android.opt.x86.o):thread_posix.cpp:function ThreadPosix::thread_callback(void*): error: undefined reference to '__atomic_fetch_add_8'
drivers/libdrivers.android.opt.x86.a(thread_posix.android.opt.x86.o):thread_posix.cpp:function ThreadPosix::get_thread_id_func_posix(): error: undefined reference to '__atomic_fetch_add_8'
servers/libservers.android.opt.x86.a(visual_server_wrap_mt.android.opt.x86.o):visual_server_wrap_mt.cpp:function VisualServerWrapMT::thread_draw(bool, double): error: undefined reference to '__atomic_fetch_sub_8'
servers/libservers.android.opt.x86.a(visual_server_wrap_mt.android.opt.x86.o):visual_server_wrap_mt.cpp:function VisualServerWrapMT::thread_flush(): error: undefined reference to '__atomic_fetch_sub_8'
core/libcore.android.opt.x86.a(memory.android.opt.x86.o):memory.cpp:function Memory::free_static(void*, bool): error: undefined reference to '__atomic_fetch_sub_8'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

[Full build log on GitLab CI](https://gitlab.com/Calinou/godot-builds-ci/-/jobs/273561246)

In comparison, ARM targets build successfully. Maybe this was caused by https://github.com/godotengine/godot/pull/31321?

**Steps to reproduce:** Build for Android x86 using `scons platform=android android_arch=x86`.

**Comment by akien-mga** [comment]
CC @julianaito @RandomShaper

**Comment by julianaito** [comment]
This very surely requires '-latomic' as a linker flag.

**Comment by akien-mga** [comment]
I'm surprised that it happens only for `x86` on Android though, and not other arches/platforms.

For `scons p=android android_arch=x86 target=release` I also get this warning:
```
./core/safe_refcount.h:124:9: warning: misaligned atomic operation may incur significant performance penalty [-Watomic-alignment]
        return __atomic_add_fetch(pw, 1, __ATOMIC_SEQ_CST);
               ^
1 warning generated.
```

**Comment by akien-mga** [comment]
Relevant explanation: https://stackoverflow.com/a/56169176

**Comment by akien-mga** [comment]
> I'm surprised that it happens only for `x86` on Android though, and not other arches/platforms.

Seems to be because Clang (used for Android builds) might not implement `__atomic_add_fetch` with instructions on `x86`, so it defers to `libatomic` at the cost of performance. From what I read it seems the same should happen for (some) ARM platforms, I guess `p=x11` on a armv7hl host might also fail until libatomic is linked.

**Comment by LinuxUserGD** [comment]
`X86_64` also compiles fine without errors

**Comment by RandomShaper** [comment]
Why don't we just remove `SafeRefCount` altogether and use atomic types from the standard library?

Maybe that would be too much for 3.2. I could do the switch for 4.0.

In the meantime, we could just revert the latest changes.

**Comment by scottkunkel** [comment]
after using [UPX](https://upx.github.io/) it will clock in at around 11Mb, same with windows builds
Note that this needs to be applied to the godot export, not the build templates.

**Comment by akien-mga** [comment]
Fixed by #31858.
