### ISSUE TITLE
Compile error for Windows tool with mingw on Linux

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#34092]
**Godot version:**
3.2-beta 40d1486cb3

**OS/device including version:**
Linux mint 19.2, gcc (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0

**Issue description:**
```
[100%] Linking Program        ==> bin/godot.windows.opt.tools.64.exe
modules/libmodules.windows.opt.tools.64.a(register_module_types.gen.windows.opt.tools.64.o):register_module_types.gen.cpp:(.text+0x14): undefined reference to `register_camera_types()'
modules/libmodules.windows.opt.tools.64.a(register_module_types.gen.windows.opt.tools.64.o):register_module_types.gen.cpp:(.text+0xe4): undefined reference to `unregister_camera_types()'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.opt.tools.64.exe] Error 1
scons: building terminated because of errors.
```

**Steps to reproduce:**
clean by `scons p=windows --clean`
delete all `*.a`, `*.o`, `*.d`
`scons p=windows`

**Minimal reproduction project:**

**Comment by bruvzg** [comment]
This is caused by #33992 camera code move, probably something else should be cleaned too (`*.gen.*` files, scons db, `git clean -dfx`).

I can build for Windows using gcc and clang MinGW toolchains without any issues.

**Comment by volzhs** [comment]
oh... i didn't know that `git clean -dfx` removes all untracked files, including my custom modules... :sob:

**Comment by volzhs** [comment]
also deleted `*.gen.*` files and did `git clean -dfx`.
but I got still the same error.

**Comment by volzhs** [comment]
I found that there is an error message at start.
```
$ scons -j 14 platform=windows bits=64 verbose=no target=release_debug debug_symbols=no
scons: Reading SConscript files ...
Configuring for Windows: target=release_debug, bits=64
Using Mingw

scons: warning: Ignoring missing SConscript 'modules/camera/SCsub'
File "/mnt/dev/godot/modules/SCsub", line 17, in <module>
```
@bruvzg do you have any clue?

**Comment by volzhs** [comment]
oh... renaming `SCSub` to `SCsub` at https://github.com/godotengine/godot/tree/master/modules/camera fixed this issue...

cc @bruvzg
