### PR TITLE
Update builtin mbedtls to 3.5.1, keeping compatiblity with mbedtls 2.x

### PR DESCRIPTION
**Pull request by lyuma**
Needed for libdatachannel support. Code compatibility was fairly straightforward. The only complexity was that a PRNG was required for parsing keys in CryptoKeyMbedTLS. Otherwise only a couple ifdefs were needed to keep compatibility with both mbedtls 3.x and 2.x.

In a non-rigorous test including both this and the libdatachannel integration, binary size was 1.1MB larger. I determined this size change was entirely due to libdatachannel.
I would like to break this down to see how much of this is from the mbedtls upgrade. Maybe we can compare github actions for a more accurate answer on binary size.

### CODE REVIEW

**Comment by akien-mga** [comment]
> I would like to break this down to see how much of this is from the mbedtls upgrade. Maybe we can compare github actions for a more accurate answer on binary size.

I did a quick comparison with the artifacts from this PR and from https://github.com/godotengine/godot/actions/runs/6292543678 merged yesterday.

The current `master` is the folders without suffix, and this PR is the folders with `(1)` suffix.
```
161915061       linux-editor-mono
161947764       linux-editor-mono(1)
71153264        linux-template-mono
71173680        linux-template-mono(1)
36410618        web-template
36373175        web-template(1)
114429440       windows-editor
114424832       windows-editor(1)
```

So there's +20/30 kB for Linux editor/templtes, but -40 kB for the Web template and the Windows editor. So it's pretty much an insignificant different.

File: modules/mbedtls/SCsub [hunk 1]
```diff
@@ -42,13 +43,14 @@ if env["builtin_mbedtls"]:
         "entropy_poll.c",
         "error.c",
         "gcm.c",
-        "havege.c",
+        "godot_core_mbedtls_platform.c",
```
Comment (akien-mga) [inline modules/mbedtls/SCsub:46]: I think this was added by mistake maybe? It's meant for the `core` integration.

Comment (lyuma) [reply modules/mbedtls/SCsub]: I removed this as well as a few of the other other new .c files based on fire's previous work on this.

**Comment by fire** [comment]
@Faless isn't confident bumping the mbedtls version right now. Also, mbedTLS 3.5 just came out, so we should do the switch soon after the release to have an entire release cycle to ensure Godot Engine networking works. Switching to mbedTLS 3.x means more maintenance burden and potentially more instability.

The plan is to merge the mbedtls update after the Godot Engine 4.2 release is out.

**Comment by akien-mga** [comment]
Sounds like a good plan :+1:

**Comment by fire** [comment]
@Faless The window for 4.3 is running down, what is the revised plan for this?

I don't see a mbedtls upgrade being essential if the webrtc isn't desired in the core, and that was the reason for the upgrade.

So the mbedlts upgrade is salvageable for someone?

Good reasons to salvage:

1. Prevent version drift
2. Support newer CryptoKey algorithms

**Comment by lyuma** [comment]
@fire You asked about being salvageable. I was able to rebase to latest master with no issue, so I think this PR should still be fine.

What are the next steps?

File: thirdparty/mbedtls/LICENSE [hunk 2]
```diff
@@ -200,3 +207,347 @@
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
+
+
+===============================================================================
+
+
+                    GNU GENERAL PUBLIC LICENSE
```
Comment (akien-mga) [inline thirdparty/mbedtls/LICENSE:215]: We shouldn't include the text of the GPL, this will freak people out. The upstream Apache-licensed source tarball usually has the edited version of the LICENSE with only Apache (basically the file we already had).

**Review by akien-mga — APPROVED** [review]
I need to test a build against a distro mbedtls 2.x to confirm it's working, but I support moving to mbedtls 3 as our bundled version.

Reserving merge for approval by @faless.

**Review by Faless — CHANGES_REQUESTED** [review]
Great work :trophy: .

This looks overall good, see my suggestion about seeding rngs on-the-fly when parsing private keys.

Also, I noticed that building with `module_mbedtls_enabled=no` is giving some weird linking error:

```
$ scons module_mbedtls_enabled=no
scons: Reading SConscript files ...
Automatically detected platform: linuxbsd
Auto-detected 8 CPU cores available for build parallelism. Using 7 cores by default. You can override it with the -j argument.
Using linker program: gold
Building for platform "linuxbsd", architecture "x86_64", target "editor".
NOTE: Developer build, with debug optimization level and debug symbols (unless overridden).
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[ 96%] Linking Program bin/godot.linuxbsd.editor.dev.x86_64 ...
[100%] progress_finish(["progress_finish"], [])
[100%] thirdparty/mbedtls/library/common.h:221: error: undefined reference to 'mbedtls_get_unaligned_uint64'
thirdparty/mbedtls/library/common.h:221: error: undefined reference to 'mbedtls_get_unaligned_uint64'
thirdparty/mbedtls/library/common.h:222: error: undefined reference to 'mbedtls_put_unaligned_uint64'
thirdparty/mbedtls/library/aes.c:650: error: undefined reference to 'mbedtls_get_unaligned_uint32'
thirdparty/mbedtls/library/aes.c:930: error: undefined reference to 'mbedtls_get_unaligned_uint32'
thirdparty/mbedtls/library/aes.c:931: error: undefined reference to 'mbedtls_get_unaligned_uint32'
thirdparty/mbedtls/library/aes.c:932: error: undefined reference to 'mbedtls_get_unaligned_uint32'
thirdparty/mbedtls/library/aes.c:966: error: undefined reference to 'mbedtls_put_unaligned_uint32'
thirdparty/mbedtls/library/aes.c:967: error: undefined reference to 'mbedtls_put_unaligned_uint32'
thirdparty/mbedtls/library/aes.c:968: error: undefined reference to 'mbedtls_put_unaligned_uint32'
thirdparty/mbedtls/library/aes.c:969: error: undefined reference to 'mbedtls_put_unaligned_uint32'
thirdparty/mbedtls/library/aes.c:1206: error: undefined reference to 'mbedtls_get_unaligned_uint64'
thirdparty/mbedtls/library/aes.c:1207: error: undefined reference to 'mbedtls_get_unaligned_uint64'
thirdparty/mbedtls/library/aes.c:1212: error: undefined reference to 'mbedtls_put_unaligned_uint64'
thirdparty/mbedtls/library/aes.c:1213: error: undefined reference to 'mbedtls_put_unaligned_uint64'
thirdparty/mbedtls/library/aes.c:1271: error: undefined reference to 'mbedtls_xor'
thirdparty/mbedtls/library/aes.c:1278: error: undefined reference to 'mbedtls_xor'
thirdparty/mbedtls/library/aes.c:1304: error: undefined reference to 'mbedtls_xor'
thirdparty/mbedtls/library/aes.c:1308: error: undefined reference to 'mbedtls_xor'
thirdparty/mbedtls/library/constant_time.c:213: error: undefined reference to 'mbedtls_put_unaligned_uint64'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.linuxbsd.editor.dev.x86_64] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:28.522]
```

**Comment by fire** [comment]
I did some work on mbedtls 3.6 upgrade in the webrtc branch but it's relatively hard to work with. Needs help.

https://github.com/V-Sekai/godot/tree/vsk-libdatachannel-4.3

**Comment by akien-mga** [comment]
Superseded by #90482.
