### ISSUE TITLE
Compilation fail with headless builds

### ISSUE THREAD

**Issue by MmAaXx500** [godotengine/godot#58922]
### Godot version

4.0.dev (f726ba37ec36b2232f0a54ce3576381477ab1aff)

### System information

Arch Linux

### Issue description

Compilation of headless version fails with the following message:
```
platform/linuxbsd/os_linuxbsd.cpp: In member function 'void OS_LinuxBSD::run()':
platform/linuxbsd/os_linuxbsd.cpp:352:17: error: 'DisplayServer' has not been declared
  352 |                 DisplayServer::get_singleton()->process_events(); // get rid of pending events
      |                 ^~~~~~~~~~~~~
```

Command used to compile: `scons -j12 platform=linuxbsd target=release_debug tools=yes x11=no vulkan=no`

Bisected, first bad commit is b396fd4eef36d23fa7325b13a4b8e120f1f000c9 (#57641).

### Steps to reproduce

Compile with `scons -j12 platform=linuxbsd target=release_debug tools=yes x11=no vulkan=no`.

**Comment by akien-mga** [comment]
Does this fix it?
```diff
diff --git a/platform/linuxbsd/os_linuxbsd.cpp b/platform/linuxbsd/os_linuxbsd.cpp
index d876932a83..6461a3d9fe 100644
--- a/platform/linuxbsd/os_linuxbsd.cpp
+++ b/platform/linuxbsd/os_linuxbsd.cpp
@@ -32,6 +32,7 @@
 
 #include "core/io/dir_access.h"
 #include "main/main.h"
+#include "servers/display_server.h"
 
 #ifdef X11_ENABLED
 #include "display_server_x11.h"
```

If so feel free to PR the fix, you did most of the work already :)

**Comment by MmAaXx500** [comment]
Thanks, here is the pr: #58923
