### ISSUE TITLE
Godot 2.1.1 Doesn't Compile From Source

### ISSUE THREAD

**Issue by Gramps** [godotengine/godot#7150]
**Windows 10 - Godot 2.1.1 Source**

**Issue description** (what happened, and what was expected):
I receive these errors when compiling either the engine or templates:
```
core\os\copymem.cpp(39): error C2059: syntax error: 'constant'
core\os\copymem.cpp(41): error C2065: 'p_bytes': undeclared identifier
scons: *** [core\os\copymem.windows.opt.64.obj] Error 2
scons: building terminated because of errors.
```

**Steps to reproduce:**
Tried compiled with command: scons platform=windows target=release tools=no

**Comment by akien-mga** [comment]
Regression from 67f65f6.

/me grumbles @punto- for pushing stuff directly to the *stable* branch.

**Comment by Gramps** [comment]
Ah... I shall await fixing, excited to try it out once it's working!

**Comment by akien-mga** [comment]
Though wait.. That file should not exist anymore.

**Comment by akien-mga** [comment]
How did you download the 2.1.1 source?

**Comment by Gramps** [comment]
I downloaded it from Branch>Tag>2.1.1-stable

However, I copies the data over to the folder I was using and overwriting files.  It now occurs to me that since there are files that shouldn't exist, I should have started clean.

**Comment by akien-mga** [comment]
Indeed. It should work fine if you start from a clean folder.

**Comment by Gramps** [comment]
Punto's off the hook!  Will do.
