### PR TITLE
Fixed rand_range not returning correct random values on windows

### LINKED ISSUE #8957: rand_range seems not to work on windows in godot 3.0
**Operating system or device - Godot version:**
Operating system: Windows 10 (Version 1703 / OS Build 15063.296)
Godot version: 3.0 - master b93fce1c18a58e752c07a634ed11aa8ec199601d

**Issue description:**
rand_range in gdscript doesn't seem to work on windows (tested mac and ubuntu and it did work there)
```
randomize()
var rndtest = rand_range(0.0, 200.0)
print(rndtest)
```
Outputs e.g. -705028414800 while the debugger shows -16777216
randf() didn't work as well while randi() seemed to work fine.
Compiled with vs2015 and vs2017 CE and tried x86 and x64 builds of godot.

**Steps to reproduce:**
Create a new project and add the above code snippet to a node.

**Link to minimal example project:**
Example project: [testproject-x86.zip](https://github.com/godotengine/godot/files/1033513/testproject-x86.zip)

### PR DESCRIPTION
**Pull request by thomas-goerlich**
This pull request fixes https://github.com/godotengine/godot/issues/8957
The Visual Studio C++ compiler seems not to automatically use unsigned int for the enums.
Declaring unsigned int explicitly for the enum fixes that problem.

### CODE REVIEW

**Review by akien-mga — DISMISSED** [review]

**Comment by akien-mga** [comment]
Apparently this syntax is not ok for clang:
```
core/math/math_funcs.h:54:7: error: expected identifier or '{'
        enum : unsigned int {
             ^
````

**Comment by tagcup** [comment]
Nope. I think it was an enum from the beginning.

**Comment by thomas-goerlich** [comment]
Sorry i didn't know that it is a C++11 only feature.

Should i change it to a static const float variable? That way we wouldn't need all the casts to float/double.
If so should i create a new pull request?

**Comment by akien-mga** [comment]
Regarding the best type to use, I guess @tagcup would know better than me what is appropriate.

You don't have to do a new PR, you can rebase this one to modify the commit. See http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by tagcup** [comment]
Ah no, it should be a uint64_t constant

**Review by akien-mga — APPROVED** [review]

**Comment by thomas-goerlich** [comment]
Okay so i changed the variable to an uint64_t and hopefully made no mistake rebasing everything (first time doing that) :-)

@tagcup could you explain why it should be an uint64_t instead of e.g. a float? It is used as a float/double everywhere and the uint64_t needs to be cast to float/double.

**Comment by tagcup** [comment]
It's like RAND_MAX in math.h, such that you can use modular division with it

**Comment by thomas-goerlich** [comment]
@tagcup not trying to be annoying or anything just wanting to learn more about game dev here ... i assume you mean modulo division right? like 10 % 5 = 0? RANDOM_MAX is never used that way in the godot code. It is always only used with normal division.

**Comment by tagcup** [comment]
It *can* be used like that. Again, just think of it as RAND_MAX from math.h.

**Comment by thomas-goerlich** [comment]
Ah! Okay so it's just a precaution. Allright, now i get it :-)
Thanks for being patient and explaining it!

**Comment by BastiaanOlij** [comment]
I'm assuming this also explains randf not behaving correctly? Works fine on Mac, gave really weird output on Windows.

I'm behind my Mac at the moment but I'll try this patch out on Windows when I get a chance, see if it resolves it. Makes sense, I remember seeing a bunch of warnings during compile about the signed/unsigned nature of this number.

**Comment by thomas-goerlich** [comment]
@BastiaanOlij Yes, this does fix randf() as well. Sorry for not mentioning it.
