### PR TITLE
Handle the case where `waitpid` returns `errno` `EINTR`.

### LINKED ISSUE #105097: Unit tests fail under `lldb` supervision
### Tested versions

a210fe6dbd27cc01bffacb0ce2816e0cf303af5e / 4.0+

### System information

Godot v4.4.1.stable - macOS Sequoia (15.3.0) - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

When using `lldb`, `test_os.h` fails `[OS] Execute`.
This is a regression from https://github.com/godotengine/godot/pull/42069 (4.0), cc @Calinou.

### Steps to reproduce

1. Be on macOS (may fail on linux too)
2. run  `❯ lldb bin/godot.macos.editor.arm64 -- --test`
3. run `run`
4. Observe the error:

```
./tests/core/os/test_os.h:199: ERROR: CHECK( exit_code == 0 ) is NOT correct!
  values: CHECK( 230 == 0 )
  logged: Running the command `sh -c "ls > /dev/null"` returns a zero (successful) exit code.

Process 42405 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x1005063b0)
    frame #0: 0x00000001005063b0 godot.macos.editor.arm64.master`TestOS::DOCTEST_ANON_FUNC_4825() at test_os.h:197:2 [opt]
   194          CHECK_MESSAGE(
   195                          err == OK,
   196                          "(Running the command `sh -c \"ls > /dev/null\"` returns the expected Godot error code (OK).");
-> 197          CHECK_MESSAGE(
   198                          exit_code == 0,
   199                          "Running the command `sh -c \"ls > /dev/null\"` returns a zero (successful) exit code.");
   200  #endif
Target 0: (godot.macos.editor.arm64.master) stopped.
warning: godot.macos.editor.arm64.master was compiled with optimization - stepping may behave oddly; variables may not be available.
```

The rest of the unit tests run through, so deleting the test is a temporary fix.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Ivorforce**
Fixes #105097 

This case indicates that a debugger is attached, and `waitpid` should be called again.
Fix in reference to [this](https://stackoverflow.com/questions/21554195/why-waitpid-return-1-when-run-in-debugger) stackoverflow answer.
I'm not 100% sure this is the best way to handle it, but it seems to at least succeed in the debugger.

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]
Tested on macOS, seems to be working.

`get_process_exit_code` and `is_process_running` probably should check for `-1`/`EINTR` as well and assume process is still running.

**Comment by Ivorforce** [comment]
@bruvzg This required a bit more refactoring, but ultimately i agree. Otherwise, we'll probably stumble over the same issue again some other time.

File: drivers/unix/os_unix.cpp [hunk 1]
```diff
@@ -805,6 +805,55 @@ Dictionary OS_Unix::execute_with_pipe(const String &p_path, const List<String> &
...
+	}
+
+	int status = 0;
+	const int result = _wait_for_pid_completion(p_pid, &status, WNOHANG);
+	if (result == 0) {
+		// Thread is still running.
+		return true;
+	}
+
+	ERR_FAIL_COND_V_MSG(result == -1, false, vformat("Thread {} exited with errno: {}", p_pid, errno));
```
[the remark this answers is not in the document]
Comment (Ivorforce) [reply drivers/unix/os_unix.cpp]: Looks like I'm still sleeping 😄

**Review by bruvzg — APPROVED** [review]
Tested on macOS (with `lldb`) and Linux (with `lldb` and `gdb`) all methods seems to work as expected.

**Comment by Repiteo** [comment]
Thanks!
