### ISSUE TITLE
Building master on macOS 10.14 fails

### ISSUE THREAD

**Issue by asmaloney** [godotengine/godot#60872]
### Godot version

563690347a6b9da4882bca15ebd9f3d79f30d3e6

### System information

macOS 10.14.6

### Issue description

Build fails on AVSpeechSynthesis.h incude:
```
In file included from platform/osx/tts_osx.mm:31:
platform/osx/tts_osx.h:40:10: fatal error: 'AVFAudio/AVSpeechSynthesis.h' file not found
#include <AVFAudio/AVSpeechSynthesis.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I didn't see on the [Compiling for macOS](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_macos.html#requirements) page what versions of macOS are supported. It looks like it's supposed to support 10.12+ given that it outputs this on build:

```
Building for macOS 10.12+, platform x86_64.
```

### Steps to reproduce

Using the following build arguments:

```
platform=osx arch=x86_64 target=debug dev=yes use_llvm=yes  tools=yes --jobs=$(sysctl -n hw.logicalcpu) 
```

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
Strange, [AVSpeechSynthesis](https://developer.apple.com/documentation/avfaudio/avspeechsynthesizer?language=objc) should be available on 10.14, check your Xcode/SDK versions.

> It looks like it's supposed to support 10.12+

It might run on older versions, but won't compile without 10.15 SDK. And Vulkan backend most likely won't fully work on anything older than 10.15.

**Comment by asmaloney** [comment]
Thanks @bruvzg.

> check your Xcode/SDK versions

I have the last version that works on 10.14.6 which is Xcode 11.3.1/MacOSX10.15.sdk.

> And Vulkan backend most likely won't fully work on anything older than 10.15.

You mean in general? I use Vulkan to run Guild Wars 2 w/DX11 through wine, so it does work. Or do you mean because of something specific in Godot? (I have built and run master many months ago - just wanted to look at it again.)

**Comment by asmaloney** [comment]
Confirm that this fixes the build. 👍 

Thank you.
