### ISSUE TITLE
Cyclic reference works in 3.0 but fails in 3.1

### ISSUE THREAD

**Issue by hpvb** [godotengine/godot#26119]
**Godot version:**
3.1-beta5

**Issue description:**
When importing the attached project in 3.1-beta5 a cyclic error is reported:
```
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error.
```
This used to work in 3.0

I'm marking this as 'high priority' as this is a pretty common pattern and is a pretty big break between 3.0 and 3.1. 

**Steps to reproduce:**
Load the project.

**Minimal reproduction project:**
[Minimal reproduction project](https://tmm.cx/nextcloud/s/3zNmffqm5HdPMqZ)

**Comment by akien-mga** [comment]
For the reference, it's already failing as early as 3.1 alpha 1.

**Comment by Zylann** [comment]
How does it happen? I remember often having this error just by opening my plugin project, which never had such cyclic reference in the past. The only clue I had once was to close all open scripts, which made the error go away

**Comment by akien-mga** [comment]
Here's how it happens in the MRP, basically two scripts preloading each other:

**Node2D.gd** (attached to scene)
```
extends Node2D

const Util = preload("res://utils.gd")

func _ready():
        var thing = Util.Thing.new()

        thing.do_thing()
```
**utils.gd**
```gdscript
const Thing = preload("res://thing.gd")
```
**thing.gd**
```gdscript
extends Node

const Utils = preload("res://utils.gd")

func do_thing():
        print("Blah")
```

**Comment by Zylann** [comment]
Uh, strange. I already convinced myself not to do this in my plugin, yet users still report the error sometimes.

**Comment by groud** [comment]
Related to #22673

**Comment by reduz** [comment]
Sorry, cyclic refereces should not work. Maybe they did before but they were never meant to be. This is broken and can also cause leaks.

**Comment by akien-mga** [comment]
@Calinou Can you add a mention to this compat breakage in the changelog?

**Comment by Calinou** [comment]
@akien-mga Done :slightly_smiling_face:
