### ISSUE TITLE
Cryptic error with shader in 3.4 beta

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#51598]
### Godot version

3.4.beta3

### System information

Manjaro Linux

### Issue description

I am trying to see how a project will work in 3.4, but I get a shader parsing error when I run it. The shader is from [this sky addon](https://github.com/7leodev/TimeOfDay).

Here's the shader: https://gist.github.com/andersmmg/21241bd3f4e0a78945b860635f341897
Here's the error:
```
ERROR: SceneShaderGLES3: Vertex Program Compilation Failed:
0:426(2): error: `frag_to_light' undeclared
0:426(2): error: type mismatch
0:426(2): error: value of type vec3 cannot be assigned to variable of type error

   at: _display_error_with_code (drivers/gles3/shader_gles3.cpp:156)
ERROR: Method failed. Returning: nullptr
   at: get_current_version (drivers/gles3/shader_gles3.cpp:331)
ERROR: Condition "!version" is true. Returned: false
   at: bind (drivers/gles3/shader_gles3.cpp:118)
ERROR: Condition "!version" is true. Returned: -1
   at: _get_uniform (drivers/gles3/shader_gles3.h:362)
```

### Steps to reproduce

You can just run the project from GitHub and it has the same issue.

**Comment by clayjohn** [comment]
Cc @Chaosus

**Comment by andersmmg** [comment]
Tested on the new 3.4.beta.4, works as expected!
