### ISSUE TITLE
C# System.Linq on Godot.Collections.Array broken in v3.2-beta6-mono_x11.64

### ISSUE THREAD

**Issue by geoffder** [godotengine/godot#35182]
**Godot version:**
Godot_v3.2-beta6_mono_x11.64

**OS/device including version:**
Ubuntu 19.04 x86_64

**Issue description:**
Error compiling project which builds fine in v3.1.2.

error CS1061: 'Array' does not contain a definition for 'Select' and no accessible extension method 'Select' accepting a first argument of type 'Array' could be found (are you missing a using directive or an assembly reference?)

**Steps to reproduce:**
1) using System.Linq
2) Attempt to use Linq functions e.g. .Select() to map over Godot.Collections.Array.

UPDATE:
Sorry, I'm new to trying out beta releases. I reverted the changes that were made to my project file and now it is compiling fine in beta6, but now Godot methods are not being found. I suppose the organization of the GodotSharp folder has changed?

**Comment by geoffder** [comment]
![image](https://user-images.githubusercontent.com/14910691/72489474-04667880-37c9-11ea-8bb6-84a4939f8d8a.png)

These are the changes made to the C# project on loading it in beta6. Reverting these allows it to compile, but the game crashes the moment any Godot function is called from the C# scripts.

**Comment by akien-mga** [comment]
Can you provide a project that reproduces the issue?

**Comment by neikeq** [comment]
I cannot reproduce this either with 3.2 RC2.

**Comment by neikeq** [comment]
Also those changes made to the csproj are expected. You shouldn't revert them.
In my test, `Select` worked as expected.
If you can still reproduce the issue, please upload an example project. I'm moving this to the next milestone for now.

**Comment by geoffder** [comment]
Sorry I took a bit to get back, I've come back to beta6 and I see now that the problem is not assembly linking Linq, it is using Linq on a Godot.Collections.Array. 

In the current stable release it is possible to use Linq.Select / .Any / etc on Godot Arrays, but now these functions don't seem to be implemented anymore. Is this intentional? I found the functionality very convenient.

**Comment by geoffder** [comment]
I can confirm now that replacing the Godot.Collection.Array Linq usage allows my game to run as before under beta6. Sorry for the confusion! Do you anticipate that this issue will be gone for the next release? Or should I just plan to use my non-Linq solutions going forward?

Thank-you / sorry for your wasted time on this issue!

**Comment by raulsntos** [comment]
`Godot.Collections.Array` implements `System.Collections.IEnumerable` not the generic `System.Collections.Generic.IEnumerable<T>` so you can't use Linq with that, but you can use [`Cast<T>()`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.cast) or [`OfType<T>()`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.oftype) on `IEnumerable` to convert it into `IEnumerable<T>` like this:
```csharp
IEnumerable<Node> children = GetChildren().Cast<Node>();
IEnumerable<Label> labels = GetChildren().OfType<Label>();
```
Then you can use Linq on the result.
If you use `Cast<T>` make sure all elements are compatible with `T`, otherwise you will get `System.InvalidCastException`, to avoid this you could use `OfType<T>` instead so if there aren't any compatible elements with type `T` it will return an empty array and no Exceptions.

In 3.1 `Array` implemented `IEnumerable<object>` but it got removed in 92b02cb027a5f87b7ebe069ed1ba7648b6db19bd as part of PR #26662 and now it only implements the non-generic `IList` (which implements `IEnumerable`) and `IDisposable`
https://github.com/godotengine/godot/blob/baf5eaadb0bc7385b80181d9018b33be700c9c30/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs#L31

**Comment by geoffder** [comment]
Thank-you at @raulsntos , that clears it up for me!
