### ISSUE TITLE
-Wmaybe-uninitialized build error in modules/basis_universal/register_types.cpp

### ISSUE THREAD

**Issue by quantmint** [godotengine/godot#37461]
**Godot version:**
4.0.dev
**OS/device including version:**
intel 2600k arch linux
**Issue description:**
Can't compile with gcc 9.3.0.
```
[Initial build] Compiling ==> thirdparty/assimp/code/Common/ImporterRegistry.cpp
[Initial build] Compiling ==> thirdparty/assimp/code/Common/PostStepRegistry.cpp
modules/basis_universal/register_types.cpp: In function 'Vector<unsigned char> basis_universal_packer(const Ref<Image>&, Image::UsedChannels)':
modules/basis_universal/register_types.cpp:145:10: error: 'decompress_format' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  145 |    *decf = decompress_format;
      |    ~~~~~~^~~~~~~~~~~~~~~~~~~
[Initial build] Compiling ==> thirdparty/assimp/code/Common/RemoveComments.cpp
cc1plus: all warnings being treated as errors
scons: *** [modules/basis_universal/register_types.linuxbsd.opt.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
>  4.0.dev

Please give the exact commit hash.

**Comment by quantmint** [comment]
The commit hash is: 047cdea7fa
The build command is:
scons platform=linuxbsd target=release_debug -j9.
I am using the godot-git aur.
