### ISSUE TITLE
Can't compile debug template on latest master

### ISSUE THREAD

**Issue by somebody1121** [godotengine/godot#69663]
### Godot version

v4.0.beta.custom_build [43e9ca40f]

### System information

Manjaro Linux

### Issue description

Fails to compile with:

`scene/debugger/scene_debugger.cpp: In static member function 'static void SceneDebugger::_save_node(ObjectID, const String&)':
scene/debugger/scene_debugger.cpp:224:28: error: 'class Node' has no member named 'duplicate_from_editor'
  224 |         Node *copy = node->duplicate_from_editor(duplimap);
      |                            ^~~~~~~~~~~~~~~~~~~~~
`

### Steps to reproduce

just compile with  `scons target=template_debug arch=x86_64 -j "$(nproc)"`

### Minimal reproduction project

Not needed

**Comment by bruvzg** [comment]
Regression from #65228, should be fixed by #69658.
