### PR TITLE
[TextServer] Ensure that built-in library headers are always included before system header, add HarfBuzz version checks for optional features.

### LINKED ISSUE #63658: Build failing on Fedora (modules/text_server_adv/text_server_adv.cpp:1362: error: 'hb_font_set_synthetic_slant' was not declared in this scope)
### Godot version

4.0 ( 9094262 )

### System information

Fedora Linux 35 (Workstation Edition)

### Issue description

After following the instructions from the [documentation](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html#doc-compiling-for-linuxbsd) (using the "one liner" for Fedora), calling `scons` ends with the following error message:
```
modules/text_server_adv/text_server_adv.cpp: In member function 'bool TextServerAdvanced::_ensure_cache_for_size(TextServerAdvanced::FontAdvanced*, const Vector2i&) const':
modules/text_server_adv/text_server_adv.cpp:1362: error: 'hb_font_set_synthetic_slant' was not declared in this scope
 1362 |                 hb_font_set_synthetic_slant(fd->hb_handle, p_font_data->transform[0][1]);
      | 
```
I verified that all requirements are met and have sufficient versions.
After doing some research of my own, it looks to me like this function should be declared in the scope (its included through `hb.h` and `text_server_adv.h`). I'd expect Godot to compile without any issues after following documentation and I'm not sure what could be causing this error.

### Steps to reproduce

Clone the repository and follow the steps laid out in the documentation for compiling on Linux.

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by bruvzg**
- Changes `Append` to `Prepend`, to ensure built-in headers are always included first.
- Adds compile time checks for non-important HarfBuzz features to allow building with older version of system HarfBuzz , should work with version 1.7.2+ (Ubuntu 18.04 LTS).

Fixes #63658

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!
