### PR TITLE
Fix GLES3 scene shader int literal type errors for WebGL

### LINKED ISSUE #118684: Web export: GLES3 scene forward fragment shader fails to compile on WebGL 2.0 (ANGLE)
### Tested versions

- Reproducible in: 4.7.dev [a8643700ce8affae9fed0d2688b9f7867f5b7d4e]

### System information

Godot v4.7.dev (a8643700c) - Windows 11 (build 26200) - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 5070 (NVIDIA; 32.0.15.9602) - AMD Ryzen 9 9900X 12-Core Processor (24 threads) - 61.66 GiB memory

### Issue description

GLES3 scene forward fragment shader compilation fails when running web export in Chrome with WebGL 2.0 backend.
 The error occurs due to mixed int/float type operations that desktop OpenGL drivers accept through implicit
conversion, but WebGL 2.0 (ANGLE) strictly rejects according to GLSL ES 3.00 specification.

Image

### Steps to reproduce

1. Create any Godot 4.7 project with Compatibility renderer (uses WebGL 2.0 by default)
2. Export to Web with default settings
3. Run in Chrome browser (uses ANGLE for WebGL)
4. Open Developer Tools console to see the shader compilation errors
5. The browser may display a black/broken screen due to failed shader compilation

### Minimal reproduction project (MRP)

- [mcp-shader-error.zip](https://github.com/user-attachments/files/26828361/mcp-shader-error.zip)
- https://shiena.github.io/mcp-shader-error/

### PR DESCRIPTION
**Pull request by shiena**
Fixes #118684.

GLSL ES 3.00 (WebGL 2.0 / ANGLE) strictly enforces type compatibility and does not allow implicit conversion between `int` and `float`, unlike desktop OpenGL drivers. Integer literals (`0`) in comparison operators and `max()` in the scene forward fragment shader caused compilation to fail on Chrome.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
