### PR TITLE
C#/Mono fixes and enhancements

### LINKED ISSUE #13355: Mono build for macOS hardcodes mono version for the framework lookup, prevents loading with different but compatible version
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacBook Air on HighSierra (OSX 10.13.1)
Godot 3.0 alpha2-mono

**Issue description:**
Unpacked the mono zip and ran the executable but nothing happened. 

Note: Godot 3.0 alpha2 NON-mono build works fine.
I also already had the most recent version of mono installed because of MonoGame.

**Steps to reproduce:**
1. Download Godot 3.0 alpha2-mono on OSX High Sierra
2. Try to start the app

Please let me know if there's anything I can do to debug this issue. :)

### LINKED ISSUE #21139: Build fails if sub-directory under 'modules/mono/glue/cs_files' contains special characters
**Godot version:**

`master` / c93888ae

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
The current master branch fails to build due to compilation errors in _cs_compressed.gen.h_ as shown below:

```
In file included from modules/mono/editor/bindings_generator.cpp:43:
modules/mono/editor/../glue/cs_compressed.gen.h:132:18: error: default initialization of an object of const type 'const int'
static const int _cs_Godot API_Properties_AssemblyInfo_compressed_size = 627;
                 ^
                           = 0                                                                                                                                                              
modules/mono/editor/../glue/cs_compressed.gen.h:132:27: error: expected ';' after top level declarator
static const int _cs_Godot API_Properties_AssemblyInfo_compressed_size = 627;
                          ^
                          ;
modules/mono/editor/../glue/cs_compressed.gen.h:133:18: error: redefinition of '_cs_Godot'
static const int _cs_Godot API_Properties_AssemblyInfo_uncompressed_size = 1355;
                 ^
modules/mono/editor/../glue/cs_compressed.gen.h:132:18: note: previous definition is here
static const int _cs_Godot API_Properties_AssemblyInfo_compressed_size = 627;
                 ^
modules/mono/editor/../glue/cs_compressed.gen.h:133:27: error: expected ';' after top level declarator
static const int _cs_Godot API_Properties_AssemblyInfo_uncompressed_size = 1355;
                          ^
                          ;
modules/mono/editor/../glue/cs_compressed.gen.h:134:28: error: redefinition of '_cs_Godot' with a different type: 'const unsigned char' vs 'const int'
static const unsigned char _cs_Godot API_Properties_AssemblyInfo_compressed[] = { 120, 156, 133, 84, 75, 110, 26, 65, 16, 221, 115, 138, 18, 27, 19, 43, 96, 76, 140, 228, 207, 10, ...
                           ^
modules/mono/editor/../glue/cs_compressed.gen.h:132:18: note: previous definition is here
static const int _cs_Godot API_Properties_AssemblyInfo_compressed_size = 627;
                 ^
modules/mono/editor/../glue/cs_compressed.gen.h:134:37: error: expected ';' after top level declarator
static const unsigned char _cs_Godot API_Properties_AssemblyInfo_compressed[] = { 120, 156, 133, 84, 75, 110, 26, 65, 16, 221, 115, 138, 18, 27, 19, 43, 96, 76, 140, 228, 207, 10, ...
                                    ^
                                    ;
modules/mono/editor/../glue/cs_compressed.gen.h:187:82: error: expected ')'
        r_files.insert("Godot API/Properties/AssemblyInfo.cs", CompressedFile(_cs_Godot API_Properties_AssemblyInfo_compressed_size, _cs_Godot API_Properties_AssemblyInfo_uncompres...
                                                                                        ^
modules/mono/editor/../glue/cs_compressed.gen.h:187:71: note: to match this '('
        r_files.insert("Godot API/Properties/AssemblyInfo.cs", CompressedFile(_cs_Godot API_Properties_AssemblyInfo_compressed_size, _cs_Godot API_Properties_AssemblyInfo_uncompres...
                                                                             ^
modules/mono/editor/../glue/cs_compressed.gen.h:187:57: error: no matching conversion for functional-style cast from 'const int' to 'CompressedFile'
        r_files.insert("Godot API/Properties/AssemblyInfo.cs", CompressedFile(_cs_Godot API_Properties_AssemblyInfo_compressed_size, _cs_Godot API_Properties_AssemblyInfo_uncompres...
                                                               ^~~~~~~~~~~~~~~~~~~~~~~~
modules/mono/editor/../glue/cs_compressed.gen.h:138:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const int' to
      'const CompressedFile' for 1st argument
struct CompressedFile
       ^
modules/mono/editor/../glue/cs_compressed.gen.h:138:8: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'const int' to 'CompressedFile' for
      1st argument
struct CompressedFile
       ^
modules/mono/editor/../glue/cs_compressed.gen.h:151:2: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
        CompressedFile() {}
        ^
modules/mono/editor/../glue/cs_compressed.gen.h:144:2: note: candidate constructor not viable: requires 3 arguments, but 1 was provided
        CompressedFile(int p_comp_size, int p_uncomp_size, const unsigned char* p_data)
        ^
[ 29%] 8 errors generated.
```
(@neikeq Could it be possible that it was caused by 72873004332b?)

### LINKED ISSUE #21667: MonoGCHandles for resources being released
**Godot version:**
3.1 Alpha 1

**OS/device including version:**
Windows 10

**Issue description:**
I ran into a bug in my game where `ResourceLoader.Load()` was returning null, but the `--verbose` log and lack of any errors (outside of my code dying on a nullref) were indicating it was fine. After compiling with debug symbols, it seems that the packed scene `MonoGCHandle`s were being released, causing the code to bail out and return a null reference when passing the packed scene resources up to my C# code.

I wasn't even touching the related code when this started breaking and, being seemingly GC related, it's pretty inconsistent to reproduce. I also doubt I'll be able to easily make a reproduction project, but Neikeq told me to make an issue so here it is.

I'm still gonna try to do some experimenting myself.

Relevant code in my project it's dying on, but it's not that useful:
```cs
protected static Godot.Control LoadScene(string path)
{
    var res = (Godot.PackedScene)Godot.ResourceLoader.Load(path);
    return (Godot.Control)res.Instance();
}
```

My theory is that it's only for the "used once then managed instance forgotten" resources like `PackedScene`. In fact that's the only case in my project I can think of where I use the objects like that.

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #21139
Fixes #13355
Fixes #21667

### CODE REVIEW

**Comment by aaronfranke** [comment]
Throws [hundreds of errors](https://pastebin.com/3jVX43Mq) when I try to compile master with Mono enabled now...

**Comment by neikeq** [comment]
Ahhh! I can't believe I forgot to mention this... This PR introduces an intentional build regression. If the file `mono_glue.gen.cpp` was generated before the changes in b1356a3590ad1a4ed7bc4f85e1ffe7e9776855c3, you will have to delete it manually. The reason is that now `mono_glue.gen.cpp` is compiled even when passing `mono_glue=no`. The newly generated file is surrounded with `#ifdef MONO_GLUE_ENABLED` so it's not a problem, but old files don't have that.

**Comment by aaronfranke** [comment]
Deleting that file worked. This may confuse many people though...

**Comment by malbach** [comment]
Hi,
Even after deleting everything "generated", I still have 2 errors : 

> ...\csharp_script.cpp(1466) : error C4716: 'CSharpInstance::mono_object_disposed' : doit retourner une valeur
> ...\csharp_script.cpp(1489) : error C4716: 'CSharpInstance::mono_object_disposed_baseref' : doit retourner une valeur

Compiling one Win10 x64 with VS2015
Those two functions are now `bool` but without any `return`, is it intentional ?

**Comment by neikeq** [comment]
No, those methods shouldn't return anything. I changed it and forgot to revert the changes.

**Comment by neikeq** [comment]
Fixed the return type build regression: 5e57beebb1a43c65d949fdfe5081f9c27f181c80
