### ISSUE TITLE
Compiling for Mingw fails (Audio Driver)

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#18046]
**Godot version:**
master

**OS/device including version:**
Antergos OS (Arch Linux)

**Issue description:**
Compiling for Mingw fails after recent pull (maybe https://github.com/godotengine/godot/commit/1570a72eee4bc0efb46cc2185c44a12a0aa57943 ?)

**Steps to reproduce:**
scons p=windows bits=64 tools=no target=release -j 8

**Error Output:**
```Swift
[ 72%] Compiling ==> drivers/gles3/shader_compiler_gles3.cpp
[ 72%] Linking Static Library ==> modules/libmodules.windows.opt.debug.64.a
drivers/wasapi/audio_driver_wasapi.cpp: In member function 'Error AudioDriverWASAPI::init_device(bool)':
drivers/wasapi/audio_driver_wasapi.cpp:154:25: error: 'PKEY_Device_FriendlyName' was not declared in this scope
    hr = props->GetValue(PKEY_Device_FriendlyName, &propvar);
                         ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/wasapi/audio_driver_wasapi.cpp: In member function 'virtual Array AudioDriverWASAPI::get_device_list()':
drivers/wasapi/audio_driver_wasapi.cpp:386:24: error: 'PKEY_Device_FriendlyName' was not declared in this scope
   hr = props->GetValue(PKEY_Device_FriendlyName, &propvar);
                        ^~~~~~~~~~~~~~~~~~~~~~~~
[ 73%] Compiling ==> drivers/gles3/rasterizer_scene_gles3.cpp
[ 73%] Compiling ==> drivers/gles2/rasterizer_canvas_gles2.cpp
scons: *** [drivers/wasapi/audio_driver_wasapi.windows.opt.debug.64.o] Error 1
Ranlib Library         ==> modules/libmodules.windows.opt.debug.64.a
scons: building terminated because of errors.
```

**Comment by vnen** [comment]
Cc @marcelofg55

**Comment by bruvzg** [comment]
I can confirm this on Debian, MinGW-w64 5.0.1-1. Probably define is missing from MinGW headers, here's how same key defined manually in OBS Studio for example: [enum-wasapi.hpp#L9-L24](https://github.com/obsproject/obs-studio/blob/master/plugins/win-wasapi/enum-wasapi.hpp#L9-L24)

**Comment by marcelofg55** [comment]
Let me know if compiling works fine after #18047, it compiled here using mingw-w64 on Ubuntu. I had to use `module_etc_enabled=no module_mbedtls_enabled=no` to compile it though, but maybe it's my mingw-w64 installation (not a mingw expert myself).

**Comment by bruvzg** [comment]
> Let me know if compiling works fine after #18047

With #18047 it compiles on Debian, MinGW-w64 5.0.1-1 (no modules disabled, build command: `scons -j8 p=windows bits=64 tools=no target=release `)
