### PR TITLE
Fix compiling Godot 2.1.x on macOS 15/Xcode 16

### LINKED ISSUE #101035: Godot 2.1 - Engine compilation errors on macOS 15/Xcode 16
### Tested versions

- Reproducible in 2.1.7.rc.custom_build [0919ee6], 2.1.7.rc.custom_build [7cef81b]

### System information

macOS 15/Xcode 16 - Mac Mini (Intel i7), MacBook Air (M1)

### Issue description

When compiling Godot 2.1 using macOS 15/Xcode 16, the 'Byte' type is not found by FreeType 1.8.1's included gzip.

The issue is not present on macOS 12/Xcode 14.

```
In file included from thirdparty/freetype/src/gzip/ftgzip.c:77:
In file included from thirdparty/freetype/src/gzip/zlib.h:34:
thirdparty/freetype/src/gzip/ftzconf.h:228:12: error: unknown type name 'Byte'
  228 |    typedef Byte  FAR Bytef;
      |            ^
In file included from thirdparty/freetype/src/gzip/ftgzip.c:95:
thirdparty/freetype/src/gzip/inftrees.h:22:7: error: unknown type name 'Byte'
   22 |       Byte Exop;        /* number of extra bits or operation */
      |       ^
thirdparty/freetype/src/gzip/inftrees.h:23:7: error: unknown type name 'Byte'
   23 |       Byte Bits;        /* number of bits in this code or subcode */
      |       ^
In file included from thirdparty/freetype/src/gzip/ftgzip.c:103:
thirdparty/freetype/src/gzip/inftrees.c:247:21: error: use of undeclared identifier 'Byte'
  247 |           r.bits = (Byte)l;     /* bits to dump before this table */
      |                     ^
thirdparty/freetype/src/gzip/inftrees.c:248:21: error: use of undeclared identifier 'Byte'
  248 |           r.exop = (Byte)j;     /* bits in this table */
      |                     ^
thirdparty/freetype/src/gzip/inftrees.c:258:17: error: use of undeclared identifier 'Byte'
  258 |       r.bits = (Byte)(k - w);
      |                 ^
thirdparty/freetype/src/gzip/inftrees.c:263:19: error: use of undeclared identifier 'Byte'
  263 |         r.exop = (Byte)(*p < 256 ? 0 : 32 + 64);     /* 256 is end-of-block */
      |                   ^
thirdparty/freetype/src/gzip/inftrees.c:268:19: error: use of undeclared identifier 'Byte'
  268 |         r.exop = (Byte)(e[*p - s] + 16 + 64);/* non-simple--look up in lists */
      |                   ^
In file included from thirdparty/freetype/src/gzip/ftgzip.c:105:
thirdparty/freetype/src/gzip/infcodes.c:50:3: error: unknown type name 'Byte'
   50 |   Byte lbits;           /* ltree bits decoded per branch */
      |   ^
thirdparty/freetype/src/gzip/infcodes.c:51:3: error: unknown type name 'Byte'
   51 |   Byte dbits;           /* dtree bits decoder per branch */
      |   ^
thirdparty/freetype/src/gzip/infcodes.c:70:17: error: use of undeclared identifier 'Byte'
   70 |     c->lbits = (Byte)bl;
      |                 ^
thirdparty/freetype/src/gzip/infcodes.c:71:17: error: use of undeclared identifier 'Byte'
   71 |     c->dbits = (Byte)bd;
      |                 ^
thirdparty/freetype/src/gzip/infcodes.c:204:9: error: use of undeclared identifier 'Byte'
  204 |         OUTBYTE(*f++)
      |         ^
thirdparty/freetype/src/gzip/infutil.h:83:27: note: expanded from macro 'OUTBYTE'
   83 | #define OUTBYTE(a) {*q++=(Byte)(a);m--;}
      |                           ^
In file included from thirdparty/freetype/src/gzip/ftgzip.c:105:
thirdparty/freetype/src/gzip/infcodes.c:213:7: error: use of undeclared identifier 'Byte'
  213 |       OUTBYTE(c->sub.lit)
      |       ^
thirdparty/freetype/src/gzip/infutil.h:83:27: note: expanded from macro 'OUTBYTE'
   83 | #define OUTBYTE(a) {*q++=(Byte)(a);m--;}
      |                           ^
14 errors generated.
scons: *** [thirdparty/freetype/src/gzip/ftgzip.osx.opt.tools.64.o] Error 1
```

### Steps to reproduce

Compile the Godot Engine (2.1.x) on macOS 15/Xcode 16.

```
scons platform=osx tools=yes target=release_debug
```

### Minimal reproduction project (MRP)

Godot 2.1.x source: https://github.com/godotengine/godot/tree/2.1

### PR DESCRIPTION
**Pull request by bherdm**
Updated a line in the included FreeType 1.8.1 from FreeType 1.12.0+ to be compatible with Xcode 16. Fixes: https://github.com/godotengine/godot/issues/101035

### CODE REVIEW

**Comment by AThousandShips** [comment]
Thank you for your contribution 

Godot 2.x is no longer supported, we do not accept general contributions to it

**Comment by bherdm** [comment]
Thank you for the response. Is there a way to submit this fix? Should this be a proposal? Or let it go? I'm very new to contributing, I apologize. I'm stuck on 2.1 to support Android API 18 for the OUYA.On Jan 2, 2025, at 11:37 AM, A Thousand Ships ***@***.***> wrote:﻿
Thank you for your contribution
Godot 2.x is no longer supported, we do not accept general contributions to it

**Comment by AThousandShips** [comment]
You can always just fix this in your own fork

Though I'd be interested in why you would be using 2.1, it was discontinued a long time ago, last release was 8 years ago

**Comment by akien-mga** [comment]
> Thank you for your contribution
> 
> Godot 2.x is no longer supported, we do not accept general contributions to it

Not supported doesn't mean we don't accept contributions for it though. But it's not a priority for sure.

In particular contributions to ensure that the code can still build on modern toolchains are quite valuable IMO for game preservation, so that's very welcome.

**Comment by akien-mga** [comment]
The fix seems fine, but is it really sufficient to build Godot on modern macOS? I don't have a system to test but at least here on Linux, I have other issues related to the Python version. Are you using an older Python 3, or Python 2?

**Comment by bherdm** [comment]
> You can always just fix this in your own fork
> 
> Though I'd be interested in why you would be using 2.1, it was discontinued a long time ago, last release was 8 years ago

I have! Just hoped I'd finally be able to contribute something back.

The OUYA needs OpenGL 2 and Android API 16. Support for those never co-exist in Godot 3. I've tried to lower the minimum Android SDK in Godot 3 with no success.

**Comment by AThousandShips** [comment]
That's an interesting use case! Thank you for the details

**Comment by bherdm** [comment]
> The fix seems fine, but is it really sufficient to build Godot 2.1 on modern macOS? I don't have a system to test but at least here on Linux, I have other issues related to the Python version. Are you using an older Python 3, or Python 2?

Yup! Works fine here. I'm using Python 2.7.18. I usually use SCons 2.5.1 for godot-for-ouya, but it seems to work fine in SCons 4.8 too. I've tested building with this change on three modern Macs running macOS 15/Xcode 16 and one older Mac running macOS 12/Xcode 14.

**Comment by akien-mga** [comment]
Interesting, for me (on Linux with osxcross, SCons 4.8.1 and Python 3.13.0) I first run into this issue:
```
# scons p=osx osxcross_sdk=darwin24.2
scons: Reading SConscript files ...
ModuleNotFoundError: No module named 'distutils':
  File "/root/godot/SConstruct", line 33:
    import detect
  File "/root/godot/platform/android/detect.py", line 5:
    from distutils.version import LooseVersion
```

After fixing it (I've backported a similar fix in `3.2` and later too recently), I get:
```
# scons p=osx osxcross_sdk=darwin24.2
scons: Reading SConscript files ...
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
Package 'x11' not found
X11 not found.. x11 disabled.
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling ==> platform/osx/crash_handler_osx.mm
In file included from platform/osx/crash_handler_osx.mm:31:
In file included from ./main/main.h:38:
In file included from ./core/os/thread.h:39:
In file included from core/ustring.h:36:
In file included from core/vector.h:40:
In file included from core/os/memory.h:36:
core/safe_refcount.h:40:39: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   40 | uint32_t atomic_conditional_increment(register uint32_t *counter);
      |                                       ^~~~~~~~
core/safe_refcount.h:41:27: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   41 | uint32_t atomic_decrement(register uint32_t *pw);
      |                           ^~~~~~~~
core/safe_refcount.h:42:27: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   42 | uint32_t atomic_increment(register uint32_t *pw);
      |                           ^~~~~~~~
core/safe_refcount.h:43:21: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   43 | uint32_t atomic_sub(register uint32_t *pw, register uint32_t val);
      |                     ^~~~~~~~
core/safe_refcount.h:43:44: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   43 | uint32_t atomic_sub(register uint32_t *pw, register uint32_t val);
      |                                            ^~~~~~~~
core/safe_refcount.h:44:21: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   44 | uint32_t atomic_add(register uint32_t *pw, register uint32_t val);
      |                     ^~~~~~~~
core/safe_refcount.h:44:44: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   44 | uint32_t atomic_add(register uint32_t *pw, register uint32_t val);
      |                                            ^~~~~~~~
core/safe_refcount.h:45:37: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   45 | uint32_t atomic_exchange_if_greater(register uint32_t *pw, register uint32_t val);
      |                                     ^~~~~~~~
core/safe_refcount.h:45:60: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   45 | uint32_t atomic_exchange_if_greater(register uint32_t *pw, register uint32_t val);
      |                                                            ^~~~~~~~
core/safe_refcount.h:47:39: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   47 | uint64_t atomic_conditional_increment(register uint64_t *counter);
      |                                       ^~~~~~~~
core/safe_refcount.h:48:27: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   48 | uint64_t atomic_decrement(register uint64_t *pw);
      |                           ^~~~~~~~
core/safe_refcount.h:49:27: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   49 | uint64_t atomic_increment(register uint64_t *pw);
      |                           ^~~~~~~~
core/safe_refcount.h:50:21: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   50 | uint64_t atomic_sub(register uint64_t *pw, register uint64_t val);
      |                     ^~~~~~~~
core/safe_refcount.h:50:44: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   50 | uint64_t atomic_sub(register uint64_t *pw, register uint64_t val);
      |                                            ^~~~~~~~
core/safe_refcount.h:51:21: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   51 | uint64_t atomic_add(register uint64_t *pw, register uint64_t val);
      |                     ^~~~~~~~
core/safe_refcount.h:51:44: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   51 | uint64_t atomic_add(register uint64_t *pw, register uint64_t val);
      |                                            ^~~~~~~~
core/safe_refcount.h:52:37: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   52 | uint64_t atomic_exchange_if_greater(register uint64_t *pw, register uint64_t val);
      |                                     ^~~~~~~~
core/safe_refcount.h:52:60: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
   52 | uint64_t atomic_exchange_if_greater(register uint64_t *pw, register uint64_t val);
      |                                                            ^~~~~~~~
```

Doesn't Xcode 16 default to C++17 if unspecified, like osxcross/Apple Clang seems to do in my cross-compilation toolchain?

**Comment by bherdm** [comment]
> Interesting, for me (on Linux with osxcross, SCons 4.8.1 and Python 3.13.0) I first run into this issue:
> 
> ```
> # scons p=osx osxcross_sdk=darwin24.2
> scons: Reading SConscript files ...
> ModuleNotFoundError: No module named 'distutils':
>   File "/root/godot/SConstruct", line 33:
>     import detect
>   File "/root/godot/platform/android/detect.py", line 5:
>     from distutils.version import LooseVersion
> ```

I ran into that too! distutils was removed in Python 3.12. I tried adding distutils manually, but, eventually, switched to Python 2.7.18. I never saw that second issue.

I can't find an official doc that says so, but I've found a few posts on StackOverflow and forums that say Apple Clang defaults to C++98 if none is specified. Here's the latest post where I see that: https://forums.developer.apple.com/forums/thread/746509

**Comment by bherdm** [comment]
> The fix seems fine

Should I make this pull request 'Ready for review'?

**Comment by akien-mga** [comment]
I included your fix in #101040 so we can test and validate compatibility with modern toolchains all at once. Could you test that PR on macOS and confirm that it works fine?

Thanks for the contribution!
