### ISSUE TITLE
GLES2 Light 2D doesn't work.

### ISSUE THREAD

**Issue by 0nepixel** [godotengine/godot#21853]
Light2D node doesn't work on GLES2.
GODOT 3.1 masterbranch.
WINDOWS 7.
1-Add a new Node2D
2- add a new Sprite and set the texture.
3- add a new light2D and set the texture.
The light doesn't affect the sprite node (or any other texture node 2D).
On GLES3 the node work just fine, so i guess this is a GLES2 Bug.
![image](https://user-images.githubusercontent.com/22958303/45248376-58fd0800-b2e6-11e8-9150-72f778afa283.png)

**Comment by Mellondill** [comment]
the same behavior is applied for me on macOS.
Besides, there is and error:
0:00:00:0093 - Directional shadow framebuffer status invalid
----------
Type:Error
Description: 
Time: 0:00:00:0093
C Error: Directional shadow framebuffer status invalid
C Source: drivers/gles2/rasterizer_scene_gles2.cpp:2474
C Function: initialize

**Comment by kiidmale** [comment]
Any progress on this issue? I can confirm it’s still not working on 3.1 alpha2 :(

**Comment by hwangmaru** [comment]
aaa

**Comment by hwangmaru** [comment]
too late on this issue. why don't you fix it quickly?.  This issue is most important feature in 3.1 isn't it??

**Comment by akien-mga** [comment]
And 3.1 is not released yet, so please stay patient and let us work.

**Comment by kiidmale** [comment]
Still happening in alpha3.
After quick investigation, I found light_internal_* functions are not implemented yet in RasterizerCanvasGLES2 as below.
https://github.com/godotengine/godot/blob/aa819a85381dc256e4e1a59dd62d5da84346e3ea/drivers/gles2/rasterizer_canvas_gles2.cpp#L42-L51
I hope it will be fixed soon before beta since Light2D is not a nice-to-have feature.

**Comment by kiidmale** [comment]
Also attaching a simple reproducible project. (a sprite with normal map)
[light2d-gles2.zip](https://github.com/godotengine/godot/files/2695149/light2d-gles2.zip)

**Comment by aaschmitz** [comment]
Testing with https://github.com/godotengine/godot/commit/3bdd1ff3875450d90f7a695aa5d527a47558d80c the "lights_and_shadows" demo (from 2D demos folder) still not working, appears on the console:

E 0:00:01:0125   CanvasShaderGLES2: Fragment shader compilation failed:
0:54(9): error: illegal use of reserved word `lowp'
0:54(9): error: syntax error, unexpected ERROR_TOK, expecting BASIC_TYPE_TOK or STRUCT or VOID_TOK or TYPE_IDENTIFIER
<C Source>     drivers/gles2/shader_gles2.cpp:196 @ _display_error_with_code()
E 0:00:01:0125   Method/Function Failed, returning: __null
<C Source>     drivers/gles2/shader_gles2.cpp:426 @ get_current_version()
E 0:00:01:0125   Condition ' !version ' is true. returned: false
<C Source>     drivers/gles2/shader_gles2.cpp:133 @ bind()
E 0:00:01:0125   Condition ' !version ' is true. returned: -1
<C Source>     drivers/gles2/shader_gles2.h:524 @ _get_uniform()

**Comment by akien-mga** [comment]
That's a different issue, moved to #24521.
