### ISSUE TITLE
[3.x] Can't compile windows size-optimzed release template with LTO

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#112753]
### Tested versions

Reproducible:
- **3.x** a117d512b00f1646db174e703e7e888519b64608
- **3.6** da1b2b5d5727a63ff5e2a3a5a43c4c8b98dc64a0

Not Reproducible:
- **3.5** 8ec5e74eab66887589964bbd8723a3447d1d3a6f
- **3.4** cdeac0135350d95aa07a98388a45493a5950a8b4
- **3.3** a14db2f7450ec81ef40dd376150501ec5bee41eb

### System information

Ubuntu 24.04.3 LTS, g++ (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0

### Issue description

Tried to compile windows release-template in Ubuntu with command:
```console
scons platform=windows target=release lto=full tools=no debug_symbols=no optimize=size
```

Debug template compiles with a lot of warnings, but release template fails with errors:
```console
scons: Reading SConscript files ...
Auto-detected 16 CPU cores available for build parallelism. Using 15 cores by default. You can override it with the -j argument.
Configuring for Windows: target=release, bits=default
Using MinGW
Using LTO: full
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[ 98%] Linking Program        ==> bin/godot.windows.opt.64.exe
[100%] progress_finish(["progress_finish"], [])
during GIMPLE pass: alias
./drivers/gles_common/rasterizer_canvas_batcher.h: In member function '__ct ':
./drivers/gles_common/rasterizer_canvas_batcher.h:509:17: internal compiler error: in binds_to_current_def_p, at symtab.cc:2497
  509 |                 RenderItemState() { reset(); }
      |                 ^
0x75cb3322a1c9 __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x75cb3322a28a __libc_start_main_impl
        ../csu/libc-start.c:360
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [/tmp/ccWanW6P.mk:104: /tmp/ccRl4llw.ltrans34.ltrans.o] Error 1
make: *** Waiting for unfinished jobs....
during GIMPLE pass: dse
./core/class_db.h: In function 'bind_method.constprop.isra':
./core/class_db.h:227:28: internal compiler error: in binds_to_current_def_p, at symtab.cc:2497
  227 |         static MethodBind *bind_method(N p_method_name, M p_method) {
      |                            ^
0x785f9f02a1c9 __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x785f9f02a28a __libc_start_main_impl
        ../csu/libc-start.c:360
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [/tmp/ccWanW6P.mk:374: /tmp/ccRl4llw.ltrans124.ltrans.o] Error 1
during GIMPLE pass: dse
servers/physics/gjk_epa.cpp: In function 'Distance.constprop':
servers/physics/gjk_epa.cpp:899: internal compiler error: in binds_to_current_def_p, at symtab.cc:2497
  899 | bool Distance(  const ShapeSW*  shape0,
      | 
0x75019da2a1c9 __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x75019da2a28a __libc_start_main_impl
        ../csu/libc-start.c:360
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [/tmp/ccWanW6P.mk:359: /tmp/ccRl4llw.ltrans119.ltrans.o] Error 1
during GIMPLE pass: dse
servers/visual/visual_server_scene.cpp: In function 'render_empty_scene.isra':
servers/visual/visual_server_scene.cpp:3215: internal compiler error: in binds_to_current_def_p, at symtab.cc:2497
 3215 | void VisualServerScene::render_empty_scene(RID p_scenario, RID p_shadow_atlas) {
      | 
0x7e8a95a2a1c9 __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x7e8a95a2a28a __libc_start_main_impl
        ../csu/libc-start.c:360
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [/tmp/ccWanW6P.mk:380: /tmp/ccRl4llw.ltrans126.ltrans.o] Error 1
during GIMPLE pass: dse
drivers/png/png_driver_common.cpp: In function 'image_to_png.isra':
drivers/png/png_driver_common.cpp:126:7: internal compiler error: in binds_to_current_def_p, at symtab.cc:2497
  126 | Error image_to_png(const Ref<Image> &p_image, PoolVector<uint8_t> &p_buffer) {
      |       ^
0x6ffc8a62a1c9 __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x6ffc8a62a28a __libc_start_main_impl
        ../csu/libc-start.c:360
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [/tmp/ccWanW6P.mk:383: /tmp/ccRl4llw.ltrans127.ltrans.o] Error 1
during GIMPLE pass: dse
./core/list.h: In member function 'push_back.isra':
./core/list.h:209: internal compiler error: in binds_to_current_def_p, at symtab.cc:2497
  209 |         Element *push_back(const T &value) {
      | 
0x798819c2a1c9 __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x798819c2a28a __libc_start_main_impl
        ../csu/libc-start.c:360
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [/tmp/ccWanW6P.mk:377: /tmp/ccRl4llw.ltrans125.ltrans.o] Error 1
during GIMPLE pass: dse
./core/method_bind.gen.inc: In member function '_gen_argument_type_info':
./core/method_bind.gen.inc:2428: internal compiler error: in binds_to_current_def_p, at symtab.cc:2497
 2428 |         virtual PropertyInfo _gen_argument_type_info(int p_argument) const {
      | 
0x7fa3cc02a1c9 __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x7fa3cc02a28a __libc_start_main_impl
        ../csu/libc-start.c:360
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [/tmp/ccWanW6P.mk:344: /tmp/ccRl4llw.ltrans114.ltrans.o] Error 1
during GIMPLE pass: dse
modules/navigation/navigation_mesh_generator.cpp: In function '_build_recast_navigation_mesh.constprop':
modules/navigation/navigation_mesh_generator.cpp:503:6: internal compiler error: in binds_to_current_def_p, at symtab.cc:2497
  503 | void NavigationMeshGenerator::_build_recast_navigation_mesh(
      |      ^
0x726d83c2a1c9 __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x726d83c2a28a __libc_start_main_impl
        ../csu/libc-start.c:360
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [/tmp/ccWanW6P.mk:365: /tmp/ccRl4llw.ltrans121.ltrans.o] Error 1
during GIMPLE pass: dse
servers/physics_2d/collision_solver_2d_sat.cpp: In function '_collision_rectangle_convex_polygon':
servers/physics_2d/collision_solver_2d_sat.cpp:909: internal compiler error: in binds_to_current_def_p, at symtab.cc:2497
  909 | static void _collision_rectangle_convex_polygon(const Shape2DSW *p_a, const Transform2D &p_transform_a, const Shape2DSW *p_b, const Transform2D &p_transform_b, _CollectorCallback2D *p_collector, const Vector2 &p_motion_a, const Vector2 &p_motion_b, real_t p_margin_A, real_t p_margin_B) {
      | 
0x7a936262a1c9 __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x7a936262a28a __libc_start_main_impl
        ../csu/libc-start.c:360
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [/tmp/ccWanW6P.mk:311: /tmp/ccRl4llw.ltrans103.ltrans.o] Error 1
during GIMPLE pass: dse
./core/class_db.h: In function 'bind_method.constprop.isra':
./core/class_db.h:227:28: internal compiler error: in binds_to_current_def_p, at symtab.cc:2497
  227 |         static MethodBind *bind_method(N p_method_name, M p_method) {
      |                            ^
0x7914eaa2a1c9 __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x7914eaa2a28a __libc_start_main_impl
        ../csu/libc-start.c:360
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
make: *** [/tmp/ccWanW6P.mk:371: /tmp/ccRl4llw.ltrans123.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/x86_64-w64-mingw32-ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.opt.64.exe] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:28.625]
```

### Steps to reproduce

1. switch to 3.x upstream
```
git pull --rebase upstream 3.x
```
2. run command
```
scons platform=windows target=release lto=full tools=no debug_symbols=no optimize=size
```

### Minimal reproduction project (MRP)

n/a

**Comment by lawnjelly** [comment]
This is mostly @akien-mga / @Repiteo 's area as they make the builds.

Afaik an internal compiler error is reporting a compiler bug, rather than an engine bug _per se_. As I understand it, it may be _indirectly_ caused by a bug in the source code, but a compiler working correctly should never be reporting internal compiler errors.

The version of MinGW may be crucial, I gather we had to downgrade to a previous version because of a compiler bug. It will be worth mentioning which versions of all the toolchains you are using and checking they are as used in the official builds.

Especially note we moved to c++17 with 3.7, so there is no guarantee that a toolchain that worked with 3.5 will still work with 3.7.

If you can post a version of the debug template errors, that might be helpful.

**Comment by akien-mga** [comment]
Yes this is likely a GCC bug, which may be fixed in newer versions (you seem to have mingw-gcc 13.3.0).

We had no issue building Windows binaries with LTO for 3.6.2-stable and 3.7-dev1 using Fedora 43's mingw-gcc (MinGW 13.0.0 with GCC 15.2.1): https://github.com/godotengine/build-containers/tree/3.6?tab=readme-ov-file#toolchains
But we actually had a crashing build when compiling 3.6.2-stable with Fedora 42's mingw-gcc (MinGW 12.0.0 with GCC 14.2.1). Especially when using LTO, mingw-gcc versions can easily run into bugs with Godot's complex codebase.

Since you can't reproduce it in 3.5 and earlier, it does mean that a Godot change triggered the GCC bug, so bisecting it could also be useful to see if we can work it around. But otherwise the solution would likely be to update to the latest mingw-gcc.

**Comment by boruok** [comment]
The merge base 991bb6ac74ac8c09d7683041b50a8ced3a2defb1 is bad.
This means the bug has been fixed between 991bb6ac74ac8c09d7683041b50a8ced3a2defb1 and [8ec5e74eab66887589964bbd8723a3447d1d3a6f].

```console
# bad: [a117d512b00f1646db174e703e7e888519b64608] Merge pull request #112170 from lawnjelly/disallow_muting_android
git bisect bad a117d512b00f1646db174e703e7e888519b64608
# status: waiting for good commit(s), bad commit known
# good: [8ec5e74eab66887589964bbd8723a3447d1d3a6f] [Windows] Rename `PKEY_Device_FriendlyName` to avoid duplicate symbols with newer MinGW SDKs.
git bisect good 8ec5e74eab66887589964bbd8723a3447d1d3a6f
# bad: [991bb6ac74ac8c09d7683041b50a8ced3a2defb1] Bump version to 3.5-stable \o/
git bisect bad 991bb6ac74ac8c09d7683041b50a8ced3a2defb1
# bad: [991bb6ac74ac8c09d7683041b50a8ced3a2defb1] Bump version to 3.5-stable \o/
git bisect bad 991bb6ac74ac8c09d7683041b50a8ced3a2defb1
```

**Comment by lawnjelly** [comment]
Sounds like it is fixed in 3.x.
We can have a look whether we can cherry pick #99036 to 3.6 and 3.5.

Ah looks like Akien might have already done this. I'll double check.

Looks like it is present in 3.5 and 3.6 currently...

It looks to have been cherry picked individually to 3.6 5 months ago, and there was a delay cherry picking to 3.x. So I'm not sure why you got the build failure on 3.6.

**Comment by boruok** [comment]
no luck with fresh installed Fedora Linux 43 (Workstation Edition) too.

```console
boruok@localhost-live:~/godot$ scons platform=windows target=release lto=full tools=no debug_symbols=no optimize=size -j6
scons: Reading SConscript files ...
Configuring for Windows: target=release, bits=default
Using MinGW
Using LTO: full
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[ 96%] Linking Program        ==> bin/godot.windows.opt.64.exe
[ 99%] progress_finish(["progress_finish"], [])
[100%] during GIMPLE pass: dse
core/translation.h: In member function '__dt ':
core/translation.h:99:16: internal compiler error: in binds_to_current_def_p, at symtab.cc:2598
   99 |         struct LocaleScriptInfo {
      |                ^
during GIMPLE pass: alias
servers/physics_2d/joints_2d_sw.cpp: In member function 'setup':
servers/physics_2d/joints_2d_sw.cpp:91:6: internal compiler error: in binds_to_current_def_p, at symtab.cc:2598
   91 | bool PinJoint2DSW::setup(real_t p_step) {
      |      ^
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make: *** [/tmp/ccqKKJU2.mk:232: /tmp/cc4myrdo.ltrans115.ltrans.o] Error 1
make: *** Waiting for unfinished jobs....
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make: *** [/tmp/ccqKKJU2.mk:206: /tmp/cc4myrdo.ltrans102.ltrans.o] Error 1
during GIMPLE pass: dse
/usr/x86_64-w64-mingw32/sys-root/mingw/include/c++/bits/stl_uninitialized.h: In function '__relocate_object_a.isra':
/usr/x86_64-w64-mingw32/sys-root/mingw/include/c++/bits/stl_uninitialized.h:1280:5: internal compiler error: in binds_to_current_def_p, at symtab.cc:2598
 1280 |     __relocate_object_a(_Tp* __restrict __dest, _Up* __restrict __orig,
      |     ^
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make: *** [/tmp/ccqKKJU2.mk:250: /tmp/cc4myrdo.ltrans124.ltrans.o] Error 1
during GIMPLE pass: dse
core/compressed_translation.h: In member function '__dt ':
core/compressed_translation.h:36:7: internal compiler error: in binds_to_current_def_p, at symtab.cc:2598
   36 | class PHashTranslation : public Translation {
      |       ^
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make: *** [/tmp/ccqKKJU2.mk:254: /tmp/cc4myrdo.ltrans126.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/lib/gcc/x86_64-w64-mingw32/15.2.1/../../../../x86_64-w64-mingw32/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.opt.64.exe] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:26.543]
```

gcc **15.2.1 20251111 (Red Hat 15.2.1-4)**
mingw64-gcc **15.2.1**
mingw64-crt **13.0.0**

**Comment by lawnjelly** [comment]
> no luck with fresh installed Fedora Linux 43 (Workstation Edition) too.

Which version of Godot is this?

**Comment by boruok** [comment]
> > no luck with fresh installed Fedora Linux 43 (Workstation Edition) too.
> 
> Which version of Godot is this?

current **upstream 3.x**

**Comment by lawnjelly** [comment]
Here's what Grok has to say, sounds like that version of MinGW is pretty broken:
<details>
The errors you’re seeing are not Godot bugs — they are GCC internal compiler errors (ICE) happening very late in the compilation, during Link-Time Optimization (LTO) with a MinGW-w64 cross-compiler (GCC 15.2.1 in your case).

### Key Parts of the Log

internal compiler error: in binds_to_current_def_p, at symtab.cc:2598

This is a classic GCC ICE in the symbol table handling when LTO is enabled.It happens in multiple unrelated files (translation.h, compressed_translation.h, joints_2d_sw.cpp, even in the standard library stl_uninitialized.h). This almost always means the compiler itself is crashing, not that the source code is wrong.The build is using full LTO (Using LTO: full) with MinGW-w64 and GCC 15.x. What This Almost Certainly MeansGCC 15.x (especially 15.0, 15.1 and early 15.2) has known, severe LTO bugs on the x86_64-w64-mingw32 target that trigger exactly this “binds_to_current_def_p” ICE when building large C++ projects like Godot.

Godot’s codebase is huge and stresses the compiler in ways most programs don’t, so it hits these bugs very reliably.These bugs are already reported upstream and many are fixed in GCC 15.2.1 or later, but the MinGW-w64 packages that ship GCC 15.2.1 in most distros (Arch, MSYS2, etc.) still contain the broken commits.How to Fix It (Practical Solutions That Work Right Now)Disable LTO completely (quickest and most reliable fix)

Run scons with:
```
scons target=release lto=full   →   change to   lto=none
```
_or_
```
scons target=release lto=thin
```
lto=thin sometimes works, lto=none always works and still gives perfectly fine performance for Godot Windows builds.
Use a known-good older or newer GCC version

Working versions for Godot Windows cross-compile right now (November 2025):GCC 14.2.0 (very stable with full LTO)
GCC 13.2 or 13.3
GCC 15.2.1 from the very latest MSYS2 packages (some people report it fixed after a recent update)

Bad versions: basically anything 15.0.0 → 15.2.0 and some early 15.2.1 builds.If you’re on Arch Linux, the current mingw-w64-gcc package is still broken for Godot with LTO. Either downgrade to 14.x or switch to MSYS2 and use their latest toolchain.

If you’re using MSYS2
Update everything and make sure you have the absolute latest:

```
pacman -Syu mingw-w64-x86_64-toolchain
```

Some users report that the November 2025 MSYS2 packages finally fixed this particular ICE.
Switch to Clang (also works very well for Godot Windows builds now)  

```
scons use_llvm=yes target=release
```

(you need mingw-w64-x86_64-clang installed)

### TL;DR
This is a known GCC 15.x + LTO bug on the MinGW target.

Just add lto=none (or lto=thin) to your scons command line and the build will finish instantly. You lose almost nothing in the final Windows binary performance.Example working command:

```
scons platform=windows target=release lto=none -j12
```

Once GCC 15.2.1+ is fully fixed in your distro’s MinGW package, you can re-enable lto=full if you really want the tiny extra optimization. For now, disabling LTO is the standard workaround used by virtually everyone cross-compiling Godot master for Windows.

</details>

Essentially, as the log indicates, this kind of bug is more important to be reported to the compiler writers (so they can fix it), rather than Godot (although it's helpful here to keep track of compiler bugs).

Sometimes there are things we can do to prevent a compiler bug manifesting, but there's a danger of degrading into a game of "whack-a-mole"...

We do a bunch of changes, they release a new version, which fix bugs we worked around, and introduces new bugs to whack.

So unless it's something obvious our side, it seems likely the best course of action is to advise on which versions _are known to work_ (presumably the same as those making the official builds).

See:
https://github.com/godotengine/godot-build-scripts
https://github.com/godotengine/build-containers

_(I don't personally know more in depth here, this is more @akien-mga  and @Repiteo 's area as they make builds.)_

**Comment by boruok** [comment]
Do official builds use **optimize(_speed, size, none_)** flag?
build fails with **none** and **size**
but with **speed** template compiles with warnings.
