### PR TITLE
GDScript: Fix getting type from PropertyInfo for Variant arguments

### LINKED ISSUE #64149: GDScript 2.0: statically typing a variable as a Variant errors when used on builtin virtual methods
### Godot version

4.0.alpha13

### System information

linux

### Issue description

In the docs:
image

In the code:
```gdscript
func _set(property: StringName, value: Variant) -> bool:
	return false
```

image

While this is a pretty useless thing to do, it shouldn't raise an error especially when this pattern is allowed in used-defined code. This or `: Variant` should be forbidden since it's totally useless.

### Steps to reproduce

```gdscript
func _set(property: StringName, value: Variant) -> bool:
	return false
```

### Minimal reproduction project

_No response_

### LINKED ISSUE #70054: GDScript 2.0: Can't use Variant type for argument when override virtual method
### Godot version

v4.0.beta8

### System information

Windows 10

### Issue description

Can't use Variant type for argument when override virtual method.

### Steps to reproduce

```
extends Node

func _set(property: StringName, value: Variant) -> bool:
	return true
```

Error: `The function signature doesn't match the parent. Parent signature is "_set(StringName, Variant) -> bool".`

### Minimal reproduction project

[override_bug.zip](https://github.com/godotengine/godot/files/10228241/override_bug.zip)

### PR DESCRIPTION
**Pull request by vonagam**
There is a difference between `PropertyInfo` for arguments and for other things: `PROPERTY_USAGE_NIL_IS_VARIANT` is [not used](https://github.com/godotengine/godot/blob/b6e06038f8a373f7fb8d26e92d5f06887e459598/core/doc_data.cpp#L85) for Variant arguments because arguments cannot be void.

But analyzer was ignoring this difference and typing variants in build-in methods wrong. Added optional bool `p_is_arg` to `GDScriptAnalyzer::type_from_property` to resolve that.

Fixes #64149.
Fixes #70054 (duplicate of the one above).

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
Looks good to me.

**Review by anvilfolk — APPROVED** [review]
LGTM also!

**Review by vnen — APPROVED** [review]

**Comment by vonagam** [comment]
Done.

**Comment by akien-mga** [comment]
Seems like one test is failing:
```
 ./modules/gdscript/tests/gdscript_test_runner_suite.h:43:
TEST SUITE: [Modules][GDScript]
TEST CASE:  Script compilation and runtime

modules/gdscript/tests/gdscript_test_runner.cpp:209: ERROR: CHECK( result.passed ) is NOT correct!
  values: CHECK( false )
  logged: /home/runner/work/godot/godot/modules/gdscript/tests/scripts/analyzer/errors/enum_shadows_outer_enum.gd
          GDTEST_OK


./modules/gdscript/tests/gdscript_test_runner_suite.h:47: FATAL ERROR: REQUIRE( fail_count == 0 ) is NOT correct!
  values: REQUIRE( 1 == 0 )
  logged: Make sure `*.out` files have expected results.
          All GDScript tests should pass.
```

**Comment by vonagam** [comment]
It is unrelated to this PR, this is about [this test](https://github.com/godotengine/godot/blob/75515e43034aab3acd014bf6c663c10fcba94900/modules/gdscript/tests/scripts/analyzer/errors/enum_shadows_outer_enum.gd) which contains valid code. Related to PR with outer lookup thing in parser. The test can be removed now.

**Comment by akien-mga** [comment]
Ah indeed, it's weird that it didn't fail CI in #70713 then. Looks like that test was added on Dec 4 so it should have run in your Dec 29 branch.

**Comment by vonagam** [comment]
Added removal of the test here.

**Comment by akien-mga** [comment]
Thanks!
