### ISSUE TITLE
Compilation error on OS X El Capitan

### ISSUE THREAD

**Issue by vigreco** [godotengine/godot#15376]
**Godot version:**
Godot 3 ([b1ab44a](https://github.com/godotengine/godot/commit/b1ab44aa05994a19f0bae5e700c4007b870a8ecf))

**OS/device including version:**
OS X 10.11.6

**Issue description:**
Godot doesn't compile on El Capitan due to an undeclared identifier introduced by #15033

```
platform/osx/os_osx.mm:108:32: error: use of undeclared identifier 'NSEventModifierFlagCommand'
                if (([event modifierFlags] & NSEventModifierFlagCommand) && [event keyCode] == 0x2f) {
```

I think `NSEventModifierFlagCommand` is only available in macOS 10.12+.

Is it macOS Sierra the minimum supported version?

**Comment by icnikerazah** [comment]
tey update xcode commandline tools.

**Comment by bruvzg** [comment]
NSEventModifierFlagCommand is 10.12+

Try adding `#define NSEventModifierFlagCommand NSCommandKeyMask` after line 60 in platform/osx/os_osx.mm

```diff
diff --git a/platform/osx/os_osx.mm b/platform/osx/os_osx.mm
index 852e983..da6d88b 100644
--- a/platform/osx/os_osx.mm
+++ b/platform/osx/os_osx.mm
@@ -58,6 +58,7 @@
 #include <unistd.h>
 
 #if MAC_OS_X_VERSION_MAX_ALLOWED < 101200
+#define NSEventModifierFlagCommand NSCommandKeyMask
 #define NSWindowStyleMaskBorderless NSBorderlessWindowMask
 #endif

```

**Comment by vigreco** [comment]
@bruvzg thanks, this solved the error 👍
