### PR TITLE
Fix wrong return type in canvas.glsl

### PR DESCRIPTION
**Pull request by TritiatedWater**
``ERROR: _display_error_with_code: CanvasShaderGLES3: Fragment Program Compilation Failed:
0:166(2): error: `return' with wrong type int, in function `map_ninepatch_axis' returning float
``
caused by e4907e50feab1af05f514a66adc0086d1c141885

and 6546735f23b8b6bd7e2a7679168edc9d9fb9ae51

### CODE REVIEW

**Comment by akien-mga** [comment]
My bad - I wondered about this but assumed it would be fine... Forgot this was glsl and not C.

**Review by akien-mga — APPROVED** [review]
Good. For the `vulkan` branch I already force-pushed a hotfix.

**Comment by akien-mga** [comment]
Thanks!
