### ISSUE TITLE
Windows Compile Fails With Custom Module

### ISSUE THREAD

**Issue by Gramps** [godotengine/godot#7166]
**Windows 10 - Godot 2.1.1**
Compiled with Visual Studio 2015, either x86 or x64, Native Tools Command Prompt.  Using Godot Steamworks module.  Godot pulled from branch tag 2.1.1-stable.  Using clean folder.

**Issue description** (what happened, and what was expected):
When compiled in Linux, exact same module and Godot 2.1.1 branch content, the resulting executable runs fine.  No issues with the editor or Steamworks.

However, when compiling it in Windows, compiling seemingly finishes correctly but the resulting executable does not work, just crashing at boot with this error:
`The procedure entry point SteamInternal_ContextInit could not be located in the dynamic link D:\Projects\Godot\godot.windows.tools.64.exe`
Opening this executable file things like Dependency Walker shows a lot of weird errors like:
`Error: At least one required implicit or forwarded dependency was not found.
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Error: Modules with different CPU types were found.`

Custom Steamworks module works fine in compiling with Godot 2.1 and custom compile of Godot 2.1.1 without the module results in a work executable.

TL,DR: 2.1 on Linux and Windows works with module, 2.1.1 does not work with module on Windows, just Linux.  What changed?

**Steps to reproduce:**
Downloaded 2.1.1 stable branch, dropped GodotSteam into the modules folder, then run
`scons platform=windows`
in VS 2015 Native Tools Command Prompt.   Resulting executable does not work.

**Link to minimal example project** (optional but very welcome):
Steamworks API for Godot - https://github.com/Gramps/GodotSteam

**Comment by akien-mga** [comment]
I guess you started from a clean source, not like in #7150? :)

**Comment by Gramps** [comment]
Haha, right?  Made sure it was a clean folder.  I'm wondering if something with the Anniversary update broke something else.

**Comment by vnen** [comment]
I compiled Godot 2.1.1 with your module in Windows 10 x64 and everything seems to work fine. At least I didn't get any crash.

**Comment by Gramps** [comment]
Hmm, interesting. Is your Windows 10 using the Anniversary Update?  That's about the only thing that changed on my system since the last time I compiled Godot.  Wondering if something in that update affected Visual Studio somehow.

**Comment by vnen** [comment]
Yes, I'm using the Anniversary Update for quite some time now (currently version 1607 build 14393).

**Comment by Gramps** [comment]
Hmm. Then I'm not sure what during compiling is going wrong or how to even start going about resolving this.

**Comment by Gramps** [comment]
This issue seems to be resolved when coupled with the newest Steamworks DLL file.  Much thanks to Vnen for confirming the compile works correctly.  As to why the DLL version only functions specifically with 1.38a on Windows but previous versions on Linux is still a mystery but the Godot end of this is resolved!
