### ISSUE TITLE
Compiling for Windows fails (mingw-w64-gcc)

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#28299]
**Godot version:**
master (https://github.com/godotengine/godot/commit/886afa9b7692bc263cf96c03882760521b74b942)
deleted godot folder and cloned again

**OS/device including version:**
Antergos (Arch Linux)

**Issue description:**
Output:
```Swift

[Initial build] Linking Program        ==> bin/godot.windows.opt.tools.64.exe
[Initial build] /usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: platform/windows/os_windows.windows.opt.tools.64.o:os_windows.cpp:(.rdata$.refptr.FOLDERID_Music[.refptr.FOLDERID_Music]+0x0): undefined reference to `FOLDERID_Music'
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: platform/windows/os_windows.windows.opt.tools.64.o:os_windows.cpp:(.rdata$.refptr.FOLDERID_Videos[.refptr.FOLDERID_Videos]+0x0): undefined reference to `FOLDERID_Videos'
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: platform/windows/os_windows.windows.opt.tools.64.o:os_windows.cpp:(.rdata$.refptr.FOLDERID_Downloads[.refptr.FOLDERID_Downloads]+0x0): undefined reference to `FOLDERID_Downloads'
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: platform/windows/os_windows.windows.opt.tools.64.o:os_windows.cpp:(.rdata$.refptr.FOLDERID_Documents[.refptr.FOLDERID_Documents]+0x0): undefined reference to `FOLDERID_Documents'
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: platform/windows/os_windows.windows.opt.tools.64.o:os_windows.cpp:(.rdata$.refptr.FOLDERID_Pictures[.refptr.FOLDERID_Pictures]+0x0): undefined reference to `FOLDERID_Pictures'
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: platform/windows/os_windows.windows.opt.tools.64.o:os_windows.cpp:(.rdata$.refptr.FOLDERID_Desktop[.refptr.FOLDERID_Desktop]+0x0): undefined reference to `FOLDERID_Desktop'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.opt.tools.64.exe] Error 1
scons: building terminated because of errors.

```

**Steps to reproduce:**
```Swift
git clone https://github.com/godotengine/godot.git
scons p=windows bits=64 target=release_debug tools=yes -j 8
```

**Comment by akien-mga** [comment]
Regression from #28166, CC @KLee1248.

**Comment by KLee1248** [comment]
Sorry for breaking this. I'm working on writing a pull request to fix this.

The issue is that for cross-compilation we just need to at the uuid library. I was able to get this to work locally (using Ubuntu), but just need to test and double-check before I submit it.

I'll also test this change against a clean Windows environment to make sure that everything still works as expected there.
