### PR TITLE
Make Godot compile on `FreeBSD`

### LINKED ISSUE #67838: FreeBSD build failure: HAVE_SECURE_GETENV erroneously set for openxr dependency
### Godot version

4.0.dev (040f49ed6e71a6e7f23d763c4b56095cbf319ef7)

### System information

FreeBSD 13.1-RELEASE, GENERIC kernel, amd64

### Issue description

When specifying the `linuxbsd` platform for scons during build, `modules/openxr/SCsub`
defines `HAVE_SECURE_GETENV` for the `openxr` third-party dependency. This define
implies the existence of the function `secure_getenv` – which FreeBSD doesn't have.

That in turn leads to the build currently failing on FreeBSD when it encounters [this](https://github.com/godotengine/godot/blob/040f49ed6e71a6e7f23d763c4b56095cbf319ef7/thirdparty/openxr/src/common/platform_utils.hpp#L53):
```cpp
#ifdef HAVE_SECURE_GETENV
    return secure_getenv(name);
```

I can confirm that commenting out the define of `HAVE_SECURE_GETENV` in
[modules/openxr/SCsub](https://github.com/godotengine/godot/blob/040f49ed6e71a6e7f23d763c4b56095cbf319ef7/modules/openxr/SCsub#L37) fixes said build failure *on FreeBSD*, but am not too
sure how to fix this without finally introducing BSD as its own platform.

I also can't speak on whether the other BSDs provide `secure_getenv`,
but a cursory check for corresponding man pages on [man.openbsd.org](https://man.openbsd.org/secure_getenv)
and [man.netbsd.org](https://man.netbsd.org/secure_getenv) yields no results.

### Steps to reproduce

* Run `scons platform=linuxbsd` on FreeBSD

### Minimal reproduction project

_No response_

### LINKED ISSUE #92130: OpenBSD build is broken due to compilation errors
### Tested versions

Reproducible with the `4.3 dev` (master branch, e.g. commit `64520fe`)

### System information

OpenBSD 7.5 GENERIC amd64 (running on QEMU)

### Issue description

OpenBSD build is broken.

I've tried to build it on freshly installed OpenBSD 7.5 in QEMU, and the build is broken due to compilation errors. I've found 2 main problems:

- With the default `scons` build command it fails because the definition of `quick_exit` standard function cannot be found when compiling the file `platform/linuxbsd/x11/detect_prime_x11.cpp`, although the header `<stdlib.h>` is included.
- If I build with OpenGL disabled with `scons opengl3=no` (that way the source file above won't be included in the build), it sill fails with another error: it can't find the header file `#include <linux/input-event-codes.h>` (which is included in `platform/linuxbsd/wayland/wayland_thread.cpp`).

And most likely there are other errors.

### Steps to reproduce

1. Checkout Godot source code, master branch
2. Install build dependencies: `pkg_add python scons llvm`
3. Run `scons` or `scons opengl3=no`

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by MBCX**
Fixes #67838, well, at least it does build on my dedicated FreeBSD 12.4 VM.

Some issues however:

1. ~~There are minor thirdparty code modifications, hopefully its acceptable.~~ Committed the changed and also documented them in a diff file.
2. ~~Not a fan of having to `import sys` directly to _specifically_ detect FreeBSD. Any other solution would be appreciated.~~ Seems like the simplest solution for now.

I'll tackle OpenBSD on a separate PR once I have that set-up.

### CODE REVIEW

File: thirdparty/linuxbsd_headers/alsa/asoundlib.h [hunk 1]
```diff
@@ -38,7 +38,11 @@
 #include <poll.h>
 #include <errno.h>
 #include <stdarg.h>
+#ifdef __FreeBSD__
+#include <sys/endian.h>
+#else
 #include <endian.h>
+#endif // __FreeBSD__
```
Comment (adamscott) [inline thirdparty/linuxbsd_headers/alsa/asoundlib.h:45]: > There are minor thirdparty code modifications, hopefully its acceptable.

Usually, we use a patch system, we don't edit thirdparty code directly. See other thirdparty code directories.

```suggestion
#include <endian.h>
```

File: platform/linuxbsd/wayland/wayland_thread.cpp [hunk 2]
```diff
@@ -32,8 +32,12 @@
 
 #ifdef WAYLAND_ENABLED
 
-// FIXME: Does this cause issues with *BSDs?
+#ifdef __FreeBSD__
+#include <dev/evdev/input-event-codes.h>
+#else
+// Assume Linux.
 #include <linux/input-event-codes.h>
+#endif
```
Comment (adamscott) [inline platform/linuxbsd/wayland/wayland_thread.cpp:40]: Same comment as before.

**Review by adamscott — CHANGES_REQUESTED** [review]

File: thirdparty/linuxbsd_headers/alsa/asoundlib.h (hunk 1 above)
Comment (akien-mga) [reply thirdparty/linuxbsd_headers/alsa/asoundlib.h:45]: The patch is to document the change made to thirdparty code, but the change should still be committed (so accepting your code suggestion would undo the fix here).

File: platform/linuxbsd/wayland/wayland_thread.cpp (hunk 2 above)
Comment (akien-mga) [reply platform/linuxbsd/wayland/wayland_thread.cpp:40]: This is first-party code, so it's fine.

File: modules/openxr/SCsub [hunk 3]
```diff
@@ -29,7 +30,9 @@ elif env["platform"] == "linuxbsd":
         env_openxr.AppendUnique(CPPDEFINES=["XR_USE_PLATFORM_EGL"])
 
     # FIXME: Review what needs to be set for Android and macOS.
-    env_openxr.AppendUnique(CPPDEFINES=["HAVE_SECURE_GETENV"])
+    # FreeBSD uses non-standard getenv functions.
+    if sys.platform.startswith("freebsd") == False:
```
Comment (akien-mga) [inline modules/openxr/SCsub:34]:
```suggestion
    if not sys.platform.startswith("freebsd"):
```

File: modules/camera/config.py [hunk 4]
```diff
@@ -1,4 +1,8 @@
+import sys
+
 def can_build(env, platform):
+    if sys.platform.startswith("freebsd"):
```
Comment (akien-mga) [inline modules/camera/config.py:4]: We should probably harmonize how we check for FreeBSD, seems we use either this one or `platform.system() == "FreeBSD"`:
```
SConstruct
341:        or sys.platform.startswith("freebsd")

platform/linuxbsd/detect.py
502:    if platform.system() == "FreeBSD":
508:        if env["use_llvm"] and platform.system() != "FreeBSD":
511:        if env["use_llvm"] and platform.system() != "FreeBSD":
```

**Comment by akien-mga** [comment]
> Not a fan of having to `import sys` directly to _specifically_ detect FreeBSD. Any other solution would be appreciated.

Yeah it's a bit hacky and would break in cross-compilation (if there's any cross-compilation toolchain that targets FreeBSD).
But for now it's acceptable, *BSDs are supported on a best-effort basis so it's not unreasonable to expect users who want to target those platforms to build on the target platform.

File: modules/camera/config.py [hunk 5]
```diff
@@ -1,4 +1,8 @@
+import sys
+
 def can_build(env, platform):
```
Comment (akien-mga) [inline modules/camera/config.py:3]: To match style guide:
```suggestion
import sys


def can_build(env, platform):
```

Comment (akien-mga) [reply modules/camera/config.py:3]: Though I would suggest moving the `import sys` inside `can_build`.

**Comment by MBCX** [comment]
So for the thirdparty code, I kept the changes as Akien mentioned, but also created a diff in the `patches`. Sounds good @adamscott?

**Review by akien-mga — APPROVED** [review]
Looks good to me.

File: platform/linuxbsd/wayland/wayland_thread.cpp (hunk 2 above)
Comment (adamscott) [reply platform/linuxbsd/wayland/wayland_thread.cpp:40]: Sorry, misread the file name.

File: thirdparty/linuxbsd_headers/alsa/asoundlib.h (hunk 1 above)
Comment (adamscott) [reply thirdparty/linuxbsd_headers/alsa/asoundlib.h:45]: @MBCX You need to remove the change here though.

**Review by adamscott — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!
