### ISSUE TITLE
Error compiling Vertex shader in alpha 15

### ISSUE THREAD

**Issue by eec36** [godotengine/godot#65350]
### Godot version

4.0 alpha 15

### System information

Windows 10, i5-9300H, NVIDIA GeForce GTX 1650 Mobile

### Issue description

When i updated from 4.0 alpha 14. and when i open my project in alpha 15, my character looked off. And i can't compile Godot alpha 15.
Then i trying run Godot in cmd, there's error message about compiling Vertex shader.
![screenshot1234567890](https://user-images.githubusercontent.com/99343051/188348802-0db7d11a-5982-4481-896e-02f33e20f2ca.png)

### Steps to reproduce

Start the editor, open the project, and close the editor.

**Comment by tinmanjuggernaut** [comment]
Please copy and paste the text. Your windows command window allows this function natively. Select the text with your mouse and press enter. Then paste it in a text file for upload, or dump it in code blocks delimited by backticks before and after. ` ` ` 

Did you write this shader or is it from somewhere else?

What block of code is flagged with error messages when you edit the shader in the Godot shader editor?

Did you try to fix the errors? It states that it can't convert a vec2 into a vec3 (2 component vector to 3 component).

If it is a problem with the engine, then you'll need to reduce your shader down to the specific problem. It's not 500 lines of shader code that is the problem it's likely just 1 line.

**Comment by eec36** [comment]
> Did you write this shader or is it from somewhere else?
No it's from official binary.

**Comment by Calinou** [comment]
@eec36 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by eec36** [comment]
[a15 bug.zip](https://github.com/godotengine/godot/files/9492197/a15.bug.zip)
if you add these line in project.godot, and trying to turn on anisotropy in StandardMaterial3D, it gonna generate error.
> [rendering]
> 
> vulkan/rendering/back_end=1
![YFYWwcIYk4](https://user-images.githubusercontent.com/99343051/188517368-d6998bf0-2cd8-4c4e-8610-29d938c39b83.png)

**Comment by tinmanjuggernaut** [comment]
I was able to reproduce this in alpha 15. A better title is, "StandardMaterial3D Anisotropy produces shader compilation error". Nothing to do with vertex shaders. 

I cannot reproduce it in Alpha 16. Anisotropy works fine. @eec36 please see if you still have an issue with this in a16.

**Comment by clayjohn** [comment]
No response and since it wasn't reproducible in Alpha 16, I am closing

**Comment by Phonfo** [comment]
> ### Godot version
> 
> 4.0 alpha 15
> ### System information
> 
> Windows 10, i5-9300H, NVIDIA GeForce GTX 1650 Mobile
> ### Issue description
> 
> When i updated from 4.0 alpha 14. and when i open my project in alpha 15, my character looked off. And i can't compile Godot alpha 15. Then i trying run Godot in cmd, there's error message about compiling Vertex shader. ![screenshot1234567890](https://user-images.githubusercontent.com/99343051/188348802-0db7d11a-5982-4481-896e-02f33e20f2ca.png)
> ### Steps to reproduce
> 
> Start the editor, open the project, and close the editor.
> ### Minimal reproduction project
> 
> _No response_

that was some amazing screenshot, what software did you use?
