### PR TITLE
Somewhat fixed Directory::get_space_left() return values.

### LINKED ISSUE #4617: Directory::get_space_left() does not return consistent "failure" values
Looking at the API for the documentation, I noticed that ``Directory::get_space_left()``:
- is only implemented on Unix
- returns ``0`` for some platforms, ``-1`` in others

For the first point, this is likely a platform limitation and just has to be properly documented. For the second point, it would be nice to streamline this by making all implementations return either 0 or -1, but not a mix of both.

- [ ] Android: Always returns ``0`` https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/platform/android/dir_access_android.cpp#L173-L176 and https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/platform/android/dir_access_jandroid.cpp#L224-L227
- [x] *Fixed by #5059.* Unix driver and OSX platform: If statvfs is enabled, returns the size on success and ``-1`` on failure. If not, returns ``0`` https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/drivers/unix/dir_access_unix.cpp#L311-L325
- [x] *Fixed by #5059.* Windows: Always returns ``-1`` https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/drivers/windows/dir_access_windows.cpp#L360-L363
- [ ] FileAccessPack: Always returns ``0`` https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/core/io/file_access_pack.cpp#L493-L496

I guess it would be best to make all error outputs be ``-1``, to make it clear that the function errored and not that the disk space available is 0 bytes?

### PR DESCRIPTION
**Pull request by J08nY**
Implemented it on windows using `GetDiskFreeSpaceEx()`.
Works on linux/osx(if STAT_VFS is enabled) and windows. On other platforms currently returns 0.

Partly fixes #4617 , only Android implementation remaining. I'm not sure what proper behavior for `DirAccessPack` is.

### CODE REVIEW

**Comment by akien-mga** [comment]
@J08nY This seems to fail on MSVC (see the Travis CI build report):
```
drivers/windows/dir_access_windows.cpp: In member function 'virtual size_t DirAccessWindows::get_space_left()':
drivers/windows/dir_access_windows.cpp:362:25: error: conversion from 'int' to non-scalar type 'ULARGE_INTEGER {aka _ULARGE_INTEGER}' requested
```

The X11 failure is unrelated and caused by 2420e46.

Also you signed commit appears as unverified, you might want to look into it.

File: drivers/windows/dir_access_windows.cpp [hunk 1]
```diff
@@ -359,8 +359,12 @@ FileType DirAccessWindows::get_file_type(const String& p_file) const {
 */
 size_t  DirAccessWindows::get_space_left() {
 
-	return -1;
-};
+	ULARGE_INTEGER bytes = 0;
+	GetDiskFreeSpaceEx(NULL,&bytes,NULL,NULL);
+
+    //this is either 0 or a value in bytes.
```
Comment (akien-mga) [inline drivers/windows/dir_access_windows.cpp]: Please make sure to use tabs for indentation like in the rest of the code.

**Comment by J08nY** [comment]
Alright, should be all fixed now, tabs and windows build error.
