### PR TITLE
3.2 New csproj style with backport of Godot.NET.Sdk

### LINKED ISSUE #15386: Error on saving project: Attribute "Version" is not known on node "PackageReference"
**Godot version:**
`master` / 8e8240450edc48f4fb379e593a4ef7f54ab656b7

**OS/device including version:**
_Manjaro Linux 17.1-rc2_

**Issue description:**
Whenever I save the project from the editor, it logs a following error message:
``` modules/mono/editor/csharp_project.cpp:117 - Method/Function Failed.```

If I launch the editor from a terminal, I can see more detailed information of the problem as below:
```
Unhandled Exception:
Microsoft.Build.Exceptions.InvalidProjectFileException: Attribute "Version" is not known on node "PackageReference" [type Microsoft.Build.Construction.ProjectItemElement].  at: /home/fender/workspace/AlleyCat/Alley Cat.csproj (72,6)
  at Microsoft.Build.Construction.ProjectElement.LoadAttribute (System.String name, System.String value) [0x0005f] in <654565be0438470588cb32d8f896dc6e>:0 
  at Microsoft.Build.Construction.ProjectItemElement.LoadAttribute (System.String name, System.String value) [0x00080] in <654565be0438470588cb32d8f896dc6e>:0 
  at Microsoft.Build.Construction.ProjectElementContainer.Load (System.Xml.XmlReader reader) [0x00091] in <654565be0438470588cb32d8f896dc6e>:0 
  at Microsoft.Build.Construction.ProjectElementContainer.LoadValue (System.Xml.XmlReader reader) [0x00018] in <654565be0438470588cb32d8f896dc6e>:0 
  at Microsoft.Build.Construction.ProjectElementContainer.Load (System.Xml.XmlReader reader) [0x0009e] in <654565be0438470588cb32d8f896dc6e>:0 
  at Microsoft.Build.Construction.ProjectElementContainer.LoadValue (System.Xml.XmlReader reader) [0x00018] in <654565be0438470588cb32d8f896dc6e>:0 
  at Microsoft.Build.Construction.ProjectElementContainer.Load (System.Xml.XmlReader reader) [0x0009e] in <654565be0438470588cb32d8f896dc6e>:0 
  at Microsoft.Build.Construction.ProjectRootElement.Load (System.Xml.XmlReader reader) [0x00000] in <654565be0438470588cb32d8f896dc6e>:0 
  at Microsoft.Build.Construction.ProjectRootElement.Open (System.String path, Microsoft.Build.Evaluation.ProjectCollection projectCollection) [0x0000f] in <654565be0438470588cb32d8f896dc6e>:0 
  at Microsoft.Build.Construction.ProjectRootElement.Open (System.String path) [0x00006] in <654565be0438470588cb32d8f896dc6e>:0 
  at GodotSharpTools.Project.ProjectUtils.AddItemToProjectChecked (System.String projectPath, System.String itemType, System.String include) [0x0000c] in <14701c1a54e940ccafcd8ac62f6777fc>:0 
ERROR: add_item: Method/Function Failed.
   At: modules/mono/editor/csharp_project.cpp:117.
```
It seems that it somehow doesn't recognize the `Version` attribute in `PackageReference` node in my project file. The offending line reads as follows:
```xml
  <ItemGroup>
    <PackageReference Include="Ensure.That" Version="7.2.1" />
    <PackageReference Include="FluentCache.Microsoft.Extensions.Caching.Memory" Version="4.0.0.1" />
    <PackageReference Include="JetBrains.Annotations" Version="11.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />
    <PackageReference Include="NETStandard.Library" Version="2.0.1" />
    <PackageReference Include="NETStandard.Library.NETFramework" Version="2.0.0-preview2-25405-01" />
  </ItemGroup>
```
Aside from the error messages, the project seems to build and run without any noticeable problem.

### LINKED ISSUE #30970: Adding a nuget package makes Godot not build
**Godot version:** 3.1.1-stable-mono-win64

**OS/device including version:**windows 10

**Issue description:**Godot doesn't include nuget package, and throw an error on build.

**Steps to reproduce:** Make any C# project. Attach a script to a node. In VS Code, add a nuget package (Using nuget, or by hand.), and restore the project. Try to build. You get : 

`ERROR: generate_scripts_metadata: Method/Function Failed, returning: FAILED
   At: modules/mono/editor/csharp_project.cpp:155
ERROR: editor_build_callback: Condition ' metadata_err != OK ' is true. returned: false
   At: modules/mono/editor/godotsharp_builds.cpp:383
ERROR: call_build: A Godot Engine build callback failed.
   At: editor/editor_node.cpp:4666`

If you remove the project, and restore again, you get no error. Build successful.

In case it's relevant, i was trying to add  Newtonsoft.json, latest version to this day (12.0.2).
I tried another version
I tried targetting another framework.
I tried adding the definition to the packagereference inside the .csproj (sorry, I tried that two days ago, and I can't find it again...)
Nothing works, i'm beat, and it's been two days of searching already.... any ideas?

**Minimal reproduction project:** Minimal test project. Just open & build.
[test.zip](https://github.com/godotengine/godot/files/3448079/test.zip)

### LINKED ISSUE #41241: [3.2.3RC3 Regression] System.Text.Json package not found when building from editor (works via Visual Studio extension)
**Godot version:** 3.2.3RC3

**OS/device including version:** Windows 10 64bit (Visual Studio 2019 with Godot extension)

**Issue description:** I am using NuGet to include the `System.Text.Json` package in my Godot project. With previous versions of Godot I was able to build both from Visual Studio 2019 and from the editor.

Now, I am able to build and launch from Visual Studio 2019 using the `Play in Editor` button, but using `Build`, `Play`, or `Play Scene` from the editor results in a build process that cannot locate the `System.Text.Json` package.

The package is referenced in the .csproj file:
```    
<PackageReference Include="System.Text.Json">
      <Version>4.7.2</Version>
</PackageReference>
```

Truncated build log from the editor:
```		
Csc: Using shared compilation with compiler from directory: C:\Program Files\dotnet\sdk\3.1.401\Roslyn\bincore
Common\DictionaryTKeyEnumTValueConverter.cs(5,19): error CS0234: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?) [V:\berg\Godot\Berg.csproj]
```

I attempted to uninstall the package and reinstall it. No change.

I understand why the editor and Visual Studio 2019 might use different build steps, but if that was an issue it doesn't make sense that this worked with Godot 3.2.2.

[PackageRegression.zip](https://github.com/godotengine/godot/files/5077688/PackageRegression.zip)

### PR DESCRIPTION
**Pull request by neikeq**
There are a lot of build issues coming from old style projects. At this point fixing every single one of those would require adding patch after patch to the project file, which is a considerable amount work and makes the csproj even more bloated than it already is.

As such I decided this effort would be better spent back-porting the Sdk style support that's already available in 4.0-dev to the 3.2 branch.

This will prevent many issues, but it will also introduce other benefits, among them:

- While target framework stays as .NET Framework v4.7.2, it can be changed to .NET Standard 2.0 or greater if desired.
- It makes it much easier to add future patches. They are added to Godot.NET.Sdk and the only change required in Godot code is to update the Sdk version to use.
- Default Godot define constants are also backported, which fixes IDE issues with the preprocessor.

There are a few differences in the changes applied during patching of the csproj compared to 4.0 with the purpose of preventing breaking builds:

- `TargetFramework` stays net472 both for new projects and when importing old ones. It can be manually changed to netstandard 2.0+ if desired though.

The following features are enabled by default for new projects. Enabling them in imported projects may result in errors that must be fixed manually:

- `EnableDefaultCompileItems` is disabled as it can result in undesired C# source files being included. Existing include items are kept. As long as `EnableDefaultCompileItems` remains disabled, Godot will continue taking care of adding and removing C# files to the csproj.
- `GenerateAssemblyInfo` is disabled as it guarantees a build error because of conflicts between the existing `AssemblyInfo.cs` and the auto-generated one.
- `Deterministic` is disabled because it doesn't like wildcards in the assembly version (1.0.*) that was in the old `AssemblyInfo.cs`.

Of importance:

This is a breaking change. A great effort was put in avoiding build errors after upgrading a project, but there may still be exceptions.

This also breaks forward compatibility. Projects opened with Godot 3.2.3 won't work out of the box with older Godot versions. This was already the case with changes introduced in 3.2.2.

Albeit C# support in 3.2.x was still labeled as alpha, we've been trying to treat it as stable for some time. Still the amount of problems this change solves justifies it, but no more changes that break project compatibility are to be introduced from now on (at least for 3.x).

Fixes #30970
Fixes #41241

-----

The 'Microsoft.Build' upgrade is needed in order to support reading and editing project files that use Sdks (which this PR introduces) as well as other new features.
A common example of issues with new features is having to specify a `PackageReference` version with a child element rather than the attribute. This is no longer the case now.
Fixes #15386

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
> `TargetFramework` stays net472 both for new projects and when importing old ones. It can be manually changed to netstandard 2.0+ if desired though.

For .NET newbies like me, the corresponding moniker is `netstandard2.1` as per https://docs.microsoft.com/en-us/dotnet/standard/frameworks

Tested locally on Windows with a pre-3.2.3 RC 5 build and it seems to work fine on the Dodge the Creeps C# demo. I was able to use C# 8.0 features like `readonly` struct members.

**Comment by 8nouk** [comment]
The new .csproj seems to enforce the use of the editor to create and move scripts. Is there a way to still be able to do all of this through the IDE without using the godot editor at any point ?

**Comment by neikeq** [comment]
@8nouk The new Sdk does not impose any of this. The project either includes the scripts automatically if the `EnableDefaultCompileItems` property is not disabled. Otherwise Godot takes care of adding the scripts to the csproj.
