### ISSUE TITLE
ERROR: unimplemented base type encountered in renderer scene cull when running `--doctool`

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#64720]
### Godot version

4.0.alpha (8a1e5980116355024cd7a7ce0c15db7d4ecb200a)

### System information

Mageia 9 Linux, x86_64

### Issue description

When running `--doctool` (and possibly other run modes), the following error is printed to the terminal:

```
ERROR: unimplemented base type encountered in renderer scene cull
   at: instance_set_base (servers/rendering/renderer_scene_cull.cpp:619)
```

And when the process terminates:
```
ERROR: 21 RID allocations of type 'N13RendererDummy11MeshStorage9DummyMeshE' were leaked at exit.
```

This bug was introduced recently (didn't happen 2 weeks ago).

### Steps to reproduce

`godot --doctool`

**Comment by BastiaanOlij** [comment]
Not entirely sure why but at some point support for creating a dummy mesh object was added to the dummy renderer however this implementation is incomplete and has loads of flow on effects. Trying to fix them all...

**Comment by clayjohn** [comment]
Looks like it was likely introduced by https://github.com/godotengine/godot/commit/3c55637459ee2939d67ac9fb87e0749b9caa7467 which allocates meshes in the Dummy Renderer but does not implement a way to free them
