### ISSUE TITLE
Crash when enabling Transmitance and Subsurface Scatter on a BaseMaterial3D

### ISSUE THREAD

**Issue by Rudolph-B** [godotengine/godot#123422]
### Tested versions

 - Reproducible in: v4.8.dev (cb41ea115), 4.8.dev5 and 4.8.dev4
 - Not reproducible in: 4.8.dev3

Believe it was introduced in #109737

### System information

Godot v4.8.dev5 - Ubuntu 24.04.4 LTS 24.04 on X11 - X11 display driver, Multi-window, 2 monitors (1920x1080 @ 119.98 Hz, 1920x1080 @ 119.98 Hz) - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (nvidia; 580.173.02) - AMD Ryzen 7 3700X 8-Core Processor (16 threads) - 31.25 GiB memory - PulseAudio (44100 Hz, Stereo/mono)

### Issue description

Enabling subsurface scattering and transmittance to a material cause a compilation error in `scene_forward_clustered.glsl`

Logs:
```
Godot Engine v4.8.dev.custom_build.cb41ea115 (2026-09-10 18:07:30 UTC) - https://godotengine.org
Vulkan 1.4.312 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 2070 SUPER

WARNING: Sub-surface scattering is not supported in viewports with a transparent background. Disabling SSS in transparent viewport.
     at: _render_scene (servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:2049)
ERROR: Error compiling Fragment shader.
   at: compile_stages (servers/rendering/renderer_rd/shader_rd.cpp:1178)
ERROR: Failed parse:
WARNING: 0:437: '' : all default precisions are highp; use precision statements to quiet warning, e.g.:
         "precision mediump int; precision highp float;"
ERROR: 0:4137: 'transmittance_z' : undeclared identifier
ERROR: 0:4137: '' : missing #endif
ERROR: 0:4137: '' : compilation terminated
ERROR: 3 compilation errors.  No code generated.

4129 |                                          light_compute(normal, L_view, view, 0.0, specular_light_color, true, 1.0, f0, roughness, metallic, specular_intensity, albedo, alpha, screen_uv, energy_compensation,
4130 | #ifdef LIGHT_BACKLIGHT_USED
4131 |                                                          backlight,
4132 | #endif
4133 | #ifdef LIGHT_TRANSMITTANCE_USED
4134 |                                                          transmittance_color,
4135 |                                                          transmittance_depth,
4136 |                                                          transmittance_boost,
4137 |                                                          transmittance_z,
4138 | #endif
4139 | #ifdef LIGHT_RIM_USED
4140 |                                                          rim, rim_tint,
4141 | #endif
4142 | #ifdef LIGHT_CLEARCOAT_USED
4143 |                                                          clearcoat, clearcoat_roughness, geo_normal,
4144 | #endif
4145 | #ifdef LIGHT_ANISOTROPY_USED
4146 |                                                          binormal,
4147 |                                                          tangent, anisotropy,
4148 | #endif
4149 |                                                          diffuse_light_discarded,
4150 |                                                          direct_specular_light);

   at: compile_stages (servers/rendering/renderer_rd/shader_rd.cpp:1182)
ERROR: Condition "variant_stages.is_empty()" is true.
   at: _compile_variant (servers/rendering/renderer_rd/shader_rd.cpp:415)
ERROR: Condition "variant_stages.is_empty()" is true.
   at: _compile_variant (servers/rendering/renderer_rd/shader_rd.cpp:415)
ERROR: Condition "variant_stages.is_empty()" is true.
   at: _compile_variant (servers/rendering/renderer_rd/shader_rd.cpp:415)
ERROR: FATAL: Index p_index = 19 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:199)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.8.dev.custom_build (cb41ea115914c61a8329087b4cffbad7477b8427)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
Load address: 6307f5f82000
```

### Steps to reproduce

- Start from an empty scene
- Add any MeshInstance3D
- Add BaseMaterial3D
  - Enable Subsurface Scatter
  - Enable Transmittance

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/32117446/mrp.zip) - Open and enable transmittance to cause the crash

**Comment by clayjohn** [comment]
This is a two-parter. 
1. The engine is crashing when there are internal shader errors in the shader template (bug with our error printing system)
2. There is a shader error in the shader template.

**Comment by Rudolph-B** [comment]
I have WIP fixes for the first 2 at least but it would seem there is a third part to this issue. 

When `scene_forward_clustered.glsl` fails to compile it logs the entire source (5000+ lines). This then freezes the engine due to `editor_log.cpp` and `editor_toaster.cpp` not being able to handle the large amounts of text.
