### ISSUE TITLE
Build failure on Linux (NixOS) due to introduction of GLAD loader

### ISSUE THREAD

**Issue by queezle42** [godotengine/godot#69033]
### Godot version

4.0.dev (7f8ecffa56834dce3ccbd736738b613d51133dea)

### System information

Linux (NixOS), X11, OpenGL3

### Issue description

I'm getting a build error when trying to build the current `master` branch on NixOS:
```
modules/openxr/openxr_api.cpp:67:10: fatal error: GL/gl.h: No such file or directory
   67 | #include <GL/gl.h>
      |          ^~~~~~~~~
```
Link to the problematic include: https://github.com/godotengine/godot/blob/7f8ecffa56834dce3ccbd736738b613d51133dea/modules/openxr/openxr_api.cpp#L67

The problem was probably introduced by PR https://github.com/godotengine/godot/pull/68586, which replaces the GL dependency with the GLAD loader.

The PR removes the pkg-config lookup of the GL-headers:
https://github.com/godotengine/godot/pull/68586/files#diff-74d244f7adeae188c7346d9de7e0e41a13aed24e7f43c98ae7fe3ce2f5ccfc0dL359

GL headers are available system-wide on some Linux distributions (but not on NixOS) so I guess this didn't manifest while testing the PR?

### Steps to reproduce

I updated nixpkgs [godot_4](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/godot/4/default.nix)-derivation to use the latest godot commit.

I can provide detailed instructions if that actually helps (you would have to have an installation of `nix` or NixOS).

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
My guess is the ``#include <GL/gl.h> `` in OpenXR just needs to be replaced with ``#include "thirdparty/glad/glad/gl.h"``

@queezle42 Could you give that a try? I unfortunately don't have a NixOS device to test on. 

CC@Riteo @BastiaanOlij

**Comment by BastiaanOlij** [comment]
CC @dsnopek 

If we include `glad/gl.h` on all platforms, I think that is a pretty safe change to make.

**Comment by queezle42** [comment]
Looks like the generated GLAD loader is missing some extensions required by OpenXR. I'm getting a lot of exceptions similar to the following:

```
godot> modules/openxr/extensions/openxr_opengl_extension.cpp:170:40: error: 'GL_SRGB8_ALPHA8_EXT' was not declared in this scope; did you mean 'GL_SRGB8_ALPHA8'?
godot>   170 |         p_usable_swap_chains.push_back(GL_SRGB8_ALPHA8_EXT);
godot>       |                                        ^~~~~~~~~~~~~~~~~~~
godot>       |                                        GL_SRGB8_ALPHA8
```

The affected names are:
https://github.com/godotengine/godot/blob/cd3d6e63a630414297cb580bcc891a0aa9f25127/modules/openxr/extensions/openxr_opengl_extension.cpp#L170-L171

https://github.com/godotengine/godot/blob/cd3d6e63a630414297cb580bcc891a0aa9f25127/modules/openxr/extensions/openxr_opengl_extension.cpp#L422-L458

My commit, for reference: https://github.com/queezle42/godot/commit/9e3368e4b61eeada5c282d4897497cb006058dc6

Also the problem is limited to OpenXR - building with `openxr=false` works just fine.

**Comment by queezle42** [comment]
Looks like the missing extensions are `EXT_texture` and `EXT_texture_sRGB`. I will try to update GLAD and see if that is enough.

**Comment by queezle42** [comment]
Ok, that fixed it. I have opened a PR with my changes: https://github.com/godotengine/godot/pull/69123

**Comment by akien-mga** [comment]
Fixed by #69123.
