### PR TITLE
Thread: Re-add pthread_np.h include for FreeBSD/OpenBSD

### LINKED ISSUE #46998: Godot 3.2.4 RC5 fails to build on FreeBSD
**Godot version:**
1d0929a

**OS/device including version:**
FreeBSD 13-RC2 / AMD64

**Issue description:**

Build process seems to hang multiple times on pthreads.

`
[Initial build] Compiling ==> drivers/gles3/rasterizer_scene_gles3.cpp
drivers/unix/thread_posix.cpp: In function 'Error set_name(const String&)':
drivers/unix/thread_posix.cpp:53:2: error: 'pthread_set_name_np' was not declared in this scope; did you mean 'pthread_setname_np'?
   53 |  pthread_set_name_np(running_thread, p_name.utf8().get_data());
      |  ^~~~~~~~~~~~~~~~~~~
      |  pthread_setname_np
scons: *** [drivers/unix/thread_posix.x11.tools.64.o] Error 1
`

**Steps to reproduce:*
Clone latest Godot 3.2.4 from git. Build with scons -j8 builtin-libvpx=False pulseaudio=False platform=x11

also will fail when adding use_llvm=yes to the command line.

### PR DESCRIPTION
**Pull request by akien-mga**
Was a regression from #45315.

Fixes #46998.

---

@nonfatmatt Could you test to confirm that it fixes your build issue on FreeBSD?

### CODE REVIEW

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.
