### ISSUE TITLE
3D-rendering is broken

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#57978]
### Godot version

36892b7fc8633d450dd54e2266147b7a5677bb97

### System information

Windows 10, GTX 1060

### Issue description

It seems like a regression after 36892b7fc8633d450dd54e2266147b7a5677bb97, if I run the editor through console it spam a lot of 
shader compilation errors (Error spam `ERROR: 0:131: 'binding' : cannot be used with push_constant`) and barely runs and even if it runs the 3D rendering is not working.

### Steps to reproduce

Run the editor.

**Comment by akien-mga** [comment]
Is it reproducible when you restart the engine? @bruvzg and I had a similar issue once or twice due to shader cache, then it worked fine.

**Comment by akien-mga** [comment]
Actually I can reproduce a ton of error spam too, even after deleting `res://.godot` and `~/.local/share/godot/shader_cache/`.

**Comment by clayjohn** [comment]
Looks like its intended behaviour. https://github.com/KhronosGroup/glslang/pull/2810

We should go through our push constants and remove the binding assignment.

**Comment by akien-mga** [comment]
I guess it's best if I revert #57948 for now and we re-do it with necessary fixes?

**Comment by Chaosus** [comment]
> Is it reproducible when you restart the engine?

The error starts spam at the project manager, so yes.

**Comment by Chaosus** [comment]
![image](https://user-images.githubusercontent.com/3036176/153634886-e08cf4c8-f1a9-4f4c-864a-2b08c3c828f3.png)

**Comment by bruvzg** [comment]
It seems to be exactly opposite from what I was thinking, it's running fine while the old cache is present, and start spamming error as soon as it is removed. So I guess shader cache not auto-updating after the change (which might be an issue on its own).
