### ISSUE TITLE
Accessing `TEXTURE_PIXEL_SIZE` in a light() function leads to shader compilation errors

### ISSUE THREAD

**Issue by limbonaut** [godotengine/godot#103600]
### Tested versions

- Reproducible in Godot 4.4-stable.
- Not reproducible in Godot 4.3-stable.

I'll bisect in a bit.

### System information

Godot v4.4.stable (cc10aa775) - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 27 Feb 2025 18:09:44 +0000 on Wayland - Wayland display driver, Single-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 threads)

### Issue description

After opening our project in Godot 4.4, I noticed shader errors printed connected to our light shader code. I narrowed it down to using `TEXTURE_PIXEL_SIZE` in a light() function within a canvas item shader. Related shaders also stopped working.

[godot.log](https://github.com/user-attachments/files/19078527/godot.log)

### Steps to reproduce

Attach this shader to a canvas item node:
```shader
shader_type canvas_item;

void light() {
	vec2 something = TEXTURE_PIXEL_SIZE;
}

```

### Minimal reproduction project (MRP)

[reproduction.zip](https://github.com/user-attachments/files/19078540/reproduction.zip)

**Comment by limbonaut** [comment]
Bisection result: a657ea42f1e656695f502a0e5f50ea9e0e041c3e is the first bad commit

**Comment by polzon** [comment]
Unfortunately this bug made it into 4.4-stable as well.

A temporary workaround I found for now is that you can set still access texture_pixel_size without issue in the fragment shader:

```
shader_type canvas_item;

varying vec2 PIXEL_SIZE;

void light() {
	vec2 something = PIXEL_SIZE;
}

fragment() {
        PIXEL_SIZE = TEXTURE_PIXEL_SIZE;
}
```
