### PR TITLE
Fix explain message not being stripped in release.

### LINKED ISSUE #33600: build fails: error C3861: 'format_error_message': identifier not found
**Godot version:**
1b65967e0

**OS/device including version:**
win10

**Issue description:**
build fail
call scons platform=windows target=release_debug tools=no use_lto=yes -j8
[ 13%] platform\windows\os_windows.cpp(2259): error C3861: 'format_error_message': identifier not found
[ 13%] platform\windows\os_windows.cpp(2860): error C3861: 'format_error_message': identifier not found
platform\windows\os_windows.cpp(2870): error C3861: 'format_error_message': identifier not found
platform\windows\os_windows.cpp(2878): error C3861: 'format_error_message': identifier not found
platform\windows\os_windows.cpp(2882): error C3861: 'format_error_message': identifier not found
 
**Steps to reproduce:**
build in x64_x86 Cross Tools

**Minimal reproduction project:**
current 3.2 source code

### PR DESCRIPTION
**Pull request by Faless**
Messages coming from `ERR_EXPLAIN` / `ERR_*_MSG` macros used to strip the error explanation in release builds and was changed in a recent refactoring.

This commit restores the old behaviour (fixing release builds).

Regression from #33517

*Bugsquad edit:* Fixes #33600.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
CC @madmiraal

**Comment by madmiraal** [comment]
I think I'm missing something. Why is stripping the error explanation in release builds the intended behaviour? Surely we would want the error explanation in the release builds too.

From what I can work out, it appears as if it's not stripped, just replaced. If the error message/explanation is an empty string, the logger code replaces it with the default error string here:
https://github.com/godotengine/godot/blob/d3a852f1241306eb697c0e2c072aa9bda09a4f7c/core/io/logger.cpp#L70-L77

Are there additional loggers that are using an empty string message as a proxy to decide not to print anything?

**Comment by Calinou** [comment]
> Why is stripping the error explanation in release builds the intended behaviour? Surely we would want the error explanation in the release builds too.

The reason is to improve run-time performance and decrease binary sizes :slightly_smiling_face:

**Comment by akien-mga** [comment]
Indeed, ignoring those on release means that we don't need to evaluate the Strings in `ERR_*_MSG` macros at all, which can often involve complex operations (as examplified by #33600).
