### PR TITLE
Fixed "Tile Set" button always showing bug introduced with #15309

### PR DESCRIPTION
**Pull request by YeldhamDev**
On the positive side, I found a unused member variable that is now being used, yay?

### CODE REVIEW

**Comment by akien-mga** [comment]
It fails building:
```
editor/plugins/tile_set_editor_plugin.cpp: In constructor 'TileSetEditor::TileSetEditor(EditorNode*)':
editor/plugins/tile_set_editor_plugin.cpp:242:63: error: 'options' was not declared in this scope
  CanvasItemEditor::get_singleton()->add_control_to_menu_panel(options);
                                                               ^
```

File: editor/plugins/tile_set_editor_plugin.cpp [hunk 1]
```diff
@@ -283,13 +283,15 @@ void TileSetEditorPlugin::make_visible(bool p_visible) {
 
 	if (p_visible) {
 		tileset_editor->show();
+		tileset_editor->menu->show();
```
Comment (akien-mga) [inline editor/plugins/tile_set_editor_plugin.cpp]: You shouldn't have to show it manually.. I guess you're not adding it properly as child of `tileset_editor`?

Comment (YeldhamDev) [reply editor/plugins/tile_set_editor_plugin.cpp]: Making it a child of the TilesetEditor was what it caused to go out of bounds. Also fixed the compilation error.

Comment (akien-mga) [reply editor/plugins/tile_set_editor_plugin.cpp]: It feels hacky this way, but well if it works..

Comment (YeldhamDev) [reply editor/plugins/tile_set_editor_plugin.cpp]: On the topic of the TilesetEditor, is the dock used at all? Because I'm trying everything with the Tile Set resource but the dock doesn't seem to participate in anything.
screenshot1
